SUMO - Simulation of Urban MObility: NBTrafficLightDefinition Class Reference
NBTrafficLightDefinition Class Reference abstract
The base class for traffic light logic definitions.
#include <NBTrafficLightDefinition.h>
Data Structures
struct StreamPair
data structure for caching needsCont information
Public Types
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of inner edges controlled by the tls.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
NBTrafficLightLogic * compute (const NBEdgeCont &ec, OptionsCont &oc)
Computes the traffic light logic.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
std::vector< std::string > getControlledInnerEdges () const
Retrieve the ids of edges explicitly controlled by the tls.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first)
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
SUMOTime getOffset ()
Returns the offset.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const std::string & getProgramID () const
Returns the ProgramID.
TrafficLightType getType () const
get the algorithm type (static etc..)
virtual void initNeedsContRelation () const
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
NBTrafficLightDefinition (const std::string &id, const std::vector< NBNode * > &junctions, const std::string &programID, SUMOTime offset, TrafficLightType type)
Constructor.
NBTrafficLightDefinition (const std::string &id, NBNode *junction, const std::string &programID, SUMOTime offset, TrafficLightType type)
Constructor.
NBTrafficLightDefinition (const std::string &id, const std::string &programID, SUMOTime offset, TrafficLightType type)
Constructor.
bool needsCont (const NBEdge *fromE, const NBEdge *toE, const NBEdge *otherFromE, const NBEdge *otherToE) const
virtual void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)=0
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
virtual void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)=0
Replaces a removed edge/lane.
void setID (const std::string &newID)
resets the id
virtual void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void setProgramID (const std::string &programID)
Sets the programID.
virtual void setTLControllingInformation (const NBEdgeCont &ec) const =0
Informs edges about being controlled by a tls.
virtual void shiftTLConnectionLaneIndex (NBEdge *edge, int offset)
patches (loaded) signal plans by modifying lane indices
virtual ~NBTrafficLightDefinition ()
Destructor.
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
Static Public Attributes
static const std::string DefaultProgramID = "0"
Protected Types
typedef std::set< StreamPair > NeedsContRelation
Protected Member Functions
virtual bool amInvalid () const
void collectAllLinks ()
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
virtual void collectEdges ()
Build the list of participating edges.
virtual void collectLinks ()=0
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
unsigned int computeBrakingTime (SUMOReal minDecel) const
Computes the time vehicles may need to brake.
virtual NBTrafficLightLogic * myCompute (const NBEdgeCont &ec, unsigned int brakingTime)=0
Computes the traffic light logic finally in dependence to the type.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
NeedsContRelation myNeedsContRelation
bool myNeedsContRelationReady
SUMOTime myOffset
The offset in the program.
std::string mySubID
The tls program's subid.
TrafficLightType myType
The algorithm type for the traffic light.
Detailed Description
The base class for traffic light logic definitions.
A base class is necessary, as we have two cases: a) the logic is given by the imported network, or b) the logic is not given and we have to compute it by ourselves. In the first case, NBLoadedTLDef should be used, in the second NBOwnTLDef.
See Also
NBLoadedTLDef
NBOwnTLDef
Definition at line 75 of file NBTrafficLightDefinition.h.
Member Typedef Documentation
typedef std::set<StreamPair> NBTrafficLightDefinition::NeedsContRelation protected
Definition at line 427 of file NBTrafficLightDefinition.h.
Member Enumeration Documentation
enum NBTrafficLightDefinition::TLColor
An enumeration of possible tl-signal states.
Enumerator
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused)
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 84 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, const std::vector< NBNode * > & junctions, const std::string & programID, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junctions List of junctions controlled by this tls
[in] programID The id of the added program ("subID")
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 59 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, NBNode * junction, const std::string & programID, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junction The (single) junction controlled by this tls
[in] programID The id of the added program ("subID")
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 85 of file NBTrafficLightDefinition.cpp.
References addNode().
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, const std::string & programID, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] programID The id of the added program ("subID")
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 96 of file NBTrafficLightDefinition.cpp.
NBTrafficLightDefinition::~NBTrafficLightDefinition () virtual
Destructor.
Definition at line 106 of file NBTrafficLightDefinition.cpp.
Member Function Documentation
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges)
Adds the given ids into the list of inner edges controlled by the tls.
Parameters
[in] edges The list of edge ids which shall be controlled despite lying with the jointly controlled node cluster
Definition at line 343 of file NBTrafficLightDefinition.cpp.
References myControlledInnerEdges.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
void NBTrafficLightDefinition::addNode (NBNode * node) virtual
Adds a node to the traffic light logic.
Parameters
[in] node A further node that shall be controlled by the tls
Definition at line 323 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and myControlledNodes.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedTLDef::addToSignalGroup(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBNode::invalidateTLS(), and NBTrafficLightDefinition().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
bool NBTrafficLightDefinition::amInvalid () const protected virtual
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 135 of file NBTrafficLightDefinition.cpp.
References myControlledLinks.
Referenced by compute(), and initNeedsContRelation().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void NBTrafficLightDefinition::collectAllLinks () protected
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
Definition at line 361 of file NBTrafficLightDefinition.cpp.
References NBEdge::Connection::fromLane, NBEdge::getConnectionsFromLane(), Named::getID(), NBEdge::getNumLanes(), NBEdge::mayBeTLSControlled(), myControlledLinks, myIncomingEdges, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and toString().
Referenced by NBLoadedSUMOTLDef::collectLinks(), and NBOwnTLDef::collectLinks().
void NBTrafficLightDefinition::collectEdges () protected virtual
Build the list of participating edges.
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 156 of file NBTrafficLightDefinition.cpp.
References Named::getID(), myControlledInnerEdges, myControlledNodes, myEdgesWithin, and myIncomingEdges.
Referenced by NBLoadedSUMOTLDef::collectEdges(), NBOwnTLDef::setParticipantsInformation(), and setParticipantsInformation().
virtual void NBTrafficLightDefinition::collectLinks () protected pure virtual
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
Implemented in NBLoadedTLDef, NBOwnTLDef, and NBLoadedSUMOTLDef.
Referenced by setParticipantsInformation().
NBTrafficLightLogic * NBTrafficLightDefinition::compute (const NBEdgeCont & ec, OptionsCont & oc)
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters
[in] ec The edge container in order to retrieve edge information
[in] oc The options container holding options needed during the building
Returns
The built logic (may be 0)
Definition at line 110 of file NBTrafficLightDefinition.cpp.
References Parameterised::addParameter(), amInvalid(), computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), Parameterised::getMap(), OptionsCont::isSet(), myCompute(), myControlledNodes, and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic().
unsigned int NBTrafficLightDefinition::computeBrakingTime (SUMOReal minDecel) const protected
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 141 of file NBTrafficLightDefinition.cpp.
References NBContHelper::maxSpeed(), myIncomingEdges, and SUMOReal.
Referenced by compute().
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 300 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), and myControlledNodes.
Referenced by NBOwnTLDef::computeUnblockedWeightedStreamNumber().
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 223 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), and myControlledNodes.
Referenced by NBOwnTLDef::computeLogicAndConts(), and mustBrake().
std::vector< std::string > NBTrafficLightDefinition::getControlledInnerEdges () const
Retrieve the ids of edges explicitly controlled by the tls.
Definition at line 349 of file NBTrafficLightDefinition.cpp.
References myControlledInnerEdges.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const inline
returns the controlled links (depends on previous call to collectLinks)
Definition at line 292 of file NBTrafficLightDefinition.h.
References myControlledLinks.
Referenced by NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), collectEdges(), ROJTRRouter::compute(), compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const
Returns the list of incoming edges (must be build first)
Returns
The edges which are incoming into the tls
Definition at line 355 of file NBTrafficLightDefinition.cpp.
References myIncomingEdges.
Referenced by NBOwnTLDef::computeLogicAndConts().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by compute(), GUIVehicle::getParameterWindow(), TraCIServerAPI_TLS::processGet(), PCPolyContainer::save(), ROVehicle::saveAllAsXML(), SUMOVTypeParameter::write(), and SUMO::Polygon::writeXML().
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const inline
Returns the list of controlled nodes.
Returns
Controlled nodes
Definition at line 172 of file NBTrafficLightDefinition.h.
References myControlledNodes.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic(), and NBNode::invalidateTLS().
SUMOTime NBTrafficLightDefinition::getOffset () inline
Returns the offset.
Returns
Offset
Definition at line 316 of file NBTrafficLightDefinition.h.
References myOffset.
Referenced by NBNode::invalidateTLS(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& NBTrafficLightDefinition::getProgramID () const inline
Returns the ProgramID.
Returns
The ID of the program (subID)
Definition at line 300 of file NBTrafficLightDefinition.h.
References mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBOwnTLDef::computeLogicAndConts(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), NBLoadedTLDef::myCompute(), NIImporter_SUMO::myEndElement(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedSUMOTLDef::removeConnection().
TrafficLightType NBTrafficLightDefinition::getType () const inline
get the algorithm type (static etc..)
Definition at line 322 of file NBTrafficLightDefinition.h.
References myType.
Referenced by NBNode::invalidateTLS(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
void NBTrafficLightDefinition::initNeedsContRelation () const virtual
Reimplemented in NBOwnTLDef.
Definition at line 396 of file NBTrafficLightDefinition.cpp.
References amInvalid(), NBOwnTLDef::initNeedsContRelation(), myControlledNodes, myNeedsContRelation, myNeedsContRelationReady, and TLTYPE_STATIC.
Referenced by needsCont().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 187 of file NBTrafficLightDefinition.cpp.
References NBNode::mustBrake(), and myControlledNodes.
Referenced by NBLoadedTLDef::mustBrake().
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
Parameters
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 213 of file NBTrafficLightDefinition.cpp.
References forbids(), NBConnection::getFrom(), and NBConnection::getTo().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See Also
forbids
Definition at line 201 of file NBTrafficLightDefinition.cpp.
References forbids().
virtual NBTrafficLightLogic* NBTrafficLightDefinition::myCompute (const NBEdgeCont & ec, unsigned int brakingTime) protected pure virtual
Computes the traffic light logic finally in dependence to the type.
Parameters
[in] ec The edge container
[in] brakingTime Duration a vehicle needs for braking in front of the tls
Returns
The computed logic
Implemented in NBLoadedTLDef, NBOwnTLDef, and NBLoadedSUMOTLDef.
Referenced by compute().
bool NBTrafficLightDefinition::needsCont (const NBEdge * fromE, const NBEdge * toE, const NBEdge * otherFromE, const NBEdge * otherToE) const
Definition at line 385 of file NBTrafficLightDefinition.cpp.
References initNeedsContRelation(), myNeedsContRelation, and myNeedsContRelationReady.
virtual void NBTrafficLightDefinition::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) pure virtual
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
Implemented in NBLoadedTLDef, NBOwnTLDef, and NBLoadedSUMOTLDef.
void NBTrafficLightDefinition::removeNode (NBNode * node) virtual
Removes the given node from the list of controlled nodes.
Parameters
[in] node The node that shall not be controlled by the tls any more
Definition at line 333 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
Referenced by NBNode::removeTrafficLight().
virtual void NBTrafficLightDefinition::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) pure virtual
Replaces a removed edge/lane.
Parameters
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
Implemented in NBLoadedTLDef, NBOwnTLDef, and NBLoadedSUMOTLDef.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void NBTrafficLightDefinition::setParticipantsInformation () virtual
Builds the list of participating nodes/edges/links.
Reimplemented in NBOwnTLDef.
Definition at line 148 of file NBTrafficLightDefinition.cpp.
References collectEdges(), and collectLinks().
void NBTrafficLightDefinition::setProgramID (const std::string & programID) inline
Sets the programID.
Parameters
[in] programID The new ID of the program (subID)
Definition at line 308 of file NBTrafficLightDefinition.h.
References mySubID.
Referenced by NBTrafficLightLogicCont::insert().
virtual void NBTrafficLightDefinition::setTLControllingInformation (const NBEdgeCont & ec) const pure virtual
Informs edges about being controlled by a tls.
Parameters
[in] ec The container of edges
Implemented in NBLoadedTLDef, NBOwnTLDef, and NBLoadedSUMOTLDef.
virtual void NBTrafficLightDefinition::shiftTLConnectionLaneIndex (NBEdge * edge, int offset) inline virtual
patches (loaded) signal plans by modifying lane indices
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 280 of file NBTrafficLightDefinition.h.
References UNUSED_PARAMETER.
Field Documentation
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" static
Definition at line 78 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges protected
Set of inner edges that shall be controlled, though.
Definition at line 385 of file NBTrafficLightDefinition.h.
Referenced by addControlledInnerEdges(), NBLoadedSUMOTLDef::collectEdges(), collectEdges(), and getControlledInnerEdges().
NBConnectionVector NBTrafficLightDefinition::myControlledLinks protected
The list of controlled links.
Definition at line 382 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedSUMOTLDef::amInvalid(), amInvalid(), collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBLoadedSUMOTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), getControlledLinks(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), and NBLoadedSUMOTLDef::shiftTLConnectionLaneIndex().
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes protected
The container with participating nodes.
Definition at line 373 of file NBTrafficLightDefinition.h.
Referenced by addNode(), NBLoadedSUMOTLDef::amInvalid(), NBLoadedSUMOTLDef::collectEdges(), collectEdges(), NBLoadedSUMOTLDef::collectLinks(), NBLoadedTLDef::collectNodes(), compute(), NBOwnTLDef::computeLogicAndConts(), foes(), forbids(), getNodes(), NBOwnTLDef::initNeedsContRelation(), initNeedsContRelation(), mustBrake(), NBTrafficLightDefinition(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and removeNode().
EdgeVector NBTrafficLightDefinition::myEdgesWithin protected
The list of edges within the area controlled by the tls.
Definition at line 379 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::collectEdges(), and collectEdges().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
EdgeVector NBTrafficLightDefinition::myIncomingEdges protected
The list of incoming edges.
Definition at line 376 of file NBTrafficLightDefinition.h.
Referenced by collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), collectEdges(), NBLoadedTLDef::collectLinks(), computeBrakingTime(), and getIncomingEdges().
NeedsContRelation NBTrafficLightDefinition::myNeedsContRelation mutable protected
Definition at line 428 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), initNeedsContRelation(), and needsCont().
bool NBTrafficLightDefinition::myNeedsContRelationReady mutable protected
Definition at line 429 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), initNeedsContRelation(), and needsCont().
SUMOTime NBTrafficLightDefinition::myOffset protected
The offset in the program.
Definition at line 391 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), getOffset(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), and NBLoadedSUMOTLDef::setOffset().
std::string NBTrafficLightDefinition::mySubID protected
The tls program's subid.
Definition at line 388 of file NBTrafficLightDefinition.h.
Referenced by getProgramID(), and setProgramID().
TrafficLightType NBTrafficLightDefinition::myType protected
The algorithm type for the traffic light.
Definition at line 394 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), getType(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), and NBLoadedSUMOTLDef::setType().
The documentation for this class was generated from the following files:
NBTrafficLightDefinition.h
NBTrafficLightDefinition.cpp