SUMO - Simulation of Urban MObility: MSMeanData Class Reference
MSMeanData Class Reference abstract
Data collector for edges/lanes.
#include <MSMeanData.h>
Data Structures
class MeanDataValues
Data structure for mean (aggregated) edge/lane values.
class MeanDataValueTracker
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual void detectorUpdate (const SUMOTime step)
Updates the detector.
const std::string & getID () const
Returns the id.
void init ()
Adds the value collectors to all relevant edges.
MSMeanData (const std::string &id, const SUMOTime dumpBegin, const SUMOTime dumpEnd, const bool useLanes, const bool withEmpty, const bool printDefaults, const bool withInternal, const bool trackVehicles, const SUMOReal minSamples, const SUMOReal maxTravelTime, const std::set< std::string > vTypes)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MSMeanData ()
Destructor.
Methods inherited from MSDetectorFileOutput.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
virtual void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "netstats" as root element.
Virtual methods to implement by derived classes
virtual void reset ()
Resets collected values.
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
Protected Member Functions
virtual
MSMeanData::MeanDataValues * createValues (MSLane *const lane, const SUMOReal length, const bool doAdd) const =0
Create an instance of MeanDataValues.
virtual std::string getEdgeID (const MSEdge *const edge)
Return the relevant edge id.
virtual void openInterval (OutputDevice &dev, const SUMOTime startTime, const SUMOTime stopTime)
Writes the interval opener.
void resetOnly (SUMOTime stopTime)
Resets network value in order to allow processing of the next interval.
void writeEdge (OutputDevice &dev, const std::vector< MeanDataValues * > &edgeValues, MSEdge *edge, SUMOTime startTime, SUMOTime stopTime)
Writes edge values into the given stream.
virtual bool writePrefix (OutputDevice &dev, const MeanDataValues &values, const SumoXMLTag tag, const std::string id) const
Checks for emptiness and writes prefix into the given stream.
Protected Attributes
const bool myDumpEmpty
Whether empty lanes/edges shall be written.
std::string myID
The name of the object.
const SUMOReal myMaxTravelTime
the maximum travel time to write
std::vector< std::vector
< MeanDataValues * > > myMeasures
Value collectors; sorted by edge, then by lane.
const SUMOReal myMinSamples
the minimum sample seconds
const std::set< std::string > myVehicleTypes
The vehicle types to look for (empty means all)
Private Member Functions
MSMeanData (const MSMeanData &)
Invalidated copy constructor.
MSMeanData & operator= (const MSMeanData &)
Invalidated assignment operator.
Private Attributes
const bool myAmEdgeBased
Information whether the output shall be edge-based (not lane-based)
const SUMOTime myDumpBegin
The first and the last time step to write information (-1 indicates always)
const SUMOTime myDumpEnd
const bool myDumpInternal
Whether internal lanes/edges shall be written.
MSEdgeVector myEdges
The corresponding first edges.
std::list< std::pair< SUMOTime,
SUMOTime > > myPendingIntervals
The intervals for which output still has to be generated (only in the tracking case)
const bool myPrintDefaults
Whether empty lanes/edges shall be written.
const bool myTrackVehicles
Whether vehicles are tracked.
Detailed Description
Data collector for edges/lanes.
This structure does not contain the data itself, it is stored within MeanDataValues-MoveReminder objects. This class is used to build the output, optionally, in the case of edge-based dump, aggregated over the edge's lanes.
Todo:
consider error-handling on write (using IOError)
Definition at line 67 of file MSMeanData.h.
Constructor & Destructor Documentation
MSMeanData::MSMeanData (const std::string & id, const SUMOTime dumpBegin, const SUMOTime dumpEnd, const bool useLanes, const bool withEmpty, const bool printDefaults, const bool withInternal, const bool trackVehicles, const SUMOReal minSamples, const SUMOReal maxTravelTime, const std::set< std::string > vTypes)
Constructor.
Parameters
[in] id The id of the detector
[in] dumpBegin Begin time of dump
[in] dumpEnd End time of dump
[in] useLanes Information whether lane-based or edge-based dump shall be generated
[in] withEmpty Information whether empty lanes/edges shall be written
[in] withInternal Information whether internal lanes/edges shall be written
[in] trackVehicles Information whether vehicles shall be tracked
[in] maxTravelTime the maximum travel time to use when calculating per vehicle output
[in] defaultEffort the value to use when calculating defaults
[in] minSamples the minimum number of sample seconds before the values are valid
[in] vTypes the set of vehicle types to consider
Definition at line 254 of file MSMeanData.cpp.
MSMeanData::~MSMeanData () virtual
Destructor.
Definition at line 323 of file MSMeanData.cpp.
References myMeasures.
MSMeanData::MSMeanData (const MSMeanData &) private
Invalidated copy constructor.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () inline virtual inherited
Builds the graphical representation.
Meant to be overridden by graphical versions of the detectors
Returns
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUIInductLoop, GUIE3Collector, GUI_E2_ZS_CollectorOverLanes, and GUIInstantInductLoop.
Definition at line 123 of file MSDetectorFileOutput.h.
virtual MSMeanData::MeanDataValues* MSMeanData::createValues (MSLane *const lane, const SUMOReal length, const bool doAdd) const protected pure virtual
Create an instance of MeanDataValues.
Parameters
[in] lane The lane to create for
[in] doAdd whether to add the values as reminder to the lane
Implemented in MSMeanData_Amitran, MSMeanData_Net, MSMeanData_Harmonoise, and MSMeanData_Emissions.
Referenced by init(), MSMeanData::MeanDataValueTracker::MeanDataValueTracker(), and writeEdge().
void MSMeanData::detectorUpdate (const SUMOTime step) virtual
Updates the detector.
Reimplemented from MSDetectorFileOutput.
Reimplemented in MSMeanData_Harmonoise.
Definition at line 495 of file MSMeanData.cpp.
References DELTA_T, init(), and myDumpBegin.
Referenced by MSMeanData_Harmonoise::detectorUpdate().
std::string MSMeanData::getEdgeID (const MSEdge *const edge) protected virtual
Return the relevant edge id.
Parameters
[in] edge The edge to retrieve the id for
Reimplemented in MSMeanData_Amitran.
Definition at line 359 of file MSMeanData.cpp.
References Named::getID().
Referenced by writeEdge().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
void MSMeanData::init ()
Adds the value collectors to all relevant edges.
Definition at line 276 of file MSMeanData.cpp.
References createValues(), MSEdge::EDGEFUNCTION_INTERNAL, MSNet::getEdgeControl(), MSEdgeControl::getEdges(), MSNet::getInstance(), MSGlobals::gUseMesoSim, myAmEdgeBased, myDumpInternal, myEdges, myMeasures, myTrackVehicles, myVehicleTypes, MSMeanData::MeanDataValues::reset(), and MSMoveReminder::setDescription().
Referenced by MSDetectorControl::add(), and detectorUpdate().
void MSMeanData::openInterval (OutputDevice & dev, const SUMOTime startTime, const SUMOTime stopTime) protected virtual
Writes the interval opener.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Reimplemented in MSMeanData_Amitran.
Definition at line 433 of file MSMeanData.cpp.
References Named::myID, OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_TAG_INTERVAL, and OutputDevice::writeAttr().
Referenced by writeXMLOutput().
MSMeanData& MSMeanData::operator= (const MSMeanData &) private
Invalidated assignment operator.
virtual void MSDetectorFileOutput::reset () inline virtual inherited
Resets collected values.
Please note that this is only a "hack" for coupled-tls-outputs.
See Also
Command_SaveTLCoupledLaneDet
Todo:
Reckeck/refactor
Reimplemented in MSE2Collector, MSE3Collector, MSInductLoop, and GUIInductLoop.
Definition at line 106 of file MSDetectorFileOutput.h.
Referenced by Command_SaveTLCoupledLaneDet::execute().
void MSMeanData::resetOnly (SUMOTime stopTime) protected
Resets network value in order to allow processing of the next interval.
Goes through the lists of edges and starts "resetOnly" for each edge.
Parameters
[in] edge The last time step that is reported
Definition at line 333 of file MSMeanData.cpp.
References MSGlobals::gUseMesoSim, myEdges, myMeasures, MSMeanData::MeanDataValues::reset(), and UNUSED_PARAMETER.
Referenced by writeXMLOutput().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void MSMeanData::writeEdge (OutputDevice & dev, const std::vector< MeanDataValues * > & edgeValues, MSEdge * edge, SUMOTime startTime, SUMOTime stopTime) protected
Writes edge values into the given stream.
microsim: It is checked whether the dump shall be generated edge- or lane-wise. In the first case, the lane-data are collected and aggregated and written directly. In the second case, "writeLane" is used to write each lane's state.
Parameters
[in] dev The output device to write the data into
[in] edgeValues List of this edge's value collectors
[in] edge The edge to write the dump of
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 365 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::addTo(), OutputDevice::closeTag(), createValues(), getEdgeID(), Named::getID(), MSMoveReminder::getLane(), MSEdge::getLanes(), MSLane::getLength(), MSEdge::getLength(), MSLane::getSpeedLimit(), MSEdge::getSpeedLimit(), MSGlobals::gUseMesoSim, myAmEdgeBased, myDumpEmpty, myPrintDefaults, myTrackVehicles, OutputDevice::openTag(), MSMeanData::MeanDataValues::reset(), SUMO_ATTR_ID, SUMO_TAG_EDGE, SUMO_TAG_LANE, SUMOReal, MSMeanData::MeanDataValues::write(), OutputDevice::writeAttr(), and writePrefix().
Referenced by writeXMLOutput().
bool MSMeanData::writePrefix (OutputDevice & dev, const MeanDataValues & values, const SumoXMLTag tag, const std::string id) const protected virtual
Checks for emptiness and writes prefix into the given stream.
Parameters
[in] dev The output device to write the data into
[in] values The values to check for emptiness
[in] tag The xml tag to write (lane / edge)
[in] id The id for the lane / edge to write
Returns
whether further output should be generated
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Reimplemented in MSMeanData_Amitran.
Definition at line 440 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::getSamples(), MSMeanData::MeanDataValues::isEmpty(), myDumpEmpty, OutputDevice::openTag(), SUMO_ATTR_ID, and OutputDevice::writeAttr().
Referenced by writeEdge().
void MSMeanData::writeXMLDetectorProlog (OutputDevice & dev) const virtual
Opens the XML-output using "netstats" as root element.
Parameters
[in] dev The output device to write the root into
See Also
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Reimplemented in MSMeanData_Amitran.
Definition at line 489 of file MSMeanData.cpp.
References OutputDevice::writeXMLHeader().
void MSMeanData::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual
Writes collected values into the given stream.
At first, it is checked whether the values for the current interval shall be written. If not, a reset is performed, only, using "resetOnly". Otherwise, both the list of single-lane edges and the list of multi-lane edges are gone through and each edge is written using "writeEdge".
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See Also
MSDetectorFileOutput::writeXMLOutput
write
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 450 of file MSMeanData.cpp.
References OutputDevice::closeTag(), DELTA_T, MIN2(), myDumpBegin, myDumpEnd, myEdges, myMeasures, myPendingIntervals, myTrackVehicles, openInterval(), resetOnly(), and writeEdge().
Field Documentation
const bool MSMeanData::myAmEdgeBased private
Information whether the output shall be edge-based (not lane-based)
Definition at line 445 of file MSMeanData.h.
Referenced by init(), and writeEdge().
const SUMOTime MSMeanData::myDumpBegin private
The first and the last time step to write information (-1 indicates always)
Definition at line 448 of file MSMeanData.h.
Referenced by detectorUpdate(), and writeXMLOutput().
const bool MSMeanData::myDumpEmpty protected
Whether empty lanes/edges shall be written.
Definition at line 441 of file MSMeanData.h.
Referenced by writeEdge(), MSMeanData_Amitran::writePrefix(), and writePrefix().
const SUMOTime MSMeanData::myDumpEnd private
Definition at line 448 of file MSMeanData.h.
Referenced by writeXMLOutput().
const bool MSMeanData::myDumpInternal private
Whether internal lanes/edges shall be written.
Definition at line 457 of file MSMeanData.h.
Referenced by init().
MSEdgeVector MSMeanData::myEdges private
The corresponding first edges.
Definition at line 451 of file MSMeanData.h.
Referenced by init(), resetOnly(), and writeXMLOutput().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const SUMOReal MSMeanData::myMaxTravelTime protected
the maximum travel time to write
Definition at line 432 of file MSMeanData.h.
std::vector<std::vector<MeanDataValues*> > MSMeanData::myMeasures protected
Value collectors; sorted by edge, then by lane.
Definition at line 438 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::detectorUpdate(), init(), resetOnly(), writeXMLOutput(), and ~MSMeanData().
const SUMOReal MSMeanData::myMinSamples protected
the minimum sample seconds
Definition at line 429 of file MSMeanData.h.
std::list< std::pair<SUMOTime, SUMOTime> > MSMeanData::myPendingIntervals private
The intervals for which output still has to be generated (only in the tracking case)
Definition at line 463 of file MSMeanData.h.
Referenced by writeXMLOutput().
const bool MSMeanData::myPrintDefaults private
Whether empty lanes/edges shall be written.
Definition at line 454 of file MSMeanData.h.
Referenced by writeEdge().
const bool MSMeanData::myTrackVehicles private
Whether vehicles are tracked.
Definition at line 460 of file MSMeanData.h.
Referenced by init(), writeEdge(), and writeXMLOutput().
const std::set<std::string> MSMeanData::myVehicleTypes protected
The vehicle types to look for (empty means all)
Definition at line 435 of file MSMeanData.h.
Referenced by MSMeanData_Emissions::createValues(), MSMeanData_Harmonoise::createValues(), MSMeanData_Net::createValues(), MSMeanData_Amitran::createValues(), init(), MSMeanData::MeanDataValues::vehicleApplies(), and MSMeanData_Amitran::MSLaneMeanDataValues::write().
The documentation for this class was generated from the following files:
MSMeanData.h
MSMeanData.cpp