SUMO - Simulation of Urban MObility: MSLCM_JE2013 Class Reference
MSLCM_JE2013 Class Reference
A lane change model developed by J. Erdmann.
#include <MSLCM_JE2013.h>
Public Types
enum MyLCAEnum {
LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18, LCA_MLEFT = 1 << 19,
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_CHANGE_TO_HELP = 1 << 23, LCA_AMBACKBLOCKER = 1 << 26, LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
SUMOReal _patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
bool alreadyMoved () const
reset the flag whether a vehicle already moved to false
void changed (int dir)
void continueLaneChangeManeuver (bool moved)
void endLaneChangeManeuver ()
SUMOReal getLaneChangeCompletion () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
int getOwnState () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuouss lane change.
void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isLaneChangeMidpointPassed () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
MSLCM_JE2013 (MSVehicle &v)
SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
void prepareStep ()
void removeLaneChangeShadow ()
remove the shadow copy of a lane change maneuver
void resetMoved ()
reset the flag whether a vehicle already moved to false
void setOwnState (int state)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual ~MSLCM_JE2013 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< SUMOReal, int > Info
information regarding save velocity (unused) and state flags of the ego vehicle
Protected Member Functions
int _wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
helper function for doing the actual work
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
bool currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
void informFollower (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed)
decide whether we will try cut in before the follower or allow to be overtaken
SUMOReal informLeader (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighLead, SUMOReal remainingSeconds)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const MSVehicle *const leader)
void saveBlockerLength (MSVehicle *blocker, int lcaCounter)
save space for vehicles which need to counter-lane-change
void saveBlockerLength (SUMOReal length)
reserve space at the end of the lane to avoid dead locks
int slowDownForBlocked (MSVehicle **blocked, int state)
compute useful slowdowns for blocked vehicles
Protected Attributes
bool myAlreadyMoved
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
bool myDontBrake
bool myHaveShadow
Wether a vehicle shadow exists.
SUMOReal myKeepRightProbability
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
bool myLaneChangeMidpointPassed
whether myLane has already been set to the target of the lane-change maneuver
SUMOReal myLeadingBlockerLength
SUMOReal myLeftSpace
SUMOReal myLookAheadSpeed
int myOwnState
The current state of the vehicle.
MSLane * myShadowLane
The lane the vehicle shadow is on during a continuous lane change.
SUMOReal mySpeedGainProbability
a value for tracking the probability that a change to the offset with the same sign is beneficial
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< SUMOReal > myVSafes
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
Detailed Description
A lane change model developed by J. Erdmann.
Definition at line 47 of file MSLCM_JE2013.h.
Member Typedef Documentation
typedef std::pair<SUMOReal, int> MSLCM_JE2013::Info protected
information regarding save velocity (unused) and state flags of the ego vehicle
Definition at line 169 of file MSLCM_JE2013.h.
Member Enumeration Documentation
enum MSLCM_JE2013::MyLCAEnum
Enumerator
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_CHANGE_TO_HELP
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 50 of file MSLCM_JE2013.h.
Constructor & Destructor Documentation
MSLCM_JE2013::MSLCM_JE2013 (MSVehicle & v)
Definition at line 115 of file MSLCM_JE2013.cpp.
MSLCM_JE2013::~MSLCM_JE2013 () virtual
Definition at line 124 of file MSLCM_JE2013.cpp.
References changed().
Member Function Documentation
SUMOReal MSLCM_JE2013::_patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel)
helper function which contains the actual logic
Definition at line 198 of file MSLCM_JE2013.cpp.
References changed(), gDebugFlag1, MSLane::getEdge(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_COOPERATIVE, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, MAX2(), MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, STEPS2TIME, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by patchSpeed().
int MSLCM_JE2013::_wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected
helper function for doing the actual work
we urgently need to change lanes to follow our route
Definition at line 646 of file MSLCM_JE2013.cpp.
References abs, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::cancelRequest(), CHANGE_PROB_THRESHOLD_LEFT, CHANGE_PROB_THRESHOLD_RIGHT, MSVehicle::Influencer::changeRequestRemainingSeconds(), MSVehicle::congested(), currentDistAllows(), currentDistDisallows(), DELTA_T, MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::influenceChangeDecision(), informFollower(), informLeader(), JAM_FACTOR, KEEP_RIGHT_ACCEPTANCE, KEEP_RIGHT_TIME, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_AHEAD_MIN_SPEED, LOOK_AHEAD_SPEED_MEMORY, LOOK_FORWARD_LEFT, LOOK_FORWARD_RIGHT, MAX2(), MIN2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, MSVehicle::LaneQ::occupation, RELGAIN_NORMALIZATION_MIN_SPEED, ROUNDABOUT_DIST_BONUS, saveBlockerLength(), slowDownForBlocked(), STEPS2TIME, SUMO_const_haltingSpeed, SUMOReal, tryID(), TS, TURN_LANE_DIST, and URGENCY.
Referenced by wantsChange().
bool MSAbstractLaneChangeModel::alreadyMoved () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 281 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyMoved.
Referenced by MSLane::executeMovements().
bool MSLCM_JE2013::amBlockingFollower () inline protected
Definition at line 152 of file MSLCM_JE2013.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_JE2013::amBlockingFollowerNB () inline protected
Definition at line 155 of file MSLCM_JE2013.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_JE2013::amBlockingFollowerPlusNB () inline protected
Definition at line 158 of file MSLCM_JE2013.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by _wantsChange().
bool MSLCM_JE2013::amBlockingLeader () inline protected
Definition at line 149 of file MSLCM_JE2013.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 60 of file MSAbstractLaneChangeModel.cpp.
References LCM_DK2008, LCM_JE2013, LCM_LC2013, and toString().
Referenced by MSVehicle::MSVehicle().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 208 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by _wantsChange(), and MSLCM_LC2013::_wantsChange().
void MSLCM_JE2013::changed (int dir) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 628 of file MSLCM_JE2013.cpp.
References MSVehicle::getBestLaneOffset(), MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LOOK_AHEAD_MIN_SPEED, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, MSAbstractLaneChangeModel::myVehicle, and myVSafes.
Referenced by _patchSpeed(), and ~MSLCM_JE2013().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 96 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
void MSAbstractLaneChangeModel::continueLaneChangeManeuver (bool moved) inherited
Definition at line 150 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), DELTA_T, MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::fixPosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSLane::getLength(), MSLane::getParallelLane(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::leaveLane(), MSAbstractLaneChangeModel::myAlreadyMoved, MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLaneChangeMidpointPassed, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::removeLaneChangeShadow(), SUMOReal, time2string(), toString(), and WRITE_WARNING.
Referenced by MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSLCM_JE2013::currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 164 of file MSLCM_JE2013.h.
References abs.
Referenced by _wantsChange().
bool MSLCM_JE2013::currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 161 of file MSLCM_JE2013.h.
References abs.
Referenced by _wantsChange().
void MSAbstractLaneChangeModel::endLaneChangeManeuver () inline inherited
Definition at line 302 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myShadowLane, and MSAbstractLaneChangeModel::removeLaneChangeShadow().
Referenced by MSVehicleTransfer::add(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSVehicle::executeMove(), and MSLane::handleCollision().
SUMOReal MSAbstractLaneChangeModel::getLaneChangeCompletion () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 266 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSVehicle::getAngle().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 276 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeDirection.
Referenced by MSVehicle::getAngle().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 255 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 196 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change(), saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuouss lane change.
Returns
The vehicle's shadow lane
Definition at line 250 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSLane::executeMovements(), and MSVehicle::getPosition().
void * MSLCM_JE2013::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 345 of file MSLCM_JE2013.cpp.
References DEBUG_COND, gDebugFlag2, MSBaseVehicle::getID(), MSNet::getInstance(), MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, and STEPS2TIME.
void MSLCM_JE2013::informFollower (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed) protected
decide whether we will try cut in before the follower or allow to be overtaken
Definition at line 479 of file MSLCM_JE2013.cpp.
References ACCEL2SPEED, MSVehicle::congested(), CUT_IN_LEFT_SPEED_THRESHOLD, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), HELP_DECEL_FACTOR, HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), LCA_AMBLOCKINGFOLLOWER, LCA_BLOCKED_BY_FOLLOWER, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT_IMPATIENCE, MAX2(), MAX_ONRAMP_LENGTH, MSAbstractLaneChangeModel::myAllowOvertakingRight, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, STEPS2TIME, and SUMOReal.
Referenced by _wantsChange().
SUMOReal MSLCM_JE2013::informLeader (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighLead, SUMOReal remainingSeconds) protected
Definition at line 366 of file MSLCM_JE2013.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), MSVehicle::congested(), MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, MAX2(), MIN2(), MIN_FALLBEHIND, MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by _wantsChange().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 54 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), and MSAbstractLaneChangeModel::myAllowOvertakingRight.
Referenced by MSFrame::setMSGlobals().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 215 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLCM_DK2008::changed(), changed(), and MSLCM_LC2013::changed().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 271 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChanger::change(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSLane::executeMovements(), MSVehicle::getAngle(), and MSVehicle::getPosition().
bool MSAbstractLaneChangeModel::isLaneChangeMidpointPassed () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 261 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeMidpointPassed.
Referenced by MSVehicle::getAngle(), MSVehicle::getPosition(), and MSVehicle::planMoveInternal().
SUMOReal MSLCM_JE2013::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 177 of file MSLCM_JE2013.cpp.
References _patchSpeed(), DEBUG_COND, gDebugFlag1, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, SUMOReal, and toString().
bool MSAbstractLaneChangeModel::predInteraction (const MSVehicle *const leader) protected virtual inherited
Definition at line 115 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, and SUMOReal.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
void MSLCM_JE2013::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 614 of file MSLCM_JE2013.cpp.
References LCA_STRATEGIC, LCA_WANTS_LANECHANGE, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, and myVSafes.
void MSAbstractLaneChangeModel::removeLaneChangeShadow () inherited
remove the shadow copy of a lane change maneuver
Definition at line 199 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, and MSLane::removeVehicle().
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), and MSAbstractLaneChangeModel::endLaneChangeManeuver().
void MSAbstractLaneChangeModel::resetMoved () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 286 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyMoved.
Referenced by MSVehicle::planMove().
void MSLCM_JE2013::saveBlockerLength (MSVehicle * blocker, int lcaCounter) protected
save space for vehicles which need to counter-lane-change
Definition at line 1185 of file MSLCM_JE2013.cpp.
References MSCFModel::brakeGap(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::saveBlockerLength(), STEPS2TIME, SUMOReal, toString(), and tryID().
Referenced by _wantsChange().
void MSLCM_JE2013::saveBlockerLength (SUMOReal length) inline protected virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 145 of file MSLCM_JE2013.h.
References MAX2(), and myLeadingBlockerLength.
void MSAbstractLaneChangeModel::setOwnState (int state) inline inherited
Definition at line 200 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change().
int MSLCM_JE2013::slowDownForBlocked (MSVehicle ** blocked, int state) protected
compute useful slowdowns for blocked vehicles
Definition at line 1149 of file MSLCM_JE2013.cpp.
References ACCEL2SPEED, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, STEPS2TIME, SUMO_const_haltingSpeed, SUMOReal, and tryID().
Referenced by _wantsChange().
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 129 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), DELTA_T, MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), MSGlobals::gLaneChangeDuration, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myHaveShadow, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLaneChangeMidpointPassed, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, and MSMoveReminder::NOTIFICATION_LANE_CHANGE.
Referenced by MSLaneChanger::startChange().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 239 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
int MSLCM_JE2013::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Implements MSAbstractLaneChangeModel.
Definition at line 130 of file MSLCM_JE2013.cpp.
References _wantsChange(), DEBUG_COND, gDebugFlag2, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), LCA_BLOCKED, LCA_CHANGE_TO_HELP, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_OVERLAPPING, LCA_SPEEDGAIN, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::myVehicle, and STEPS2TIME.
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 358 of file MSAbstractLaneChangeModel.h.
Referenced by _wantsChange(), MSLCM_LC2013::_wantsChange(), informFollower(), informLeader(), MSLCM_LC2013::informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyMoved protected inherited
whether the vehicle has already moved this step
Definition at line 342 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyMoved(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), and MSAbstractLaneChangeModel::resetMoved().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 351 of file MSAbstractLaneChangeModel.h.
Referenced by _wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_DK2008::informBlocker(), informLeader(), MSLCM_LC2013::informLeader(), MSAbstractLaneChangeModel::predInteraction(), slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
bool MSLCM_JE2013::myDontBrake protected
Definition at line 189 of file MSLCM_JE2013.h.
Referenced by _patchSpeed(), changed(), and prepareStep().
bool MSAbstractLaneChangeModel::myHaveShadow protected inherited
Wether a vehicle shadow exists.
Definition at line 348 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel().
SUMOReal MSLCM_JE2013::myKeepRightProbability protected
Definition at line 179 of file MSLCM_JE2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 333 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getLaneChangeCompletion(), MSAbstractLaneChangeModel::isChangingLanes(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 336 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLaneChangeMidpointPassed protected inherited
whether myLane has already been set to the target of the lane-change maneuver
Definition at line 339 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::isLaneChangeMidpointPassed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOReal MSLCM_JE2013::myLeadingBlockerLength protected
Definition at line 181 of file MSLCM_JE2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_JE2013::myLeftSpace protected
Definition at line 182 of file MSLCM_JE2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informFollower(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_JE2013::myLookAheadSpeed protected
Definition at line 186 of file MSLCM_JE2013.h.
Referenced by _wantsChange(), and changed().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 330 of file MSAbstractLaneChangeModel.h.
Referenced by _patchSpeed(), MSLCM_LC2013::_patchSpeed(), _wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_DK2008::amBlockingFollower(), amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_DK2008::changed(), changed(), MSLCM_LC2013::changed(), MSAbstractLaneChangeModel::getOwnState(), MSLCM_DK2008::inform(), inform(), MSLCM_LC2013::inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), prepareStep(), MSLCM_LC2013::prepareStep(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
The lane the vehicle shadow is on during a continuous lane change.
Definition at line 345 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel().
SUMOReal MSLCM_JE2013::mySpeedGainProbability protected
a value for tracking the probability that a change to the offset with the same sign is beneficial
Definition at line 175 of file MSLCM_JE2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 327 of file MSAbstractLaneChangeModel.h.
Referenced by _patchSpeed(), MSLCM_LC2013::_patchSpeed(), _wantsChange(), MSLCM_LC2013::_wantsChange(), MSAbstractLaneChangeModel::cancelRequest(), changed(), MSLCM_LC2013::changed(), MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), inform(), MSLCM_DK2008::informBlocker(), informFollower(), MSLCM_LC2013::informFollower(), informLeader(), MSLCM_LC2013::informLeader(), MSLCM_DK2008::patchSpeed(), patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSAbstractLaneChangeModel::removeLaneChangeShadow(), saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), wantsChange(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel().
std::vector<SUMOReal> MSLCM_JE2013::myVSafes protected
Definition at line 188 of file MSLCM_JE2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), inform(), informFollower(), informLeader(), prepareStep(), and slowDownForBlocked().
The documentation for this class was generated from the following files:
MSLCM_JE2013.h
MSLCM_JE2013.cpp