SUMO - Simulation of Urban MObility: MSLink Class Reference
MSLink Class Reference
#include <MSLink.h>
Data Structures
struct ApproachingVehicleInformation
A structure holding the information about vehicles approaching a link.
struct LinkLeader
Public Types
typedef std::vector< LinkLeader > LinkLeaders
Public Member Functions
void addBlockedLink (MSLink *link)
bool blockedAtTime (SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal arrivalSpeed, SUMOReal leaveSpeed, bool sameTargetLane, SUMOReal impatience, SUMOReal decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > *collectFoes=0) const
Returns the information whether this link is blocked Valid after the vehicles have set their requests.
ApproachingVehicleInformation getApproaching (const SUMOVehicle *veh) const
MSLane * getApproachingLane () const
Returns the lane leading to this link.
LinkDirection getDirection () const
Returns the direction the vehicle passing this link take.
int getIndex () const
Returns the respond index (for visualization)
const MSJunction * getJunction () const
return the junction to which this link belongs
MSLane * getLane () const
Returns the connected lane.
SUMOTime getLastStateChange () const
SUMOTime getLeaveTime (const SUMOTime arrivalTime, const SUMOReal arrivalSpeed, const SUMOReal leaveSpeed, const SUMOReal vehicleLength) const
return the expected time at which the given vehicle will clear the link
SUMOReal getLength () const
Returns the length of this link.
LinkState getState () const
Returns the current state of the link.
MSLane * getViaLaneOrLane () const
return the via lane if it exists and the lane otherwise
bool hasApproachingFoe (SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal speed, SUMOReal decel) const
Returns the information whether a vehicle is approaching on one of the link's foe streams.
bool hasFoes () const
Returns whether this link belongs to a junction where more than one edge is incoming.
bool havePriority () const
Returns whether this link is a major link.
bool haveRed () const
Returns whether this link is blocked by a red (or redyellow) traffic light.
bool isBlockingAnyone () const
bool isCont () const
bool lastWasContMajor () const
whether this is a link past an internal junction which currently has priority
MSLink (MSLane *succLane, LinkDirection dir, LinkState state, SUMOReal length)
Constructor for simulation not using internal lanes.
bool opened (SUMOTime arrivalTime, SUMOReal arrivalSpeed, SUMOReal leaveSpeed, SUMOReal vehicleLength, SUMOReal impatience, SUMOReal decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > *collectFoes=0) const
Returns the information whether the link may be passed.
void removeApproaching (const SUMOVehicle *veh)
removes the vehicle from myApproachingVehicles
void setApproaching (const SUMOVehicle *approaching, const SUMOTime arrivalTime, const SUMOReal arrivalSpeed, const SUMOReal leaveSpeed, const bool setRequest, const SUMOTime arrivalTimeBraking, const SUMOReal arrivalSpeedBraking, const SUMOTime waitingTime)
Sets the information about an approaching vehicle.
void setRequestInformation (int index, bool hasFoes, bool isCont, const std::vector< MSLink * > &foeLinks, const std::vector< MSLane * > &foeLanes, MSLane *internalLaneBefore=0)
Sets the request information.
void setTLState (LinkState state, SUMOTime t)
Sets the current tl-state.
bool willHaveBlockedFoe () const
void writeApproaching (OutputDevice &od, const std::string fromLaneID) const
write information about all approaching vehicles to the given output device
~MSLink ()
Destructor.
Private Member Functions
MSLink (const MSLink &s)
invalidated copy constructor
MSLink & operator= (const MSLink &s)
invalidated assignment operator
Static Private Member Functions
static bool maybeOccupied (MSLane *lane)
returns whether the given lane may still be occupied by a vehicle currently on it
static bool unsafeMergeSpeeds (SUMOReal leaderSpeed, SUMOReal followerSpeed, SUMOReal leaderDecel, SUMOReal followerDecel)
return whether the given vehicles may NOT merge safely
Private Attributes
bool myAmCont
std::map< const SUMOVehicle
*, ApproachingVehicleInformation > myApproachingVehicles
std::set< MSLink * > myBlockedFoeLinks
LinkDirection myDirection
An abstract (hopefully human readable) definition of the link's direction.
std::vector< const MSLane * > myFoeLanes
std::vector< MSLink * > myFoeLinks
bool myHasFoes
Whether any foe links exist.
int myIndex
The position within this respond.
const MSJunction * myJunction
the junction to which this link belongs
MSLane * myLane
The lane (but the internal one) approached by this link.
SUMOTime myLastStateChange
The time of the last state change.
SUMOReal myLength
The length of the link.
LinkState myState
The state of the link.
Static Private Attributes
static SUMOTime myLookaheadTime = TIME2STEPS(1)
Detailed Description
Definition at line 76 of file MSLink.h.
Member Typedef Documentation
typedef std::vector<LinkLeader> MSLink::LinkLeaders
Definition at line 88 of file MSLink.h.
Constructor & Destructor Documentation
MSLink::MSLink (MSLane * succLane, LinkDirection dir, LinkState state, SUMOReal length)
Constructor for simulation not using internal lanes.
Parameters
[in] succLane The lane approached by this link
[in] dir The direction of this link
[in] state The state of this link
[in] length The length of this link
Definition at line 62 of file MSLink.cpp.
MSLink::~MSLink ()
Destructor.
Definition at line 89 of file MSLink.cpp.
MSLink::MSLink (const MSLink & s) private
invalidated copy constructor
Member Function Documentation
void MSLink::addBlockedLink (MSLink * link)
Definition at line 242 of file MSLink.cpp.
References myBlockedFoeLinks.
bool MSLink::blockedAtTime (SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal arrivalSpeed, SUMOReal leaveSpeed, bool sameTargetLane, SUMOReal impatience, SUMOReal decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > * collectFoes = 0) const
Returns the information whether this link is blocked Valid after the vehicles have set their requests.
Parameters
[in] arrivalTime The arrivalTime of the vehicle who checks for an approaching foe
[in] leaveTime The leaveTime of the vehicle who checks for an approaching foe
[in] arrivalSpeed The speed with which the checking vehicle plans to arrive at the link
[in] leaveSpeed The speed with which the checking vehicle plans to leave the link
[in] sameTargetLane Whether the link that calls this method has the same target lane as this link
[in] impatience The impatience of the checking vehicle
[in] decel The maximum deceleration of the checking vehicle
[in] waitingTime The waiting time of the checking vehicle
[in] collectFoes If a vector is passed the return value is always False, instead all blocking foes are collected and inserted into this vector
Returns
Whether this link is blocked
Note
Since this needs to be called without a SUMOVehicle (TraCI), we cannot simply pass the checking vehicle itself
Definition at line 315 of file MSLink.cpp.
References LINKSTATE_ALLWAY_STOP, myApproachingVehicles, myLookaheadTime, myState, and unsafeMergeSpeeds().
MSLink::ApproachingVehicleInformation MSLink::getApproaching (const SUMOVehicle * veh) const
Definition at line 266 of file MSLink.cpp.
References myApproachingVehicles.
MSLane * MSLink::getApproachingLane () const
Returns the lane leading to this link.
Returns
The lane leading to this link
Definition at line 425 of file MSLink.cpp.
References MSLane::getIncomingLanes(), getIndex(), MSLane::getLinkCont(), myLane, toString(), and WRITE_WARNING.
Referenced by MSRailSignal::init().
LinkDirection MSLink::getDirection () const
Returns the direction the vehicle passing this link take.
Returns
The direction of this link
Definition at line 405 of file MSLink.cpp.
References myDirection.
Referenced by MSVehicle::executeMove(), and TraCIServerAPI_Lane::processGet().
int MSLink::getIndex () const inline
Returns the respond index (for visualization)
Returns
The respond index for this link
Definition at line 292 of file MSLink.h.
References myIndex.
Referenced by GUILane::drawLinkNo(), and getApproachingLane().
const MSJunction* MSLink::getJunction () const inline
return the junction to which this link belongs
Definition at line 367 of file MSLink.h.
References myJunction.
Referenced by MSVehicle::executeMove(), MSRailSignal::init(), and GUIVehicle::selectBlockingFoes().
MSLane * MSLink::getLane () const
Returns the connected lane.
Returns
The lane approached by this link
Definition at line 420 of file MSLink.cpp.
References myLane.
Referenced by MSVehicle::checkRewindLinkLanes(), Command_SaveTLSSwitches::execute(), MSLinkContHelper::getConnectingLink(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), and writeApproaching().
SUMOTime MSLink::getLastStateChange () const inline
Definition at line 254 of file MSLink.h.
References myLastStateChange.
SUMOTime MSLink::getLeaveTime (const SUMOTime arrivalTime, const SUMOReal arrivalSpeed, const SUMOReal leaveSpeed, const SUMOReal vehicleLength) const
return the expected time at which the given vehicle will clear the link
Definition at line 277 of file MSLink.cpp.
References getLength(), MAX2(), NUMERICAL_EPS, SUMOReal, and TIME2STEPS.
Referenced by opened(), and setApproaching().
SUMOReal MSLink::getLength () const inline
Returns the length of this link.
Returns
The length of this link
Definition at line 316 of file MSLink.h.
References myLength.
Referenced by MSVehicle::estimateLeaveSpeed(), getLeaveTime(), and TraCIServerAPI_Lane::processGet().
LinkState MSLink::getState () const inline
Returns the current state of the link.
Returns
The current state of this link
Definition at line 248 of file MSLink.h.
References myState.
Referenced by GUILane::drawLinkRule(), Command_SaveTLCoupledLaneDet::execute(), MSVehicle::executeMove(), MSLane::getIncomingLinkState(), and TraCIServerAPI_Lane::processGet().
MSLane * MSLink::getViaLaneOrLane () const
return the via lane if it exists and the lane otherwise
Definition at line 611 of file MSLink.cpp.
References myLane.
Referenced by GUIVehicle::drawGLAdditional(), MSVehicle::estimateLeaveSpeed(), MSVehicle::executeMove(), MSLinkContHelper::getConnectingLink(), MSPModel_Striping::getNextLane(), GUIVehicle::selectBlockingFoes(), and setRequestInformation().
bool MSLink::hasApproachingFoe (SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal speed, SUMOReal decel) const
Returns the information whether a vehicle is approaching on one of the link's foe streams.
Valid after the vehicles have set their requests
Parameters
[in] arrivalTime The arrivalTime of the vehicle who checks for an approaching foe
[in] leaveTime The leaveTime of the vehicle who checks for an approaching foe
[in] speed The speed with which the checking vehicle plans to leave the link
[in] decel The maximum deceleration of the checking vehicle
Returns
Whether a foe of this link is approaching
Definition at line 389 of file MSLink.cpp.
References myFoeLanes, myFoeLinks, and myLane.
Referenced by TraCIServerAPI_Lane::processGet().
bool MSLink::hasFoes () const inline
Returns whether this link belongs to a junction where more than one edge is incoming.
Returns
Whether any foe links exist
Definition at line 324 of file MSLink.h.
References myHasFoes.
Referenced by MSVehicle::checkRewindLinkLanes(), and setRequestInformation().
bool MSLink::havePriority () const inline
Returns whether this link is a major link.
Returns
Whether the link has a large priority
Definition at line 300 of file MSLink.h.
References myState.
Referenced by MSEdge::changeLanes(), MSVehicle::checkRewindLinkLanes(), GUILane::drawGL(), MSVehicle::executeMove(), lastWasContMajor(), and TraCIServerAPI_Lane::processGet().
bool MSLink::haveRed () const inline
Returns whether this link is blocked by a red (or redyellow) traffic light.
Returns
Whether the link has a red light
Definition at line 307 of file MSLink.h.
References LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, and myState.
Referenced by opened().
bool MSLink::isBlockingAnyone () const inline
Definition at line 224 of file MSLink.h.
References myApproachingVehicles.
bool MSLink::isCont () const inline
Definition at line 329 of file MSLink.h.
References myAmCont.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), and setRequestInformation().
bool MSLink::lastWasContMajor () const
whether this is a link past an internal junction which currently has priority
Definition at line 453 of file MSLink.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLane::getLogicalPredecessorLane(), MSEdge::getPurpose(), havePriority(), and myAmCont.
Referenced by MSVehicle::executeMove().
bool MSLink::maybeOccupied (MSLane * lane) static private
returns whether the given lane may still be occupied by a vehicle currently on it
Definition at line 368 of file MSLink.cpp.
References MSVehicle::getCarFollowModel(), MSLane::getLastVehicle(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), and SUMOReal.
bool MSLink::opened (SUMOTime arrivalTime, SUMOReal arrivalSpeed, SUMOReal leaveSpeed, SUMOReal vehicleLength, SUMOReal impatience, SUMOReal decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > * collectFoes = 0) const
Returns the information whether the link may be passed.
Valid after the junctions have set their reponds
Parameters
[in] collectFoes If a vector is passed, all blocking foes are collected and inserted into this vector
Returns
Whether this link may be passed.
Definition at line 284 of file MSLink.cpp.
References getLeaveTime(), MSGlobals::gUseMesoSim, MSGlobals::gUsingInternalLanes, haveRed(), LINKSTATE_ALLWAY_STOP, LINKSTATE_STOP, myAmCont, myFoeLinks, myLane, and myState.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSPModel_Striping::moveInDirectionOnLane(), TraCIServerAPI_Lane::processGet(), and GUIVehicle::selectBlockingFoes().
MSLink& MSLink::operator= (const MSLink & s) private
invalidated assignment operator
void MSLink::removeApproaching (const SUMOVehicle * veh)
removes the vehicle from myApproachingVehicles
Definition at line 260 of file MSLink.cpp.
References myApproachingVehicles.
Referenced by MSVehicle::executeMove().
void MSLink::setApproaching (const SUMOVehicle * approaching, const SUMOTime arrivalTime, const SUMOReal arrivalSpeed, const SUMOReal leaveSpeed, const bool setRequest, const SUMOTime arrivalTimeBraking, const SUMOReal arrivalSpeedBraking, const SUMOTime waitingTime)
Sets the information about an approaching vehicle.
The information is stored in myApproachingVehicles.
Definition at line 232 of file MSLink.cpp.
References getLeaveTime(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), and myApproachingVehicles.
void MSLink::setRequestInformation (int index, bool hasFoes, bool isCont, const std::vector< MSLink * > & foeLinks, const std::vector< MSLane * > & foeLanes, MSLane * internalLaneBefore = 0)
Sets the request information.
Because traffic lights and junction logics are loaded after links, we have to assign the information about the right-of-way requests and responses after the initialisation.
Todo:
Unsecure!
Definition at line 93 of file MSLink.cpp.
References MSLane::getEdge(), MSEdge::getFromJunction(), Named::getID(), MSLane::getIncomingLanes(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSLane::getShape(), getViaLaneOrLane(), MSLane::getWidth(), hasFoes(), MSLane::interpolateGeometryPosToLanePos(), PositionVector::intersectsAtLengths2D(), isCont(), MSEdge::isInternal(), myAmCont, myFoeLanes, myFoeLinks, myHasFoes, myIndex, myJunction, myLane, NUMERICAL_EPS, toString(), and UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
void MSLink::setTLState (LinkState state, SUMOTime t)
Sets the current tl-state.
Parameters
[in] state The current state of the link
[in] t The time of the state change
Definition at line 411 of file MSLink.cpp.
References myLastStateChange, and myState.
Referenced by MSTrafficLightLogic::addLink().
static bool MSLink::unsafeMergeSpeeds (SUMOReal leaderSpeed, SUMOReal followerSpeed, SUMOReal leaderDecel, SUMOReal followerDecel) inline static private
return whether the given vehicles may NOT merge safely
Definition at line 373 of file MSLink.h.
Referenced by blockedAtTime().
bool MSLink::willHaveBlockedFoe () const
Definition at line 249 of file MSLink.cpp.
References myBlockedFoeLinks.
void MSLink::writeApproaching (OutputDevice & od, const std::string fromLaneID) const
write information about all approaching vehicles to the given output device
Definition at line 476 of file MSLink.cpp.
References MSLink::ApproachingVehicleInformation::arrivalSpeed, MSLink::ApproachingVehicleInformation::arrivalSpeedBraking, MSLink::ApproachingVehicleInformation::arrivalTime, MSLink::ApproachingVehicleInformation::arrivalTimeBraking, OutputDevice::closeTag(), getLane(), MSLink::ApproachingVehicleInformation::leaveSpeed, MSLink::ApproachingVehicleInformation::leavingTime, myApproachingVehicles, OutputDevice::openTag(), SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_TO, SUMO_ATTR_VIA, time2string(), toString(), MSLink::ApproachingVehicleInformation::willPass, and OutputDevice::writeAttr().
Field Documentation
bool MSLink::myAmCont private
Definition at line 406 of file MSLink.h.
Referenced by isCont(), lastWasContMajor(), opened(), and setRequestInformation().
std::map<const SUMOVehicle*, ApproachingVehicleInformation> MSLink::myApproachingVehicles private
Definition at line 385 of file MSLink.h.
Referenced by blockedAtTime(), getApproaching(), isBlockingAnyone(), removeApproaching(), setApproaching(), and writeApproaching().
std::set<MSLink*> MSLink::myBlockedFoeLinks private
Definition at line 386 of file MSLink.h.
Referenced by addBlockedLink(), and willHaveBlockedFoe().
LinkDirection MSLink::myDirection private
An abstract (hopefully human readable) definition of the link's direction.
Definition at line 398 of file MSLink.h.
Referenced by getDirection().
std::vector<const MSLane*> MSLink::myFoeLanes private
Definition at line 427 of file MSLink.h.
Referenced by hasApproachingFoe(), and setRequestInformation().
std::vector<MSLink*> MSLink::myFoeLinks private
Definition at line 426 of file MSLink.h.
Referenced by hasApproachingFoe(), opened(), and setRequestInformation().
bool MSLink::myHasFoes private
Whether any foe links exist.
Definition at line 404 of file MSLink.h.
Referenced by hasFoes(), and setRequestInformation().
int MSLink::myIndex private
The position within this respond.
Definition at line 389 of file MSLink.h.
Referenced by getIndex(), and setRequestInformation().
const MSJunction* MSLink::myJunction private
the junction to which this link belongs
Definition at line 424 of file MSLink.h.
Referenced by getJunction(), and setRequestInformation().
MSLane* MSLink::myLane private
The lane (but the internal one) approached by this link.
Definition at line 383 of file MSLink.h.
Referenced by getApproachingLane(), getLane(), getViaLaneOrLane(), hasApproachingFoe(), opened(), and setRequestInformation().
SUMOTime MSLink::myLastStateChange private
The time of the last state change.
Definition at line 395 of file MSLink.h.
Referenced by getLastStateChange(), and setTLState().
SUMOReal MSLink::myLength private
The length of the link.
Definition at line 401 of file MSLink.h.
Referenced by getLength().
SUMOTime MSLink::myLookaheadTime = TIME2STEPS(1) static private
Definition at line 428 of file MSLink.h.
Referenced by blockedAtTime().
LinkState MSLink::myState private
The state of the link.
Definition at line 392 of file MSLink.h.
Referenced by blockedAtTime(), getState(), havePriority(), haveRed(), opened(), and setTLState().
The documentation for this class was generated from the following files:
MSLink.h
MSLink.cpp