SUMO - Simulation of Urban MObility: MSRailSignal Class Reference
MSRailSignal Class Reference
A signal for rails.
#include <MSRailSignal.h>
Public Types
Structure definitions
typedef std::vector
< MSPhaseDefinition * > Phases
Definition of a list of phases, being the junction logic.
typedef std::vector< MSLink * > LinkVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LinkVector > LinkVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector< MSLane * > LaneVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a list that holds lists of links that do have the same attribute.
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
const std::string & getID () const
Returns the id.
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
void init (NLDetectorBuilder &nb)
Initialises the rail signal with information about adjacent rail signals.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSRailSignal (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &subid, const std::map< std::string, std::string > &parameters)
Constructor.
void setID (const std::string &newID)
resets the id
~MSRailSignal ()
Destructor.
Handling of controlled links
void adaptLinkInformationFrom (const MSTrafficLightLogic &logic)
Applies information about controlled links and lanes from the given logic.
Switching and setting current rows
std::string getAppropriateState ()
returns the state of the signal that actually required
void updateCurrentPhase ()
updates the current phase of the signal
SUMOTime trySwitch ()
Switches to the next phase.
Static Information Retrieval
unsigned int getPhaseNumber () const
Returns the number of phases.
const Phases & getPhases () const
Returns the phases of this tls program.
const MSPhaseDefinition & getPhase (unsigned int givenstep) const
Returns the definition of the phase from the given position within the plan.
const std::string getLogicType () const
Returns the type of the logic as a string.
Dynamic Information Retrieval
unsigned int getCurrentPhaseIndex () const
Returns the current index within the program.
const MSPhaseDefinition & getCurrentPhaseDef () const
Returns the definition of the current phase.
Conversion between time and phase
SUMOTime getPhaseIndexAtTime (SUMOTime simStep) const
Returns the index of the logic at the given simulation step.
SUMOTime getOffsetFromIndex (unsigned int index) const
Returns the position (start of a phase during a cycle) from of a given step.
unsigned int getIndexFromOffset (SUMOTime offset) const
Returns the step (the phasenumber) of a given position of the cycle.
Changing phases and phase durations
void changeStepAndDuration (MSTLLogicControl &tlcontrol, SUMOTime simStep, unsigned int step, SUMOTime stepDuration)
Changes the current phase and her duration.
Handling of controlled links
void addLink (MSLink *link, MSLane *lane, unsigned int pos)
Adds a link on building.
std::map< MSLink *, LinkState > collectLinkStates () const
Returns the (uncontrolled) states of the controlled links.
void resetLinkStates (const std::map< MSLink *, LinkState > &vals) const
Resets the states of controlled links.
Switching and setting current rows
bool setTrafficLightSignals (SUMOTime t) const
Applies the current signal states to controlled links.
Static Information Retrieval
const std::string & getProgramID () const
Returns this tl-logic's id.
const LaneVectorVector & getLaneVectors () const
Returns the list of lists of all lanes controlled by this tls.
const LaneVector & getLanesAt (unsigned int i) const
Returns the list of lanes that are controlled by the signals at the given position.
const LinkVectorVector & getLinks () const
Returns the list of lists of all affected links.
const LinkVector & getLinksAt (unsigned int i) const
Returns the list of links that are controlled by the signals at the given position.
int getLinkIndex (const MSLink *const link) const
Returns the index of the given link.
Dynamic Information Retrieval
SUMOTime getDefaultCycleTime () const
Returns the cycle time (in ms)
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
Changing phases and phase durations
void addOverridingDuration (SUMOTime duration)
Changes the duration of the next phase.
void setCurrentDurationIncrement (SUMOTime delay)
Delays current phase by the given delay.
Protected Attributes
std::map< MSLink
*, std::vector< MSLane * > > myAfferentBlocks
A map that maps a link from the junction to its vector of lanes leading from a previous signal to this link.
SUMOTime myCurrentDurationIncrement
A value for enlarge the current duration.
MSPhaseDefinition myCurrentPhase
The current phase.
SUMOTime myDefaultCycleTime
The cycle time (without changes)
std::string myID
The name of the object.
LaneVectorVector myLanes
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
std::map< MSLink *, unsigned int > myLinkIndices
A map that maps a link to its link index.
LinkVectorVector myLinks
The list of LinkVectors; each vector contains the links that belong to the same link index.
std::map< MSLane
*, std::vector< MSLink * > > myLinksToLane
A map that maps an outgoing lane from the junction to its set of links that lead to this lane.
std::vector< MSLane * > myOutgoingLanes
The set of lanes going out from the junction.
std::vector< SUMOTime > myOverridingTimes
A list of duration overrides.
Phases myPhases
The list of phases this logic uses.
std::string myProgramID
The id of the logic.
std::map< MSLane
*, std::vector< const MSLane * > > mySucceedingBlocks
A map that maps an outgoing lane from the junction to its vector of lanes leading to the next signal.
SwitchCommand * mySwitchCommand
The current switch command.
Static Protected Attributes
static const LaneVector myEmptyLaneVector
An empty lane vector.
Detailed Description
A signal for rails.
Definition at line 54 of file MSRailSignal.h.
Member Typedef Documentation
typedef std::vector<MSLane*> MSTrafficLightLogic::LaneVector inherited
Definition of the list of links that participate in this tl-light.
Definition at line 78 of file MSTrafficLightLogic.h.
typedef std::vector<LaneVector> MSTrafficLightLogic::LaneVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 81 of file MSTrafficLightLogic.h.
typedef std::vector<MSLink*> MSTrafficLightLogic::LinkVector inherited
Definition of the list of links that participate in this tl-light.
Definition at line 72 of file MSTrafficLightLogic.h.
typedef std::vector<LinkVector> MSTrafficLightLogic::LinkVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 75 of file MSTrafficLightLogic.h.
typedef std::vector<MSPhaseDefinition*> MSTrafficLightLogic::Phases inherited
Definition of a list of phases, being the junction logic.
Definition at line 69 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
MSRailSignal::MSRailSignal (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & subid, const std::map< std::string, std::string > & parameters)
Constructor.
Parameters
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] subid This tls' sub-id (program id)
[in] parameters This tls' parameters
Definition at line 54 of file MSRailSignal.cpp.
References DELTA_T, and MSTrafficLightLogic::myDefaultCycleTime.
MSRailSignal::~MSRailSignal ()
Destructor.
Definition at line 149 of file MSRailSignal.cpp.
Member Function Documentation
void MSRailSignal::adaptLinkInformationFrom (const MSTrafficLightLogic & logic) virtual
Applies information about controlled links and lanes from the given logic.
Parameters
[in] logic The logic to use the information about controlled links/lanes from
See Also
MSTrafficLightLogic::adaptLinkInformationFrom
Reimplemented from MSTrafficLightLogic.
Definition at line 154 of file MSRailSignal.cpp.
References MSTrafficLightLogic::adaptLinkInformationFrom(), and updateCurrentPhase().
void MSTrafficLightLogic::addLink (MSLink * link, MSLane * lane, unsigned int pos) inherited
Adds a link on building.
Parameters
[in] link The controlled link
[in] lane The lane this link starts at
[in] pos The link's index (signal group) within this program
Definition at line 163 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, and MSLink::setTLState().
void MSTrafficLightLogic::addOverridingDuration (SUMOTime duration) inherited
Changes the duration of the next phase.
Parameters
[in] duration The new duration
Definition at line 254 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myOverridingTimes.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
void MSRailSignal::changeStepAndDuration (MSTLLogicControl & tlcontrol, SUMOTime simStep, unsigned int step, SUMOTime stepDuration) inline virtual
Changes the current phase and her duration.
Parameters
[in] tlcontrol The responsible traffic lights control
[in] simStep The current simulation step
[in] step Index of the phase to use
[in] stepDuration The left duration of the phase
See Also
MSTrafficLightLogic::changeStepAndDuration
Implements MSTrafficLightLogic.
Definition at line 202 of file MSRailSignal.h.
References UNUSED_PARAMETER.
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
std::map< MSLink *, LinkState > MSTrafficLightLogic::collectLinkStates () const inherited
Returns the (uncontrolled) states of the controlled links.
Returns
The controlled link's states
Definition at line 188 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
std::string MSRailSignal::getAppropriateState ()
returns the state of the signal that actually required
Returns the state of the rail signal that is actually required based on the occupation of the adjoining blocks.
Returns
The state actually required for this signal.
Definition at line 169 of file MSRailSignal.cpp.
References myAfferentBlocks, myLinkIndices, MSTrafficLightLogic::myLinks, myLinksToLane, myOutgoingLanes, and mySucceedingBlocks.
Referenced by updateCurrentPhase().
const MSPhaseDefinition & MSRailSignal::getCurrentPhaseDef () const virtual
Returns the definition of the current phase.
Returns
The current phase
Implements MSTrafficLightLogic.
Definition at line 257 of file MSRailSignal.cpp.
References myCurrentPhase.
unsigned int MSRailSignal::getCurrentPhaseIndex () const virtual
Returns the current index within the program.
Returns
The index of the current phase within the tls (here, always zero will be returned)
See Also
MSTrafficLightLogic::getCurrentPhaseIndex
Implements MSTrafficLightLogic.
Definition at line 252 of file MSRailSignal.cpp.
SUMOTime MSTrafficLightLogic::getDefaultCycleTime () const inline inherited
Returns the cycle time (in ms)
Returns
The (maybe changing) cycle time of this tls
Definition at line 268 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myDefaultCycleTime.
Referenced by MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
unsigned int MSRailSignal::getIndexFromOffset (SUMOTime offset) const virtual
Returns the step (the phasenumber) of a given position of the cycle.
Parameters
[in] offset The offset (time) for which the according phase shall be returned
Returns
The according phase (here, always zero will be returned)
See Also
MSTrafficLightLogic::getIndexFromOffset
Implements MSTrafficLightLogic.
Definition at line 273 of file MSRailSignal.cpp.
const LaneVector& MSTrafficLightLogic::getLanesAt (unsigned int i) const inline inherited
Returns the list of lanes that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The lanes controlled by the signal at the given index
Definition at line 191 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myEmptyLaneVector, and MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::drawGL(), Command_SaveTLSSwitches::execute(), MSActuatedTrafficLightLogic::gapControl(), and GUIViewTraffic::onGamingClick().
const LaneVectorVector& MSTrafficLightLogic::getLaneVectors () const inline inherited
Returns the list of lists of all lanes controlled by this tls.
Returns
All lanes controlled by this tls, sorted by the signal index
Definition at line 182 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::getCenteringBoundary(), TraCIServerAPI_TLS::processGet(), and MSFullExport::writeTLS().
int MSTrafficLightLogic::getLinkIndex (const MSLink *const link) const inherited
Returns the index of the given link.
Parameters
[in] link The link to retrieve the index for
Returns
The index of the given link (-1 if it is not controlled by this tls)
Definition at line 230 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by GUITrafficLightLogicWrapper::getLinkIndex().
const LinkVectorVector& MSTrafficLightLogic::getLinks () const inline inherited
Returns the list of lists of all affected links.
Returns
All links controlled by this tls, sorted by the signal index
Definition at line 203 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUINet::createTLWrapper(), GUITLLogicPhasesTrackerWindow::drawValues(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), TraCIServerAPI_TLS::processGet(), and MSOffTrafficLightLogic::rebuildPhase().
const LinkVector& MSTrafficLightLogic::getLinksAt (unsigned int i) const inline inherited
Returns the list of links that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The links controlled by the signal at the given index
Definition at line 212 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
const std::string MSRailSignal::getLogicType () const inline virtual
Returns the type of the logic as a string.
Returns
The type of the logic
Implements MSTrafficLightLogic.
Definition at line 142 of file MSRailSignal.h.
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), TraCIServerAPI_TLS::processGet(), PCPolyContainer::save(), ROVehicle::saveAllAsXML(), SUMOVTypeParameter::write(), and SUMO::Polygon::writeXML().
SUMOTime MSTrafficLightLogic::getNextSwitchTime () const inherited
Returns the assumed next switch time.
The time may change in case of adaptive/actuated traffic lights.
Returns
The assumed next switch time (simulation time)
Definition at line 247 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::SwitchCommand::getNextSwitchTime(), and MSTrafficLightLogic::mySwitchCommand.
Referenced by MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), and TraCIServerAPI_TLS::processGet().
SUMOTime MSRailSignal::getOffsetFromIndex (unsigned int index) const virtual
Returns the position (start of a phase during a cycle) from of a given step.
Parameters
[in] index The index of the phase to return the begin of
Returns
The begin time of the phase (here, always zero will be returned)
See Also
MSTrafficLightLogic::getOffsetFromIndex
Implements MSTrafficLightLogic.
Definition at line 268 of file MSRailSignal.cpp.
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
const MSPhaseDefinition & MSRailSignal::getPhase (unsigned int givenstep) const virtual
Returns the definition of the phase from the given position within the plan.
Returns the current phase as there does not exist a plan of the phases.
Parameters
[in] givenstep The index of the phase within the plan
Returns
The definition of the phase at the given position
See Also
MSTrafficLightLogic::getPhase
Implements MSTrafficLightLogic.
Definition at line 246 of file MSRailSignal.cpp.
References myCurrentPhase.
SUMOTime MSRailSignal::getPhaseIndexAtTime (SUMOTime simStep) const virtual
Returns the index of the logic at the given simulation step.
Returns
The (estimated) index of the tls at the given simulation time step (here, always zero will be returned)
See Also
MSTrafficLightLogic::getPhaseIndexAtTime
Implements MSTrafficLightLogic.
Definition at line 263 of file MSRailSignal.cpp.
unsigned int MSRailSignal::getPhaseNumber () const virtual
Returns the number of phases.
Returns
The number of this tls program's phases (always zero)
See Also
MSTrafficLightLogic::getPhaseNumber
Implements MSTrafficLightLogic.
Definition at line 236 of file MSRailSignal.cpp.
const MSTrafficLightLogic::Phases & MSRailSignal::getPhases () const virtual
Returns the phases of this tls program.
Returns
The phases of this tls program
See Also
MSTrafficLightLogic::getPhases
Implements MSTrafficLightLogic.
Definition at line 241 of file MSRailSignal.cpp.
References myPhases.
const std::string& MSTrafficLightLogic::getProgramID () const inline inherited
Returns this tl-logic's id.
Returns
This program's id
Definition at line 174 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myProgramID.
Referenced by Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSTrafficLightLogic::init(), GUIViewTraffic::onGamingClick(), and TraCIServerAPI_TLS::processGet().
void MSRailSignal::init (NLDetectorBuilder & nb) virtual
Initialises the rail signal with information about adjacent rail signals.
Parameters
[in] nb The detector builder
Exceptions
ProcessError If something fails on initialisation
Reimplemented from MSTrafficLightLogic.
Definition at line 63 of file MSRailSignal.cpp.
References MSLink::getApproachingLane(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), Named::getID(), MSLane::getIncomingLanes(), MSNet::getInstance(), MSLink::getJunction(), MSLink::getLane(), MSLane::getLinkCont(), MSLane::getOutgoingLanes(), MSEdge::getToJunction(), MSJunction::getType(), myAfferentBlocks, MSTrafficLightLogic::myLanes, myLinkIndices, MSTrafficLightLogic::myLinks, myLinksToLane, myOutgoingLanes, mySucceedingBlocks, NODETYPE_RAIL_SIGNAL, MSTrafficLightLogic::setTrafficLightSignals(), updateCurrentPhase(), and WRITE_WARNING.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void MSTrafficLightLogic::resetLinkStates (const std::map< MSLink *, LinkState > & vals) const inherited
Resets the states of controlled links.
Parameters
[in] vals The state of controlled links to use
Definition at line 217 of file MSTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::myLinks.
void MSTrafficLightLogic::setCurrentDurationIncrement (SUMOTime delay) inherited
Delays current phase by the given delay.
Parameters
[in] delay The time by which the current phase shall be delayed
Definition at line 260 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myCurrentDurationIncrement.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
bool MSTrafficLightLogic::setTrafficLightSignals (SUMOTime t) const inherited
Applies the current signal states to controlled links.
Parameters
[in] t The current time
Returns
Always true
See Also
LinkState
MSLink::setTLState
Definition at line 201 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSSimpleTrafficLightLogic::changeStepAndDuration(), init(), and trySwitch().
SUMOTime MSRailSignal::trySwitch () virtual
Switches to the next phase.
Returns
The time of the next switch (always the next step)
See Also
MSTrafficLightLogic::trySwitch
Implements MSTrafficLightLogic.
Definition at line 162 of file MSRailSignal.cpp.
References DELTA_T, MSNet::getInstance(), MSTrafficLightLogic::setTrafficLightSignals(), and updateCurrentPhase().
void MSRailSignal::updateCurrentPhase ()
updates the current phase of the signal
Definition at line 229 of file MSRailSignal.cpp.
References DELTA_T, getAppropriateState(), and myCurrentPhase.
Referenced by adaptLinkInformationFrom(), init(), and trySwitch().
Field Documentation
std::map<MSLink*, std::vector<MSLane*> > MSRailSignal::myAfferentBlocks protected
A map that maps a link from the junction to its vector of lanes leading from a previous signal to this link.
Definition at line 222 of file MSRailSignal.h.
Referenced by getAppropriateState(), and init().
SUMOTime MSTrafficLightLogic::myCurrentDurationIncrement protected inherited
A value for enlarge the current duration.
Definition at line 411 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::setCurrentDurationIncrement(), and MSSimpleTrafficLightLogic::trySwitch().
MSPhaseDefinition MSRailSignal::myCurrentPhase protected
The current phase.
Definition at line 237 of file MSRailSignal.h.
Referenced by getCurrentPhaseDef(), getPhase(), and updateCurrentPhase().
SUMOTime MSTrafficLightLogic::myDefaultCycleTime protected inherited
The cycle time (without changes)
Definition at line 417 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getDefaultCycleTime(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSOffTrafficLightLogic::MSOffTrafficLightLogic(), MSRailSignal(), and MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic().
const MSTrafficLightLogic::LaneVector MSTrafficLightLogic::myEmptyLaneVector static protected inherited
An empty lane vector.
Definition at line 420 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getLanesAt().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
LaneVectorVector MSTrafficLightLogic::myLanes protected inherited
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
Definition at line 405 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSTrafficLightLogic::getLanesAt(), MSTrafficLightLogic::getLaneVectors(), init(), MSActuatedTrafficLightLogic::init(), and MSTrafficLightLogic::init().
std::map<MSLink*, unsigned int> MSRailSignal::myLinkIndices protected
A map that maps a link to its link index.
Definition at line 216 of file MSRailSignal.h.
Referenced by getAppropriateState(), and init().
LinkVectorVector MSTrafficLightLogic::myLinks protected inherited
The list of LinkVectors; each vector contains the links that belong to the same link index.
Definition at line 402 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSTrafficLightLogic::collectLinkStates(), getAppropriateState(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), init(), MSTrafficLightLogic::resetLinkStates(), and MSTrafficLightLogic::setTrafficLightSignals().
std::map<MSLane*, std::vector<MSLink*> > MSRailSignal::myLinksToLane protected
A map that maps an outgoing lane from the junction to its set of links that lead to this lane.
Definition at line 219 of file MSRailSignal.h.
Referenced by getAppropriateState(), and init().
std::vector<MSLane*> MSRailSignal::myOutgoingLanes protected
The set of lanes going out from the junction.
Definition at line 213 of file MSRailSignal.h.
Referenced by getAppropriateState(), and init().
std::vector<SUMOTime> MSTrafficLightLogic::myOverridingTimes protected inherited
A list of duration overrides.
Definition at line 408 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::addOverridingDuration(), and MSSimpleTrafficLightLogic::trySwitch().
Phases MSRailSignal::myPhases protected
The list of phases this logic uses.
This vector is always empty and only constructed because the superclass MSTrafficLightLogic requires it.
Definition at line 234 of file MSRailSignal.h.
Referenced by getPhases().
std::string MSTrafficLightLogic::myProgramID protected inherited
The id of the logic.
Definition at line 399 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getProgramID(), and MSActuatedTrafficLightLogic::init().
std::map<MSLane*, std::vector<const MSLane*> > MSRailSignal::mySucceedingBlocks protected
A map that maps an outgoing lane from the junction to its vector of lanes leading to the next signal.
Definition at line 225 of file MSRailSignal.h.
Referenced by getAppropriateState(), and init().
SwitchCommand* MSTrafficLightLogic::mySwitchCommand protected inherited
The current switch command.
Definition at line 414 of file MSTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getNextSwitchTime(), and MSTrafficLightLogic::MSTrafficLightLogic().
The documentation for this class was generated from the following files:
MSRailSignal.h
MSRailSignal.cpp