SUMO - Simulation of Urban MObility: GL2PSbackend Struct Reference
GL2PSbackend Struct Reference
Data Fields
void(* beginViewport)(GLint viewport[4])
const char * description
GLint(* endViewport)(void)
const char * file_extension
void(* printFinalPrimitive)(void)
void(* printFooter)(void)
void(* printHeader)(void)
void(* printPrimitive)(void *data)
Detailed Description
Definition at line 249 of file gl2ps.c.
Field Documentation
void(* GL2PSbackend::beginViewport)(GLint viewport[4])
Definition at line 252 of file gl2ps.c.
Referenced by gl2psBeginViewport().
const char* GL2PSbackend::description
Definition at line 257 of file gl2ps.c.
Referenced by gl2psGetFormatDescription().
GLint(* GL2PSbackend::endViewport)(void)
Definition at line 253 of file gl2ps.c.
Referenced by gl2psEndViewport().
const char* GL2PSbackend::file_extension
Definition at line 256 of file gl2ps.c.
Referenced by gl2psGetFileExtension().
void(* GL2PSbackend::printFinalPrimitive)(void)
Definition at line 255 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
void(* GL2PSbackend::printFooter)(void)
Definition at line 251 of file gl2ps.c.
Referenced by gl2psEndPage().
void(* GL2PSbackend::printHeader)(void)
Definition at line 250 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
void(* GL2PSbackend::printPrimitive)(void *data)
Definition at line 254 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
The documentation for this struct was generated from the following file:
gl2ps.c