SUMO - Simulation of Urban MObility: SUMOVehicle Class Reference
SUMOVehicle Class Reference abstract
Representation of a vehicle.
#include <SUMOVehicle.h>
Public Member Functions
virtual void addContainer (MSContainer *container)=0
Adds a container to this vehicle.
virtual void addPerson (MSPerson *person)=0
Adds a person to this vehicle.
virtual bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0)=0
Adds a stop.
virtual SUMOReal getAcceleration () const =0
Returns the vehicle's acceleration.
virtual SUMOReal getAngle () const =0
Get the vehicle's angle.
virtual SUMOReal getArrivalPos () const =0
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
virtual SUMOReal getChosenSpeedFactor () const =0
virtual const
ConstMSEdgeVector::const_iterator & getCurrentRouteEdge () const =0
Returns an iterator pointing to the current edge in this vehicles route.
virtual SUMOTime getDeparture () const =0
Returns this vehicle's real departure time.
virtual MSDevice * getDevice (const std::type_info &type) const =0
Returns a device of the given type if it exists or 0.
virtual const std::vector
< MSDevice * > & getDevices () const =0
Returns this vehicle's devices.
virtual const MSEdge * getEdge () const =0
Returns the edge the vehicle is currently at.
virtual const std::string & getID () const =0
Get the vehicle's ID.
virtual SUMOReal getImpatience () const =0
Returns this vehicles impatience.
virtual SUMOReal getMaxSpeed () const =0
Returns the vehicle's maximum speed.
virtual unsigned int getNumberReroutes () const =0
Returns the number of new routes this vehicle got.
virtual const
SUMOVehicleParameter & getParameter () const =0
Returns the vehicle's parameter (including departure definition)
virtual Position getPosition (const SUMOReal offset=0) const =0
Return current position (x/y, cartesian)
virtual SUMOReal getPositionOnLane () const =0
Get the vehicle's position along the lane.
virtual const MSRoute & getRoute () const =0
Returns the current route.
virtual SUMOReal getSlope () const =0
Returns the slope of the road at vehicle's position.
virtual SUMOReal getSpeed () const =0
Returns the vehicle's current speed.
virtual SUMOVehicleClass getVClass () const =0
Returns the vehicle's access class.
virtual const MSVehicleType & getVehicleType () const =0
Returns the vehicle's type.
virtual SUMOTime getWaitingTime () const =0
virtual bool hasArrived () const =0
Returns whether this vehicle has arrived.
virtual bool hasDeparted () const =0
Returns whether this vehicle has departed.
virtual bool isOnRoad () const =0
Returns the information whether the vehicle is on a road (is simulated)
virtual bool isStopped () const =0
Returns whether the vehicle is at a stop.
virtual bool isStoppedTriggered () const =0
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
virtual void onDepart ()=0
Called when the vehicle is inserted into the network.
virtual bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0)=0
Replaces the current route by the given one.
virtual bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false)=0
Replaces the current route by the given edges.
virtual void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)=0
Performs a rerouting using the given router.
virtual void setChosenSpeedFactor (const SUMOReal factor)=0
virtual const MSEdge * succEdge (unsigned int nSuccs) const =0
Returns the nSuccs'th successor of edge the vehicle is currently at.
virtual ~SUMOVehicle ()
Destructor.
state io
virtual void saveState (OutputDevice &out)=0
Saves the states of a vehicle.
virtual void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)=0
Loads the state of this vehicle from the given description.
Detailed Description
Representation of a vehicle.
Definition at line 65 of file SUMOVehicle.h.
Constructor & Destructor Documentation
virtual SUMOVehicle::~SUMOVehicle () inline virtual
Destructor.
Definition at line 68 of file SUMOVehicle.h.
Member Function Documentation
virtual void SUMOVehicle::addContainer (MSContainer * container) pure virtual
Adds a container to this vehicle.
May do nothing since containers are not supported by default
Parameters
[in] container The container to add
Implemented in MSVehicle, and MSBaseVehicle.
virtual void SUMOVehicle::addPerson (MSPerson * person) pure virtual
Adds a person to this vehicle.
May do nothing since persons are not supported by default
Parameters
[in] person The person to add
Implemented in MSVehicle, and MSBaseVehicle.
virtual bool SUMOVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0) pure virtual
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implemented in MSVehicle.
Referenced by MSBaseVehicle::addStops().
virtual SUMOReal SUMOVehicle::getAcceleration () const pure virtual
Returns the vehicle's acceleration.
Returns
The acceleration
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getAngle () const pure virtual
Get the vehicle's angle.
Returns
The angle of the vehicle (in degree)
Implemented in MSVehicle.
Referenced by MSEmissionExport::write(), MSFCDExport::write(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getArrivalPos () const pure virtual
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::notifyLeave().
virtual SUMOReal SUMOVehicle::getChosenSpeedFactor () const pure virtual
Implemented in MSBaseVehicle.
Referenced by MSLane::getVehicleMaxSpeed(), and MSVehicleControl::vehicleDeparted().
virtual const ConstMSEdgeVector::const_iterator& SUMOVehicle::getCurrentRouteEdge () const pure virtual
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput().
virtual SUMOTime SUMOVehicle::getDeparture () const pure virtual
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::generateOutput(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::vehicleDeparted(), and MSAmitranTrajectories::writeVehicle().
virtual MSDevice* SUMOVehicle::getDevice (const std::type_info & type) const pure virtual
Returns a device of the given type if it exists or 0.
Implemented in MSBaseVehicle.
Referenced by MSInsertionControl::checkCandidates(), and MSDevice_Example::notifyMove().
virtual const std::vector<MSDevice*>& SUMOVehicle::getDevices () const pure virtual
Returns this vehicle's devices.
Returns
This vehicle's devices
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), and MSVehicleControl::scheduleVehicleRemoval().
virtual const MSEdge* SUMOVehicle::getEdge () const pure virtual
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), MSInsertionControl::checkCandidates(), MSDevice_Tripinfo::generateOutput(), MSEdge::insertVehicle(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Container::notifyMove(), MSDevice_Person::notifyMove(), MSDevice_Tripinfo::notifyMove(), and MSInsertionControl::tryInsert().
virtual const std::string& SUMOVehicle::getID () const pure virtual
Get the vehicle's ID.
Returns
The the ID of the vehicle
Implemented in MSBaseVehicle.
Referenced by MSDevice_Container::buildVehicleDevices(), MSDevice_Tripinfo::buildVehicleDevices(), MSDevice_Person::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_Vehroutes::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSInductLoop::collectVehiclesOnDet(), MSVehicleControl::deleteVehicle(), MSE3Collector::enter(), MSDevice::equippedByDefaultAssignmentOptions(), MSVTypeProbe::execute(), MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::generateOutput(), TraCIServerAPI_Vehicle::getSingularType(), MSEdge::insertVehicle(), MSE3Collector::leave(), MSInductLoop::leaveDetectorByMove(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSLane::succLinkSec(), TraCIServer::vehicleStateChanged(), MSFCDExport::write(), MSEmissionExport::write(), MSInstantInductLoop::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getImpatience () const pure virtual
Returns this vehicles impatience.
Implemented in MSBaseVehicle.
virtual SUMOReal SUMOVehicle::getMaxSpeed () const pure virtual
Returns the vehicle's maximum speed.
Returns
The vehicle's maximum speed
Implemented in MSBaseVehicle.
Referenced by MSEdge::getMinimumTravelTime(), and MSDevice_Tripinfo::notifyMove().
virtual unsigned int SUMOVehicle::getNumberReroutes () const pure virtual
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), and MSDevice_Vehroutes::writeXMLRoute().
virtual const SUMOVehicleParameter& SUMOVehicle::getParameter () const pure virtual
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implemented in MSBaseVehicle.
Referenced by MSVehicleContainer::add(), MSDevice_Example::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSRouteHandler::closeVehicle(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::generateOutput(), MSVehicleControl::getWaitingVehicle(), MSEdge::insertVehicle(), MSDevice_Routing::MSDevice_Routing(), MSDevice_Vehroutes::notifyEnter(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSInsertionControl::tryInsert(), and MSVehicleControl::vehicleDeparted().
virtual Position SUMOVehicle::getPosition (const SUMOReal offset = 0) const pure virtual
Return current position (x/y, cartesian)
If the vehicle is not in the net, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See Also
myLane
Implemented in MSVehicle.
Referenced by MSVTypeProbe::execute(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSFCDExport::write(), MSEmissionExport::write(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getPositionOnLane () const pure virtual
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implemented in MSVehicle.
Referenced by MSVTypeProbe::execute(), MSDevice_Tripinfo::generateOutput(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSE2Collector::by_vehicle_position_sorter::operator()(), MSFCDExport::write(), MSEmissionExport::write(), MSXMLRawOut::writeVehicle(), and MSFullExport::writeVehicles().
virtual const MSRoute& SUMOVehicle::getRoute () const pure virtual
Returns the current route.
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), MSRouteHandler::closeVehicle(), MSDevice_Tripinfo::generateOutput(), MSTriggeredRerouter::getCurrentReroute(), MSRouteProbe::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), MSEmissionExport::write(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getSlope () const pure virtual
Returns the slope of the road at vehicle's position.
Returns
The slope
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSFCDExport::write(), and MSFullExport::writeVehicles().
virtual SUMOReal SUMOVehicle::getSpeed () const pure virtual
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implemented in MSVehicle.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSE3Collector::detectorUpdate(), MSE3Collector::enter(), MSVTypeProbe::execute(), MSE3Collector::leave(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSInstantInductLoop::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSFCDExport::write(), MSEmissionExport::write(), MSAmitranTrajectories::writeVehicle(), MSXMLRawOut::writeVehicle(), and MSFullExport::writeVehicles().
virtual SUMOVehicleClass SUMOVehicle::getVClass () const pure virtual
Returns the vehicle's access class.
Returns
The vehicle's access class
Implemented in MSBaseVehicle.
Referenced by MSDevice_Routing::reroute().
virtual const MSVehicleType& SUMOVehicle::getVehicleType () const pure virtual
Returns the vehicle's type.
Returns
The vehicle's type
Implemented in MSBaseVehicle.
Referenced by MSDevice_Example::buildVehicleDevices(), MSInductLoop::collectVehiclesOnDet(), MSDevice::equippedByDefaultAssignmentOptions(), MSVTypeProbe::execute(), MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::generateOutput(), MSBusStop::getLastFreePos(), MSContainerStop::getLastFreePos(), TraCIServerAPI_Vehicle::getSingularType(), MSEdge::insertVehicle(), MSInductLoop::leaveDetectorByMove(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSInstantInductLoop::notifyMove(), MSDevice_Emissions::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSEdge::prohibits(), MSLink::setApproaching(), MSLane::succLinkSec(), MSMeanData::MeanDataValues::vehicleApplies(), MSVehicleControl::vehicleDeparted(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
virtual SUMOTime SUMOVehicle::getWaitingTime () const pure virtual
Implemented in MSVehicle.
Referenced by MSBaseVehicle::getImpatience().
virtual bool SUMOVehicle::hasArrived () const pure virtual
Returns whether this vehicle has arrived.
Implemented in MSBaseVehicle, and MSVehicle.
Referenced by MSDevice_Vehroutes::generateOutput(), and MSMeanData::MeanDataValues::notifyMove().
virtual bool SUMOVehicle::hasDeparted () const pure virtual
Returns whether this vehicle has departed.
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), and MSDevice_Tripinfo::generateOutputForUnfinished().
virtual bool SUMOVehicle::isOnRoad () const pure virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSVTypeProbe::execute(), GUIVehicleControl::insertVehicleIDs(), MSE2Collector::notifyEnter(), MSFCDExport::write(), MSEmissionExport::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
virtual bool SUMOVehicle::isStopped () const pure virtual
Returns whether the vehicle is at a stop.
Returns
Whether the has stopped
Implemented in MSVehicle.
Referenced by MSDevice_Container::notifyMove(), and MSDevice_Person::notifyMove().
virtual bool SUMOVehicle::isStoppedTriggered () const pure virtual
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
Implemented in MSVehicle.
virtual void SUMOVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) pure virtual
Loads the state of this vehicle from the given description.
Implemented in MSVehicle.
Referenced by MSStateHandler::myStartElement().
virtual void SUMOVehicle::onDepart () pure virtual
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implemented in MSBaseVehicle.
Referenced by MSInsertionControl::tryInsert().
virtual bool SUMOVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0) pure virtual
Replaces the current route by the given one.
Implemented in MSVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), and MSBaseVehicle::replaceRouteEdges().
virtual bool SUMOVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false) pure virtual
Replaces the current route by the given edges.
Implemented in MSBaseVehicle.
virtual void SUMOVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) pure virtual
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See Also
replaceRoute
Implemented in MSBaseVehicle.
Referenced by MSDevice_Routing::reroute().
virtual void SUMOVehicle::saveState (OutputDevice & out) pure virtual
Saves the states of a vehicle.
Implemented in MSVehicle, and MSBaseVehicle.
virtual void SUMOVehicle::setChosenSpeedFactor (const SUMOReal factor) pure virtual
Implemented in MSBaseVehicle.
Referenced by MSEdge::insertVehicle().
virtual const MSEdge* SUMOVehicle::succEdge (unsigned int nSuccs) const pure virtual
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) than nSuccs, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implemented in MSBaseVehicle.
Referenced by MSLane::succLinkSec().
The documentation for this class was generated from the following file:
SUMOVehicle.h