SUMO - Simulation of Urban MObility: GUIGlObject_AbstractAdd Class Reference
GUIGlObject_AbstractAdd Class Reference abstract
#include <GUIGlObject_AbstractAdd.h>
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
GUIGlObject_AbstractAdd (const std::string &prefix, GUIGlObjectType type, const std::string &id)
~GUIGlObject_AbstractAdd ()
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)=0
Returns an own popup-menu.
virtual GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)=0
Returns an own parameter window.
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
virtual Boundary getCenteringBoundary () const =0
Returns the boundary to which the view shall be centered in order to show the object.
virtual void drawGL (const GUIVisualizationSettings &s) const =0
Draws the object.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector
< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Attributes
static std::vector
< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string,
GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Detailed Description
Definition at line 47 of file GUIGlObject_AbstractAdd.h.
Constructor & Destructor Documentation
GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd (const std::string & prefix, GUIGlObjectType type, const std::string & id)
Definition at line 54 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), myObjectList, and myObjects.
GUIGlObject_AbstractAdd::~GUIGlObject_AbstractAdd ()
Definition at line 61 of file GUIGlObject_AbstractAdd.cpp.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 65 of file GUIGlObject_AbstractAdd.cpp.
References myObjectList, and myObjects.
Referenced by GUINet::~GUINet().
virtual void GUIGlObject::drawGL (const GUIVisualizationSettings & s) const pure virtual inherited
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
Implemented in GUILane, GUIInductLoop::MyWrapper, GUITriggeredRerouter::GUITriggeredRerouterEdge, GUINet, GUIEdge, GUI_E2_ZS_Collector::MyWrapper, GUIBusStop, GUIContainerStop, GUIE3Collector::MyWrapper, GUI_E2_ZS_CollectorOverLanes::MyWrapper, GUITriggeredRerouter, GUIVehicle, GUIJunctionWrapper, GUIPointOfInterest, GUICalibrator, GUIInstantInductLoop::MyWrapper, GUILaneSpeedTrigger, GUIPolygon, GUIPerson, GUIContainer, and GUITrafficLightLogicWrapper.
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIEdge::drawGL().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static
Returns a named object.
Definition at line 76 of file GUIGlObject_AbstractAdd.cpp.
References myObjects.
virtual Boundary GUIGlObject::getCenteringBoundary () const pure virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
Implemented in GUILane, GUIInductLoop::MyWrapper, GUITriggeredRerouter::GUITriggeredRerouterEdge, GUINet, GUIEdge, GUI_E2_ZS_Collector::MyWrapper, GUIBusStop, GUIContainerStop, GUIE3Collector::MyWrapper, GUI_E2_ZS_CollectorOverLanes::MyWrapper, GUITriggeredRerouter, GUIVehicle, GUIJunctionWrapper, GUIPointOfInterest, GUICalibrator, GUIInstantInductLoop::MyWrapper, GUILaneSpeedTrigger, GUIPolygon, GUIPerson, GUIContainer, and GUITrafficLightLogicWrapper.
Referenced by SUMORTree::addAdditionalGLObject(), GUISUMOAbstractView::centerTo(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::MyWrapper(), and SUMORTree::removeAdditionalGLObject().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIJunctionWrapper::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GUILane::getColorValue(), GUIVehicle::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), GUILane::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static
Returns the list of gl-ids of all additional objects.
Definition at line 99 of file GUIGlObject_AbstractAdd.cpp.
References myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static
Returns the list of all additional objects.
Definition at line 93 of file GUIGlObject_AbstractAdd.cpp.
References myObjectList.
virtual GUIParameterTableWindow* GUIGlObject::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) pure virtual inherited
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Implemented in GUILane, GUIInductLoop::MyWrapper, GUITriggeredRerouter::GUITriggeredRerouterEdge, GUINet, GUIEdge, GUI_E2_ZS_Collector::MyWrapper, GUIBusStop, GUIContainerStop, GUIE3Collector::MyWrapper, GUI_E2_ZS_CollectorOverLanes::MyWrapper, GUITriggeredRerouter, GUIVehicle, GUIJunctionWrapper, GUIPointOfInterest, GUICalibrator, GUIInstantInductLoop::MyWrapper, GUILaneSpeedTrigger, GUIPerson, GUIPolygon, GUIContainer, and GUITrafficLightLogicWrapper.
Referenced by GUIGLObjectPopupMenu::onCmdShowPars().
virtual GUIGLObjectPopupMenu* GUIGlObject::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) pure virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
Implemented in GUILane, GUITriggeredRerouter::GUITriggeredRerouterEdge, GUINet, GUIEdge, GUIBusStop, GUIContainerStop, GUIVehicle, GUITriggeredRerouter, GUIJunctionWrapper, GUIPointOfInterest, GUICalibrator, GUILaneSpeedTrigger, GUIPerson, GUIPolygon, GUIContainer, GUITrafficLightLogicWrapper, and GUIDetectorWrapper.
Referenced by GUISUMOAbstractView::openObjectDialog().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUIJunctionWrapper::getColorValue(), GUILane::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUILane::getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static
Removes an object.
Definition at line 86 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), myObjectList, and myObjects.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by clearDictionary(), getIDList(), getObjectList(), GUIGlObject_AbstractAdd(), and remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by clearDictionary(), get(), GUIGlObject_AbstractAdd(), and remove().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIGlObject_AbstractAdd.h
GUIGlObject_AbstractAdd.cpp