## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('simple-clwpr-example',
                                 ['core', 'network', 'wifi', 'internet', 'clwpr', 'mobility', 'winner-models', 'flow-monitor', 'applications'])
    obj.source = 'simple-clwpr-example.cc'
