SUMO - Simulation of Urban MObility: SUMOTime.cpp File Reference
SUMOTime.cpp File Reference
#include <config.h>
#include <sstream>
#include "SUMOTime.h"
#include "TplConvert.h"
Functions
SUMOTime string2time (const std::string &r)
std::string time2string (SUMOTime t)
Function Documentation
SUMOTime string2time (const std::string & r)
Definition at line 48 of file SUMOTime.cpp.
References STEPS2TIME, SUMOTime_MAX, and TIME2STEPS.
Referenced by MSDetectorControl::add(), MSDetectorControl::addDetectorAndInterval(), NLHandler::addEdgeLaneMeanData(), NLBuilder::build(), NLBuilder::buildRouteLoaderControl(), NLTriggerBuilder::buildVaporizer(), MSDevice_Routing::buildVehicleDevices(), MSFrame::checkOptions(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), computeRoutes(), GUIDialog_Breakpoints::GUIDialog_Breakpoints(), GUISettingsHandler::loadBreakpoints(), main(), MSNet::MSNet(), MSPhaseDefinition::MSPhaseDefinition(), MSPModel_Striping::MSPModel_Striping(), MSVehicleControl::MSVehicleControl(), SUMORouteHandler::myEndElement(), GUIDialog_Breakpoints::onCmdEditTable(), ROLoader::openRoutes(), TraCIServer::openSocket(), SUMOVehicleParameter::parseDepart(), readDetectorFlows(), MSDevice_Routing::reroute(), TraCITestClient::run(), GUILoadThread::run(), MSFrame::setMSGlobals(), and startComputation().
std::string time2string (SUMOTime t)
Definition at line 61 of file SUMOTime.cpp.
References OUTPUT_ACCURACY, and STEPS2TIME.
Referenced by MSVehicleTransfer::add(), GUIRunThread::begin(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), NLBuilder::build(), CHRouter< E, V, PF >::buildContractionHierarchy(), NLBuilder::buildNet(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), NBOwnTLDef::computeLogicAndConts(), computeRoutes(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GUITLLogicPhasesTrackerWindow::drawValues(), GUIDialog_Breakpoints::encode2TXT(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSContainerControl::erase(), MSPersonControl::erase(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::generateOutput(), GUICalibrator::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIVehicle::getStopInfo(), MSLane::handleCollision(), GUIApplicationWindow::handleEvent_SimulationEnded(), MSVehicle::Influencer::influenceChangeDecision(), GUIRunThread::makeStep(), MSLaneSpeedTrigger::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), ROLoader::openRoutes(), MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), ROLoader::processRoutes(), GUIDialog_Breakpoints::rebuildList(), MSPerson::MSPersonStage_Walking::routeOutput(), MSContainer::MSContainerStage_Waiting::routeOutput(), MSPerson::MSPersonStage_Waiting::routeOutput(), MSNet::simulate(), MSLane::succLinkSec(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSContainer::MSContainerStage_Waiting::tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Waiting::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSQueueExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::write(), MSXMLRawOut::write(), ODMatrix::write(), SUMOVehicleParameter::write(), MSLink::writeApproaching(), RODFDetector::writeEmitterDefinition(), ODMatrix::writeFlows(), MSNet::writeOutput(), RODFDetector::writeSingleSpeedTrigger(), ROLoader::writeStats(), MSInductLoop::writeTypedXMLOutput(), TrajectoriesHandler::writeXMLEmissions(), MSRouteProbe::writeXMLOutput(), MSCalibrator::writeXMLOutput(), MSE2Collector::writeXMLOutput(), MSE3Collector::writeXMLOutput(), and MSDevice_Vehroutes::writeXMLRoute().