SUMO - Simulation of Urban MObility: GUITriggeredRerouter::GUITriggeredRerouterPopupMenu Class Reference
GUITriggeredRerouter::GUITriggeredRerouterPopupMenu Class Reference
#include <GUITriggeredRerouter.h>
Public Member Functions
GUISUMOAbstractView * getParentView ()
return the real owner of this popup
GUITriggeredRerouterPopupMenu (GUIMainWindow &app, GUISUMOAbstractView &parent, GUIGlObject &o)
long onCmdAddSelected (FXObject *, FXSelector, void *)
Called if the object shall be added to the list of selected objects.
long onCmdCenter (FXObject *, FXSelector, void *)
Called if the assigned objects shall be centered.
long onCmdCopyCursorGeoPosition (FXObject *, FXSelector, void *)
Called if the cursor geo-position shall be copied to clipboard.
long onCmdCopyCursorPosition (FXObject *, FXSelector, void *)
Called if the cursor position shall be copied to clipboard.
long onCmdCopyName (FXObject *, FXSelector, void *)
Called if the name shall be copied to clipboard.
long onCmdCopyTypedName (FXObject *, FXSelector, void *)
Called if the typed name shall be copied to clipboard.
long onCmdOpenManip (FXObject *, FXSelector, void *)
Called if the object's manipulator shall be shown.
long onCmdRemoveSelected (FXObject *, FXSelector, void *)
Called if the object shall be removed from the list of selected objects.
long onCmdShowPars (FXObject *, FXSelector, void *)
Called if the parameter of this object shall be shown.
~GUITriggeredRerouterPopupMenu ()
Protected Member Functions
GUITriggeredRerouterPopupMenu ()
Protected Attributes
GUIMainWindow * myApplication
The main application.
Position myNetworkPosition
The position within the network the cursor was above when instanting the popup.
GUIGlObject * myObject
The object that belongs to this popup-menu.
GUISUMOAbstractView * myParent
The parent window.
Detailed Description
Definition at line 205 of file GUITriggeredRerouter.h.
Constructor & Destructor Documentation
GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::GUITriggeredRerouterPopupMenu (GUIMainWindow & app, GUISUMOAbstractView & parent, GUIGlObject & o)
Definition at line 207 of file GUITriggeredRerouter.cpp.
GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::~GUITriggeredRerouterPopupMenu ()
Definition at line 213 of file GUITriggeredRerouter.cpp.
GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::GUITriggeredRerouterPopupMenu () inline protected
Definition at line 218 of file GUITriggeredRerouter.h.
Member Function Documentation
GUISUMOAbstractView* GUIGLObjectPopupMenu::getParentView () inline inherited
return the real owner of this popup
Definition at line 99 of file GUIGLObjectPopupMenu.h.
References GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdAddSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be added to the list of selected objects.
Definition at line 130 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISelectedStorage::select().
long GUIGLObjectPopupMenu::onCmdCenter (FXObject * , FXSelector , void *) inherited
Called if the assigned objects shall be centered.
Definition at line 83 of file GUIGLObjectPopupMenu.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor geo-position shall be copied to clipboard.
Definition at line 112 of file GUIGLObjectPopupMenu.cpp.
References GeoConvHelper::cartesian2geo(), GUIUserIO::copyToClipboard(), GEO_OUTPUT_ACCURACY, GeoConvHelper::getFinal(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, toString(), Position::x(), and Position::y().
long GUIGLObjectPopupMenu::onCmdCopyCursorPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor position shall be copied to clipboard.
Definition at line 105 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, and toString().
long GUIGLObjectPopupMenu::onCmdCopyName (FXObject * , FXSelector , void *) inherited
Called if the name shall be copied to clipboard.
Definition at line 91 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getMicrosimID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdCopyTypedName (FXObject * , FXSelector , void *) inherited
Called if the typed name shall be copied to clipboard.
Definition at line 98 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getFullName(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip (FXObject * , FXSelector , void *)
Called if the object's manipulator shall be shown.
Definition at line 217 of file GUITriggeredRerouter.cpp.
References GUITriggeredRerouter::openManipulator().
long GUIGLObjectPopupMenu::onCmdRemoveSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be removed from the list of selected objects.
Definition at line 138 of file GUIGLObjectPopupMenu.cpp.
References GUISelectedStorage::deselect(), GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdShowPars (FXObject * , FXSelector , void *) inherited
Called if the parameter of this object shall be shown.
Definition at line 123 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Field Documentation
GUIMainWindow* GUIGLObjectPopupMenu::myApplication protected inherited
The main application.
Definition at line 111 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdShowPars().
Position GUIGLObjectPopupMenu::myNetworkPosition protected inherited
The position within the network the cursor was above when instanting the popup.
Definition at line 114 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), and GUIGLObjectPopupMenu::onCmdCopyCursorPosition().
GUIGlObject* GUIGLObjectPopupMenu::myObject protected inherited
The object that belongs to this popup-menu.
Definition at line 108 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), and GUIGLObjectPopupMenu::onCmdShowPars().
GUISUMOAbstractView* GUIGLObjectPopupMenu::myParent protected inherited
The parent window.
Definition at line 105 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::getParentView(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), and GUIGLObjectPopupMenu::onCmdShowPars().
The documentation for this class was generated from the following files:
GUITriggeredRerouter.h
GUITriggeredRerouter.cpp