SUMO - Simulation of Urban MObility: SUMOAbstractRouter< E, V > Class Template Reference
SUMOAbstractRouter< E, V > Class Template Reference abstract
#include <SUMOAbstractRouter.h>
Public Types
typedef SUMOReal(* Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter * clone () const =0
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
virtual void prepare (const E *, const V *, bool)
virtual SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const =0
void startQuery ()
SUMOAbstractRouter (Operation operation, const std::string &type)
Constructor.
virtual ~SUMOAbstractRouter ()
Destructor.
Protected Attributes
Operation myOperation
The object's operation to perform.
Private Member Functions
SUMOAbstractRouter & operator= (const SUMOAbstractRouter &s)
Invalidated assignment operator.
Private Attributes
SUMOLong myNumQueries
SUMOLong myQueryStartTime
the time spent querying in milliseconds
SUMOLong myQueryTimeSum
SUMOLong myQueryVisits
counters for performance logging
const std::string myType
the type of this router
Detailed Description
template<class E, class V>
class SUMOAbstractRouter< E, V >
The interface for routing the vehicles over the network.
Definition at line 53 of file SUMOAbstractRouter.h.
Member Typedef Documentation
template<class E, class V> typedef SUMOReal(* SUMOAbstractRouter< E, V >::Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 56 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
template<class E, class V> SUMOAbstractRouter< E, V >::SUMOAbstractRouter (Operation operation, const std::string & type) inline
Constructor.
Definition at line 59 of file SUMOAbstractRouter.h.
template<class E, class V> virtual SUMOAbstractRouter< E, V >::~SUMOAbstractRouter () inline virtual
Destructor.
Definition at line 69 of file SUMOAbstractRouter.h.
Member Function Documentation
template<class E, class V> virtual SUMOAbstractRouter* SUMOAbstractRouter< E, V >::clone () const pure virtual
Implemented in PedestrianRouter< E, L, N, INTERNALROUTER >, PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >, CHRouter< E, V, PF >, BulkStarRouter< E, V, PF >, CHRouterWrapper< E, V, PF >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, and ROJTRRouter.
Referenced by RONet::saveAndRemoveRoutesUntil().
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) pure virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implemented in PedestrianRouter< E, L, N, INTERNALROUTER >, PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >, BulkStarRouter< E, V, PF >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, and CHRouterWrapper< E, V, PF >.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), MSTriggeredRerouter::notifyEnter(), RORouteDef::preComputeCurrentRoute(), TraCIServerAPI_Vehicle::processSet(), RORouteDef::repairCurrentRoute(), MSBaseVehicle::reroute(), and ROMAAssignments::sue().
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), BulkStarRouter< E, V, PF >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V> SUMOAbstractRouter& SUMOAbstractRouter< E, V >::operator= (const SUMOAbstractRouter< E, V > & s) private
Invalidated assignment operator.
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual
Reimplemented in BulkStarRouter< E, V, PF >.
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by RORouteAggregator::processAllRoutes().
template<class E, class V> virtual SUMOReal SUMOAbstractRouter< E, V >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const pure virtual
Implemented in PedestrianRouter< E, L, N, INTERNALROUTER >, PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >, CHRouter< E, V, PF >, BulkStarRouter< E, V, PF >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >, and CHRouterWrapper< E, V, PF >.
Referenced by RORouteDef::addAlternative(), computeRoutes(), and ROMAAssignments::sue().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V> SUMOLong SUMOAbstractRouter< E, V >::myNumQueries private
Definition at line 115 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::startQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), CHRouterWrapper< E, V, PF >::clone(), BulkStarRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::getEffort().
template<class E, class V> SUMOLong SUMOAbstractRouter< E, V >::myQueryStartTime private
the time spent querying in milliseconds
Definition at line 117 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::startQuery().
template<class E, class V> SUMOLong SUMOAbstractRouter< E, V >::myQueryTimeSum private
Definition at line 118 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> SUMOLong SUMOAbstractRouter< E, V >::myQueryVisits private
counters for performance logging
Definition at line 114 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::endQuery(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
template<class E, class V> const std::string SUMOAbstractRouter< E, V >::myType private
the type of this router
Definition at line 111 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, PedestrianTrip< E, N > >::~SUMOAbstractRouter().
The documentation for this class was generated from the following file:
SUMOAbstractRouter.h