SUMO - Simulation of Urban MObility: MSEdge::person_by_offset_sorter Class Reference
MSEdge::person_by_offset_sorter Class Reference
Sorts persons by their positions.
#include <MSEdge.h>
Public Member Functions
int operator() (const MSPerson *const p1, const MSPerson *const p2) const
comparing operator
person_by_offset_sorter (SUMOTime timestep)
constructor
Private Attributes
SUMOTime myTime
Detailed Description
Sorts persons by their positions.
Definition at line 662 of file MSEdge.h.
Constructor & Destructor Documentation
MSEdge::person_by_offset_sorter::person_by_offset_sorter (SUMOTime timestep) inline explicit
constructor
Definition at line 665 of file MSEdge.h.
Member Function Documentation
int MSEdge::person_by_offset_sorter::operator() (const MSPerson *const p1, const MSPerson *const p2) const
comparing operator
Definition at line 664 of file MSEdge.cpp.
References MSPerson::getCurrentStage(), MSPerson::MSPersonStage::getEdgePos(), MSPerson::getID(), myTime, and SUMOReal.
Field Documentation
SUMOTime MSEdge::person_by_offset_sorter::myTime private
Definition at line 670 of file MSEdge.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
MSEdge.h
MSEdge.cpp