SUMO - Simulation of Urban MObility: GUIInductLoop Class Reference
GUIInductLoop Class Reference
The gui-version of the MSInductLoop.
#include <GUIInductLoop.h>
Data Structures
class MyWrapper
A MSInductLoop-visualiser.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Returns this detector's visualisation-wrapper.
std::vector< VehicleData > collectVehiclesOnDet (SUMOTime t) const
Returns vehicle data for vehicles that have been on the detector starting at the given time.
const std::string & getDescription () const
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getPosition () const
Returns the position of the detector on the lane.
GUIInductLoop (const std::string &id, MSLane *const lane, SUMOReal position, bool splitByType)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void reset ()
Resets all generated values to allow computation of next interval.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
~GUIInductLoop ()
Destructor.
Methods inherited from MSMoveReminder
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Dismisses the vehicle if it is on the detector due to a lane change.
Methods returning current values
SUMOReal getCurrentSpeed () const
Returns the speed of the vehicle on the detector.
SUMOReal getCurrentLength () const
Returns the length of the vehicle on the detector.
SUMOReal getCurrentOccupancy () const
Returns the current occupancy.
unsigned int getCurrentPassedNumber () const
Returns the number of vehicles that have passed the detector.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the ids of vehicles that have passed the detector.
SUMOReal getTimestepsSinceLastDetection () const
Returns the time since the last vehicle left the detector.
Methods inherited from MSDetectorFileOutput.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason)
Checks whether the reminder is activated by a vehicle entering the lane.
Virtual methods to implement by derived classes
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values)
Data Fields
MFXMutex myLock
Mutex preventing parallel read/write access to internal MSInductLoop state.
Protected Types
typedef std::deque< VehicleData > VehicleDataCont
Type of myVehicleDataCont.
typedef std::map< SUMOVehicle
*, SUMOReal > VehicleMap
Type of myVehiclesOnDet.
Protected Member Functions
void writeTypedXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime, const std::string &type, const VehicleDataCont &vdc, const VehicleMap &vm)
Methods that add and remove vehicles from internal container
void enterDetectorByMove (SUMOVehicle &veh, SUMOReal entryTimestep)
Introduces a vehicle to the detector's map myVehiclesOnDet.
void leaveDetectorByMove (SUMOVehicle &veh, SUMOReal leaveTimestep)
Processes a vehicle that leaves the detector.
void leaveDetectorByLaneChange (SUMOVehicle &veh, SUMOReal lastPos)
Removes a vehicle from the detector's map myVehiclesOnDet.
Static Protected Member Functions
Function for summing up values
static SUMOReal speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::speedM.
static SUMOReal lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::lengthM.
Protected Attributes
std::string myDescription
a description of this moveReminder
unsigned myDismissedVehicleNumber
The number of dismissed vehicles.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myLastLeaveTime
Leave-time of the last vehicle detected [s].
SUMOReal myLastOccupancy
Occupancy by the last vehicle detected.
VehicleDataCont myLastVehicleDataCont
Data of vehicles that have completely passed the detector in the last time interval.
const SUMOReal myPosition
Detector's position on lane [m].
bool mySplitByType
Whether additional information split by vehicle classes shall be generated.
VehicleDataCont myVehicleDataCont
Data of vehicles that have completely passed the detector.
VehicleMap myVehiclesOnDet
Data for vehicles that have entered the detector (vehicle -> enter time)
Detailed Description
The gui-version of the MSInductLoop.
Allows the building of a wrapper (also declared herein) which draws the detector on the gl-canvas. Uses a mutex to avoid parallel read/write operations. The mutex is only set within methods that change MSInductLoop-internal state and within "collectVehiclesOnDet". All other reading operations should be performed via the simulation loop only.
Definition at line 55 of file GUIInductLoop.h.
Member Typedef Documentation
typedef std::deque< VehicleData > MSInductLoop::VehicleDataCont protected inherited
Type of myVehicleDataCont.
Definition at line 344 of file MSInductLoop.h.
typedef std::map< SUMOVehicle*, SUMOReal > MSInductLoop::VehicleMap protected inherited
Type of myVehiclesOnDet.
Definition at line 354 of file MSInductLoop.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
GUIInductLoop::GUIInductLoop (const std::string & id, MSLane *const lane, SUMOReal position, bool splitByType)
Constructor.
Parameters
[in] id Unique id
[in] lane Lane where detector woks on
[in] position Position of the detector within the lane
[in] splitByType Whether additional information split by vehicle classes shall be generated
Definition at line 56 of file GUIInductLoop.cpp.
GUIInductLoop::~GUIInductLoop ()
Destructor.
Definition at line 61 of file GUIInductLoop.cpp.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
GUIDetectorWrapper * GUIInductLoop::buildDetectorGUIRepresentation () virtual
Returns this detector's visualisation-wrapper.
Returns
The wrapper representing the detector
Reimplemented from MSDetectorFileOutput.
Definition at line 65 of file GUIInductLoop.cpp.
References MSInductLoop::myPosition.
std::vector< MSInductLoop::VehicleData > GUIInductLoop::collectVehiclesOnDet (SUMOTime t) const virtual
Returns vehicle data for vehicles that have been on the detector starting at the given time.
This method uses a mutex to prevent parallel read/write access to the vehicle buffer
Parameters
[in] t The time from which vehicles shall be counted
Returns
The list of vehicles
See Also
MSInductLoop::collectVehiclesOnDet()
Reimplemented from MSInductLoop.
Definition at line 97 of file GUIInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), and myLock.
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) inline virtual inherited
Updates the detector (computes values)
Parameters
[in] step The current time step
Reimplemented in MSMeanData, MSE3Collector, MSMeanData_Harmonoise, and MSE2Collector.
Definition at line 113 of file MSDetectorFileOutput.h.
References UNUSED_PARAMETER.
void GUIInductLoop::enterDetectorByMove (SUMOVehicle & veh, SUMOReal entryTimestep) protected virtual
Introduces a vehicle to the detector's map myVehiclesOnDet.
Locks the internal mutex before calling MSInductLoop::enterDetectorByMove()
See Also
MSInductLoop::enterDetectorByMove()
Parameters
veh The entering vehicle.
entryTimestep Timestep (not necessary integer) of entrance.
See Also
MSInductLoop::enterDetectorByMove()
Reimplemented from MSInductLoop.
Definition at line 78 of file GUIInductLoop.cpp.
References MSInductLoop::enterDetectorByMove(), and myLock.
SUMOReal MSInductLoop::getCurrentLength () const inherited
Returns the length of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's length.
Returns
The length [m] of the vehicle if one is on the detector, -1 otherwise
Definition at line 138 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), MSInductLoop::lengthSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentOccupancy () const inherited
Returns the current occupancy.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, its occupancy value is returned. If no vehicle has passed, 0 is returned.
Returns
This detector's current occupancy
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 147 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getCurrentTimeStep(), MSNet::getInstance(), HAS_NOT_LEFT_DETECTOR, MAX2(), MIN2(), STEPS2TIME, SUMOReal, and TS.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
unsigned int MSInductLoop::getCurrentPassedNumber () const inherited
Returns the number of vehicles that have passed the detector.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, 1 is returned. If no vehicle has passed, 0 is returned.
Returns
The number of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 166 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, and MSNet::getInstance().
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentSpeed () const inherited
Returns the speed of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's current speed.
Returns
The speed [m/s] of the vehicle if one is on the detector, -1 otherwise
Definition at line 129 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), MSInductLoop::speedSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
std::vector< std::string > MSInductLoop::getCurrentVehicleIDs () const inherited
Returns the ids of vehicles that have passed the detector.
Returns
The ids of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 173 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, and MSNet::getInstance().
Referenced by TraCIServerAPI_InductionLoop::processGet().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 215 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSE2Collector::detectorUpdate(), MSDevice_Tripinfo::generateOutput(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
SUMOReal MSInductLoop::getPosition () const inline inherited
Returns the position of the detector on the lane.
Returns
The detector's position in meters
Definition at line 100 of file MSInductLoop.h.
References MSInductLoop::myPosition.
Referenced by TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getTimestepsSinceLastDetection () const inherited
Returns the time since the last vehicle left the detector.
Returns
Timesteps from last leaving (detection) of the detector
Definition at line 184 of file MSInductLoop.cpp.
References MSNet::getInstance(), MSInductLoop::myLastLeaveTime, MSInductLoop::myVehiclesOnDet, and STEPS2TIME.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
void GUIInductLoop::leaveDetectorByLaneChange (SUMOVehicle & veh, SUMOReal lastPos) protected virtual
Removes a vehicle from the detector's map myVehiclesOnDet.
Locks the internal mutex before calling MSInductLoop::leaveDetectorByLaneChange()
See Also
MSInductLoop::leaveDetectorByLaneChange()
Parameters
veh The leaving vehicle.
lastPos The last position of the leaving vehicle.
Reimplemented from MSInductLoop.
Definition at line 90 of file GUIInductLoop.cpp.
References MSInductLoop::leaveDetectorByLaneChange(), and myLock.
void GUIInductLoop::leaveDetectorByMove (SUMOVehicle & veh, SUMOReal leaveTimestep) protected virtual
Processes a vehicle that leaves the detector.
Locks the internal mutex before calling MSInductLoop::leaveDetectorByMove()
See Also
MSInductLoop::leaveDetectorByMove()
Parameters
veh The leaving vehicle.
leaveTimestep Timestep (not necessary integer) of leaving.
See Also
MSInductLoop::leaveDetectorByMove()
Reimplemented from MSInductLoop.
Definition at line 84 of file GUIInductLoop.cpp.
References MSInductLoop::leaveDetectorByMove(), and myLock.
static SUMOReal MSInductLoop::lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) inline static protected inherited
Adds up VehicleData::lengthM.
Definition at line 320 of file MSInductLoop.h.
References MSInductLoop::VehicleData::lengthM.
Referenced by MSInductLoop::getCurrentLength(), and MSInductLoop::writeTypedXMLOutput().
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason) inline virtual inherited
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True if vehicle enters the reminder.
See Also
Notification
Reimplemented in MSMeanData::MeanDataValueTracker, MSE2Collector, MSDevice_Routing, MSMeanData_Net::MSLaneMeanDataValues, MSCalibrator::VehicleRemover, MSTriggeredRerouter, MSMeanData_Amitran::MSLaneMeanDataValues, MSDevice_Example, MSDevice_BTreceiver, MSMeanData::MeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSDevice_Vehroutes, MSDevice_BTsender, MSDevice_Tripinfo, MSRouteProbe, MSDevice_Person, and MSDevice_Container.
Definition at line 130 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
bool MSInductLoop::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual inherited
Dismisses the vehicle if it is on the detector due to a lane change.
If the vehicle is on the detector, it will be dismissed by incrementing myDismissedVehicleNumber and removing this vehicle's entering time from myVehiclesOnDet.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See Also
leaveDetectorByLaneChange
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 119 of file MSInductLoop.cpp.
References MSInductLoop::leaveDetectorByLaneChange(), and MSMoveReminder::NOTIFICATION_JUNCTION.
bool MSInductLoop::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual inherited
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
As soon a vehicle enters the detector, its entry time is computed and stored in myVehiclesOnDet via enterDetectorByMove. If it passes the detector, the according leaving time is computed and stored, too, using leaveDetectorByMove.
Parameters
[in] veh Vehicle that asks this remider.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the detector completely.
See Also
MSMoveReminder
MSMoveReminder::notifyMove
enterDetectorByMove
leaveDetectorByMove
Reimplemented from MSMoveReminder.
Definition at line 86 of file MSInductLoop.cpp.
References MSInductLoop::enterDetectorByMove(), MSNet::getInstance(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), MSInductLoop::leaveDetectorByMove(), MSInductLoop::myPosition, MSInductLoop::myVehiclesOnDet, STEPS2TIME, and SUMOReal.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 203 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
void GUIInductLoop::reset () virtual
Resets all generated values to allow computation of next interval.
Locks the internal mutex before calling MSInductLoop::reset()
See Also
MSInductLoop::reset()
Reimplemented from MSInductLoop.
Definition at line 71 of file GUIInductLoop.cpp.
References myLock, and MSInductLoop::reset().
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 211 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), and MSCalibrator::MSCalibrator().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
static SUMOReal MSInductLoop::speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) inline static protected inherited
Adds up VehicleData::speedM.
Definition at line 315 of file MSInductLoop.h.
References MSInductLoop::VehicleData::speedM.
Referenced by MSInductLoop::getCurrentSpeed(), and MSInductLoop::writeTypedXMLOutput().
void MSInductLoop::writeTypedXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime, const std::string & type, const VehicleDataCont & vdc, const VehicleMap & vm) protected inherited
Definition at line 233 of file MSInductLoop.cpp.
References StringUtils::escapeXML(), Named::getID(), MSInductLoop::lengthSum(), MAX2(), MIN2(), MSInductLoop::myDismissedVehicleNumber, MSInductLoop::speedSum(), STEPS2TIME, SUMOReal, and time2string().
Referenced by MSInductLoop::writeXMLOutput().
void MSInductLoop::writeXMLDetectorProlog (OutputDevice & dev) const virtual inherited
Opens the XML-output using "detector" as root element.
Parameters
[in] dev The output device to write the root into
See Also
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 194 of file MSInductLoop.cpp.
References OutputDevice::writeXMLHeader().
void MSInductLoop::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual inherited
Writes collected values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See Also
MSDetectorFileOutput::writeXMLOutput
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 200 of file MSInductLoop.cpp.
References MSInductLoop::mySplitByType, MSInductLoop::myVehicleDataCont, MSInductLoop::myVehiclesOnDet, MSInductLoop::reset(), and MSInductLoop::writeTypedXMLOutput().
Field Documentation
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 229 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
unsigned MSInductLoop::myDismissedVehicleNumber protected inherited
The number of dismissed vehicles.
Definition at line 340 of file MSInductLoop.h.
Referenced by MSInductLoop::leaveDetectorByLaneChange(), MSInductLoop::reset(), and MSInductLoop::writeTypedXMLOutput().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 227 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), and MSMoveReminder::MSMoveReminder().
SUMOReal MSInductLoop::myLastLeaveTime protected inherited
Leave-time of the last vehicle detected [s].
Definition at line 334 of file MSInductLoop.h.
Referenced by MSInductLoop::getTimestepsSinceLastDetection(), and MSInductLoop::leaveDetectorByMove().
SUMOReal MSInductLoop::myLastOccupancy protected inherited
Occupancy by the last vehicle detected.
Definition at line 337 of file MSInductLoop.h.
Referenced by MSInductLoop::leaveDetectorByMove().
VehicleDataCont MSInductLoop::myLastVehicleDataCont protected inherited
Data of vehicles that have completely passed the detector in the last time interval.
Definition at line 350 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), and MSInductLoop::reset().
MFXMutex GUIInductLoop::myLock mutable
Mutex preventing parallel read/write access to internal MSInductLoop state.
Definition at line 210 of file GUIInductLoop.h.
Referenced by collectVehiclesOnDet(), enterDetectorByMove(), leaveDetectorByLaneChange(), leaveDetectorByMove(), and reset().
const SUMOReal MSInductLoop::myPosition protected inherited
Detector's position on lane [m].
Definition at line 328 of file MSInductLoop.h.
Referenced by buildDetectorGUIRepresentation(), GUIInductLoop::MyWrapper::getParameterWindow(), MSInductLoop::getPosition(), MSInductLoop::leaveDetectorByLaneChange(), MSInductLoop::MSInductLoop(), and MSInductLoop::notifyMove().
bool MSInductLoop::mySplitByType protected inherited
Whether additional information split by vehicle classes shall be generated.
Definition at line 331 of file MSInductLoop.h.
Referenced by MSInductLoop::writeXMLOutput().
VehicleDataCont MSInductLoop::myVehicleDataCont protected inherited
Data of vehicles that have completely passed the detector.
Definition at line 347 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSInductLoop::leaveDetectorByMove(), MSInductLoop::reset(), and MSInductLoop::writeXMLOutput().
VehicleMap MSInductLoop::myVehiclesOnDet protected inherited
Data for vehicles that have entered the detector (vehicle -> enter time)
Definition at line 357 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSInductLoop::enterDetectorByMove(), MSInductLoop::getTimestepsSinceLastDetection(), MSInductLoop::leaveDetectorByLaneChange(), MSInductLoop::leaveDetectorByMove(), MSInductLoop::notifyMove(), and MSInductLoop::writeXMLOutput().
The documentation for this class was generated from the following files:
GUIInductLoop.h
GUIInductLoop.cpp