SUMO - Simulation of Urban MObility: RORouteAggregator Class Reference
RORouteAggregator Class Reference
#include <RORouteAggregator.h>
Data Structures
struct ComparatorNumVehicles
Static Public Member Functions
static void processAllRoutes (RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
precomputes all routes grouped by their destination edge
Private Types
typedef std::set< const ROEdge * > EdgeSet
typedef std::map< const ROEdge
*, VehVec > SameTargetMap
typedef std::vector< ROVehicle * > VehVec
Static Private Member Functions
static EdgeSet approachingEdges (EdgeSet edges)
static EdgeSet getNearby (const ROEdge *edge, const int distance)
static SameTargetMap mergeTargets (SameTargetMap &stm, const int distance)
Detailed Description
Definition at line 48 of file RORouteAggregator.h.
Member Typedef Documentation
typedef std::set<const ROEdge*> RORouteAggregator::EdgeSet private
Definition at line 114 of file RORouteAggregator.h.
typedef std::map<const ROEdge*, VehVec> RORouteAggregator::SameTargetMap private
Definition at line 113 of file RORouteAggregator.h.
typedef std::vector<ROVehicle*> RORouteAggregator::VehVec private
Definition at line 112 of file RORouteAggregator.h.
Member Function Documentation
static EdgeSet RORouteAggregator::approachingEdges (EdgeSet edges) inline static private
Definition at line 182 of file RORouteAggregator.h.
Referenced by getNearby().
static EdgeSet RORouteAggregator::getNearby (const ROEdge * edge, const int distance) inline static private
Definition at line 170 of file RORouteAggregator.h.
References approachingEdges().
Referenced by mergeTargets().
static SameTargetMap RORouteAggregator::mergeTargets (SameTargetMap & stm, const int distance) inline static private
Definition at line 136 of file RORouteAggregator.h.
References getNearby().
Referenced by processAllRoutes().
static void RORouteAggregator::processAllRoutes (RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router) inline static
precomputes all routes grouped by their destination edge
Note
: the current setup is not suitable for using RORouteDef_Complete along with –repair since the sequence is not optimized for in-between destinations
Definition at line 56 of file RORouteAggregator.h.
References ROVehicle::getDepartureTime(), RORouteDef::getDestination(), NamedObjectCont< T >::getMyMap(), ROVehicle::getRouteDefinition(), RONet::getVehicles(), mergeTargets(), RORouteDef::preComputeCurrentRoute(), SUMOAbstractRouter< E, V >::prepare(), NamedObjectCont< T >::size(), toString(), and WRITE_MESSAGE.
Referenced by ROLoader::processAllRoutesWithBulkRouter().
The documentation for this class was generated from the following file:
RORouteAggregator.h