SUMO - Simulation of Urban MObility: MSContainer Class Reference
MSContainer Class Reference
#include <MSContainer.h>
Data Structures
class MSContainerStage
class MSContainerStage_Driving
class MSContainerStage_Tranship
class MSContainerStage_Waiting
Public Types
typedef std::vector
< MSContainerStage * > MSContainerPlan
the structure holding the plan of a container
enum StageType { DRIVING = 0, WAITING = 1, TRANSHIP = 2 }
Public Member Functions
virtual SUMOReal getAngle () const
return the current angle of the container
MSContainerStage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the container
virtual MSContainerStop * getDepartContainerStop () const
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
virtual SUMOReal getEdgePos () const
Return the position on the edge.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the container id
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
const SUMOVehicleParameter & getParameter () const
virtual Position getPosition () const
Return the Network coordinate of the container.
virtual SUMOReal getSpeed () const
the current speed of the container
const MSVehicleType & getVehicleType () const
virtual SUMOReal getWaitingSeconds () const
the time this container spent waiting in seconds
bool isWaiting4Vehicle () const
Whether the container waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the container waits for a vehicle of the line specified.
MSContainer (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSContainerPlan *plan)
constructor
bool proceed (MSNet *net, SUMOTime time)
void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
virtual ~MSContainer ()
destructor
Data Fields
const MSEdge * lastDestination
the last destination of the route of the container
Static Public Attributes
static const SUMOReal ROADSIDE_OFFSET
the offset for computing container positions when standing at an edge
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the container
MSContainerPlan * myPlan
the plan of the container
MSContainerPlan::iterator myStep
the iterator over the route
const MSVehicleType * myVType
This container's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Private Member Functions
MSContainer (const MSContainer &)
Invalidated copy constructor.
MSContainer & operator= (const MSContainer &)
Invalidated assignment operator.
Detailed Description
The class holds a simulated container together with its movement stages
Definition at line 69 of file MSContainer.h.
Member Typedef Documentation
typedef std::vector<MSContainerStage*> MSContainer::MSContainerPlan
the structure holding the plan of a container
Definition at line 553 of file MSContainer.h.
Member Enumeration Documentation
enum MSContainer::StageType
Enumerator
DRIVING
WAITING
TRANSHIP
Definition at line 71 of file MSContainer.h.
Constructor & Destructor Documentation
MSContainer::MSContainer (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSContainerPlan * plan)
constructor
Definition at line 470 of file MSContainer.cpp.
References getDestination(), lastDestination, myPlan, and myStep.
MSContainer::~MSContainer () virtual
destructor
Definition at line 476 of file MSContainer.cpp.
References myParameter, and myPlan.
MSContainer::MSContainer (const MSContainer &) private
Invalidated copy constructor.
Member Function Documentation
SUMOReal MSContainer::getAngle () const virtual
return the current angle of the container
Reimplemented in GUIContainer.
Definition at line 525 of file MSContainer.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getAngle(), and MSFCDExport::write().
MSContainerStage* MSContainer::getCurrentStage () const inline
Return the current stage.
Definition at line 641 of file MSContainer.h.
References myStep.
Referenced by MSEdge::container_by_position_sorter::operator()().
std::string MSContainer::getCurrentStageDescription () const inline
Returns the current stage description as a string.
Definition at line 636 of file MSContainer.h.
Referenced by GUIContainer::getParameterWindow().
StageType MSContainer::getCurrentStageType () const inline
the current stage type of the container
Definition at line 631 of file MSContainer.h.
Referenced by GUIContainer::getColorValue(), and GUIContainer::getPosition().
MSContainerStop * MSContainer::getDepartContainerStop () const virtual
Definition at line 540 of file MSContainer.cpp.
SUMOTime MSContainer::getDesiredDepart () const
Returns the desired departure time.
Definition at line 505 of file MSContainer.cpp.
References SUMOVehicleParameter::depart, and myParameter.
Referenced by MSContainerControl::erase(), and routeOutput().
const MSEdge& MSContainer::getDestination () const inline
Returns the current destination.
Definition at line 596 of file MSContainer.h.
Referenced by GUIContainer::getParameterWindow(), MSContainer(), MSDevice_Container::notifyLeave(), MSDevice_Container::notifyMove(), MSContainer::MSContainerStage_Driving::routeOutput(), and MSContainer::MSContainerStage_Waiting::routeOutput().
const MSEdge* MSContainer::getEdge () const inline
Returns the current edge.
Definition at line 606 of file MSContainer.h.
Referenced by MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSContainer::MSContainerStage_Driving::getEdgePos(), GUIContainer::getParameterWindow(), GUIContainer::getPosition(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
SUMOReal MSContainer::getEdgePos () const virtual
Return the position on the edge.
Reimplemented in GUIContainer.
Definition at line 515 of file MSContainer.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getEdgePos(), and MSFCDExport::write().
const MSEdge* MSContainer::getFromEdge () const inline
Returns the departure edge.
Definition at line 611 of file MSContainer.h.
Referenced by GUIContainer::getParameterWindow(), and MSContainer::MSContainerStage_Driving::routeOutput().
const std::string & MSContainer::getID () const
returns the container id
Definition at line 485 of file MSContainer.cpp.
References SUMOVehicleParameter::id, and myParameter.
Referenced by MSContainerControl::abortWaiting(), MSVehicle::addContainer(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSContainerControl::erase(), GUIContainer::getParameterWindow(), MSDevice_Container::notifyLeave(), MSEdge::container_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSContainer::MSContainerStage_Driving::routeOutput(), MSContainer::MSContainerStage_Waiting::routeOutput(), MSContainerControl::setTranship(), MSContainerControl::unsetTranship(), and MSFCDExport::write().
const MSEdge& MSContainer::getNextDestination () const inline
Returns the destination after the current destination.
Definition at line 601 of file MSContainer.h.
References myStep.
const SUMOVehicleParameter& MSContainer::getParameter () const inline
Definition at line 677 of file MSContainer.h.
References myParameter.
Referenced by GUIContainer::setFunctionalColor().
Position MSContainer::getPosition () const virtual
Return the Network coordinate of the container.
Reimplemented in GUIContainer.
Definition at line 520 of file MSContainer.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getPosition(), and MSFCDExport::write().
SUMOReal MSContainer::getSpeed () const virtual
the current speed of the container
Reimplemented in GUIContainer.
Definition at line 535 of file MSContainer.cpp.
Referenced by GUIContainer::getSpeed(), and MSFCDExport::write().
const MSVehicleType& MSContainer::getVehicleType () const inline
Definition at line 681 of file MSContainer.h.
References myVType.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIContainer::drawAction_drawAsPoly(), and GUIContainer::setFunctionalColor().
SUMOReal MSContainer::getWaitingSeconds () const virtual
the time this container spent waiting in seconds
Reimplemented in GUIContainer.
Definition at line 530 of file MSContainer.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and STEPS2TIME.
Referenced by GUIContainer::getWaitingSeconds().
bool MSContainer::isWaiting4Vehicle () const inline
Whether the container waits for a vehicle.
Definition at line 673 of file MSContainer.h.
Referenced by GUIContainer::getColorValue(), GUIContainer::getPosition(), MSContainer::MSContainerStage_Driving::getStageDescription(), and MSContainer::MSContainerStage_Driving::getWaitingTime().
bool MSContainer::isWaitingFor (const std::string & line) const inline
Whether the container waits for a vehicle of the line specified.
Definition at line 668 of file MSContainer.h.
MSContainer& MSContainer::operator= (const MSContainer &) private
Invalidated assignment operator.
bool MSContainer::proceed (MSNet * net, SUMOTime time)
Definition at line 490 of file MSContainer.cpp.
References myPlan, myStep, MSEdge::removeContainer(), and SUMOReal.
Referenced by MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Container::notifyLeave(), and MSDevice_Container::notifyMove().
void MSContainer::routeOutput (OutputDevice & os) const
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Definition at line 552 of file MSContainer.cpp.
References getDesiredDepart(), MSContainer::MSContainerStage_Waiting::getUntil(), myPlan, and WAITING.
Referenced by MSContainerControl::erase().
void MSContainer::setDeparted (SUMOTime now)
logs depart time of the current stage
Definition at line 510 of file MSContainer.cpp.
void MSContainer::tripInfoOutput (OutputDevice & os) const
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Definition at line 545 of file MSContainer.cpp.
References myPlan.
Referenced by MSContainerControl::erase().
Field Documentation
const MSEdge* MSContainer::lastDestination
the last destination of the route of the container
Definition at line 556 of file MSContainer.h.
Referenced by MSContainer().
const SUMOVehicleParameter* MSContainer::myParameter protected
the plan of the container
Definition at line 560 of file MSContainer.h.
Referenced by getDesiredDepart(), getID(), getParameter(), and ~MSContainer().
MSContainerPlan* MSContainer::myPlan protected
the plan of the container
Definition at line 567 of file MSContainer.h.
Referenced by MSContainer(), proceed(), routeOutput(), tripInfoOutput(), and ~MSContainer().
MSContainerPlan::iterator MSContainer::myStep protected
the iterator over the route
Definition at line 570 of file MSContainer.h.
Referenced by getCurrentStage(), getNextDestination(), MSContainer(), and proceed().
const MSVehicleType* MSContainer::myVType protected
This container's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 564 of file MSContainer.h.
Referenced by getVehicleType().
bool MSContainer::myWriteEvents protected
Whether events shall be written.
Definition at line 573 of file MSContainer.h.
const SUMOReal MSContainer::ROADSIDE_OFFSET static
the offset for computing container positions when standing at an edge
Definition at line 78 of file MSContainer.h.
Referenced by MSContainer::MSContainerStage_Driving::getPosition(), and MSContainer::MSContainerStage_Waiting::getPosition().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp