SUMO - Simulation of Urban MObility: ROLoader Class Reference
ROLoader Class Reference
The data loader.
#include <ROLoader.h>
Data Structures
class EdgeFloatTimeLineRetriever_EdgeTravelTime
Obtains edge travel times from a weights handler and stores them within the edges.
class EdgeFloatTimeLineRetriever_EdgeWeight
Obtains edge weights from a weights handler and stores them within the edges.
Public Member Functions
virtual void loadNet (RONet &toFill, ROAbstractEdgeBuilder &eb)
Loads the network.
bool loadWeights (RONet &net, const std::string &optionName, const std::string &measure, bool useLanes)
Loads the net weights.
void openRoutes (RONet &net)
Builds and opens all route loaders.
void processAllRoutesWithBulkRouter (SUMOTime start, SUMOTime end, RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Loads all routes and processes them with BulkStarRouter.
void processRoutes (const SUMOTime start, const SUMOTime end, const SUMOTime increment, RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Loads routes from all previously build route loaders.
ROLoader (OptionsCont &oc, const bool emptyDestinationsAllowed, const bool logSteps)
Constructor.
virtual ~ROLoader ()
Destructor.
Protected Member Functions
bool openTypedRoutes (const std::string &optionName, RONet &net)
Opens route handler of the given type.
void writeStats (SUMOTime time, SUMOTime start, int absNo, bool endGiven)
Private Member Functions
ROLoader & operator= (const ROLoader &src)
Invalidated assignment operator.
ROLoader (const ROLoader &src)
Invalidated copy constructor.
Private Attributes
const bool myEmptyDestinationsAllowed
Information whether empty destinations are allowed.
SUMORouteLoaderControl myLoaders
List of route loaders.
const bool myLogSteps
Information whether the routing steps should be logged.
OptionsCont & myOptions
Options to use.
Detailed Description
The data loader.
Loads the network and route descriptions using further classes.
Is capable to either load all routes in one step or go through them step wise.
Definition at line 63 of file ROLoader.h.
Constructor & Destructor Documentation
ROLoader::ROLoader (OptionsCont & oc, const bool emptyDestinationsAllowed, const bool logSteps)
Constructor.
Parameters
[in] oc The options to use
[in] emptyDestinationsAllowed Whether trips may be given without destinations
Todo:
Recheck usage of emptyDestinationsAllowed
Definition at line 112 of file ROLoader.cpp.
ROLoader::~ROLoader () virtual
Destructor.
Definition at line 120 of file ROLoader.cpp.
ROLoader::ROLoader (const ROLoader & src) private
Invalidated copy constructor.
Member Function Documentation
void ROLoader::loadNet (RONet & toFill, ROAbstractEdgeBuilder & eb) virtual
Loads the network.
Definition at line 125 of file ROLoader.cpp.
References deprecatedVehicleClassesSeen, OptionsCont::getString(), OptionsCont::getStringVector(), FileHelpers::isReadable(), OptionsCont::isSet(), myOptions, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, XMLSubSys::runParser(), GenericSAXHandler::setFileName(), toString(), and WRITE_WARNING.
Referenced by initNet().
bool ROLoader::loadWeights (RONet & net, const std::string & optionName, const std::string & measure, bool useLanes)
Loads the net weights.
Definition at line 273 of file ROLoader.cpp.
References RONet::getEdgeMap(), OptionsCont::getStringVector(), OptionsCont::isUsableFileList(), myOptions, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, XMLSubSys::runParser(), and WRITE_MESSAGE.
Referenced by initNet().
void ROLoader::openRoutes (RONet & net)
Builds and opens all route loaders.
Definition at line 166 of file ROLoader.cpp.
References RONet::furtherStored(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), SUMORouteLoaderControl::getFirstLoadTime(), OptionsCont::getString(), SUMORouteLoaderControl::loadNext(), myLoaders, myOptions, openTypedRoutes(), string2time(), time2string(), MsgHandler::wasInformed(), and WRITE_MESSAGE.
Referenced by computeRoutes().
bool ROLoader::openTypedRoutes (const std::string & optionName, RONet & net) protected
Opens route handler of the given type.
Checks whether the given option name is known, returns true if not (this means that everything's ok, though the according handler is not built).
Checks then whether the given option name is set and his value is one or a set of valid (existing) files. This is done via a call to "OptionsCont::isUsableFileList" (which generates a proper error message).
If the given files are valid, the proper instance(s) is built using "buildNamedHandler" and if this could be done, it is added to the list of route handlers to use ("myHandler")
Returns whether the wished handler(s) could be built.
Parameters
[in] optionName The name of the option that refers to which handler and which files shall be used
[in] net The net to assign to the built handlers
Returns
Whether the wished handler(s) could be built
Definition at line 238 of file ROLoader.cpp.
References SUMORouteLoaderControl::add(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getStringVector(), OptionsCont::isSet(), OptionsCont::isUsableFileList(), myEmptyDestinationsAllowed, myLoaders, myOptions, and WRITE_ERROR.
Referenced by openRoutes().
ROLoader& ROLoader::operator= (const ROLoader & src) private
Invalidated assignment operator.
void ROLoader::processAllRoutesWithBulkRouter (SUMOTime start, SUMOTime end, RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router)
Loads all routes and processes them with BulkStarRouter.
Definition at line 229 of file ROLoader.cpp.
References SUMORouteLoaderControl::loadNext(), myLoaders, myOptions, RORouteAggregator::processAllRoutes(), RONet::saveAndRemoveRoutesUntil(), and SUMOTime_MAX.
Referenced by computeRoutes().
void ROLoader::processRoutes (const SUMOTime start, const SUMOTime end, const SUMOTime increment, RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router)
Loads routes from all previously build route loaders.
Definition at line 197 of file ROLoader.cpp.
References RONet::furtherStored(), MsgHandler::getErrorInstance(), SUMORouteLoaderControl::getFirstLoadTime(), OptionsCont::getOptions(), SUMORouteLoaderControl::haveAllLoaded(), OptionsCont::isDefault(), SUMORouteLoaderControl::loadNext(), MIN2(), myLoaders, myLogSteps, myOptions, RONet::saveAndRemoveRoutesUntil(), time2string(), MsgHandler::wasInformed(), WRITE_MESSAGE, and writeStats().
Referenced by computeRoutes().
void ROLoader::writeStats (SUMOTime time, SUMOTime start, int absNo, bool endGiven) protected
Definition at line 316 of file ROLoader.cpp.
References myLogSteps, SUMOReal, time2string(), and toString().
Referenced by processRoutes().
Field Documentation
const bool ROLoader::myEmptyDestinationsAllowed private
Information whether empty destinations are allowed.
Definition at line 192 of file ROLoader.h.
Referenced by openTypedRoutes().
SUMORouteLoaderControl ROLoader::myLoaders private
List of route loaders.
Definition at line 198 of file ROLoader.h.
Referenced by openRoutes(), openTypedRoutes(), processAllRoutesWithBulkRouter(), and processRoutes().
const bool ROLoader::myLogSteps private
Information whether the routing steps should be logged.
Definition at line 195 of file ROLoader.h.
Referenced by processRoutes(), and writeStats().
OptionsCont& ROLoader::myOptions private
Options to use.
Definition at line 189 of file ROLoader.h.
Referenced by loadNet(), loadWeights(), openRoutes(), openTypedRoutes(), processAllRoutesWithBulkRouter(), and processRoutes().
The documentation for this class was generated from the following files:
ROLoader.h
ROLoader.cpp