SUMO - Simulation of Urban MObility: ROMAAssignments Class Reference
ROMAAssignments Class Reference
assignment methods
#include <ROMAAssignments.h>
Public Member Functions
SUMOReal capacityConstraintFunction (const ROEdge *edge, const SUMOReal flow) const
void incremental (const int numIter)
ROMAAssignments (const SUMOTime begin, const SUMOTime end, RONet &net, ODMatrix &matrix, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Constructor.
void sue (const int maxOuterIteration, const int maxInnerIteration, const int kPaths, const SUMOReal penalty, const SUMOReal tolerance, const std::string routeChoiceMethod)
void ue ()
~ROMAAssignments ()
Destructor.
Static Public Member Functions
static SUMOReal getPenalizedEffort (const ROEdge *const e, const ROVehicle *const v, SUMOReal t)
Returns the effort to pass an edge including penalties.
static SUMOReal getPenalizedTT (const ROEdge *const e, const ROVehicle *const v, SUMOReal t)
Returns the traveltime on an edge including penalties.
static SUMOReal getTravelTime (const ROEdge *const e, const ROVehicle *const v, SUMOReal t)
Returns the traveltime on an edge without penalties.
Private Member Functions
bool addRoute (ConstROEdgeVector &edges, std::vector< RORoute * > &paths, std::string routeId, SUMOReal costs, SUMOReal prob)
add a route and check for duplicates
void getKPaths (const int kPaths, const SUMOReal penalty)
get the k shortest paths
ROMAAssignments & operator= (const ROMAAssignments &src)
Invalidated assignment operator.
Private Attributes
const SUMOTime myBegin
const SUMOTime myEnd
ODMatrix & myMatrix
RONet & myNet
SUMOAbstractRouter< ROEdge,
ROVehicle > & myRouter
Static Private Attributes
static ROVehicle * myDefaultVehicle = 0
static std::map< const ROEdge
*const, SUMOReal > myPenalties
Detailed Description
assignment methods
Definition at line 58 of file ROMAAssignments.h.
Constructor & Destructor Documentation
ROMAAssignments::ROMAAssignments (const SUMOTime begin, const SUMOTime end, RONet & net, ODMatrix & matrix, SUMOAbstractRouter< ROEdge, ROVehicle > & router)
Constructor.
Definition at line 61 of file ROMAAssignments.cpp.
References DEFAULT_VTYPE_ID, RONet::getVehicleTypeSecure(), and myDefaultVehicle.
ROMAAssignments::~ROMAAssignments ()
Destructor.
Definition at line 68 of file ROMAAssignments.cpp.
References myDefaultVehicle.
Member Function Documentation
bool ROMAAssignments::addRoute (ConstROEdgeVector & edges, std::vector< RORoute * > & paths, std::string routeId, SUMOReal costs, SUMOReal prob) private
add a route and check for duplicates
Definition at line 125 of file ROMAAssignments.cpp.
References RORoute::addProbability().
Referenced by getKPaths(), incremental(), and sue().
SUMOReal ROMAAssignments::capacityConstraintFunction (const ROEdge * edge, const SUMOReal flow) const
Definition at line 74 of file ROMAAssignments.cpp.
References ROEdge::ET_DISTRICT, ROEdge::getLaneNo(), ROEdge::getLength(), ROEdge::getPriority(), ROEdge::getSpeed(), and ROEdge::getType().
Referenced by incremental(), and sue().
void ROMAAssignments::getKPaths (const int kPaths, const SUMOReal penalty) private
get the k shortest paths
Definition at line 143 of file ROMAAssignments.cpp.
References addRoute(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, ODMatrix::getCells(), RONet::getEdge(), myDefaultVehicle, myMatrix, myNet, myPenalties, myRouter, ODCell::origin, ODCell::pathsVector, and toString().
Referenced by sue().
SUMOReal ROMAAssignments::getPenalizedEffort (const ROEdge *const e, const ROVehicle *const v, SUMOReal t) static
Returns the effort to pass an edge including penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See Also
DijkstraRouterTT_ByProxi
Definition at line 276 of file ROMAAssignments.cpp.
References ROEdge::getEffort(), and myPenalties.
Referenced by computeRoutes().
SUMOReal ROMAAssignments::getPenalizedTT (const ROEdge *const e, const ROVehicle *const v, SUMOReal t) static
Returns the traveltime on an edge including penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See Also
DijkstraRouterTT_ByProxi
Definition at line 283 of file ROMAAssignments.cpp.
References ROEdge::getTravelTime(), and myPenalties.
Referenced by computeRoutes().
SUMOReal ROMAAssignments::getTravelTime (const ROEdge *const e, const ROVehicle *const v, SUMOReal t) static
Returns the traveltime on an edge without penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See Also
DijkstraRouterTT_ByProxi
Definition at line 290 of file ROMAAssignments.cpp.
References ROEdge::getTravelTime().
Referenced by computeRoutes().
void ROMAAssignments::incremental (const int numIter)
Definition at line 161 of file ROMAAssignments.cpp.
References ROEdge::addEffort(), addRoute(), ROEdge::addTravelTime(), capacityConstraintFunction(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, ODMatrix::getCells(), RONet::getEdge(), myBegin, myDefaultVehicle, myEnd, myMatrix, myNet, myRouter, ODCell::origin, ODCell::pathsVector, STEPS2TIME, SUMOReal, toString(), and ODCell::vehicleNumber.
ROMAAssignments& ROMAAssignments::operator= (const ROMAAssignments & src) private
Invalidated assignment operator.
void ROMAAssignments::sue (const int maxOuterIteration, const int maxInnerIteration, const int kPaths, const SUMOReal penalty, const SUMOReal tolerance, const std::string routeChoiceMethod)
Definition at line 183 of file ROMAAssignments.cpp.
References abs, ROEdge::addEffort(), addRoute(), ROEdge::addTravelTime(), capacityConstraintFunction(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, RouteCostCalculator< R, E, V >::getCalculator(), ODMatrix::getCells(), RONet::getEdge(), RONet::getEdgeMap(), RORoute::getEdgeVector(), ROEdge::getEffort(), ROMAEdge::getHelpFlow(), getKPaths(), RORoute::getProbability(), myBegin, myDefaultVehicle, myEnd, myMatrix, myNet, myRouter, ODCell::origin, ODCell::pathsVector, SUMOAbstractRouter< E, V >::recomputeCosts(), RORoute::setCosts(), ROMAEdge::setHelpFlow(), RORoute::setProbability(), STEPS2TIME, SUMOReal, toString(), and ODCell::vehicleNumber.
void ROMAAssignments::ue ()
Field Documentation
const SUMOTime ROMAAssignments::myBegin private
Definition at line 125 of file ROMAAssignments.h.
Referenced by incremental(), and sue().
ROVehicle * ROMAAssignments::myDefaultVehicle = 0 static private
Definition at line 131 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), ROMAAssignments(), sue(), and ~ROMAAssignments().
const SUMOTime ROMAAssignments::myEnd private
Definition at line 126 of file ROMAAssignments.h.
Referenced by incremental(), and sue().
ODMatrix& ROMAAssignments::myMatrix private
Definition at line 128 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), and sue().
RONet& ROMAAssignments::myNet private
Definition at line 127 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), and sue().
std::map< const ROEdge *const, SUMOReal > ROMAAssignments::myPenalties static private
Definition at line 130 of file ROMAAssignments.h.
Referenced by getKPaths(), getPenalizedEffort(), and getPenalizedTT().
SUMOAbstractRouter<ROEdge, ROVehicle>& ROMAAssignments::myRouter private
Definition at line 129 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), and sue().
The documentation for this class was generated from the following files:
ROMAAssignments.h
ROMAAssignments.cpp