SUMO - Simulation of Urban MObility: MSJunctionControl Class Reference
MSJunctionControl Class Reference
Container for junctions; performs operations on all stored junctions.
#include <MSJunctionControl.h>
Public Types
typedef std::map< std::string,
MSJunction * > IDMap
Definition of the key to pointer map type.
Public Member Functions
virtual bool add (const std::string &id, MSJunction *item)
Adds an item.
const std::vector< MSJunction * > & buildAndGetStaticVector () const
void clear ()
Removes all items from the container (deletes them, too)
bool erase (const std::string &id)
Removes the named item from the container.
MSJunction * get (const std::string &id) const
Retrieves an item.
const IDMap & getMyMap () const
std::vector< MSJunction * > getTempVector () const
void insertIDs (std::vector< std::string > &into) const
MSJunctionControl ()
Constructor.
void postloadInitContainer ()
Closes building of junctions.
virtual bool remove (const std::string &id)
Removes an item.
unsigned int size () const
Returns the number of items within the container.
~MSJunctionControl ()
Destructor.
Private Member Functions
MSJunctionControl (const MSJunctionControl &)
Invalidated copy constructor.
MSJunctionControl & operator= (const MSJunctionControl &)
Invalidated assignment operator.
Detailed Description
Container for junctions; performs operations on all stored junctions.
Definition at line 57 of file MSJunctionControl.h.
Member Typedef Documentation
typedef std::map< std::string, MSJunction * > NamedObjectCont< MSJunction * >::IDMap inherited
Definition of the key to pointer map type.
Definition at line 57 of file NamedObjectCont.h.
Constructor & Destructor Documentation
MSJunctionControl::MSJunctionControl ()
Constructor.
Definition at line 46 of file MSJunctionControl.cpp.
MSJunctionControl::~MSJunctionControl ()
Destructor.
Definition at line 50 of file MSJunctionControl.cpp.
MSJunctionControl::MSJunctionControl (const MSJunctionControl &) private
Invalidated copy constructor.
Member Function Documentation
virtual bool NamedObjectCont< MSJunction * >::add (const std::string & id, MSJunction * item) inline virtual inherited
Adds an item.
If another item with the same name is already known, false is reported and the item is not added.
Parameters
[in] id The id of the item to add
[in] item The item to add
Returns
If the item could been added (no item with the same id was within the container before)
Definition at line 80 of file NamedObjectCont.h.
const std::vector<MSJunction * >& NamedObjectCont< MSJunction * >::buildAndGetStaticVector () const inline inherited
Definition at line 179 of file NamedObjectCont.h.
Referenced by postloadInitContainer().
void NamedObjectCont< MSJunction * >::clear () inline inherited
Removes all items from the container (deletes them, too)
Definition at line 123 of file NamedObjectCont.h.
bool NamedObjectCont< MSJunction * >::erase (const std::string & id) inline inherited
Removes the named item from the container.
If the named object exists, it is deleted, the key is removed from the map, and true is returned. If the id was not known, false is returned.
Parameters
[in] id The id of the item to delete
Returns
Whether the object could be deleted (was within the map)
Definition at line 151 of file NamedObjectCont.h.
MSJunction * NamedObjectCont< MSJunction * >::get (const std::string & id) const inline inherited
Retrieves an item.
Returns 0 when no item with the given id is stored within the container
Parameters
[in] id The id of the item to retrieve
Returns
The item stored under the given id, or 0 if no such item exists
Definition at line 113 of file NamedObjectCont.h.
const IDMap& NamedObjectCont< MSJunction * >::getMyMap () const inline inherited
Definition at line 224 of file NamedObjectCont.h.
std::vector<MSJunction * > NamedObjectCont< MSJunction * >::getTempVector () const inline inherited
Definition at line 199 of file NamedObjectCont.h.
void NamedObjectCont< MSJunction * >::insertIDs (std::vector< std::string > & into) const inline inherited
Definition at line 212 of file NamedObjectCont.h.
MSJunctionControl& MSJunctionControl::operator= (const MSJunctionControl &) private
Invalidated assignment operator.
void MSJunctionControl::postloadInitContainer ()
Closes building of junctions.
Calls "postloadInit" on all stored junctions.
Exceptions
ProcessError From the called "postloadInit"
See Also
MSJunction::postloadInit
Definition at line 55 of file MSJunctionControl.cpp.
References NamedObjectCont< MSJunction * >::buildAndGetStaticVector().
Referenced by MSNet::closeBuilding().
virtual bool NamedObjectCont< MSJunction * >::remove (const std::string & id) inline virtual inherited
Removes an item.
Parameters
[in] id The id of the item to remove
Returns
If the item could been removed (an item with the id was within the container before)
Definition at line 94 of file NamedObjectCont.h.
unsigned int NamedObjectCont< MSJunction * >::size () const inline inherited
Returns the number of items within the container.
Returns
The number of stored items
Definition at line 137 of file NamedObjectCont.h.
The documentation for this class was generated from the following files:
MSJunctionControl.h
MSJunctionControl.cpp