SUMO - Simulation of Urban MObility: StdDefs.cpp File Reference
StdDefs.cpp File Reference
#include "RGBColor.h"
#include "StdDefs.h"
Functions
const std::string getBuildName (const std::string &version)
attach some build flags to the version string
const RGBColor & getLinkColor (const LinkState &ls)
Variables
bool gDebugFlag1 = false
global utility flags for debugging
bool gDebugFlag2 = false
const RGBColor SUMO_color_ALLWAY_STOP (0, 0, 192)
const RGBColor SUMO_color_DEADEND (0, 0, 0)
const RGBColor SUMO_color_EQUAL (128, 128, 128)
const RGBColor SUMO_color_MAJOR (255, 255, 255)
const RGBColor SUMO_color_MINOR (51, 51, 51)
const RGBColor SUMO_color_STOP (128, 0, 128)
const RGBColor SUMO_color_TL_GREEN_MAJOR (0, 255, 0)
const RGBColor SUMO_color_TL_GREEN_MINOR (0, 179, 0)
const RGBColor SUMO_color_TL_OFF_BLINKING (128, 64, 0)
const RGBColor SUMO_color_TL_OFF_NOSIGNAL (0, 255, 255)
const RGBColor SUMO_color_TL_RED (255, 0, 0)
const RGBColor SUMO_color_TL_REDYELLOW (255, 128, 0)
const RGBColor SUMO_color_TL_YELLOW_MAJOR (255, 255, 0)
const RGBColor SUMO_color_TL_YELLOW_MINOR (255, 255, 0)
Detailed Description
Author
Jakob Erdmann
Michael Behrisch
Laura Bieker
Date
2014-01-07
Version
Id:
StdDefs.cpp 18095 2015-03-17 09:39:00Z behrisch
Definition in file StdDefs.cpp.
Function Documentation
const std::string getBuildName (const std::string & version)
attach some build flags to the version string
Definition at line 88 of file StdDefs.cpp.
Referenced by GUIApplicationWindow::closeAllWindows(), GUIApplicationWindow::dependentBuild(), GUIDialog_AboutSUMO::GUIDialog_AboutSUMO(), GUIApplicationWindow::handleEvent_SimulationLoaded(), and main().
const RGBColor& getLinkColor (const LinkState & ls)
Definition at line 52 of file StdDefs.cpp.
References LINKSTATE_ALLWAY_STOP, LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_STOP, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, SUMO_color_ALLWAY_STOP, SUMO_color_DEADEND, SUMO_color_EQUAL, SUMO_color_MAJOR, SUMO_color_MINOR, SUMO_color_STOP, SUMO_color_TL_GREEN_MAJOR, SUMO_color_TL_GREEN_MINOR, SUMO_color_TL_OFF_BLINKING, SUMO_color_TL_OFF_NOSIGNAL, SUMO_color_TL_RED, SUMO_color_TL_REDYELLOW, SUMO_color_TL_YELLOW_MAJOR, and SUMO_color_TL_YELLOW_MINOR.
Referenced by GUILane::drawLane2LaneConnections(), GUILane::drawLinkRule(), and GUITLLogicPhasesTrackerWindow::drawValues().
Variable Documentation
bool gDebugFlag1 = false
global utility flags for debugging
Definition at line 99 of file StdDefs.cpp.
Referenced by MSLCM_JE2013::_patchSpeed(), NBNode::buildCrossings(), NBNode::buildWalkingAreas(), NBNode::checkCrossing(), NBEdge::getCrossingAngle(), NBNode::getEdgesSortedByAngleAtNodeCenter(), NBNode::guessCrossings(), and MSLCM_JE2013::patchSpeed().
bool gDebugFlag2 = false
Definition at line 100 of file StdDefs.cpp.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_JE2013::inform(), MSLCM_JE2013::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_JE2013::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), and MSLCM_JE2013::wantsChange().
const RGBColor SUMO_color_ALLWAY_STOP(0, 0, 192)
Referenced by getLinkColor().
const RGBColor SUMO_color_DEADEND(0, 0, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_EQUAL(128, 128, 128)
Referenced by getLinkColor().
const RGBColor SUMO_color_MAJOR(255, 255, 255)
Referenced by getLinkColor().
const RGBColor SUMO_color_MINOR(51, 51, 51)
Referenced by getLinkColor().
const RGBColor SUMO_color_STOP(128, 0, 128)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_GREEN_MAJOR(0, 255, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_GREEN_MINOR(0, 179, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_OFF_BLINKING(128, 64, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_OFF_NOSIGNAL(0, 255, 255)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_RED(255, 0, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_REDYELLOW(255, 128, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_YELLOW_MAJOR(255, 255, 0)
Referenced by getLinkColor().
const RGBColor SUMO_color_TL_YELLOW_MINOR(255, 255, 0)
Referenced by getLinkColor().