SUMO - Simulation of Urban MObility: GUIDialog_Breakpoints Class Reference
GUIDialog_Breakpoints Class Reference
Editor for simulation breakpoints.
#include <GUIDialog_Breakpoints.h>
Public Member Functions
GUIDialog_Breakpoints (GUIMainWindow *parent, std::vector< SUMOTime > &breakpoints, MFXMutex &breakpointLock)
Constructor.
~GUIDialog_Breakpoints ()
Destructor.
FOX-callbacks
long onCmdLoad (FXObject *, FXSelector, void *)
Called when the user presses the Load-button.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user presses the Save-button.
long onCmdClear (FXObject *, FXSelector, void *)
Called when the user presses the Clear-button.
long onCmdClose (FXObject *, FXSelector, void *)
Called when the user presses the Close-button.
long onCmdEditTable (FXObject *, FXSelector, void *)
Called when the table was changed.
Protected Member Functions
GUIDialog_Breakpoints ()
FOX needs this.
Private Member Functions
std::string encode2TXT ()
Builds a text representation of the items in the list.
void rebuildList ()
Rebuilds the entire list.
Private Attributes
MFXMutex * myBreakpointLock
Lock for modifying the list of breakpoints.
std::vector< SUMOTime > * myBreakpoints
List of breakpoints.
GUIMainWindow * myParent
The parent window.
MFXAddEditTypedTable * myTable
The list that holds the ids.
Detailed Description
Editor for simulation breakpoints.
This dialog shows and lets the user edit the list of breakpoints - simulation time steps where the simulation halts.
Todo:
Use a LineReader instead of >> while reading
Definition at line 56 of file GUIDialog_Breakpoints.h.
Constructor & Destructor Documentation
GUIDialog_Breakpoints::GUIDialog_Breakpoints (GUIMainWindow * parent, std::vector< SUMOTime > & breakpoints, MFXMutex & breakpointLock)
Constructor.
Parameters
[in] parent The parent window
Definition at line 86 of file GUIDialog_Breakpoints.cpp.
References CT_REAL, GUIIconSubSys::getIcon(), OptionsCont::getOptions(), ICON_APP_BREAKPOINTS, MID_CANCEL, MID_CHOOSEN_CLEAR, MID_CHOOSEN_LOAD, MID_CHOOSEN_SAVE, MID_TABLE, string2time(), and SUMOTime_MAX.
GUIDialog_Breakpoints::~GUIDialog_Breakpoints ()
Destructor.
Definition at line 126 of file GUIDialog_Breakpoints.cpp.
References myParent, and GUIMainWindow::removeChild().
GUIDialog_Breakpoints::GUIDialog_Breakpoints () inline protected
FOX needs this.
Definition at line 118 of file GUIDialog_Breakpoints.h.
Member Function Documentation
std::string GUIDialog_Breakpoints::encode2TXT () private
Builds a text representation of the items in the list.
Returns
Breakpoints encoded as a string
Definition at line 199 of file GUIDialog_Breakpoints.cpp.
References INVALID_VALUE, MFXMutex::lock(), myBreakpointLock, myBreakpoints, time2string(), and MFXMutex::unlock().
Referenced by onCmdSave().
long GUIDialog_Breakpoints::onCmdClear (FXObject * , FXSelector , void *)
Called when the user presses the Clear-button.
Definition at line 214 of file GUIDialog_Breakpoints.cpp.
References MFXMutex::lock(), myBreakpointLock, myBreakpoints, rebuildList(), and MFXMutex::unlock().
long GUIDialog_Breakpoints::onCmdClose (FXObject * , FXSelector , void *)
Called when the user presses the Close-button.
Definition at line 225 of file GUIDialog_Breakpoints.cpp.
long GUIDialog_Breakpoints::onCmdEditTable (FXObject * , FXSelector , void * data)
Called when the table was changed.
Definition at line 232 of file GUIDialog_Breakpoints.cpp.
References MFXEditedTableItem::col, INVALID_VALUE, INVALID_VALUE_STR, MFXEditedTableItem::item, MFXMutex::lock(), myBreakpointLock, myBreakpoints, rebuildList(), MFXEditedTableItem::row, string2time(), MFXMutex::unlock(), and MFXEditedTableItem::updateOnly.
long GUIDialog_Breakpoints::onCmdLoad (FXObject * , FXSelector , void *)
Called when the user presses the Load-button.
Definition at line 159 of file GUIDialog_Breakpoints.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, GUISettingsHandler::loadBreakpoints(), MFXMutex::lock(), myBreakpointLock, myBreakpoints, rebuildList(), and MFXMutex::unlock().
long GUIDialog_Breakpoints::onCmdSave (FXObject * , FXSelector , void *)
Called when the user presses the Save-button.
Definition at line 181 of file GUIDialog_Breakpoints.cpp.
References OutputDevice::close(), encode2TXT(), gCurrentFolder, OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), and ICON_EMPTY.
void GUIDialog_Breakpoints::rebuildList () private
Rebuilds the entire list.
Definition at line 132 of file GUIDialog_Breakpoints.cpp.
References myBreakpoints, myTable, and time2string().
Referenced by onCmdClear(), onCmdEditTable(), and onCmdLoad().
Field Documentation
MFXMutex* GUIDialog_Breakpoints::myBreakpointLock private
Lock for modifying the list of breakpoints.
Definition at line 113 of file GUIDialog_Breakpoints.h.
Referenced by encode2TXT(), onCmdClear(), onCmdEditTable(), and onCmdLoad().
std::vector<SUMOTime>* GUIDialog_Breakpoints::myBreakpoints private
List of breakpoints.
Definition at line 110 of file GUIDialog_Breakpoints.h.
Referenced by encode2TXT(), onCmdClear(), onCmdEditTable(), onCmdLoad(), and rebuildList().
GUIMainWindow* GUIDialog_Breakpoints::myParent private
The parent window.
Definition at line 107 of file GUIDialog_Breakpoints.h.
Referenced by ~GUIDialog_Breakpoints().
MFXAddEditTypedTable* GUIDialog_Breakpoints::myTable private
The list that holds the ids.
Definition at line 104 of file GUIDialog_Breakpoints.h.
Referenced by rebuildList().
The documentation for this class was generated from the following files:
GUIDialog_Breakpoints.h
GUIDialog_Breakpoints.cpp