SUMO - Simulation of Urban MObility: NBNodesEdgesSorter::crossing_by_junction_angle_sorter Class Reference
NBNodesEdgesSorter::crossing_by_junction_angle_sorter Class Reference
Sorts crossings by minimum clockwise clockwise edge angle. Use the ordering found in myAllEdges of the given node.
#include <NBAlgorithms.h>
Public Member Functions
crossing_by_junction_angle_sorter (const NBNode *node, const EdgeVector &ordering)
int operator() (const NBNode::Crossing &c1, const NBNode::Crossing &c2) const
Private Member Functions
size_t getMinRank (const EdgeVector &e) const
retrieves the minimum index in myAllEdges
crossing_by_junction_angle_sorter & operator= (const crossing_by_junction_angle_sorter &s)
invalidated assignment operator
Private Attributes
EdgeVector myOrdering
Detailed Description
Sorts crossings by minimum clockwise clockwise edge angle. Use the ordering found in myAllEdges of the given node.
Definition at line 119 of file NBAlgorithms.h.
Constructor & Destructor Documentation
NBNodesEdgesSorter::crossing_by_junction_angle_sorter::crossing_by_junction_angle_sorter (const NBNode * node, const EdgeVector & ordering) explicit
Definition at line 424 of file NBAlgorithms.cpp.
References myOrdering.
Member Function Documentation
size_t NBNodesEdgesSorter::crossing_by_junction_angle_sorter::getMinRank (const EdgeVector & e) const inline private
retrieves the minimum index in myAllEdges
Definition at line 129 of file NBAlgorithms.h.
References MIN2(), and myOrdering.
Referenced by operator()().
int NBNodesEdgesSorter::crossing_by_junction_angle_sorter::operator() (const NBNode::Crossing & c1, const NBNode::Crossing & c2) const inline
Definition at line 123 of file NBAlgorithms.h.
References NBNode::Crossing::edges, and getMinRank().
crossing_by_junction_angle_sorter& NBNodesEdgesSorter::crossing_by_junction_angle_sorter::operator= (const crossing_by_junction_angle_sorter & s) private
invalidated assignment operator
Field Documentation
EdgeVector NBNodesEdgesSorter::crossing_by_junction_angle_sorter::myOrdering private
Definition at line 139 of file NBAlgorithms.h.
Referenced by crossing_by_junction_angle_sorter(), and getMinRank().
The documentation for this class was generated from the following files:
NBAlgorithms.h
NBAlgorithms.cpp