SUMO - Simulation of Urban MObility: NBNode::ApproachingDivider Class Reference
NBNode::ApproachingDivider Class Reference
Computes lane-2-lane connections.
#include <NBNode.h>
Public Member Functions
ApproachingDivider (EdgeVector *approaching, NBEdge *currentOutgoing, const bool buildCrossingsAndWalkingAreas)
Constructor.
void execute (const unsigned int src, const unsigned int dest)
unsigned int numAvailableLanes () const
std::deque< int > * spread (const std::vector< int > &approachingLanes, int dest) const
~ApproachingDivider ()
Destructor.
Private Attributes
EdgeVector * myApproaching
The list of edges that approach the current edge.
std::vector< unsigned int > myAvailableLanes
The available lanes to which connections shall be built.
NBEdge * myCurrentOutgoing
The approached current edge.
Detailed Description
Computes lane-2-lane connections.
Being a bresenham-callback, this class computes which lanes are approached by the current lane (first callback parameter). The second callback parameter is the destination lane that is the middle of the computed lanes. The lanes are spreaded from this middle position both to left and right but may also be transposed in full when there is not enough space.
Definition at line 96 of file NBNode.h.
Constructor & Destructor Documentation
NBNode::ApproachingDivider::ApproachingDivider (EdgeVector * approaching, NBEdge * currentOutgoing, const bool buildCrossingsAndWalkingAreas)
Constructor.
Parameters
[in] approaching The list of the edges that approach the outgoing edge
[in] currentOutgoing The outgoing edge
Definition at line 99 of file NBNode.cpp.
References NBEdge::getNumLanes(), NBEdge::getPermissions(), isForbidden(), myApproaching, myAvailableLanes, myCurrentOutgoing, and SVC_PEDESTRIAN.
NBNode::ApproachingDivider::~ApproachingDivider ()
Destructor.
Definition at line 129 of file NBNode.cpp.
Member Function Documentation
void NBNode::ApproachingDivider::execute (const unsigned int src, const unsigned int dest) virtual
the bresenham-callback
Implements Bresenham::BresenhamCallBack.
Definition at line 133 of file NBNode.cpp.
References NBEdge::getConnectionLanes(), NBEdge::L2L_COMPUTED, NBEdge::LANES2LANES_DONE, and NBEdge::LANES2LANES_USER.
unsigned int NBNode::ApproachingDivider::numAvailableLanes () const inline
Definition at line 118 of file NBNode.h.
References myAvailableLanes.
Referenced by NBNode::computeLanes2Lanes().
std::deque< int > * NBNode::ApproachingDivider::spread (const std::vector< int > & approachingLanes, int dest) const
the method that spreads the wished number of lanes from the the lane given by the bresenham-call to both left and right
Definition at line 159 of file NBNode.cpp.
Field Documentation
EdgeVector* NBNode::ApproachingDivider::myApproaching private
The list of edges that approach the current edge.
Definition at line 99 of file NBNode.h.
Referenced by ApproachingDivider().
std::vector<unsigned int> NBNode::ApproachingDivider::myAvailableLanes private
The available lanes to which connections shall be built.
Definition at line 105 of file NBNode.h.
Referenced by ApproachingDivider(), and numAvailableLanes().
NBEdge* NBNode::ApproachingDivider::myCurrentOutgoing private
The approached current edge.
Definition at line 102 of file NBNode.h.
Referenced by ApproachingDivider().
The documentation for this class was generated from the following files:
NBNode.h
NBNode.cpp