SUMO - Simulation of Urban MObility: MSDevice_Vehroutes Class Reference
MSDevice_Vehroutes Class Reference
A device which collects info on the vehicle trip (mainly on departure and arrival)
#include <MSDevice_Vehroutes.h>
Data Structures
class RouteReplaceInfo
Information about a replaced route.
class StateListener
A class that is notified about reroutings.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void generateOutput () const
Called on writing tripinfo output.
const std::string & getDescription () const
SUMOVehicle & getHolder () const
Returns the vehicle that holds this device.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
const MSRoute * getRoute (int index) const
Called on route retrieval.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
~MSDevice_Vehroutes ()
Destructor.
Methods called on vehicle movement / state change, overwriting MSDevice
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Does nothing, returns true only if exit times should be collected.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, Notification reason)
Saves exit times if needed.
Interface methods, to be derived by subclasses
virtual bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
Static Public Member Functions
static MSDevice_Vehroutes * buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice * > &into, unsigned int maxRoutes=INT_MAX)
Build devices for the given vehicle, if needed.
static void buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice * > &into)
Build devices for the given vehicle, if needed.
static void generateOutputForUnfinished ()
generate vehroute output for vehicles which are still in the network
static void init ()
Static intialization.
static void insertOptions (OptionsCont &oc)
Inserts options for building devices.
Static Protected Member Functions
Helper methods for device assignment
static void insertDefaultAssignmentOptions (const std::string &deviceName, const std::string &optionsTopic, OptionsCont &oc)
Adds common command options that allow to assign devices to vehicles.
static bool equippedByDefaultAssignmentOptions (const OptionsCont &oc, const std::string &deviceName, SUMOVehicle &v)
Determines whether a vehicle should get a certain device.
Protected Attributes
std::string myDescription
a description of this moveReminder
SUMOVehicle & myHolder
The vehicle that stores the device.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
void addRoute ()
Called on route change.
MSDevice_Vehroutes (SUMOVehicle &holder, const std::string &id, unsigned int maxRoutes)
Constructor.
MSDevice_Vehroutes (const MSDevice_Vehroutes &)
Invalidated copy constructor.
MSDevice_Vehroutes & operator= (const MSDevice_Vehroutes &)
Invalidated assignment operator.
void writeXMLRoute (OutputDevice &os, int index=-1) const
Called on route output.
Private Attributes
const MSRoute * myCurrentRoute
The currently used route.
std::vector< SUMOTime > myExits
The times the vehicle exites an edge.
const MSEdge * myLastSavedAt
The last edge the exit time was saved for.
const unsigned int myMaxRoutes
The maximum number of routes to report.
std::vector< RouteReplaceInfo > myReplacedRoutes
Prior routes.
Static Private Attributes
static std::map< const
SUMOTime, int > myDepartureCounts
Map needed to sort vehicles by departure time.
static bool myDUAStyle = false
A shortcut for the Option "vehroute-output.dua".
static bool myIntendedDepart = false
A shortcut for the Option "vehroute-output.intended-depart".
static bool myLastRouteOnly = false
A shortcut for the Option "vehroute-output.last-route".
static std::map< const
SUMOTime, std::map< const
std::string, std::string > > myRouteInfos
static bool mySaveExits = false
A shortcut for the Option "vehroute-output.exit-times".
static bool mySorted = false
A shortcut for the Option "vehroute-output.sorted".
static StateListener myStateListener
A class that is notified about reroutings.
static bool myWithTaz = false
A shortcut for the Option "device.routing.with-taz".
Detailed Description
A device which collects info on the vehicle trip (mainly on departure and arrival)
Each device collects departure time, lane and speed and the same for arrival.
See Also
MSDevice
Definition at line 58 of file MSDevice_Vehroutes.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSDevice_Vehroutes::~MSDevice_Vehroutes ()
Destructor.
Definition at line 120 of file MSDevice_Vehroutes.cpp.
References myCurrentRoute, MSDevice_Vehroutes::StateListener::myDevices, MSDevice::myHolder, myReplacedRoutes, myStateListener, and MSRoute::release().
MSDevice_Vehroutes::MSDevice_Vehroutes (SUMOVehicle & holder, const std::string & id, unsigned int maxRoutes) private
Constructor.
Parameters
[in] holder The vehicle that holds this device
[in] id The ID of the device
Definition at line 114 of file MSDevice_Vehroutes.cpp.
References MSRoute::addReference(), and myCurrentRoute.
Referenced by buildVehicleDevices().
MSDevice_Vehroutes::MSDevice_Vehroutes (const MSDevice_Vehroutes &) private
Invalidated copy constructor.
Member Function Documentation
void MSDevice_Vehroutes::addRoute () private
Called on route change.
Definition at line 296 of file MSDevice_Vehroutes.cpp.
References MSRoute::addReference(), MSNet::getCurrentTimeStep(), SUMOVehicle::getEdge(), MSNet::getInstance(), SUMOVehicle::getRoute(), SUMOVehicle::hasDeparted(), myCurrentRoute, MSDevice::myHolder, myMaxRoutes, myReplacedRoutes, and MSRoute::release().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
MSDevice_Vehroutes * MSDevice_Vehroutes::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice * > & into, unsigned int maxRoutes = INT_MAX) static
Build devices for the given vehicle, if needed.
The options are read and evaluated whether a vehroutes-device shall be built for the given vehicle.
The built device is stored in the given vector.
Parameters
[in] v The vehicle for which a device may be built
filled] into The vector to store the built device in
Definition at line 84 of file MSDevice_Vehroutes.cpp.
References SUMOVehicle::getID(), OptionsCont::getOptions(), OptionsCont::isSet(), MSDevice_Vehroutes(), MSDevice_Vehroutes::StateListener::myDevices, myLastRouteOnly, and myStateListener.
Referenced by MSDevice::buildVehicleDevices(), and GUIVehicle::GUIVehicle().
void MSDevice::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice * > & into) static inherited
Build devices for the given vehicle, if needed.
Parameters
[in] v The vehicle for which a device may be built
filled] into The vector to store the built device in
Definition at line 73 of file MSDevice.cpp.
References MSDevice_Tripinfo::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), and MSDevice_Routing::buildVehicleDevices().
Referenced by MSBaseVehicle::MSBaseVehicle().
bool MSDevice::equippedByDefaultAssignmentOptions (const OptionsCont & oc, const std::string & deviceName, SUMOVehicle & v) static protected inherited
Determines whether a vehicle should get a certain device.
Parameters
[in] oc The options container to get the information about assignment from
[in] deviceName The name of the device type
[in] v The vehicle to determine whether it shall be equipped or not
Definition at line 99 of file MSDevice.cpp.
References TplConvert::_2bool(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getFloat(), SUMOVehicle::getID(), MSNet::getInstance(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), MSVehicleControl::getQuota(), OptionsCont::getStringVector(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), OptionsCont::isSet(), Parameterised::knowsParameter(), MSDevice::myExplicitIDs, and RandHelper::rand().
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), and MSDevice_Routing::buildVehicleDevices().
void MSDevice_Vehroutes::generateOutput () const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
See Also
MSDevice::tripInfoOutput
Reimplemented from MSDevice.
Definition at line 217 of file MSDevice_Vehroutes.cpp.
References DEFAULT_VTYPE_ID, SUMOVehicleParameter::depart, MSRoute::distDictionary(), SUMOVehicleParameter::fromTaz, SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), SUMOVehicle::getParameter(), RandomDistributor< T >::getProbs(), RandomDistributor< T >::getVals(), SUMOVehicle::getVehicleType(), SUMOVehicle::hasArrived(), OutputDevice::isBinary(), myCurrentRoute, myDepartureCounts, myDUAStyle, MSDevice::myHolder, myIntendedDepart, myReplacedRoutes, myRouteInfos, mySorted, myWithTaz, SUMO_ATTR_COST, SUMO_ATTR_DEPART, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_ID, SUMO_ATTR_LAST, SUMO_ATTR_PROB, SUMO_ATTR_TO_TAZ, SUMO_ATTR_TYPE, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, time2string(), SUMOVehicleParameter::toTaz, and writeXMLRoute().
void MSDevice_Vehroutes::generateOutputForUnfinished () static
generate vehroute output for vehicles which are still in the network
Definition at line 316 of file MSDevice_Vehroutes.cpp.
References MSDevice_Vehroutes::StateListener::myDevices, and myStateListener.
Referenced by MSNet::closeSimulation().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 215 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
SUMOVehicle& MSDevice::getHolder () const inline inherited
Returns the vehicle that holds this device.
Returns
The vehicle that holds this device
Definition at line 105 of file MSDevice.h.
References MSDevice::myHolder.
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSE2Collector::detectorUpdate(), MSDevice_Tripinfo::generateOutput(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
const MSRoute * MSDevice_Vehroutes::getRoute (int index) const
Called on route retrieval.
Parameters
[in] index The index of the route to retrieve
Returns
the route at the index
Definition at line 290 of file MSDevice_Vehroutes.cpp.
References myReplacedRoutes.
Referenced by GUIVehicle::drawRoute().
void MSDevice_Vehroutes::init () static
Static intialization.
Definition at line 69 of file MSDevice_Vehroutes.cpp.
References MSNet::addVehicleStateListener(), OutputDevice::createDeviceByOption(), OptionsCont::getBool(), MSNet::getInstance(), OptionsCont::getOptions(), myDUAStyle, myIntendedDepart, myLastRouteOnly, mySaveExits, mySorted, myStateListener, and myWithTaz.
Referenced by MSFrame::buildStreams().
void MSDevice::insertDefaultAssignmentOptions (const std::string & deviceName, const std::string & optionsTopic, OptionsCont & oc) static protected inherited
Adds common command options that allow to assign devices to vehicles.
Parameters
[in] deviceName The name of the device type
[in] optionsTopic The options topic into which the options shall be added
filled] oc The options container to add the options to
!! describe
!! describe
!! describe
Definition at line 85 of file MSDevice.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by MSDevice_BTsender::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Emissions::insertOptions(), and MSDevice_Routing::insertOptions().
void MSDevice::insertOptions (OptionsCont & oc) static inherited
Inserts options for building devices.
Parameters
filled] oc The options container to add the options to
Definition at line 63 of file MSDevice.cpp.
References MSDevice_Example::insertOptions(), MSDevice_BTsender::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Emissions::insertOptions(), and MSDevice_Routing::insertOptions().
Referenced by MSFrame::fillOptions().
bool MSDevice_Vehroutes::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) virtual
Does nothing, returns true only if exit times should be collected.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True, if exit times are to be collected.
See Also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 130 of file MSDevice_Vehroutes.cpp.
References SUMOVehicleParameter::depart, MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getParameter(), myDepartureCounts, MSDevice_Vehroutes::StateListener::myDevices, MSDevice::myHolder, myIntendedDepart, mySaveExits, mySorted, myStateListener, and MSMoveReminder::NOTIFICATION_DEPARTED.
bool MSDevice_Vehroutes::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual
Saves exit times if needed.
The exit time is collected on all occasions except for lane change.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See Also
MSMoveReminder::notifyLeave
Returns
True, if exit times are to be collected.
Reimplemented from MSMoveReminder.
Definition at line 140 of file MSDevice_Vehroutes.cpp.
References MSNet::getCurrentTimeStep(), SUMOVehicle::getEdge(), MSNet::getInstance(), myExits, myLastSavedAt, mySaveExits, MSMoveReminder::NOTIFICATION_LANE_CHANGE, and MSMoveReminder::NOTIFICATION_TELEPORT.
virtual bool MSMoveReminder::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) inline virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented in MSE3Collector::MSE3LeaveReminder, MSE2Collector, MSInductLoop, MSDevice_BTreceiver, MSMeanData::MeanDataValues, MSDevice_BTsender, MSDevice_Emissions, MSE3Collector::MSE3EntryReminder, MSInstantInductLoop, MSDevice_Example, MSDevice_Tripinfo, MSDevice_Person, and MSDevice_Container.
Definition at line 150 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 203 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
MSDevice_Vehroutes& MSDevice_Vehroutes::operator= (const MSDevice_Vehroutes &) private
Invalidated assignment operator.
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 211 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), and MSCalibrator::MSCalibrator().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void MSDevice_Vehroutes::writeXMLRoute (OutputDevice & os, int index = -1) const private
Called on route output.
Parameters
[in] os the device to write into
[in] index The index of the route to write (-1 writes the current route)
Definition at line 154 of file MSDevice_Vehroutes.cpp.
References MSRoute::begin(), SUMOVehicle::getNumberReroutes(), myCurrentRoute, myExits, MSDevice::myHolder, myReplacedRoutes, mySaveExits, OutputDevice::openTag(), MSRoute::size(), SUMO_TAG_ROUTE, time2string(), and MSRoute::writeEdgeIDs().
Referenced by generateOutput().
Field Documentation
const MSRoute* MSDevice_Vehroutes::myCurrentRoute private
The currently used route.
Definition at line 243 of file MSDevice_Vehroutes.h.
Referenced by addRoute(), generateOutput(), MSDevice_Vehroutes(), writeXMLRoute(), and ~MSDevice_Vehroutes().
std::map< const SUMOTime, int > MSDevice_Vehroutes::myDepartureCounts static private
Map needed to sort vehicles by departure time.
Definition at line 203 of file MSDevice_Vehroutes.h.
Referenced by generateOutput(), and notifyEnter().
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 229 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
bool MSDevice_Vehroutes::myDUAStyle = false static private
A shortcut for the Option "vehroute-output.dua".
Definition at line 167 of file MSDevice_Vehroutes.h.
Referenced by generateOutput(), and init().
std::vector<SUMOTime> MSDevice_Vehroutes::myExits private
The times the vehicle exites an edge.
Definition at line 249 of file MSDevice_Vehroutes.h.
Referenced by notifyLeave(), and writeXMLRoute().
SUMOVehicle& MSDevice::myHolder protected inherited
The vehicle that stores the device.
Definition at line 153 of file MSDevice.h.
Referenced by addRoute(), MSDevice_Tripinfo::generateOutput(), generateOutput(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice::getHolder(), notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Routing::preInsertionReroute(), MSDevice_Routing::reroute(), writeXMLRoute(), and ~MSDevice_Vehroutes().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
bool MSDevice_Vehroutes::myIntendedDepart = false static private
A shortcut for the Option "vehroute-output.intended-depart".
Definition at line 173 of file MSDevice_Vehroutes.h.
Referenced by generateOutput(), init(), and notifyEnter().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 227 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), and MSMoveReminder::MSMoveReminder().
bool MSDevice_Vehroutes::myLastRouteOnly = false static private
A shortcut for the Option "vehroute-output.last-route".
Definition at line 164 of file MSDevice_Vehroutes.h.
Referenced by buildVehicleDevices(), and init().
const MSEdge* MSDevice_Vehroutes::myLastSavedAt private
The last edge the exit time was saved for.
Definition at line 255 of file MSDevice_Vehroutes.h.
Referenced by notifyLeave().
const unsigned int MSDevice_Vehroutes::myMaxRoutes private
The maximum number of routes to report.
Definition at line 252 of file MSDevice_Vehroutes.h.
Referenced by addRoute().
std::vector<RouteReplaceInfo> MSDevice_Vehroutes::myReplacedRoutes private
Prior routes.
Definition at line 246 of file MSDevice_Vehroutes.h.
Referenced by addRoute(), generateOutput(), getRoute(), writeXMLRoute(), and ~MSDevice_Vehroutes().
std::map< const SUMOTime, std::map< const std::string, std::string > > MSDevice_Vehroutes::myRouteInfos static private
Todo:
: describe
Definition at line 206 of file MSDevice_Vehroutes.h.
Referenced by generateOutput().
bool MSDevice_Vehroutes::mySaveExits = false static private
A shortcut for the Option "vehroute-output.exit-times".
Definition at line 161 of file MSDevice_Vehroutes.h.
Referenced by init(), notifyEnter(), notifyLeave(), and writeXMLRoute().
bool MSDevice_Vehroutes::mySorted = false static private
A shortcut for the Option "vehroute-output.sorted".
Definition at line 170 of file MSDevice_Vehroutes.h.
Referenced by generateOutput(), init(), and notifyEnter().
MSDevice_Vehroutes::StateListener MSDevice_Vehroutes::myStateListener static private
A class that is notified about reroutings.
Definition at line 200 of file MSDevice_Vehroutes.h.
Referenced by buildVehicleDevices(), generateOutputForUnfinished(), init(), notifyEnter(), and ~MSDevice_Vehroutes().
bool MSDevice_Vehroutes::myWithTaz = false static private
A shortcut for the Option "device.routing.with-taz".
Definition at line 176 of file MSDevice_Vehroutes.h.
Referenced by generateOutput(), and init().
The documentation for this class was generated from the following files:
MSDevice_Vehroutes.h
MSDevice_Vehroutes.cpp