SUMO - Simulation of Urban MObility: BulkStarRouter< E, V, PF > Class Template Reference
BulkStarRouter< E, V, PF > Class Template Reference
#include <BulkStarRouter.h>
Data Structures
struct EdgeInfo
class EdgeInfoComparator
Public Types
typedef SUMOReal(E::* MinTTOperation)(const V *const) const
typedef SUMOReal(* Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
BulkStarRouter (size_t noE, bool unbuildIsWarning, Operation operation, MinTTOperation minTTOperation)
Constructor.
virtual SUMOAbstractRouter< E,
V > * clone () const
void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum travel time.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
SUMOReal getMinEffort (const E *const e, const V *const v) const
void init ()
void prepare (const E *destination, const V *fastestVehicle, bool skip)
Builds a complete shorteset path tree in the (static) reverse graph from destination (Dijkstra until all EdgeInfos are visited)
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void startQuery ()
virtual ~BulkStarRouter ()
Destructor.
Protected Attributes
Operation myOperation
The object's operation to perform.
Private Types
enum Prepared { NO, YES, YES_EXACT }
Private Attributes
EdgeInfoComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontier
A container for reusage of the min edge heap.
MinTTOperation myMinTTOperation
const E * myPreparedDestination
Detailed Description
template<class E, class V, class PF>
class BulkStarRouter< E, V, PF >
Definition at line 74 of file BulkStarRouter.h.
Member Typedef Documentation
template<class E , class V , class PF > typedef SUMOReal(E::* BulkStarRouter< E, V, PF >::MinTTOperation)(const V *const) const
Definition at line 79 of file BulkStarRouter.h.
template<class E , class V , class PF > typedef SUMOReal(* BulkStarRouter< E, V, PF >::Operation)(const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 78 of file BulkStarRouter.h.
Member Enumeration Documentation
template<class E , class V , class PF > enum BulkStarRouter::Prepared private
Enumerator
NO
YES
YES_EXACT
Definition at line 355 of file BulkStarRouter.h.
Constructor & Destructor Documentation
template<class E , class V , class PF > BulkStarRouter< E, V, PF >::BulkStarRouter (size_t noE, bool unbuildIsWarning, Operation operation, MinTTOperation minTTOperation) inline
Constructor.
Definition at line 83 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::myEdgeInfos.
template<class E , class V , class PF > virtual BulkStarRouter< E, V, PF >::~BulkStarRouter () inline virtual
Destructor.
Definition at line 94 of file BulkStarRouter.h.
Member Function Documentation
template<class E , class V , class PF > void BulkStarRouter< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 345 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::EdgeInfo::edge, and BulkStarRouter< E, V, PF >::EdgeInfo::prev.
Referenced by BulkStarRouter< E, V, PF >::compute().
template<class E , class V , class PF > virtual SUMOAbstractRouter<E, V>* BulkStarRouter< E, V, PF >::clone () const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 96 of file BulkStarRouter.h.
References MsgHandler::getWarningInstance(), BulkStarRouter< E, V, PF >::myEdgeInfos, BulkStarRouter< E, V, PF >::myErrorMsgHandler, BulkStarRouter< E, V, PF >::myMinTTOperation, and SUMOAbstractRouter< E, V >::myOperation.
template<class E , class V , class PF > void BulkStarRouter< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum travel time.
Implements SUMOAbstractRouter< E, V >.
Definition at line 249 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::buildPathFrom(), BulkStarRouter< E, V, PF >::EdgeInfo::edge, SUMOAbstractRouter< E, V >::endQuery(), SUMOAbstractRouter< E, V >::getEffort(), BulkStarRouter< E, V, PF >::EdgeInfo::heuristicTime, MsgHandler::inform(), BulkStarRouter< E, V, PF >::init(), max, MAX2(), BulkStarRouter< E, V, PF >::EdgeInfo::minRemaining, BulkStarRouter< E, V, PF >::myComparator, BulkStarRouter< E, V, PF >::myEdgeInfos, BulkStarRouter< E, V, PF >::myErrorMsgHandler, BulkStarRouter< E, V, PF >::myFound, BulkStarRouter< E, V, PF >::myFrontier, BulkStarRouter< E, V, PF >::myPreparedDestination, BulkStarRouter< E, V, PF >::NO, BulkStarRouter< E, V, PF >::EdgeInfo::prev, SUMOAbstractRouter< E, V >::startQuery(), STEPS2TIME, SUMOReal, SVC_IGNORING, BulkStarRouter< E, V, PF >::EdgeInfo::traveltime, BulkStarRouter< E, V, PF >::EdgeInfo::visited, BulkStarRouter< E, V, PF >::YES, and BulkStarRouter< E, V, PF >::YES_EXACT.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), BulkStarRouter< E, V, PF >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E , class V , class PF > SUMOReal BulkStarRouter< E, V, PF >::getMinEffort (const E *const e, const V *const v) const inline
Definition at line 156 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::myMinTTOperation.
Referenced by BulkStarRouter< E, V, PF >::prepare().
template<class E , class V , class PF > void BulkStarRouter< E, V, PF >::init () inline
Definition at line 235 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::myFound, and BulkStarRouter< E, V, PF >::myFrontier.
Referenced by BulkStarRouter< E, V, PF >::compute().
template<class E , class V , class PF > void BulkStarRouter< E, V, PF >::prepare (const E * destination, const V * fastestVehicle, bool skip) inline virtual
Builds a complete shorteset path tree in the (static) reverse graph from destination (Dijkstra until all EdgeInfos are visited)
Parameters
[in] destination The common destination for the following routes
[in] fastestVehicle An optimistic vehicle (fastest, least restriction) for the following routes
[in] skip Whether to shortcut the preparation (query uses euclidean heuristic)
Reimplemented from SUMOAbstractRouter< E, V >.
Definition at line 167 of file BulkStarRouter.h.
References BulkStarRouter< E, V, PF >::EdgeInfo::edge, BulkStarRouter< E, V, PF >::getMinEffort(), BulkStarRouter< E, V, PF >::EdgeInfo::heuristicTime, max, BulkStarRouter< E, V, PF >::EdgeInfo::minRemaining, BulkStarRouter< E, V, PF >::myComparator, BulkStarRouter< E, V, PF >::myEdgeInfos, BulkStarRouter< E, V, PF >::myFound, BulkStarRouter< E, V, PF >::myFrontier, BulkStarRouter< E, V, PF >::myPreparedDestination, BulkStarRouter< E, V, PF >::EdgeInfo::prev, SUMOReal, BulkStarRouter< E, V, PF >::EdgeInfo::traveltime, and BulkStarRouter< E, V, PF >::EdgeInfo::visited.
template<class E , class V , class PF > SUMOReal BulkStarRouter< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 331 of file BulkStarRouter.h.
References SUMOAbstractRouter< E, V >::getEffort(), STEPS2TIME, and SUMOReal.
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E , class V , class PF > EdgeInfoComparator BulkStarRouter< E, V, PF >::myComparator private
Definition at line 369 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::compute(), and BulkStarRouter< E, V, PF >::prepare().
template<class E , class V , class PF > std::vector<EdgeInfo> BulkStarRouter< E, V, PF >::myEdgeInfos private
The container of edge information.
Definition at line 362 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::BulkStarRouter(), BulkStarRouter< E, V, PF >::clone(), BulkStarRouter< E, V, PF >::compute(), and BulkStarRouter< E, V, PF >::prepare().
template<class E , class V , class PF > MsgHandler* const BulkStarRouter< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 372 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::clone(), and BulkStarRouter< E, V, PF >::compute().
template<class E , class V , class PF > std::vector<EdgeInfo*> BulkStarRouter< E, V, PF >::myFound private
list of visited Edges (for resetting)
Definition at line 367 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::compute(), BulkStarRouter< E, V, PF >::init(), and BulkStarRouter< E, V, PF >::prepare().
template<class E , class V , class PF > std::vector<EdgeInfo*> BulkStarRouter< E, V, PF >::myFrontier private
A container for reusage of the min edge heap.
Definition at line 365 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::compute(), BulkStarRouter< E, V, PF >::init(), and BulkStarRouter< E, V, PF >::prepare().
template<class E , class V , class PF > MinTTOperation BulkStarRouter< E, V, PF >::myMinTTOperation private
Definition at line 374 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::clone(), and BulkStarRouter< E, V, PF >::getMinEffort().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), CHRouterWrapper< E, V, PF >::clone(), BulkStarRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::getEffort().
template<class E , class V , class PF > const E* BulkStarRouter< E, V, PF >::myPreparedDestination private
Definition at line 376 of file BulkStarRouter.h.
Referenced by BulkStarRouter< E, V, PF >::compute(), and BulkStarRouter< E, V, PF >::prepare().
The documentation for this class was generated from the following file:
BulkStarRouter.h