SUMO - Simulation of Urban MObility: GUIContainerControl Class Reference
GUIContainerControl Class Reference
GUI-version of the container control for building gui containers.
#include <GUIContainerControl.h>
Public Types
typedef std::vector
< MSContainer * > ContainerVector
Public Member Functions
void abortWaiting ()
aborts the plan for any container that is still waiting for a ride
bool add (const std::string &id, MSContainer *container)
adds a single container, returns false if an id clash occured
void addWaiting (const MSEdge *edge, MSContainer *container)
adds a container to the list of containers waiting for a vehicle on the specified edge
virtual MSContainer * buildContainer (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSContainer::MSContainerPlan *plan) const
Builds a new container.
void checkWaitingContainers (MSNet *net, const SUMOTime time)
checks whether any containers waiting time is over
virtual void erase (MSContainer *container)
removes a single container
GUIContainerControl ()
constructor
bool hasContainers () const
checks whether any container waits to finish her plan
bool hasNonWaiting () const
checks whether any container is still engaged in walking / stopping
bool loadAnyWaiting (MSEdge *edge, MSVehicle *vehicle, MSVehicle::Stop *stop)
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
void setDeparture (SUMOTime time, MSContainer *container)
sets the arrival time for a waiting container
void setTranship (MSContainer *c)
adds a container to myTranship
void setWaitEnd (SUMOTime time, MSContainer *container)
sets the arrival time for a waiting container
void unsetTranship (MSContainer *c)
removes a container from myTranship
virtual ~GUIContainerControl ()
destructor
Detailed Description
GUI-version of the container control for building gui containers.
Definition at line 44 of file GUIContainerControl.h.
Member Typedef Documentation
typedef std::vector<MSContainer*> MSContainerControl::ContainerVector inherited
Definition at line 60 of file MSContainerControl.h.
Constructor & Destructor Documentation
GUIContainerControl::GUIContainerControl ()
constructor
Definition at line 46 of file GUIContainerControl.cpp.
GUIContainerControl::~GUIContainerControl () virtual
destructor
Definition at line 49 of file GUIContainerControl.cpp.
Member Function Documentation
void MSContainerControl::abortWaiting () inherited
aborts the plan for any container that is still waiting for a ride
Definition at line 220 of file MSContainerControl.cpp.
References MSContainerControl::erase(), MSContainer::getID(), MSContainerControl::myWaiting4Vehicle, MSEdge::removeContainer(), and WRITE_WARNING.
Referenced by MSNet::simulationState().
bool MSContainerControl::add (const std::string & id, MSContainer * container) inherited
adds a single container, returns false if an id clash occured
Definition at line 63 of file MSContainerControl.cpp.
References MSContainerControl::myContainers.
void MSContainerControl::addWaiting (const MSEdge * edge, MSContainer * container) inherited
adds a container to the list of containers waiting for a vehicle on the specified edge
Definition at line 142 of file MSContainerControl.cpp.
References MSContainerControl::myWaiting4Vehicle.
Referenced by MSContainer::MSContainerStage_Driving::proceed().
MSContainer * GUIContainerControl::buildContainer (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSContainer::MSContainerPlan * plan) const virtual
Builds a new container.
Parameters
[in] pars The parameter
[in] vtype The type (reusing vehicle type container here)
[in] plan This container's plan
Reimplemented from MSContainerControl.
Definition at line 54 of file GUIContainerControl.cpp.
void MSContainerControl::checkWaitingContainers (MSNet * net, const SUMOTime time) inherited
checks whether any containers waiting time is over
Definition at line 117 of file MSContainerControl.cpp.
References MSContainerControl::erase(), MSContainerControl::myWaiting4Departure, and MSContainerControl::myWaitingUntil.
Referenced by MSNet::simulationStep().
void MSContainerControl::erase (MSContainer * container) virtual inherited
removes a single container
Definition at line 73 of file MSContainerControl.cpp.
References OutputDevice::closeTag(), MSContainer::getDesiredDepart(), OutputDevice::getDeviceByOption(), MSContainer::getID(), MSNet::getInstance(), OptionsCont::getOptions(), MSContainerControl::myContainers, OutputDevice::openTag(), MSContainer::routeOutput(), time2string(), MSContainer::tripInfoOutput(), and OutputDevice::writeAttr().
Referenced by MSContainerControl::abortWaiting(), MSContainerControl::checkWaitingContainers(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Container::notifyLeave(), and MSDevice_Container::notifyMove().
bool MSContainerControl::hasContainers () const inherited
checks whether any container waits to finish her plan
Definition at line 193 of file MSContainerControl.cpp.
References MSContainerControl::myContainers.
bool MSContainerControl::hasNonWaiting () const inherited
checks whether any container is still engaged in walking / stopping
Definition at line 199 of file MSContainerControl.cpp.
References MSContainerControl::myTranship, MSContainerControl::myWaiting4Departure, and MSContainerControl::myWaitingUntil.
Referenced by MSNet::simulationState().
bool MSContainerControl::loadAnyWaiting (MSEdge * edge, MSVehicle * vehicle, MSVehicle::Stop * stop) inherited
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
Parameters
[in] the edge on which the loading should take place
[in] the vehicle which is taking on containers
Returns
Whether any containers have been loaded
Definition at line 157 of file MSContainerControl.cpp.
References MSVehicle::addContainer(), MSVehicle::Stop::duration, MSVehicle::Stop::endPos, MSVehicleType::getContainerCapacity(), MSVehicle::getContainerNumber(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicleType::getLoadingDuration(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, MSContainerControl::myWaiting4Vehicle, MSEdge::removeContainer(), MSVehicle::Stop::startPos, and MSVehicle::Stop::timeToLoadNextContainer.
Referenced by MSVehicle::processNextStop().
void MSContainerControl::setDeparture (SUMOTime time, MSContainer * container) inherited
sets the arrival time for a waiting container
Definition at line 97 of file MSContainerControl.cpp.
References DELTA_T, and MSContainerControl::myWaiting4Departure.
Referenced by MSRouteHandler::closeContainer().
void MSContainerControl::setTranship (MSContainer * c) inherited
adds a container to myTranship
Definition at line 205 of file MSContainerControl.cpp.
References MSContainer::getID(), and MSContainerControl::myTranship.
Referenced by MSContainer::MSContainerStage_Tranship::proceed().
void MSContainerControl::setWaitEnd (SUMOTime time, MSContainer * container) inherited
sets the arrival time for a waiting container
Definition at line 107 of file MSContainerControl.cpp.
References DELTA_T, and MSContainerControl::myWaitingUntil.
Referenced by MSContainer::MSContainerStage_Waiting::proceed().
void MSContainerControl::unsetTranship (MSContainer * c) inherited
removes a container from myTranship
Definition at line 211 of file MSContainerControl.cpp.
References MSContainer::getID(), and MSContainerControl::myTranship.
Referenced by MSContainer::MSContainerStage_Tranship::moveToNextEdge().
The documentation for this class was generated from the following files:
GUIContainerControl.h
GUIContainerControl.cpp