SUMO - Simulation of Urban MObility: MSPerson Class Reference
MSPerson Class Reference
#include <MSPerson.h>
Data Structures
class MSPersonStage
class MSPersonStage_Driving
class MSPersonStage_Waiting
class MSPersonStage_Walking
Public Types
typedef std::vector
< MSPersonStage * > MSPersonPlan
the structure holding the plan of a person
enum StageType { WALKING = 0, DRIVING = 1, WAITING = 2 }
Public Member Functions
virtual SUMOReal getAngle () const
return the current angle of the person
MSPersonStage * getCurrentStage () const
std::string getCurrentStageDescription () const
StageType getCurrentStageType () const
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
virtual SUMOReal getEdgePos () const
return the offset from the start of the current edge
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the person id
const SUMOVehicleParameter & getParameter () const
virtual Position getPosition () const
return the Network coordinate of the person
virtual SUMOReal getSpeed () const
the current speed of the person
const MSVehicleType & getVehicleType () const
virtual SUMOReal getWaitingSeconds () const
the time this person spent waiting in seconds
bool isWaiting4Vehicle () const
Whether the person waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the person waits for a vehicle of the line specified.
MSPerson (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSPersonPlan *plan)
constructor
bool proceed (MSNet *net, SUMOTime time)
void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs end of the step
void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
virtual ~MSPerson ()
destructor
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the person
MSPersonPlan * myPlan
the plan of the person
MSPersonPlan::iterator myStep
the iterator over the route
const MSVehicleType * myVType
This Persons's type. (mainly used for drawing related information.
bool myWriteEvents
Whether events shall be written.
Private Member Functions
MSPerson (const MSPerson &)
Invalidated copy constructor.
MSPerson & operator= (const MSPerson &)
Invalidated assignment operator.
Detailed Description
The class holds a simulated person together with her movement stages
Definition at line 69 of file MSPerson.h.
Member Typedef Documentation
typedef std::vector<MSPersonStage*> MSPerson::MSPersonPlan
the structure holding the plan of a person
Definition at line 514 of file MSPerson.h.
Member Enumeration Documentation
enum MSPerson::StageType
Enumerator
WALKING
DRIVING
WAITING
Definition at line 71 of file MSPerson.h.
Constructor & Destructor Documentation
MSPerson::MSPerson (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSPersonPlan * plan)
constructor
Definition at line 536 of file MSPerson.cpp.
References myPlan, and myStep.
MSPerson::~MSPerson () virtual
destructor
Definition at line 542 of file MSPerson.cpp.
References myParameter, and myPlan.
MSPerson::MSPerson (const MSPerson &) private
Invalidated copy constructor.
Member Function Documentation
SUMOReal MSPerson::getAngle () const virtual
return the current angle of the person
Reimplemented in GUIPerson.
Definition at line 627 of file MSPerson.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIPerson::getAngle(), TraCIServerAPI_Person::processGet(), and MSFCDExport::write().
MSPersonStage* MSPerson::getCurrentStage () const inline
Definition at line 576 of file MSPerson.h.
References myStep.
Referenced by GUIPerson::drawAction_drawWalkingareaPath(), and MSEdge::person_by_offset_sorter::operator()().
std::string MSPerson::getCurrentStageDescription () const inline
Definition at line 572 of file MSPerson.h.
Referenced by GUIPerson::getParameterWindow().
StageType MSPerson::getCurrentStageType () const inline
Definition at line 567 of file MSPerson.h.
Referenced by MSPModel_Striping::add(), GUIPerson::getColorValue(), and GUIPerson::getPosition().
SUMOTime MSPerson::getDesiredDepart () const
Returns the desired departure time.
Definition at line 585 of file MSPerson.cpp.
References SUMOVehicleParameter::depart, and myParameter.
Referenced by MSPersonControl::erase(), and routeOutput().
const MSEdge& MSPerson::getDestination () const inline
Returns the current destination.
Definition at line 537 of file MSPerson.h.
Referenced by GUIPerson::getParameterWindow(), MSDevice_Person::notifyLeave(), MSDevice_Person::notifyMove(), MSPerson::MSPersonStage_Driving::routeOutput(), and MSPerson::MSPersonStage_Waiting::routeOutput().
const MSEdge* MSPerson::getEdge () const inline
Returns the current edge.
Definition at line 542 of file MSPerson.h.
Referenced by MSPModel_Striping::add(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::getEdgePos(), GUIPerson::getParameterWindow(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and TraCIServerAPI_Person::processGet().
SUMOReal MSPerson::getEdgePos () const virtual
return the offset from the start of the current edge
Reimplemented in GUIPerson.
Definition at line 616 of file MSPerson.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIPerson::getEdgePos(), TraCIServerAPI_Person::processGet(), and MSFCDExport::write().
const MSEdge* MSPerson::getFromEdge () const inline
Returns the departure edge.
Definition at line 547 of file MSPerson.h.
Referenced by GUIPerson::getParameterWindow(), and MSPerson::MSPersonStage_Driving::routeOutput().
const std::string & MSPerson::getID () const
returns the person id
Definition at line 552 of file MSPerson.cpp.
References SUMOVehicleParameter::id, and myParameter.
Referenced by MSPersonControl::abortWaiting(), MSVehicle::addPerson(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSPersonControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), GUIPerson::getParameterWindow(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSDevice_Person::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::person_by_offset_sorter::operator()(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), MSPerson::MSPersonStage_Driving::routeOutput(), MSPerson::MSPersonStage_Waiting::routeOutput(), MSPersonControl::setWalking(), MSPersonControl::unsetWalking(), and MSFCDExport::write().
const SUMOVehicleParameter& MSPerson::getParameter () const inline
Definition at line 605 of file MSPerson.h.
References myParameter.
Referenced by TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), and GUIPerson::setFunctionalColor().
Position MSPerson::getPosition () const virtual
return the Network coordinate of the person
Reimplemented in GUIPerson.
Definition at line 621 of file MSPerson.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by TraCIServerAPI_Person::getPosition(), GUIPerson::getPosition(), TraCIServerAPI_Person::processGet(), and MSFCDExport::write().
SUMOReal MSPerson::getSpeed () const virtual
the current speed of the person
Reimplemented in GUIPerson.
Definition at line 637 of file MSPerson.cpp.
Referenced by GUIPerson::getSpeed(), TraCIServerAPI_Person::processGet(), and MSFCDExport::write().
const MSVehicleType& MSPerson::getVehicleType () const inline
Definition at line 610 of file MSPerson.h.
References myVType.
Referenced by GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), TraCIServerAPI_Person::processGet(), and GUIPerson::setFunctionalColor().
SUMOReal MSPerson::getWaitingSeconds () const virtual
the time this person spent waiting in seconds
Reimplemented in GUIPerson.
Definition at line 632 of file MSPerson.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and STEPS2TIME.
Referenced by GUIPerson::getWaitingSeconds(), and TraCIServerAPI_Person::processGet().
bool MSPerson::isWaiting4Vehicle () const inline
Whether the person waits for a vehicle.
Definition at line 600 of file MSPerson.h.
Referenced by GUIPerson::getColorValue(), GUIPerson::getPosition(), MSPerson::MSPersonStage_Driving::getStageDescription(), and MSPerson::MSPersonStage_Driving::getWaitingTime().
bool MSPerson::isWaitingFor (const std::string & line) const inline
Whether the person waits for a vehicle of the line specified.
Definition at line 595 of file MSPerson.h.
MSPerson& MSPerson::operator= (const MSPerson &) private
Invalidated assignment operator.
bool MSPerson::proceed (MSNet * net, SUMOTime time)
Definition at line 558 of file MSPerson.cpp.
References myPlan, myStep, MSEdge::removePerson(), and SUMOReal.
Referenced by MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSDevice_Person::notifyLeave(), MSDevice_Person::notifyMove(), and MSPerson::MSPersonStage_Walking::proceed().
void MSPerson::routeOutput (OutputDevice & os) const
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Definition at line 605 of file MSPerson.cpp.
References getDesiredDepart(), MSPerson::MSPersonStage_Waiting::getUntil(), myPlan, and WAITING.
Referenced by MSPersonControl::erase().
void MSPerson::setDeparted (SUMOTime now)
logs end of the step
Definition at line 591 of file MSPerson.cpp.
void MSPerson::tripInfoOutput (OutputDevice & os) const
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Definition at line 597 of file MSPerson.cpp.
References myPlan.
Referenced by MSPersonControl::erase().
Field Documentation
const SUMOVehicleParameter* MSPerson::myParameter protected
the plan of the person
Definition at line 617 of file MSPerson.h.
Referenced by getDesiredDepart(), getID(), getParameter(), and ~MSPerson().
MSPersonPlan* MSPerson::myPlan protected
the plan of the person
Definition at line 623 of file MSPerson.h.
Referenced by MSPerson(), proceed(), routeOutput(), tripInfoOutput(), and ~MSPerson().
MSPersonPlan::iterator MSPerson::myStep protected
the iterator over the route
Definition at line 626 of file MSPerson.h.
Referenced by getCurrentStage(), MSPerson(), and proceed().
const MSVehicleType* MSPerson::myVType protected
This Persons's type. (mainly used for drawing related information.
Definition at line 620 of file MSPerson.h.
Referenced by getVehicleType().
bool MSPerson::myWriteEvents protected
Whether events shall be written.
Definition at line 629 of file MSPerson.h.
The documentation for this class was generated from the following files:
MSPerson.h
MSPerson.cpp