SUMO - Simulation of Urban MObility: TraCIAPI::PolygonScope Class Reference
TraCIAPI::PolygonScope Class Reference
Scope for interaction with polygons.
#include <TraCIAPI.h>
Public Member Functions
void add (const std::string &polygonID, const TraCIPositionVector &shape, const TraCIColor &c, bool fill, const std::string &type, int layer) const
TraCIColor getColor (const std::string &polygonID) const
std::vector< std::string > getIDList () const
TraCIPositionVector getShape (const std::string &polygonID) const
std::string getType (const std::string &polygonID) const
PolygonScope (TraCIAPI &parent)
void remove (const std::string &polygonID, int layer=0) const
void setColor (const std::string &polygonID, const TraCIColor &c) const
void setShape (const std::string &polygonID, const TraCIPositionVector &shape) const
void setType (const std::string &polygonID, const std::string &setType) const
virtual ~PolygonScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
PolygonScope & operator= (const PolygonScope &src)
invalidated assignment operator
PolygonScope (const PolygonScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with polygons.
Definition at line 470 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::PolygonScope::PolygonScope (TraCIAPI & parent) inline
Definition at line 472 of file TraCIAPI.h.
virtual TraCIAPI::PolygonScope::~PolygonScope () inline virtual
Definition at line 473 of file TraCIAPI.h.
TraCIAPI::PolygonScope::PolygonScope (const PolygonScope & src) private
invalidated copy constructor
Member Function Documentation
void TraCIAPI::PolygonScope::add (const std::string & polygonID, const TraCIPositionVector & shape, const TraCIColor & c, bool fill, const std::string & type, int layer) const
Definition at line 1044 of file TraCIAPI.cpp.
References TraCIAPI::TraCIColor::a, ADD, TraCIAPI::TraCIColor::b, CMD_SET_POLYGON_VARIABLE, TraCIAPI::TraCIColor::g, TraCIAPI::TraCIColor::r, TYPE_COLOR, TYPE_COMPOUND, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_UBYTE, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
TraCIAPI::TraCIColor TraCIAPI::PolygonScope::getColor (const std::string & polygonID) const
Definition at line 1007 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_COLOR.
std::vector< std::string > TraCIAPI::PolygonScope::getIDList () const
Definition at line 992 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and ID_LIST.
TraCIAPI::TraCIPositionVector TraCIAPI::PolygonScope::getShape (const std::string & polygonID) const
Definition at line 1002 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_SHAPE.
std::string TraCIAPI::PolygonScope::getType (const std::string & polygonID) const
Definition at line 997 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_TYPE.
PolygonScope& TraCIAPI::PolygonScope::operator= (const PolygonScope & src) private
invalidated assignment operator
void TraCIAPI::PolygonScope::remove (const std::string & polygonID, int layer = 0) const
Definition at line 1070 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, REMOVE, TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::PolygonScope::setColor (const std::string & polygonID, const TraCIColor & c) const
Definition at line 1033 of file TraCIAPI.cpp.
References TraCIAPI::TraCIColor::a, TraCIAPI::TraCIColor::b, CMD_SET_POLYGON_VARIABLE, TraCIAPI::TraCIColor::g, TraCIAPI::TraCIColor::r, TYPE_COLOR, VAR_COLOR, and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::PolygonScope::setShape (const std::string & polygonID, const TraCIPositionVector & shape) const
Definition at line 1021 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, TYPE_POLYGON, VAR_POSITION, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::PolygonScope::setType (const std::string & polygonID, const std::string & setType) const
Definition at line 1013 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, TYPE_STRING, VAR_TYPE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 190 of file TraCIAPI.h.
Referenced by TraCIAPI::EdgeScope::getIDList().
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp