SUMO - Simulation of Urban MObility: Shape Class Reference
Shape Class Reference
A 2D- or 3D-Shape.
#include <Shape.h>
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string & getID () const
Returns the id.
void setID (const std::string &newID)
resets the id
Shape (const std::string &id, const std::string &type, const RGBColor &color, SUMOReal layer, SUMOReal angle, const std::string &imgFile)
Constructor.
virtual ~Shape ()
Destructor.
Getter
const std::string & getType () const
Returns the (abstract) type of the Shape.
const RGBColor & getColor () const
Returns the color of the Shape.
SUMOReal getLayer () const
Returns the layer of the Shape.
SUMOReal getAngle () const
Returns the angle of the Shape.
const std::string & getImgFile () const
Returns the imgFile of the Shape.
Setter
void setType (const std::string &type)
Sets a new type.
void setColor (const RGBColor &col)
Sets a new color.
void setLayer (const SUMOReal layer)
Sets a new layer.
void setAngle (const SUMOReal angle)
Sets a new angle.
void setImgFile (const std::string &imgFile)
Sets a new imgFile.
Static Public Attributes
static const SUMOReal DEFAULT_ANGLE = 0
static const std::string DEFAULT_IMG_FILE = ""
static const SUMOReal DEFAULT_IMG_HEIGHT = 1
static const SUMOReal DEFAULT_IMG_WIDTH = 1
static const SUMOReal DEFAULT_LAYER = 128
static const std::string DEFAULT_TYPE = ""
Protected Attributes
SUMOReal myAngle
The angle of the Shape.
RGBColor myColor
The color of the Shape.
std::string myID
The name of the object.
std::string myImgFile
The angle of the Shape.
SUMOReal myLayer
The layer of the Shape.
std::string myType
The type of the Shape.
Detailed Description
A 2D- or 3D-Shape.
Definition at line 46 of file Shape.h.
Constructor & Destructor Documentation
Shape::Shape (const std::string & id, const std::string & type, const RGBColor & color, SUMOReal layer, SUMOReal angle, const std::string & imgFile)
Constructor.
Parameters
[in] id The name of the shape
[in] type The (abstract) type of the shape
[in] color The color of the shape
[in] layer The layer of the shape
[in] angle The rotation of the shape
[in] imgFile The raster image of the shape
Definition at line 51 of file Shape.cpp.
Shape::~Shape () virtual
Destructor.
Definition at line 63 of file Shape.cpp.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
SUMOReal Shape::getAngle () const inline
Returns the angle of the Shape.
Returns
The Shape's rotation angle
Definition at line 94 of file Shape.h.
References myAngle.
Referenced by GUIPointOfInterest::drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const RGBColor& Shape::getColor () const inline
Returns the color of the Shape.
Returns
The Shape's color
Definition at line 79 of file Shape.h.
References myColor.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const std::string& Shape::getImgFile () const inline
Returns the imgFile of the Shape.
Returns
The Shape's rotation imgFile
Definition at line 101 of file Shape.h.
References myImgFile.
Referenced by GUIPolygon::drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
SUMOReal Shape::getLayer () const inline
Returns the layer of the Shape.
Returns
The Shape's layer
Definition at line 87 of file Shape.h.
References myLayer.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const std::string& Shape::getType () const inline
Returns the (abstract) type of the Shape.
Returns
The Shape's (abstract) type
Definition at line 71 of file Shape.h.
References myType.
Referenced by TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
void Shape::setAngle (const SUMOReal angle) inline
Sets a new angle.
Parameters
[in] layer The new angle to use
Definition at line 137 of file Shape.h.
References myAngle.
void Shape::setColor (const RGBColor & col) inline
Sets a new color.
Parameters
[in] col The new color to use
Definition at line 121 of file Shape.h.
References myColor.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void Shape::setImgFile (const std::string & imgFile) inline
Sets a new imgFile.
Parameters
[in] imgFile The new imgFile to use
Definition at line 144 of file Shape.h.
References myImgFile.
void Shape::setLayer (const SUMOReal layer) inline
Sets a new layer.
Parameters
[in] layer The new layer to use
Definition at line 129 of file Shape.h.
References myLayer.
void Shape::setType (const std::string & type) inline
Sets a new type.
Parameters
[in] type The new type to use
Definition at line 113 of file Shape.h.
References myType.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
Field Documentation
const SUMOReal Shape::DEFAULT_ANGLE = 0 static
Definition at line 151 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const std::string Shape::DEFAULT_IMG_FILE = "" static
Definition at line 152 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const SUMOReal Shape::DEFAULT_IMG_HEIGHT = 1 static
Definition at line 154 of file Shape.h.
Referenced by ShapeHandler::addPOI(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), and PCPolyContainer::save().
const SUMOReal Shape::DEFAULT_IMG_WIDTH = 1 static
Definition at line 153 of file Shape.h.
Referenced by ShapeHandler::addPOI(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), and PCPolyContainer::save().
const SUMOReal Shape::DEFAULT_LAYER = 128 static
Definition at line 150 of file Shape.h.
Referenced by ShapeHandler::addPoly().
const std::string Shape::DEFAULT_TYPE = "" static
Definition at line 149 of file Shape.h.
Referenced by ShapeHandler::addPoly().
SUMOReal Shape::myAngle protected
The angle of the Shape.
Definition at line 167 of file Shape.h.
Referenced by getAngle(), and setAngle().
RGBColor Shape::myColor protected
The color of the Shape.
Definition at line 161 of file Shape.h.
Referenced by getColor(), and setColor().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string Shape::myImgFile protected
The angle of the Shape.
Definition at line 170 of file Shape.h.
Referenced by GUIPointOfInterest::drawGL(), getImgFile(), and setImgFile().
SUMOReal Shape::myLayer protected
The layer of the Shape.
Definition at line 164 of file Shape.h.
Referenced by getLayer(), and setLayer().
std::string Shape::myType protected
The type of the Shape.
Definition at line 158 of file Shape.h.
Referenced by GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getType(), and setType().
The documentation for this class was generated from the following files:
Shape.h
Shape.cpp