SUMO - Simulation of Urban MObility: GUIEdge Class Reference
GUIEdge Class Reference
A road/street connecting two junctions (gui-version)
#include <GUIEdge.h>
Public Types
typedef std::map< const MSEdge
*, std::vector< MSLane * > * > AllowedLanesCont
Suceeding edges (keys) and allowed lanes to reach these edges (values).
typedef std::map
< SUMOVehicleClass,
AllowedLanesCont > ClassedAllowedLanesCont
Map from vehicle types to lanes that may be used to reach one of the next edges.
enum EdgeBasicFunction {
EDGEFUNCTION_UNKNOWN = -1, EDGEFUNCTION_NORMAL = 0, EDGEFUNCTION_CONNECTOR = 1, EDGEFUNCTION_INTERNAL = 2,
EDGEFUNCTION_DISTRICT = 3, EDGEFUNCTION_CROSSING = 4, EDGEFUNCTION_WALKINGAREA = 5
}
Defines possible edge types.
Public Member Functions
void addContainer (MSContainer *c) const
Add a container to myContainers.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addPerson (MSPerson *p) const
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual void changeLanes (SUMOTime t)
Performs lane changing on this edge.
void clearParameter ()
Clears the parameter map.
void closeBuilding ()
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
Boundary getBoundary () const
Returns the street's geometry.
SUMOReal getCurrentTravelTime (const SUMOReal minSpeed=NUMERICAL_EPS) const
Computes and returns the current travel time for this edge.
SUMOReal getDistanceTo (const MSEdge *other) const
optimistic air distance heuristic for use in routing
const std::string & getID () const
Returns the id.
MSLane & getLane (size_t laneNo)
returns the enumerated lane (!!! why not private with a friend?)
SUMOReal getLength () const
return the length of the edge
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
SUMOReal getMinimumTravelTime (const SUMOVehicle *const veh) const
returns the minimum travel time for the given vehicle
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
SVCPermissions getPermissions () const
SUMOReal getSpeedLimit () const
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
SUMOReal getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the maximum speed the vehicle may use on this edge.
GUIEdge (const std::string &id, int numericalID, const EdgeBasicFunction function, const std::string &streetName, const std::string &edgeType, int priority)
Constructor.
void initialize (const std::vector< MSLane * > *lanes)
Initialize the edge.
bool isRoundabout () const
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void markAsRoundabout ()
void markDelayed () const
bool prohibits (const SUMOVehicle *const vehicle) const
Returns whether the vehicle (class) is not allowed on the edge.
void rebuildAllowedLanes ()
void recalcCache ()
Recalculates the cached values.
void removeContainer (MSContainer *c) const
Remove container from myContainers.
void removePerson (MSPerson *p) const
void setID (const std::string &newID)
resets the id
~GUIEdge ()
Destructor.
inherited from GUIGlObject
virtual GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
virtual GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Access to the edge's lanes
MSLane * leftLane (const MSLane *const lane) const
Returns the lane left to the one given, 0 if the given lane is leftmost.
MSLane * rightLane (const MSLane *const lane) const
Returns the lane right to the one given, 0 if the given lane is rightmost.
MSLane * parallelLane (const MSLane *const lane, int offset) const
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
const std::vector< MSLane * > & getLanes () const
Returns this edge's lanes.
std::vector< MSPerson * > getSortedPersons (SUMOTime timestep) const
Returns this edge's persons sorted by pos.
std::vector< MSContainer * > getSortedContainers (SUMOTime timestep) const
Returns this edge's containers sorted by pos.
const std::vector< MSLane * > * allowedLanes (const MSEdge &destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * allowedLanes (SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes for the given vehicle class.
Access to other edge attributes
EdgeBasicFunction getPurpose () const
Returns the edge type (EdgeBasicFunction)
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
int getNumericalID () const
Returns the numerical id of the edge.
const std::string & getStreetName () const
Returns the street name of the edge.
const std::string & getEdgeType () const
Returns the type of the edge.
int getPriority () const
Returns the priority of the edge.
Access to succeeding/predecessing edges
void addSuccessor (MSEdge *edge)
Adds an edge to the list of edges which may be reached from this edge and to the incoming of the other edge.
const MSEdgeVector & getIncomingEdges () const
Returns the list of edges from which this edge may be reached.
unsigned int getNumSuccessors () const
Returns the number of edges that may be reached from this edge.
const MSEdgeVector & getSuccessors () const
Returns the following edges.
const MSEdgeVector & getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
unsigned int getNumPredecessors () const
Returns the number of edges this edge is connected to.
const MSEdgeVector & getPredecessors () const
Returns the edge at the given position from the list of reachable edges.
const MSJunction * getFromJunction () const
const MSJunction * getToJunction () const
void setJunctions (MSJunction *from, MSJunction *to)
Access to vaporizing interface
bool isVaporizing () const
Returns whether vehicles on this edge shall be vaporized.
SUMOTime incVaporization (SUMOTime t)
Enables vaporization.
SUMOTime decVaporization (SUMOTime t)
Disables vaporization.
Methods releated to vehicle insertion
bool insertVehicle (SUMOVehicle &v, SUMOTime time, const bool checkOnly=false) const
Tries to insert the given vehicle into the network.
MSLane * getFreeLane (const std::vector< MSLane * > *allowed, const SUMOVehicleClass vclass) const
Finds the emptiest lane allowing the vehicle class.
MSLane * getDepartLane (MSVehicle &veh) const
Finds a depart lane for the given vehicle parameters.
SUMOTime getLastFailedInsertionTime () const
Returns the last time a vehicle could not be inserted.
void setLastFailedInsertionTime (SUMOTime time) const
Sets the last time a vehicle could not be inserted.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSEdge *edge)
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
static MSEdge * dictionary (const std::string &id)
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
static MSEdge * dictionary (size_t index)
Returns the MSEdge at the index.
static size_t dictSize ()
Returns the number of edges.
static void fill (std::vector< GUIEdge * > &netsWrappers)
static std::vector< GUIGlID > getIDs (bool includeInternal)
static std::pair< SUMOReal,
SUMOReal > getLaneOffsets (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2, SUMOReal prev, SUMOReal wanted)
static SUMOReal getTotalLength (bool includeInternal, bool eachLane)
static SUMOReal getTravelTimeStatic (const MSEdge *const edge, const SUMOVehicle *const veh, SUMOReal time)
Returns the travel time for the given edge.
static void insertIDs (std::vector< std::string > &into)
Inserts IDs of all known edges into the given vector.
static size_t numericalDictSize ()
Returns the number of edges with a numerical id.
Static parser helper
static void parseEdgesList (const std::string &desc, ConstMSEdgeVector &into, const std::string &rid)
Parses the given string assuming it contains a list of edge ids divided by spaces.
static void parseEdgesList (const std::vector< std::string > &desc, ConstMSEdgeVector &into, const std::string &rid)
Parses the given string vector assuming it edge ids.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::map
< SUMOVehicleClass,
MSEdgeVector > ClassesSuccesorMap
The successors available for a given vClass.
Protected Member Functions
const std::vector< MSLane * > * allowedLanes (const MSEdge *destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * getAllowedLanesWithDefault (const AllowedLanesCont &c, const MSEdge *dest) const
lookup in map and return 0 if not found
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
bool myAmDelayed
whether this edge had a vehicle with less than max speed on it
bool myAmRoundabout
whether this edge belongs to a roundabout
ClassesSuccesorMap myClassesSuccessorMap
std::set< MSContainer * > myContainers
Containers on the edge.
std::string myEdgeType
the type of the edge (optionally used during network creation)
SUMOReal myEmptyTraveltime
the traveltime on the empty edge (cached value for speedup)
MSJunction * myFromJunction
the junctions for this edge
const EdgeBasicFunction myFunction
the purpose of the edge
std::string myID
The name of the object.
MSLaneChanger * myLaneChanger
This member will do the lane-change.
const std::vector< MSLane * > * myLanes
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
SUMOTime myLastFailedInsertionTime
The time of last insertion failure.
SUMOReal myLength
the length of the edge (cached value for speedup)
const int myNumericalID
This edge's numerical id.
std::set< MSPerson * > myPersons
Persons on the edge (only for drawing)
MSEdgeVector myPredecessors
The preceeding edges.
const int myPriority
the priority of the edge (used during network creation)
std::string myStreetName
the real-world name of this edge (need not be unique)
MSEdgeVector mySuccessors
The succeeding edges.
MSJunction * myToJunction
int myVaporizationRequests
Vaporizer counter.
Storages for allowed lanes (depending on vehicle classes)
AllowedLanesCont myAllowed
Associative container from destination-edge to allowed-lanes.
ClassedAllowedLanesCont myClassedAllowed
From vehicle class to lanes allowed to be used by it.
SVCPermissions myMinimumPermissions
The intersection of lane permissions for this edge.
SVCPermissions myCombinedPermissions
The union of lane permissions for this edge.
Private Member Functions
GUIEdge (const GUIEdge &s)
invalidated copy constructor
GUIEdge & operator= (const GUIEdge &s)
invalidated assignment operator
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of myPersons/ myContainers.
Static edge container
typedef std::map< std::string,
MSEdge * > DictType
definition of the static dictionary type
static DictType myDict
Static dictionary to associate string-ids with objects.
static MSEdgeVector myEdges
Static list of edges.
Detailed Description
A road/street connecting two junctions (gui-version)
See Also
MSEdge
Definition at line 61 of file GUIEdge.h.
Member Typedef Documentation
typedef std::map< const MSEdge*, std::vector<MSLane*>* > MSEdge::AllowedLanesCont inherited
Suceeding edges (keys) and allowed lanes to reach these edges (values).
Definition at line 109 of file MSEdge.h.
typedef std::map< SUMOVehicleClass, AllowedLanesCont > MSEdge::ClassedAllowedLanesCont inherited
Map from vehicle types to lanes that may be used to reach one of the next edges.
Definition at line 112 of file MSEdge.h.
typedef std::map<SUMOVehicleClass, MSEdgeVector> MSEdge::ClassesSuccesorMap protected inherited
The successors available for a given vClass.
Definition at line 794 of file MSEdge.h.
typedef std::map< std::string, MSEdge* > MSEdge::DictType protected inherited
definition of the static dictionary type
Definition at line 779 of file MSEdge.h.
Member Enumeration Documentation
enum MSEdge::EdgeBasicFunction inherited
Defines possible edge types.
For different purposes, it is necessary to know whether the edge is a normal street or something special.
Enumerator
EDGEFUNCTION_UNKNOWN
The purpose of the edge is not known.
EDGEFUNCTION_NORMAL
The edge is a normal street.
EDGEFUNCTION_CONNECTOR
The edge is a macroscopic connector (source/sink)
EDGEFUNCTION_INTERNAL
The edge is an internal edge.
EDGEFUNCTION_DISTRICT
The edge is a district edge.
EDGEFUNCTION_CROSSING
The edge is a pedestrian crossing (a special type of internal edge)
EDGEFUNCTION_WALKINGAREA
The edge is a pedestrian walking area (a special type of internal edge)
Definition at line 90 of file MSEdge.h.
Constructor & Destructor Documentation
GUIEdge::GUIEdge (const std::string & id, int numericalID, const EdgeBasicFunction function, const std::string & streetName, const std::string & edgeType, int priority)
Constructor.
Parameters
[in] id The id of the edge
[in] numericalID The numerical id (index) of the edge
See Also
MSEdge
Definition at line 77 of file GUIEdge.cpp.
GUIEdge::~GUIEdge ()
Destructor.
Definition at line 84 of file GUIEdge.cpp.
References MFXMutex::locked(), myLock, and MFXMutex::unlock().
GUIEdge::GUIEdge (const GUIEdge & s) private
invalidated copy constructor
Member Function Documentation
void GUIEdge::addContainer (MSContainer * container) const inline virtual
Add a container to myContainers.
Reimplemented from MSEdge.
Definition at line 158 of file GUIEdge.h.
References MSEdge::addContainer(), and myLock.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIEdge::addPerson (MSPerson * p) const inline virtual
Reimplemented from MSEdge.
Definition at line 147 of file GUIEdge.h.
References MSEdge::addPerson(), and myLock.
void MSEdge::addSuccessor (MSEdge * edge) inline inherited
Adds an edge to the list of edges which may be reached from this edge and to the incoming of the other edge.
This is mainly used by the taz (district) parsing
Parameters
[in] edge The edge to add
Definition at line 291 of file MSEdge.h.
References MSEdge::myPredecessors, and MSEdge::mySuccessors.
Referenced by NLHandler::addDistrict().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge & destination, SUMOVehicleClass vclass = SVC_IGNORING) const inherited
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 217 of file MSEdge.cpp.
Referenced by MSEdge::allowedLanes(), MSVehicleTransfer::checkInsertions(), MSEdge::getDepartLane(), MSEdge::getFreeLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSEdge::getSuccessors(), MSLane::by_connections_to_sorter::operator()(), and MSVehicle::updateBestLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (SUMOVehicleClass vclass = SVC_IGNORING) const inherited
Get the allowed lanes for the given vehicle class.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used by the given vclass
Definition at line 223 of file MSEdge.cpp.
References MSEdge::allowedLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge * destination, SUMOVehicleClass vclass = SVC_IGNORING) const protected inherited
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 239 of file MSEdge.cpp.
References MSEdge::getAllowedLanesWithDefault(), MSEdge::myAllowed, MSEdge::myClassedAllowed, and MSEdge::myMinimumPermissions.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void MSEdge::changeLanes (SUMOTime t) virtual inherited
Performs lane changing on this edge.
Definition at line 457 of file MSEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getLogicalPredecessorLane(), MSLink::havePriority(), MSLaneChanger::laneChange(), MSEdge::myFunction, MSEdge::myLaneChanger, and MSEdge::myLanes.
Referenced by MSEdgeControl::changeLanes().
void MSEdge::clear () static inherited
Clears the dictionary.
Definition at line 577 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by MSNet::clearAll(), and MSVehicle::updateBestLanes().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void MSEdge::closeBuilding () inherited
Todo:
Has to be called after all edges were built and all connections were set...; Still, is not very nice
Definition at line 129 of file MSEdge.cpp.
References MSLane::getEdge(), MSEdge::myAllowed, MSEdge::myLanes, MSEdge::myPredecessors, MSEdge::mySuccessors, and MSEdge::rebuildAllowedLanes().
SUMOTime MSEdge::decVaporization (SUMOTime t) inherited
Disables vaporization.
The internal vaporization counter is decreased what disables the vaporization if it was only once enabled. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 285 of file MSEdge.cpp.
References MSEdge::myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer().
bool MSEdge::dictionary (const std::string & id, MSEdge * edge) static inherited
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Definition at line 531 of file MSEdge.cpp.
References MSEdge::getNumericalID(), MSEdge::myDict, and MSEdge::myEdges.
Referenced by NLHandler::addConnection(), NLHandler::addDistrict(), NLHandler::addDistrictEdge(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), NLHandler::addRoundabout(), NLEdgeControlBuilder::beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), NLHandler::closeEdge(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), NLDetectorBuilder::getEdgeChecking(), TraCIServerAPI_Simulation::getLaneChecking(), TraCIServerAPI_Edge::getShape(), MSPModel_Striping::initWalkingAreaPaths(), NLHandler::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), GUIApplicationWindow::onCmdEditChosen(), NLTriggerBuilder::parseAndBuildRerouter(), MSEdge::parseEdgesList(), MSRouteHandler::parseFromViaTo(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), MSStateHandler::saveState(), and TraCIServerAPI_Vehicle::vtdMap().
MSEdge * MSEdge::dictionary (const std::string & id) static inherited
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
Definition at line 547 of file MSEdge.cpp.
References MSEdge::myDict.
MSEdge * MSEdge::dictionary (size_t index) static inherited
Returns the MSEdge at the index.
Definition at line 558 of file MSEdge.cpp.
References MSEdge::myEdges.
size_t MSEdge::dictSize () static inherited
Returns the number of edges.
Definition at line 565 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by fill(), MSPModel_Striping::initWalkingAreaPaths(), GUIApplicationWindow::onCmdEditChosen(), and MSStateHandler::saveState().
void GUIEdge::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See Also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 214 of file GUIEdge.cpp.
References Position::add(), GUIVisualizationTextSettings::color, GUIVisualizationSettings::containerSize, GUIVisualizationSettings::cwaEdgeName, GUIContainer::drawGL(), GUIPerson::drawGL(), GUILane::drawGL(), GUIGlObject::drawName(), GLHelper::drawText(), MSEdge::EDGEFUNCTION_CONNECTOR, MSEdge::EDGEFUNCTION_CROSSING, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_NORMAL, MSEdge::EDGEFUNCTION_WALKINGAREA, GUIVisualizationSettings::edgeName, GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUILane::getShape(), MSEdge::getStreetName(), GLO_MAX, MSGlobals::gUseMesoSim, GUIVisualizationSettings::hideConnectors, GUIVisualizationSettings::internalEdgeName, PositionVector::length(), MFXMutex::lock(), GUIVisualizationSizeSettings::minSize, Position::mul(), MSEdge::myContainers, MSEdge::myFunction, MSEdge::myLanes, myLock, MSEdge::myPersons, MSEdge::myStreetName, GUIVisualizationSettings::personSize, PositionVector::positionAtOffset(), PositionVector::rotationDegreeAtOffset(), GUIVisualizationSettings::scale, GUIVisualizationTextSettings::show, GUIVisualizationTextSettings::size, GUIVisualizationSettings::streetName, SUMOReal, MFXMutex::unlock(), and GUIVisualizationSettings::vehicleSize.
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and drawGL().
void GUIEdge::fill (std::vector< GUIEdge * > & netsWrappers) static
Definition at line 140 of file GUIEdge.cpp.
References MSEdge::dictSize(), MSEdge::EDGEFUNCTION_DISTRICT, and MSEdge::myDict.
Referenced by GUINet::initGUIStructures().
const std::vector< MSLane * > * MSEdge::getAllowedLanesWithDefault (const AllowedLanesCont & c, const MSEdge * dest) const protected inherited
lookup in map and return 0 if not found
Definition at line 229 of file MSEdge.cpp.
Referenced by MSEdge::allowedLanes().
Boundary GUIEdge::getBoundary () const
Returns the street's geometry.
Definition at line 129 of file GUIEdge.cpp.
References Boundary::add(), Boundary::grow(), and MSEdge::myLanes.
Referenced by getCenteringBoundary().
Boundary GUIEdge::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See Also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 206 of file GUIEdge.cpp.
References getBoundary(), and Boundary::grow().
SUMOReal MSEdge::getCurrentTravelTime (const SUMOReal minSpeed = NUMERICAL_EPS) const inherited
Computes and returns the current travel time for this edge.
The mean speed of all lanes is used to compute the travel time. To avoid infinite travel times, the given minimum speed is used.
Parameters
[in] minSpeed The minimumSpeed to assume if traffic on this edge is stopped
Returns
The current effort (travel time) to pass the edge
Definition at line 501 of file MSEdge.cpp.
References MSEdge::getLength(), MSGlobals::gUseMesoSim, MAX2(), MSEdge::myAmDelayed, MSEdge::myEmptyTraveltime, MSEdge::myLanes, and SUMOReal.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), TraCIServerAPI_Edge::processGet(), and MSFullExport::writeEdge().
MSLane * MSEdge::getDepartLane (MSVehicle & veh) const inherited
Finds a depart lane for the given vehicle parameters.
Depending on the depart lane procedure a depart lane is chosen. Repeated calls with the same vehicle may return different results if the procedure is "random" or "free". In case no appropriate lane was found, 0 is returned.
Parameters
[in] veh The vehicle to get the depart lane for
Returns
a possible/chosen depart lane, 0 if no lane can be used
Definition at line 312 of file MSEdge.cpp.
References MSEdge::allowedLanes(), MSRoute::begin(), DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_DEFAULT, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, MSVehicle::getBestLanes(), MSEdge::getFreeLane(), MSBaseVehicle::getParameter(), RandHelper::getRandomFrom(), MSBaseVehicle::getRoute(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSEdge::myLanes, MSRoute::size(), SUMOReal, and MSVehicle::updateBestLanes().
Referenced by MSEdge::insertVehicle().
SUMOReal MSEdge::getDistanceTo (const MSEdge * other) const inherited
optimistic air distance heuristic for use in routing
Parameters
[in] other The edge to which the distance shall be returned
Returns
The distance to the other edge
Definition at line 624 of file MSEdge.cpp.
References Position::distanceTo2D(), MSEdge::getFromJunction(), MSEdge::getLanes(), MSJunction::getPosition(), and MSEdge::getToJunction().
const std::string& MSEdge::getEdgeType () const inline inherited
Returns the type of the edge.
Definition at line 270 of file MSEdge.h.
References MSEdge::myEdgeType.
Referenced by GUILane::getParameterWindow().
MSLane * MSEdge::getFreeLane (const std::vector< MSLane * > * allowed, const SUMOVehicleClass vclass) const inherited
Finds the emptiest lane allowing the vehicle class.
The emptiest lane is the one with the fewest vehicles on. If there is more than one, the first according to its index in the lane container is chosen.
If allowed==0, the lanes allowed for the given vehicle class will be used.
Parameters
[in] allowed The lanes to choose from
[in] vclass The vehicle class to look for
Returns
the least occupied lane
See Also
allowedLanes
Definition at line 292 of file MSEdge.cpp.
References MSEdge::allowedLanes(), max, and SUMOReal.
Referenced by MSVehicleTransfer::checkInsertions(), and MSEdge::getDepartLane().
const MSJunction* MSEdge::getFromJunction () const inline inherited
Definition at line 345 of file MSEdge.h.
References MSEdge::myFromJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSEdge::getDistanceTo(), MSPModel_Striping::getNextLane(), MSPModel_Striping::PState::PState(), MSLink::setRequestInformation(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIJunctionWrapper::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GUILane::getColorValue(), GUIVehicle::getColorValue(), getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), GUILane::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
std::vector< GUIGlID > GUIEdge::getIDs (bool includeInternal) static
Definition at line 100 of file GUIEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, GUIGlObject::getGlID(), MSEdge::getPurpose(), and MSEdge::myDict.
Referenced by GUINet::getParameterWindow(), and GUISUMOViewParent::onCmdLocate().
const MSEdgeVector& MSEdge::getIncomingEdges () const inline inherited
Returns the list of edges from which this edge may be reached.
Returns
Edges from which this edge may be reached
Definition at line 300 of file MSEdge.h.
References MSEdge::myPredecessors.
Referenced by NLEdgeControlBuilder::build(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLogicalPredecessorLane(), and MSPModel_Striping::initWalkingAreaPaths().
MSLane & GUIEdge::getLane (size_t laneNo)
returns the enumerated lane (!!! why not private with a friend?)
Definition at line 93 of file GUIEdge.cpp.
static std::pair<SUMOReal, SUMOReal> GUIEdge::getLaneOffsets (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2, SUMOReal prev, SUMOReal wanted) static
returns the position on the line given by the coordinates where "prev" is the length of the line and "wanted" the distance from the begin !!! should be within another class
const std::vector<MSLane*>& MSEdge::getLanes () const inline inherited
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 186 of file MSEdge.h.
References MSEdge::myLanes.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSVehicleTransfer::add(), NLHandler::addConnection(), MSBaseVehicle::calculateArrivalPos(), MSEdgeControl::changeLanes(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeVehicle(), CState::computeTranshipTime(), GUILane::drawMarkings(), MSCalibrator::execute(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSEdge::getDistanceTo(), MSPerson::MSPersonStage::getEdgeAngle(), MSContainer::MSContainerStage::getEdgeAngle(), GUILane::getEdgeLaneNumber(), MSPerson::MSPersonStage::getEdgePosition(), MSContainer::MSContainerStage::getEdgePosition(), TraCIServerAPI_Simulation::getLaneChecking(), MSVehicle::getLaneIndex(), getPopUpMenu(), GUIContainer::getPosition(), MSVehicle::getPosition(), TraCIServerAPI_Edge::getShape(), MSPModel::getSidewalk(), MSEdge::getSpeedLimit(), getTotalLength(), MSEdge::getVehicleMaxSpeed(), GUICalibrator::GUICalibrator(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), MSVehicle::Influencer::influenceChangeDecision(), GUINet::initGUIStructures(), MSCalibrator::invalidJam(), GUISUMOViewParent::isSelected(), MSCalibrator::MSCalibrator(), MSRouteProbe::MSRouteProbe(), MSLCM_DK2008::patchSpeed(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Vehicle::processSet(), MSCalibrator::remainingVehicleCapacity(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), and MSMeanData::writeEdge().
SUMOTime MSEdge::getLastFailedInsertionTime () const inline inherited
Returns the last time a vehicle could not be inserted.
Returns
The current value
Definition at line 486 of file MSEdge.h.
References MSEdge::myLastFailedInsertionTime.
Referenced by MSInsertionControl::checkCandidates().
SUMOReal MSEdge::getLength () const inline inherited
return the length of the edge
Returns
The edge's length
Definition at line 535 of file MSEdge.h.
References MSEdge::myLength.
Referenced by NLTriggerBuilder::buildCalibrator(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSDevice_Tripinfo::generateOutput(), MSEdge::getCurrentTravelTime(), MSContainer::MSContainerStage_Driving::getEdgePos(), MSPerson::MSPersonStage_Driving::getEdgePos(), MSEdge::getMinimumTravelTime(), MSPModel_Striping::getNextLane(), getParameterWindow(), getTotalLength(), MSEdge::insertVehicle(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), MSCalibrator::remainingVehicleCapacity(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), and MSMeanData::writeEdge().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), TraCIServerAPI_TLS::processGet(), PCPolyContainer::save(), ROVehicle::saveAllAsXML(), SUMOVTypeParameter::write(), and SUMO::Polygon::writeXML().
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
SUMOReal MSEdge::getMinimumTravelTime (const SUMOVehicle *const veh) const inline inherited
returns the minimum travel time for the given vehicle
Definition at line 410 of file MSEdge.h.
References MSEdge::getLength(), SUMOVehicle::getMaxSpeed(), MSEdge::getSpeedLimit(), MSEdge::getVehicleMaxSpeed(), and MIN2().
Referenced by MSDevice_Routing::getEffort(), and MSNet::getTravelTime().
int MSEdge::getNumericalID () const inline inherited
Returns the numerical id of the edge.
Returns
This edge's numerical id
Definition at line 257 of file MSEdge.h.
References MSEdge::myNumericalID.
Referenced by MSEdgeControl::changeLanes(), MSEdge::dictionary(), MSMeanData_Amitran::getEdgeID(), and MSDevice_Routing::getEffort().
unsigned int MSEdge::getNumPredecessors () const inline inherited
Returns the number of edges this edge is connected to.
Returns
The number of edges following this edge
Definition at line 331 of file MSEdge.h.
References MSEdge::myPredecessors.
Referenced by MSRouteHandler::parseFromViaTo().
unsigned int MSEdge::getNumSuccessors () const inline inherited
Returns the number of edges that may be reached from this edge.
Returns
The number of following edges
Definition at line 308 of file MSEdge.h.
References MSEdge::mySuccessors.
Referenced by NLEdgeControlBuilder::build(), and MSRouteHandler::parseFromViaTo().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
GUIParameterTableWindow * GUIEdge::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See Also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 170 of file GUIEdge.cpp.
References GUIParameterTableWindow::closeBuilding(), MSEdge::getLength(), GUISUMOAbstractView::getPositionInformation(), GUIParameterTableWindow::mkItem(), MSEdge::myLanes, and UNUSED_PARAMETER.
SVCPermissions MSEdge::getPermissions () const inline inherited
Definition at line 518 of file MSEdge.h.
References MSEdge::myCombinedPermissions.
GUIGLObjectPopupMenu * GUIEdge::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See Also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 153 of file GUIEdge.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), MSEdge::getLanes(), GUISUMOAbstractView::getPositionInformation(), MSGlobals::gUseMesoSim, SUMOReal, and toString().
const MSEdgeVector& MSEdge::getPredecessors () const inline inherited
Returns the edge at the given position from the list of reachable edges.
Parameters
[in] pos The position of the list within the list of approached
Returns
The following edge, stored at position pos
Definition at line 340 of file MSEdge.h.
References MSEdge::myPredecessors.
int MSEdge::getPriority () const inline inherited
Returns the priority of the edge.
Definition at line 276 of file MSEdge.h.
References MSEdge::myPriority.
Referenced by GUILane::getColorValue(), GUILane::getParameterWindow(), and GUILane::getScaleValue().
EdgeBasicFunction MSEdge::getPurpose () const inline inherited
Returns the edge type (EdgeBasicFunction)
Returns
This edge's EdgeBasicFunction
See Also
EdgeBasicFunction
Definition at line 235 of file MSEdge.h.
References MSEdge::myFunction.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLane::addApproachingLane(), MSLane::appropriate(), MSVehicle::checkRewindLinkLanes(), GUILane::drawGL(), MSVehicle::enterLaneAtMove(), MSVehicle::getBestLanesContinuation(), getIDs(), MSLane::getInternalFollower(), getTotalLength(), MSEdge::insertVehicle(), MSLink::lastWasContMajor(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSDevice_Routing::preInsertionReroute(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector< MSContainer * > MSEdge::getSortedContainers (SUMOTime timestep) const inherited
Returns this edge's containers sorted by pos.
Returns
This edge's containers sorted by pos
Definition at line 656 of file MSEdge.cpp.
References MSEdge::myContainers.
Referenced by MSXMLRawOut::writeEdge().
std::vector< MSPerson * > MSEdge::getSortedPersons (SUMOTime timestep) const inherited
Returns this edge's persons sorted by pos.
Returns
This edge's persons sorted by pos
Definition at line 648 of file MSEdge.cpp.
References MSEdge::myPersons.
Referenced by MSXMLRawOut::writeEdge().
SUMOReal MSEdge::getSpeedLimit () const inherited
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
Returns
The maximum speed allowed on this edge
Definition at line 634 of file MSEdge.cpp.
References MSEdge::getLanes().
Referenced by GUIApplicationWindow::checkGamingEvents(), MSEdge::getMinimumTravelTime(), MSEdge::insertVehicle(), MSCalibrator::invalidJam(), MSEdge::recalcCache(), MSCalibrator::remainingVehicleCapacity(), and MSMeanData::writeEdge().
const std::string& MSEdge::getStreetName () const inline inherited
Returns the street name of the edge.
Definition at line 264 of file MSEdge.h.
References MSEdge::myStreetName.
Referenced by drawGL(), and GUILane::getParameterWindow().
const MSEdgeVector& MSEdge::getSuccessors () const inline inherited
Returns the following edges.
Definition at line 315 of file MSEdge.h.
References MSEdge::mySuccessors.
Referenced by NLEdgeControlBuilder::build(), MSLane::getInternalFollower(), and MSPModel_Striping::initWalkingAreaPaths().
const MSEdgeVector & MSEdge::getSuccessors (SUMOVehicleClass vClass) const inherited
Returns the following edges, restricted by vClass.
Parameters
[in] vClass The vClass for which to restrict the successors
Returns
The eligible following edges
Definition at line 684 of file MSEdge.cpp.
References MSEdge::allowedLanes(), MSEdge::myClassesSuccessorMap, MSEdge::mySuccessors, and SVC_IGNORING.
const MSJunction* MSEdge::getToJunction () const inline inherited
Definition at line 349 of file MSEdge.h.
References MSEdge::myToJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSEdge::getDistanceTo(), MSPModel_Striping::getNextLane(), MSRailSignal::init(), and MSPModel_Striping::PState::PState().
SUMOReal GUIEdge::getTotalLength (bool includeInternal, bool eachLane) static
Definition at line 115 of file GUIEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::getLanes(), MSEdge::getLength(), MSEdge::getPurpose(), MSEdge::myDict, and SUMOReal.
Referenced by GUINet::getParameterWindow().
static SUMOReal MSEdge::getTravelTimeStatic (const MSEdge *const edge, const SUMOVehicle *const veh, SUMOReal time) inline static inherited
Returns the travel time for the given edge.
Parameters
[in] edge The edge for which the travel time shall be retrieved
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The traveltime needed by the given vehicle to pass the edge at the given time
Definition at line 426 of file MSEdge.h.
References MSNet::getInstance(), and MSNet::getTravelTime().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUIJunctionWrapper::getColorValue(), GUILane::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUILane::getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
SUMOReal MSEdge::getVehicleMaxSpeed (const SUMOVehicle *const veh) const inherited
Returns the maximum speed the vehicle may use on this edge.
Note that the vehicle's max. speed is not considered herein, only the edge's speed limit and the driver's adaptation of this speed. Only the first lane is considered
Returns
The maximum velocity on this edge for the given vehicle
Definition at line 641 of file MSEdge.cpp.
References MSEdge::getLanes().
Referenced by MSEdge::getMinimumTravelTime(), MSEdge::insertVehicle(), and MSDevice_Tripinfo::notifyMove().
SUMOTime MSEdge::incVaporization (SUMOTime t) inherited
Enables vaporization.
The internal vaporization counter is increased enabling the vaporization. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 278 of file MSEdge.cpp.
References MSEdge::myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer().
void MSEdge::initialize (const std::vector< MSLane * > * lanes) inherited
Initialize the edge.
Parameters
[in] allowed Information which edges may be reached from which lanes
[in] lanes List of this edge's lanes
Definition at line 107 of file MSEdge.cpp.
References MSEdge::EDGEFUNCTION_DISTRICT, OptionsCont::getOptions(), MSEdge::myCombinedPermissions, MSEdge::myFunction, MSEdge::myLaneChanger, MSEdge::myLanes, MSEdge::recalcCache(), and SVCAll.
Referenced by NLHandler::addDistrict(), and NLEdgeControlBuilder::closeEdge().
void MSEdge::insertIDs (std::vector< std::string > & into) static inherited
Inserts IDs of all known edges into the given vector.
Definition at line 586 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by TraCIServerAPI_Edge::processGet().
bool MSEdge::insertVehicle (SUMOVehicle & v, SUMOTime time, const bool checkOnly = false) const inherited
Tries to insert the given vehicle into the network.
The procedure for choosing the proper lane is determined, first. In dependance to this, the proper lane is chosen.
Insertion itself is done by calling the chose lane's "insertVehicle" method but only if the checkOnly argument is false. The check needs to be certain only in the negative case (if false is returned, there is no way this vehicle would be inserted).
Parameters
[in] v The vehicle to insert
[in] time The current simulation time
[in] checkOnly whether we perform only the check without actually inserting
Returns
Whether the vehicle could be inserted
See Also
MSLane::insertVehicle
Definition at line 367 of file MSEdge.cpp.
References MSVehicleType::computeChosenSpeedDeviation(), DEPART_LANE_DEFAULT, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_GIVEN, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_SPEED_GIVEN, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSEdge::EDGEFUNCTION_DISTRICT, MSLane::getBruttoOccupancy(), MSEdge::getDepartLane(), SUMOVehicle::getEdge(), Named::getID(), SUMOVehicle::getID(), MSEdge::getLength(), MSVehicleType::getLengthWithGap(), SUMOVehicle::getParameter(), MSEdge::getPurpose(), MSVehicleType::getSpeedDeviation(), MSVehicleType::getSpeedFactor(), MSEdge::getSpeedLimit(), MSEdge::getVehicleMaxSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gUseMesoSim, SUMOVehicleParameter::id, MSLane::insertVehicle(), MSEdge::isVaporizing(), MSEdge::myLanes, MSEdge::myLength, RandHelper::rand(), SUMOVehicle::setChosenSpeedFactor(), SUMOReal, toString(), UNUSED_PARAMETER, and WRITE_WARNING.
Referenced by MSInsertionControl::checkCandidates(), and MSCalibrator::execute().
bool MSEdge::isCrossing () const inline inherited
return whether this edge is a pedestrian crossing
Definition at line 245 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_CROSSING, and MSEdge::myFunction.
Referenced by MSPModel_Striping::getNextLane().
bool MSEdge::isInternal () const inline inherited
return whether this edge is an internal edge
Definition at line 240 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_INTERNAL, and MSEdge::myFunction.
Referenced by NLEdgeControlBuilder::build(), MSDevice_Tripinfo::generateOutput(), MSPModel_Striping::getNextLane(), and MSLink::setRequestInformation().
bool MSEdge::isRoundabout () const inline inherited
Definition at line 580 of file MSEdge.h.
References MSEdge::myAmRoundabout.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::executeMove().
bool MSEdge::isVaporizing () const inline inherited
Returns whether vehicles on this edge shall be vaporized.
Returns
Whether no vehicle shall be on this edge
Definition at line 368 of file MSEdge.h.
References MSEdge::myVaporizationRequests.
Referenced by MSVehicle::executeMove(), MSLane::executeMovements(), and MSEdge::insertVehicle().
bool MSEdge::isWalkingArea () const inline inherited
return whether this edge is walking area
Definition at line 250 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_WALKINGAREA, and MSEdge::myFunction.
Referenced by MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::initWalkingAreaPaths(), MSPModel_Striping::moveInDirection(), and MSPModel_Striping::PState::PState().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
MSLane * MSEdge::leftLane (const MSLane *const lane) const inherited
Returns the lane left to the one given, 0 if the given lane is leftmost.
Parameters
[in] lane The lane right to the one to be returned
Returns
The lane left to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 190 of file MSEdge.cpp.
References MSEdge::parallelLane().
void MSEdge::markAsRoundabout () inline inherited
Definition at line 584 of file MSEdge.h.
References MSEdge::myAmRoundabout.
Referenced by NLHandler::addRoundabout(), and NLEdgeControlBuilder::build().
void MSEdge::markDelayed () const inline inherited
Definition at line 588 of file MSEdge.h.
References MSEdge::myAmDelayed.
Referenced by MSLane::incorporateVehicle(), and MSLane::integrateNewVehicle().
size_t MSEdge::numericalDictSize () static inherited
Returns the number of edges with a numerical id.
Definition at line 571 of file MSEdge.cpp.
References MSEdge::myEdges.
Referenced by MSNet::getRouterEffort(), MSNet::getRouterTT(), and MSDevice_Routing::reroute().
GUIEdge& GUIEdge::operator= (const GUIEdge & s) private
invalidated assignment operator
MSLane * MSEdge::parallelLane (const MSLane *const lane, int offset) const inherited
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
Parameters
[in] lane The base lane
[in] offset The offset of the result lane
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 202 of file MSEdge.cpp.
References MSEdge::myLanes.
Referenced by MSLane::getParallelLane(), MSEdge::leftLane(), and MSEdge::rightLane().
void MSEdge::parseEdgesList (const std::string & desc, ConstMSEdgeVector & into, const std::string & rid) static inherited
Parses the given string assuming it contains a list of edge ids divided by spaces.
Splits the string at spaces, uses polymorph method to generate edge vector.
Parameters
[in] desc The string containing space-separated edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 594 of file MSEdge.cpp.
References BinaryFormatter::BF_ROUTE, StringTokenizer::getVector(), and FileHelpers::readEdgeVector().
Referenced by MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and TraCIServerAPI_Vehicle::processSet().
void MSEdge::parseEdgesList (const std::vector< std::string > & desc, ConstMSEdgeVector & into, const std::string & rid) static inherited
Parses the given string vector assuming it edge ids.
Parameters
[in] desc The string vector containing edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 609 of file MSEdge.cpp.
References MSEdge::dictionary().
bool MSEdge::prohibits (const SUMOVehicle *const vehicle) const inline inherited
Returns whether the vehicle (class) is not allowed on the edge.
Definition at line 510 of file MSEdge.h.
References MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), and MSEdge::myCombinedPermissions.
void MSEdge::rebuildAllowedLanes () inherited
Definition at line 168 of file MSEdge.cpp.
References MSEdge::myClassedAllowed, MSEdge::myClassesSuccessorMap, MSEdge::myCombinedPermissions, MSEdge::myLanes, MSEdge::myMinimumPermissions, and SVCAll.
Referenced by MSEdge::closeBuilding(), TraCIServerAPI_Edge::processSet(), and TraCIServerAPI_Lane::processSet().
void MSEdge::recalcCache () inherited
Recalculates the cached values.
Definition at line 122 of file MSEdge.cpp.
References MSEdge::getSpeedLimit(), MAX2(), MSEdge::myEmptyTraveltime, MSEdge::myLanes, MSEdge::myLength, and NUMERICAL_EPS.
Referenced by MSEdge::initialize(), MSLane::setLength(), and MSLane::setMaxSpeed().
void GUIEdge::removeContainer (MSContainer * container) const inline virtual
Remove container from myContainers.
Reimplemented from MSEdge.
Definition at line 163 of file GUIEdge.h.
References myLock, and MSEdge::removeContainer().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIEdge::removePerson (MSPerson * p) const inline virtual
Reimplemented from MSEdge.
Definition at line 152 of file GUIEdge.h.
References myLock, and MSEdge::removePerson().
MSLane * MSEdge::rightLane (const MSLane *const lane) const inherited
Returns the lane right to the one given, 0 if the given lane is rightmost.
Parameters
[in] lane The lane left to the one to be returned
Returns
The lane right to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 196 of file MSEdge.cpp.
References MSEdge::parallelLane().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void MSEdge::setJunctions (MSJunction * from, MSJunction * to) inline inherited
Definition at line 354 of file MSEdge.h.
References MSEdge::myFromJunction, and MSEdge::myToJunction.
Referenced by NLHandler::myEndElement().
void MSEdge::setLastFailedInsertionTime (SUMOTime time) const inline inherited
Sets the last time a vehicle could not be inserted.
Parameters
[in] time the new value
Definition at line 494 of file MSEdge.h.
References MSEdge::myLastFailedInsertionTime.
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
AllowedLanesCont MSEdge::myAllowed protected inherited
Associative container from destination-edge to allowed-lanes.
Definition at line 742 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), MSEdge::closeBuilding(), and MSEdge::~MSEdge().
bool MSEdge::myAmDelayed mutable protected inherited
whether this edge had a vehicle with less than max speed on it
Definition at line 770 of file MSEdge.h.
Referenced by MSEdge::getCurrentTravelTime(), and MSEdge::markDelayed().
bool MSEdge::myAmRoundabout protected inherited
whether this edge belongs to a roundabout
Definition at line 773 of file MSEdge.h.
Referenced by MSEdge::isRoundabout(), and MSEdge::markAsRoundabout().
ClassedAllowedLanesCont MSEdge::myClassedAllowed mutable protected inherited
From vehicle class to lanes allowed to be used by it.
Definition at line 746 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), MSEdge::rebuildAllowedLanes(), and MSEdge::~MSEdge().
ClassesSuccesorMap MSEdge::myClassesSuccessorMap mutable protected inherited
Definition at line 795 of file MSEdge.h.
Referenced by MSEdge::getSuccessors(), and MSEdge::rebuildAllowedLanes().
SVCPermissions MSEdge::myCombinedPermissions protected inherited
The union of lane permissions for this edge.
Definition at line 751 of file MSEdge.h.
Referenced by MSEdge::getPermissions(), MSEdge::initialize(), MSEdge::prohibits(), and MSEdge::rebuildAllowedLanes().
std::set<MSContainer*> MSEdge::myContainers mutable protected inherited
Containers on the edge.
Definition at line 736 of file MSEdge.h.
Referenced by MSEdge::addContainer(), drawGL(), MSEdge::getSortedContainers(), and MSEdge::removeContainer().
MSEdge::DictType MSEdge::myDict static protected inherited
Static dictionary to associate string-ids with objects.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 784 of file MSEdge.h.
Referenced by MSEdge::clear(), MSEdge::dictionary(), MSEdge::dictSize(), fill(), getIDs(), getTotalLength(), and MSEdge::insertIDs().
MSEdgeVector MSEdge::myEdges static protected inherited
Static list of edges.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 789 of file MSEdge.h.
Referenced by MSEdge::dictionary(), and MSEdge::numericalDictSize().
std::string MSEdge::myEdgeType protected inherited
the type of the edge (optionally used during network creation)
Definition at line 758 of file MSEdge.h.
Referenced by MSEdge::getEdgeType().
SUMOReal MSEdge::myEmptyTraveltime protected inherited
the traveltime on the empty edge (cached value for speedup)
Definition at line 767 of file MSEdge.h.
Referenced by MSEdge::getCurrentTravelTime(), and MSEdge::recalcCache().
MSJunction* MSEdge::myFromJunction protected inherited
the junctions for this edge
Definition at line 729 of file MSEdge.h.
Referenced by MSEdge::getFromJunction(), and MSEdge::setJunctions().
const EdgeBasicFunction MSEdge::myFunction protected inherited
the purpose of the edge
Definition at line 714 of file MSEdge.h.
Referenced by MSEdge::changeLanes(), drawGL(), MSEdge::getPurpose(), MSEdge::initialize(), MSEdge::isCrossing(), MSEdge::isInternal(), and MSEdge::isWalkingArea().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLaneChanger* MSEdge::myLaneChanger protected inherited
This member will do the lane-change.
Definition at line 711 of file MSEdge.h.
Referenced by MSEdge::changeLanes(), MSEdge::initialize(), and MSEdge::~MSEdge().
const std::vector<MSLane*>* MSEdge::myLanes protected inherited
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
Definition at line 708 of file MSEdge.h.
Referenced by MSEdge::changeLanes(), MSEdge::closeBuilding(), drawGL(), getBoundary(), MSEdge::getCurrentTravelTime(), MSEdge::getDepartLane(), MSEdge::getLanes(), getParameterWindow(), MSEdge::initialize(), MSEdge::insertVehicle(), MSEdge::parallelLane(), MSEdge::rebuildAllowedLanes(), MSEdge::recalcCache(), and MSEdge::~MSEdge().
SUMOTime MSEdge::myLastFailedInsertionTime mutable protected inherited
The time of last insertion failure.
Definition at line 720 of file MSEdge.h.
Referenced by MSEdge::getLastFailedInsertionTime(), and MSEdge::setLastFailedInsertionTime().
SUMOReal MSEdge::myLength protected inherited
the length of the edge (cached value for speedup)
Definition at line 764 of file MSEdge.h.
Referenced by MSEdge::getLength(), MSEdge::insertVehicle(), and MSEdge::recalcCache().
MFXMutex GUIEdge::myLock mutable private
The mutex used to avoid concurrent updates of myPersons/ myContainers.
Definition at line 212 of file GUIEdge.h.
Referenced by addContainer(), addPerson(), drawGL(), removeContainer(), removePerson(), and ~GUIEdge().
SVCPermissions MSEdge::myMinimumPermissions protected inherited
The intersection of lane permissions for this edge.
Definition at line 749 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), and MSEdge::rebuildAllowedLanes().
const int MSEdge::myNumericalID protected inherited
This edge's numerical id.
Definition at line 705 of file MSEdge.h.
Referenced by MSEdge::getNumericalID().
std::set<MSPerson*> MSEdge::myPersons mutable protected inherited
Persons on the edge (only for drawing)
Definition at line 733 of file MSEdge.h.
Referenced by MSEdge::addPerson(), drawGL(), MSEdge::getSortedPersons(), and MSEdge::removePerson().
MSEdgeVector MSEdge::myPredecessors protected inherited
The preceeding edges.
Definition at line 726 of file MSEdge.h.
Referenced by MSEdge::addSuccessor(), MSEdge::closeBuilding(), MSEdge::getIncomingEdges(), MSEdge::getNumPredecessors(), and MSEdge::getPredecessors().
const int MSEdge::myPriority protected inherited
the priority of the edge (used during network creation)
Definition at line 761 of file MSEdge.h.
Referenced by MSEdge::getPriority().
std::string MSEdge::myStreetName protected inherited
the real-world name of this edge (need not be unique)
Definition at line 755 of file MSEdge.h.
Referenced by drawGL(), and MSEdge::getStreetName().
MSEdgeVector MSEdge::mySuccessors protected inherited
The succeeding edges.
Definition at line 723 of file MSEdge.h.
Referenced by MSEdge::addSuccessor(), MSEdge::closeBuilding(), MSEdge::getNumSuccessors(), and MSEdge::getSuccessors().
MSJunction* MSEdge::myToJunction protected inherited
Definition at line 730 of file MSEdge.h.
Referenced by MSEdge::getToJunction(), and MSEdge::setJunctions().
int MSEdge::myVaporizationRequests protected inherited
Vaporizer counter.
Definition at line 717 of file MSEdge.h.
Referenced by MSEdge::decVaporization(), MSEdge::incVaporization(), and MSEdge::isVaporizing().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIEdge.h
GUIEdge.cpp