SUMO - Simulation of Urban MObility: RODFEdgeBuilder Class Reference
RODFEdgeBuilder Class Reference
Interface for building instances of dfrouter-edges.
#include <RODFEdgeBuilder.h>
Public Member Functions
RODFEdgeBuilder ()
Constructor.
~RODFEdgeBuilder ()
Destructor.
Methods to be implemented, inherited from ROAbstractEdgeBuilder
ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to, const int priority)
Builds an edge with the given name.
Protected Member Functions
unsigned int getNextIndex ()
Returns the index of the edge to built.
Detailed Description
Interface for building instances of dfrouter-edges.
This ROAbstractEdgeBuilder implementation builds edges for the duarouter (instances of RODFEdge).
See Also
RODFEdge
Definition at line 57 of file RODFEdgeBuilder.h.
Constructor & Destructor Documentation
RODFEdgeBuilder::RODFEdgeBuilder ()
Constructor.
Definition at line 44 of file RODFEdgeBuilder.cpp.
RODFEdgeBuilder::~RODFEdgeBuilder ()
Destructor.
Definition at line 47 of file RODFEdgeBuilder.cpp.
Member Function Documentation
ROEdge * RODFEdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to, const int priority) virtual
Builds an edge with the given name.
This implementation builds a RODFEdge.
Parameters
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] priority The edge priority (road class)
Returns
A proper instance of the named edge
See Also
RODFEdge
Implements ROAbstractEdgeBuilder.
Definition at line 51 of file RODFEdgeBuilder.cpp.
References ROAbstractEdgeBuilder::getNextIndex().
unsigned int ROAbstractEdgeBuilder::getNextIndex () inline protected inherited
Returns the index of the edge to built.
Returns
Next valid edge index
Definition at line 90 of file ROAbstractEdgeBuilder.h.
References ROAbstractEdgeBuilder::myCurrentIndex.
Referenced by AGStreet::Builder::buildEdge(), ROJTREdgeBuilder::buildEdge(), buildEdge(), ROMAEdgeBuilder::buildEdge(), and RODUAEdgeBuilder::buildEdge().
The documentation for this class was generated from the following files:
RODFEdgeBuilder.h
RODFEdgeBuilder.cpp