SUMO - Simulation of Urban MObility: NWWriter_OpenDrive Class Reference
NWWriter_OpenDrive Class Reference
Exporter writing networks using the openDRIVE format.
#include <NWWriter_OpenDrive.h>
Static Public Member Functions
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a openDRIVE-file.
Static Protected Member Functions
static int getID (const std::string &origID, StringBijection< int > &map, int &lastID)
static void writeEmptyCenterLane (OutputDevice &device, const std::string &mark, SUMOReal markWidth)
static void writePlanView (const PositionVector &shape, OutputDevice &device)
Detailed Description
Exporter writing networks using the openDRIVE format.
Definition at line 53 of file NWWriter_OpenDrive.h.
Member Function Documentation
int NWWriter_OpenDrive::getID (const std::string & origID, StringBijection< int > & map, int & lastID) static protected
Definition at line 236 of file NWWriter_OpenDrive.cpp.
References StringBijection< T >::get(), StringBijection< T >::hasString(), and StringBijection< T >::insert().
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeEmptyCenterLane (OutputDevice & device, const std::string & mark, SUMOReal markWidth) static protected
Definition at line 224 of file NWWriter_OpenDrive.cpp.
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into a openDRIVE-file.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 60 of file NWWriter_OpenDrive.cpp.
References PositionVector::append(), NBNodeCont::begin(), NBEdgeCont::begin(), NBNodeCont::end(), NBEdgeCont::end(), StringUtils::escapeXML(), NBEdge::Connection::fromLane, GeoConvHelper::getConvBoundary(), OutputDevice::getDevice(), NBNetBuilder::getEdgeCont(), GeoConvHelper::getFinal(), NBEdge::getFromNode(), Named::getID(), getID(), NBNode::getIncomingEdges(), NBEdge::Connection::getInternalLaneID(), NBEdge::getLanes(), NBEdge::getLaneShape(), NBEdge::getLaneWidth(), NBEdge::getLength(), NBNetBuilder::getNodeCont(), NBEdge::getNumLanes(), NBEdge::getStreetName(), OptionsCont::getString(), NBEdge::getToNode(), NBEdge::Connection::haveVia, OptionsCont::isSet(), PositionVector::length(), PositionVector::move2side(), NBEdge::Connection::shape, NBNodeCont::size(), NBEdgeCont::size(), SUMO_const_laneWidth, SUMOReal, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, NBEdge::Connection::viaShape, writeEmptyCenterLane(), writePlanView(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by NWFrame::writeNetwork().
void NWWriter_OpenDrive::writePlanView (const PositionVector & shape, OutputDevice & device) static protected
Definition at line 209 of file NWWriter_OpenDrive.cpp.
References Line::length(), PositionVector::lineAt(), Line::p1(), Line::p2(), SUMOReal, Position::x(), and Position::y().
Referenced by writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_OpenDrive.h
NWWriter_OpenDrive.cpp