SUMO - Simulation of Urban MObility: ROEdge Class Reference
ROEdge Class Reference
A basic edge for routing applications.
#include <ROEdge.h>
Public Types
enum EdgeType {
ET_NORMAL, ET_DISTRICT, ET_SOURCE, ET_SINK,
ET_WALKINGAREA, ET_CROSSING, ET_INTERNAL
}
Possible types of edges.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
SUMOReal getDistanceTo (const ROEdge *other) const
optimistic distance heuristic for use in routing
const RONode * getFromJunction () const
const std::string & getID () const
Returns the id.
const std::vector< ROLane * > & getLanes () const
Returns this edge's lanes.
int getPriority () const
get edge priority (road class)
const RONode * getToJunction () const
ROEdge (const std::string &id, RONode *from, RONode *to, unsigned int index, const int priority)
Constructor.
void setID (const std::string &newID)
resets the id
void setJunctions (RONode *from, RONode *to)
virtual ~ROEdge ()
Destructor.
Set-up methods
virtual void addLane (ROLane *lane)
Adds a lane to the edge while loading.
virtual void addSuccessor (ROEdge *s, std::string dir="")
Adds information about a connected edge.
void setType (EdgeType type)
Sets the type of te edge.
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
void buildTimeLines (const std::string &measure)
Builds the internal representation of the travel time/effort.
Getter methods
EdgeType getType () const
Returns the type of the edge.
SUMOReal getLength () const
Returns the length of the edge.
unsigned int getNumericalID () const
Returns the index (numeric id) of the edge.
SUMOReal getSpeed () const
Returns the speed allowed on this edge.
unsigned int getLaneNo () const
Returns the number of lanes this edge has.
RONode * getFromNode () const
Returns the node this edge starts at.
RONode * getToNode () const
Returns the node this edge ends at.
bool isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const
returns the information whether this edge is directly connected to the given
bool prohibits (const ROVehicle *const vehicle) const
Returns whether this edge prohibits the given vehicle to pass it.
SVCPermissions getPermissions () const
bool allFollowersProhibit (const ROVehicle *const vehicle) const
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Static Public Member Functions
static ROEdge * dictionary (size_t index)
Returns the ROEdge at the index.
static size_t dictSize ()
Returns the number of edges.
static void setTimeLineOptions (bool useBoundariesOnOverrideTT, bool useBoundariesOnOverrideE, bool interpolate)
Protected Types
typedef std::map
< SUMOVehicleClass,
ROEdgeVector > ClassesSuccesorMap
The successors available for a given vClass.
Protected Member Functions
bool getStoredEffort (SUMOReal time, SUMOReal &ret) const
Retrieves the stored effort.
Protected Attributes
ROEdgeVector myApproachingEdges
List of edges that approached this edge.
ClassesSuccesorMap myClassesSuccessorMap
SVCPermissions myCombinedPermissions
The list of allowed vehicle classes combined across lanes.
ValueTimeLine< SUMOReal > myEfforts
Container storing passing time varying over time for the edge.
ROEdgeVector myFollowingEdges
List of edges that may be approached from this edge.
RONode * myFromJunction
the junctions for this edge
RONode *const myFromNode
The nodes this edge is connecting.
std::string myID
The name of the object.
const unsigned int myIndex
The index (numeric id) of the edge.
std::vector< ROLane * > myLanes
This edge's lanes.
SUMOReal myLength
The length of the edge.
const int myPriority
The edge priority (road class)
SUMOReal mySpeed
The maximum speed allowed on this edge.
RONode * myToJunction
RONode *const *const myToNode
ValueTimeLine< SUMOReal > myTravelTimes
Container storing passing time varying over time for the edge.
EdgeType myType
The type of the edge.
bool myUsingETimeLine
Information whether the time line shall be used instead of the length value.
bool myUsingTTTimeLine
Information whether the time line shall be used instead of the length value.
Static Protected Attributes
static ROEdgeVector myEdges
static bool myHaveEWarned = false
Information whether the edge has reported missing weights.
static bool myHaveTTWarned = false
Information whether the edge has reported missing weights.
static bool myInterpolate = false
Information whether to interpolate at interval boundaries.
static bool myUseBoundariesOnOverrideE = false
Whether overriding weight boundaries shall be reported.
static bool myUseBoundariesOnOverrideTT = false
Whether overriding weight boundaries shall be reported.
Private Member Functions
ROEdge & operator= (const ROEdge &src)
Invalidated assignment operator.
ROEdge (const ROEdge &src)
Invalidated copy constructor.
Methods for getting/setting travel time and cost information
void addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a weight value.
void addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a travel time value.
unsigned int getNumSuccessors () const
Returns the number of edges this edge is connected to.
const ROEdgeVector & getSuccessors () const
Returns the following edges.
const ROEdgeVector & getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
unsigned int getNumPredecessors () const
Returns the number of edges connected to this edge.
const ROEdgeVector & getPredecessors () const
Returns the edge at the given position from the list of incoming edges.
SUMOReal getEffort (const ROVehicle *const veh, SUMOReal time) const
Returns the effort for this edge.
SUMOReal getTravelTime (const ROVehicle *const veh, SUMOReal time) const
Returns the travel time for this edge.
SUMOReal getMinimumTravelTime (const ROVehicle *const veh) const
Returns a lower bound for the travel time on this edge without using any stored timeLine.
static SUMOReal getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Returns the effort for the given edge.
static SUMOReal getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Returns the travel time for the given edge.
template<PollutantsInterface::EmissionType ET>
static SUMOReal getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
static SUMOReal getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Detailed Description
A basic edge for routing applications.
The edge contains two time lines, one for the travel time and one for a second measure which may be used for computing the costs of a route. After loading the weights, it is needed to call "buildTimeLines" in order to initialise these time lines.
Definition at line 73 of file ROEdge.h.
Member Typedef Documentation
typedef std::map<SUMOVehicleClass, ROEdgeVector> ROEdge::ClassesSuccesorMap protected
The successors available for a given vClass.
Definition at line 513 of file ROEdge.h.
Member Enumeration Documentation
enum ROEdge::EdgeType
Possible types of edges.
Enumerator
ET_NORMAL
A normal edge.
ET_DISTRICT
An edge representing a whole district.
ET_SOURCE
An edge where vehicles are inserted at (no vehicle may come from back)
ET_SINK
An edge where vehicles disappear (no vehicle may leave this edge)
ET_WALKINGAREA
An internal edge which models walking areas for pedestrians.
ET_CROSSING
An internal edge which models pedestrian crossings.
ET_INTERNAL
An internal edge which models vehicles driving across a junction. This is currently not used for routing.
Definition at line 79 of file ROEdge.h.
Constructor & Destructor Documentation
ROEdge::ROEdge (const std::string & id, RONode * from, RONode * to, unsigned int index, const int priority)
Constructor.
Parameters
[in] id The id of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] index The numeric id of the edge
Definition at line 67 of file ROEdge.cpp.
References myEdges.
ROEdge::~ROEdge () virtual
Destructor.
Definition at line 82 of file ROEdge.cpp.
References myLanes.
ROEdge::ROEdge (const ROEdge & src) private
Invalidated copy constructor.
Member Function Documentation
void ROEdge::addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a weight value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 112 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), myEfforts, and myUsingETimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), ROMAAssignments::incremental(), and ROMAAssignments::sue().
void ROEdge::addLane (ROLane * lane) virtual
Adds a lane to the edge while loading.
The lane's length is adapted. Additionally, the information about allowed/disallowed vehicle classes is patched using the information stored in the lane.
Parameters
[in] lane The lane to add
Todo:
What about vehicle-type aware connections?
Definition at line 90 of file ROEdge.cpp.
References ROLane::getLength(), ROLane::getPermissions(), ROLane::getSpeed(), myCombinedPermissions, myLanes, myLength, mySpeed, and SUMOReal.
Referenced by RONetHandler::parseLane().
void ROEdge::addSuccessor (ROEdge * s, std::string dir = "") virtual
Adds information about a connected edge.
The edge s is added to "myFollowingEdges" and this edge is added as predecessor to s.
Parameters
[in] s The edge to add
Todo:
What about vehicle-type aware connections?
Reimplemented in ROMAEdge, and ROJTREdge.
Definition at line 103 of file ROEdge.cpp.
References myApproachingEdges, and myFollowingEdges.
Referenced by RONet::addDistrictEdge(), ROJTREdge::addSuccessor(), and ROMAEdge::addSuccessor().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
void ROEdge::addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a travel time value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 119 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), myTravelTimes, and myUsingTTTimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), ROMAAssignments::incremental(), and ROMAAssignments::sue().
bool ROEdge::allFollowersProhibit (const ROVehicle *const vehicle) const
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle may continue its route on any of the following edges
Definition at line 262 of file ROEdge.cpp.
References myFollowingEdges.
Referenced by ROJTREdge::chooseNext().
void ROEdge::buildTimeLines (const std::string & measure)
Builds the internal representation of the travel time/effort.
Should be called after weights / travel times have been loaded.
In the case "weight-attribute" is one of "CO", "CO2", "HC", "NOx", "PMx", or "fuel" the proper value (departs/s) is computed and multiplied with the travel time.
Parameters
[in] measure The name of the measure to use.
Definition at line 231 of file ROEdge.cpp.
References PollutantsInterface::CO, PollutantsInterface::CO2, PollutantsInterface::compute(), ValueTimeLine< T >::fillGaps(), PollutantsInterface::FUEL, PollutantsInterface::getClassByName(), PollutantsInterface::HC, myEfforts, myLength, mySpeed, myTravelTimes, myUseBoundariesOnOverrideE, myUseBoundariesOnOverrideTT, myUsingETimeLine, myUsingTTTimeLine, PollutantsInterface::NO_X, PollutantsInterface::PM_X, and SUMOReal.
ROEdge * ROEdge::dictionary (size_t index) static
Returns the ROEdge at the index.
Definition at line 273 of file ROEdge.cpp.
References myEdges.
static size_t ROEdge::dictSize () inline static
Returns the number of edges.
Definition at line 402 of file ROEdge.h.
References myEdges.
SUMOReal ROEdge::getDistanceTo (const ROEdge * other) const
optimistic distance heuristic for use in routing
Definition at line 136 of file ROEdge.cpp.
References Position::distanceTo2D(), getFromNode(), RONode::getPosition(), and getToNode().
SUMOReal ROEdge::getEffort (const ROVehicle *const veh, SUMOReal time) const
Returns the effort for this edge.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 126 of file ROEdge.cpp.
References getStoredEffort(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), myLength, mySpeed, and SUMOReal.
Referenced by getEffortStatic(), ROMAAssignments::getPenalizedEffort(), and ROMAAssignments::sue().
static SUMOReal ROEdge::getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static
Returns the effort for the given edge.
Parameters
[in] edge The edge for which the effort shall be retrieved
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 350 of file ROEdge.h.
References getEffort().
template<PollutantsInterface::EmissionType ET> static SUMOReal ROEdge::getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static
Definition at line 378 of file ROEdge.h.
References PollutantsInterface::computeDefault(), SUMOVTypeParameter::emissionClass, SUMOVTypeParameter::get(), SUMOVTypeParameter::getDefaultAccel(), SUMOVTypeParameter::getDefaultImperfection(), getStoredEffort(), getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), mySpeed, SUMO_ATTR_ACCEL, SUMO_ATTR_SIGMA, SUMOReal, and SUMOVTypeParameter::vehicleClass.
const RONode* ROEdge::getFromJunction () const inline
Definition at line 420 of file ROEdge.h.
References myFromJunction.
RONode* ROEdge::getFromNode () const inline
Returns the node this edge starts at.
Returns
The node this edge starts at
Definition at line 214 of file ROEdge.h.
References myFromNode.
Referenced by RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and getDistanceTo().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
unsigned int ROEdge::getLaneNo () const inline
Returns the number of lanes this edge has.
Returns
This edge's number of lanes
Definition at line 206 of file ROEdge.h.
References myLanes.
Referenced by ROMAAssignments::capacityConstraintFunction(), and RODFDetectorHandler::myStartElement().
const std::vector<ROLane*>& ROEdge::getLanes () const inline
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 438 of file ROEdge.h.
References myLanes.
Referenced by RONetHandler::parseConnection().
SUMOReal ROEdge::getLength () const inline
Returns the length of the edge.
Returns
This edge's length
Definition at line 183 of file ROEdge.h.
References myLength.
Referenced by RORouteHandler::addStop(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), AGPosition::compute2dPosition(), RODFNet::getAbsPos(), getTravelTime(), RONetHandler::parseBusStop(), RONetHandler::parseContainerStop(), AGActivityGenHandler::parseStreets(), AGStreet::print(), AGPosition::print(), AGPosition::randomPositionInStreet(), and RORouteHandler::routePedestrian().
SUMOReal ROEdge::getMinimumTravelTime (const ROVehicle *const veh) const inline
Returns a lower bound for the travel time on this edge without using any stored timeLine.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Definition at line 372 of file ROEdge.h.
References ROVehicle::getChosenSpeedFactor(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), myLength, and mySpeed.
Referenced by computeRoutes(), and getTravelTime().
SUMOReal ROEdge::getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) static
Definition at line 171 of file ROEdge.cpp.
References HelpersHarmonoise::computeNoise(), SUMOVTypeParameter::emissionClass, getStoredEffort(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), mySpeed, and SUMOReal.
Referenced by computeRoutes().
unsigned int ROEdge::getNumericalID () const inline
Returns the index (numeric id) of the edge.
Returns
This edge's numerical id
Definition at line 190 of file ROEdge.h.
References myIndex.
unsigned int ROEdge::getNumPredecessors () const
Returns the number of edges connected to this edge.
If this edge's type is set to "source", 0 is returned, otherwise the number of edges stored in "myApproachingEdges".
Returns
The number of edges reaching into this edge
Definition at line 216 of file ROEdge.cpp.
References ET_SOURCE, getType(), and myApproachingEdges.
Referenced by RORouteHandler::parseFromViaTo().
unsigned int ROEdge::getNumSuccessors () const
Returns the number of edges this edge is connected to.
If this edge's type is set to "sink", 0 is returned, otherwise the number of edges stored in "myFollowingEdges".
Returns
The number of edges following this edge
Definition at line 207 of file ROEdge.cpp.
References ET_SINK, getType(), and myFollowingEdges.
Referenced by RODFDetector::computeSplitProbabilities(), and RORouteHandler::parseFromViaTo().
SVCPermissions ROEdge::getPermissions () const inline
Definition at line 245 of file ROEdge.h.
References myCombinedPermissions.
Referenced by AGStreet::allows().
const ROEdgeVector& ROEdge::getPredecessors () const inline
Returns the edge at the given position from the list of incoming edges.
Parameters
[in] pos The position of the list within the list of incoming
Returns
The incoming edge, stored at position pos
Definition at line 318 of file ROEdge.h.
References myApproachingEdges.
Referenced by RODFDetector::computeSplitProbabilities().
int ROEdge::getPriority () const inline
get edge priority (road class)
Definition at line 416 of file ROEdge.h.
References myPriority.
Referenced by ROMAAssignments::capacityConstraintFunction().
SUMOReal ROEdge::getSpeed () const inline
Returns the speed allowed on this edge.
Returns
The speed allowed on this edge
Definition at line 198 of file ROEdge.h.
References mySpeed.
Referenced by RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), RODFNet::computeRoutesFor(), getTravelTime(), RODFNet::isDestination(), RODFNet::isFalseSource(), and RODFNet::isSource().
bool ROEdge::getStoredEffort (SUMOReal time, SUMOReal & ret) const protected
Retrieves the stored effort.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned
Returns
Whether the effort is given
Definition at line 182 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getSplitTime(), ValueTimeLine< T >::getValue(), myEfforts, myHaveEWarned, Named::myID, myInterpolate, myTravelTimes, myUsingETimeLine, SUMOReal, toString(), and WRITE_WARNING.
Referenced by getEffort(), getEmissionEffort(), and getNoiseEffort().
const ROEdgeVector& ROEdge::getSuccessors () const inline
Returns the following edges.
Definition at line 292 of file ROEdge.h.
References myFollowingEdges.
Referenced by RODFNet::buildApproachList(), and isConnectedTo().
const ROEdgeVector & ROEdge::getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
Parameters
[in] vClass The vClass for which to restrict the successors
Returns
The eligible following edges
Definition at line 280 of file ROEdge.cpp.
References ROLane::getEdge(), ROLane::getOutgoingLanes(), ROLane::getPermissions(), myClassesSuccessorMap, myFollowingEdges, myLanes, and SVC_IGNORING.
const RONode* ROEdge::getToJunction () const inline
Definition at line 424 of file ROEdge.h.
References myToJunction.
RONode* ROEdge::getToNode () const inline
Returns the node this edge ends at.
Returns
The node this edge ends at
Definition at line 222 of file ROEdge.h.
References myToNode.
Referenced by RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and getDistanceTo().
SUMOReal ROEdge::getTravelTime (const ROVehicle *const veh, SUMOReal time) const
Returns the travel time for this edge.
Parameters
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The travel time needed by the given vehicle to pass the edge at the given time
Definition at line 147 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), getMinimumTravelTime(), ValueTimeLine< T >::getSplitTime(), ROVehicle::getType(), ValueTimeLine< T >::getValue(), MAX2(), SUMOVTypeParameter::maxSpeed, MIN2(), myHaveTTWarned, Named::myID, myInterpolate, myLength, mySpeed, myTravelTimes, myUsingTTTimeLine, SUMOVTypeParameter::speedFactor, SUMOReal, toString(), and WRITE_WARNING.
Referenced by ROJTRRouter::compute(), getEmissionEffort(), ROMAAssignments::getPenalizedTT(), ROMAAssignments::getTravelTime(), and getTravelTimeStatic().
static SUMOReal ROEdge::getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static
Returns the travel time for the given edge.
Parameters
[in] edge The edge for which the travel time shall be retrieved
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The traveltime needed by the given vehicle to pass the edge at the given time
Definition at line 362 of file ROEdge.h.
References getTravelTime().
Referenced by computeRoutes().
EdgeType ROEdge::getType () const inline
Returns the type of the edge.
Returns
This edge's type
See Also
EdgeType
Definition at line 175 of file ROEdge.h.
References myType.
Referenced by RONet::addEdge(), ROMAAssignments::capacityConstraintFunction(), ROJTRRouter::compute(), getNumPredecessors(), and getNumSuccessors().
bool ROEdge::isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const
returns the information whether this edge is directly connected to the given
Parameters
[in] e The edge which may be connected
[in] vehicle The vehicle for which the connectivity is checked
Returns
Whether the given edge is a direct successor to this one
Definition at line 312 of file ROEdge.cpp.
References getSuccessors(), ROVehicle::getVClass(), and SVC_IGNORING.
bool ROEdge::isCrossing () const inline
return whether this edge is a pedestrian crossing
Definition at line 145 of file ROEdge.h.
References ET_CROSSING, and myType.
bool ROEdge::isInternal () const inline
return whether this edge is an internal edge
Definition at line 140 of file ROEdge.h.
References ET_INTERNAL, and myType.
bool ROEdge::isWalkingArea () const inline
return whether this edge is walking area
Definition at line 150 of file ROEdge.h.
References ET_WALKINGAREA, and myType.
ROEdge& ROEdge::operator= (const ROEdge & src) private
Invalidated assignment operator.
bool ROEdge::prohibits (const ROVehicle *const vehicle) const inline
Returns whether this edge prohibits the given vehicle to pass it.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle must not enter this edge
Definition at line 240 of file ROEdge.h.
References ROVehicle::getVClass(), and myCombinedPermissions.
Referenced by ROJTREdge::chooseNext(), and ROJTRRouter::compute().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void ROEdge::setJunctions (RONode * from, RONode * to) inline
Definition at line 429 of file ROEdge.h.
References myFromJunction, and myToJunction.
Referenced by RONetHandler::myEndElement().
static void ROEdge::setTimeLineOptions (bool useBoundariesOnOverrideTT, bool useBoundariesOnOverrideE, bool interpolate) inline static
Definition at line 406 of file ROEdge.h.
References myInterpolate, myUseBoundariesOnOverrideE, and myUseBoundariesOnOverrideTT.
Referenced by RODUAEdgeBuilder::RODUAEdgeBuilder(), and ROMAEdgeBuilder::ROMAEdgeBuilder().
void ROEdge::setType (ROEdge::EdgeType type)
Sets the type of te edge.
Parameters
[in] type The new type for the edge
Definition at line 225 of file ROEdge.cpp.
References myType.
Referenced by RONet::addDistrict(), loadJTRDefinitions(), ROJTRTurnDefLoader::myStartElement(), and RONetHandler::parseEdge().
Field Documentation
ROEdgeVector ROEdge::myApproachingEdges protected
List of edges that approached this edge.
Definition at line 495 of file ROEdge.h.
Referenced by addSuccessor(), getNumPredecessors(), and getPredecessors().
ClassesSuccesorMap ROEdge::myClassesSuccessorMap mutable protected
Definition at line 514 of file ROEdge.h.
Referenced by getSuccessors().
SVCPermissions ROEdge::myCombinedPermissions protected
The list of allowed vehicle classes combined across lanes.
Definition at line 504 of file ROEdge.h.
Referenced by addLane(), getPermissions(), and prohibits().
ROEdgeVector ROEdge::myEdges static protected
Definition at line 506 of file ROEdge.h.
Referenced by dictionary(), dictSize(), and ROEdge().
ValueTimeLine<SUMOReal> ROEdge::myEfforts mutable protected
Container storing passing time varying over time for the edge.
Definition at line 477 of file ROEdge.h.
Referenced by addEffort(), buildTimeLines(), and getStoredEffort().
ROEdgeVector ROEdge::myFollowingEdges protected
List of edges that may be approached from this edge.
Definition at line 492 of file ROEdge.h.
Referenced by addSuccessor(), allFollowersProhibit(), ROJTREdge::chooseNext(), getNumSuccessors(), getSuccessors(), and ROJTREdge::setTurnDefaults().
RONode* ROEdge::myFromJunction protected
the junctions for this edge
Definition at line 509 of file ROEdge.h.
Referenced by getFromJunction(), and setJunctions().
RONode* const ROEdge::myFromNode protected
The nodes this edge is connecting.
Definition at line 454 of file ROEdge.h.
Referenced by getFromNode().
bool ROEdge::myHaveEWarned = false static protected
Information whether the edge has reported missing weights.
Definition at line 487 of file ROEdge.h.
Referenced by getStoredEffort().
bool ROEdge::myHaveTTWarned = false static protected
Information whether the edge has reported missing weights.
Definition at line 489 of file ROEdge.h.
Referenced by getTravelTime().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), getStoredEffort(), getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const unsigned int ROEdge::myIndex protected
The index (numeric id) of the edge.
Definition at line 457 of file ROEdge.h.
Referenced by getNumericalID().
bool ROEdge::myInterpolate = false static protected
Information whether to interpolate at interval boundaries.
Definition at line 484 of file ROEdge.h.
Referenced by getStoredEffort(), getTravelTime(), and setTimeLineOptions().
std::vector<ROLane*> ROEdge::myLanes protected
This edge's lanes.
Definition at line 501 of file ROEdge.h.
Referenced by addLane(), getLaneNo(), getLanes(), getSuccessors(), and ~ROEdge().
SUMOReal ROEdge::myLength protected
The length of the edge.
Definition at line 466 of file ROEdge.h.
Referenced by addLane(), buildTimeLines(), getEffort(), getLength(), getMinimumTravelTime(), and getTravelTime().
const int ROEdge::myPriority protected
The edge priority (road class)
Definition at line 460 of file ROEdge.h.
Referenced by getPriority().
SUMOReal ROEdge::mySpeed protected
The maximum speed allowed on this edge.
Definition at line 463 of file ROEdge.h.
Referenced by addLane(), buildTimeLines(), getEffort(), getEmissionEffort(), getMinimumTravelTime(), getNoiseEffort(), getSpeed(), and getTravelTime().
RONode* ROEdge::myToJunction protected
Definition at line 510 of file ROEdge.h.
Referenced by getToJunction(), and setJunctions().
RONode* const * const ROEdge::myToNode protected
Definition at line 454 of file ROEdge.h.
Referenced by getToNode().
ValueTimeLine<SUMOReal> ROEdge::myTravelTimes mutable protected
Container storing passing time varying over time for the edge.
Definition at line 470 of file ROEdge.h.
Referenced by addTravelTime(), buildTimeLines(), getStoredEffort(), and getTravelTime().
EdgeType ROEdge::myType protected
The type of the edge.
Definition at line 498 of file ROEdge.h.
Referenced by getType(), isCrossing(), isInternal(), isWalkingArea(), and setType().
bool ROEdge::myUseBoundariesOnOverrideE = false static protected
Whether overriding weight boundaries shall be reported.
Definition at line 481 of file ROEdge.h.
Referenced by buildTimeLines(), and setTimeLineOptions().
bool ROEdge::myUseBoundariesOnOverrideTT = false static protected
Whether overriding weight boundaries shall be reported.
Definition at line 474 of file ROEdge.h.
Referenced by buildTimeLines(), and setTimeLineOptions().
bool ROEdge::myUsingETimeLine protected
Information whether the time line shall be used instead of the length value.
Definition at line 479 of file ROEdge.h.
Referenced by addEffort(), buildTimeLines(), and getStoredEffort().
bool ROEdge::myUsingTTTimeLine protected
Information whether the time line shall be used instead of the length value.
Definition at line 472 of file ROEdge.h.
Referenced by addTravelTime(), buildTimeLines(), and getTravelTime().
The documentation for this class was generated from the following files:
ROEdge.h
ROEdge.cpp