SUMO - Simulation of Urban MObility: GUILane Class Reference
GUILane Class Reference
Representation of a lane in the micro simulation (gui-version)
#include <GUILane.h>
Public Types
typedef std::vector< MSVehicle * > VehCont
Container for vehicles.
Public Member Functions
void addApproachingLane (MSLane *lane)
void addIncomingLane (MSLane *lane, MSLink *viaLink)
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool allowsVehicleClass (SUMOVehicleClass vclass) const
virtual bool appropriate (const MSVehicle *veh)
void clearParameter ()
Clears the parameter map.
void detectCollisions (SUMOTime timestep, const std::string &stage)
void drawBikeMarkings () const
bike lane markings on top of an intersection
void drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const
draw crossties for railroads or pedestrian crossings
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawMarkings (const GUIVisualizationSettings &s, SUMOReal scale) const
draw lane borders and white markings
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
bool empty () const
Returns true if there is not a single vehicle on the lane.
void enteredByLaneChange (MSVehicle *v)
SUMOReal firstWaitingTime () const
std::pair< MSVehicle *const,
SUMOReal > getCriticalLeader (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle &veh) const
Returns the most dangerous leader and the distance to him.
int getCrossingIndex () const
return the index of the link to the next crossing if this is walkingArea, else -1
MSEdge & getEdge () const
Returns the lane's edge.
SUMOReal getEdgeLaneNumber () const
MSVehicle * getFirstVehicle () const
std::pair< MSVehicle *const,
SUMOReal > getFollowerOnConsecutive (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const
return the follower with the largest missing rear gap among all predecessor lanes (within dist)
SUMOReal getHalfWidth () const
const std::string & getID () const
Returns the id.
const std::vector
< IncomingLaneInfo > & getIncomingLanes () const
LinkState getIncomingLinkState () const
get the state of the link from the logical predecessor to this lane
const MSEdge * getInternalFollower () const
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
MSVehicle * getLastVehicle () const
returns the last vehicle
std::pair< MSVehicle *const,
SUMOReal > getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle &veh, const std::vector< MSLane * > &bestLaneConts) const
Returns the immediate leader and the distance to him.
const MSLinkCont & getLinkCont () const
returns the container with all links !!!
SUMOReal getLoadedEdgeWeight () const
Returns the loaded weight (effort) for the edge of this lane.
MSLane * getLogicalPredecessorLane () const
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
SUMOReal getMissingRearGap (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const
return by how much further the leader must be inserted to avoid rear end collisions
std::vector< const MSLane * > getOutgoingLanes () const
get the list of outgoing lanes
MSLane * getParallelLane (int offset) const
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const PositionVector & getShape () const
const std::vector< SUMOReal > & getShapeLengths () const
const std::vector< SUMOReal > & getShapeRotations () const
SUMOReal getStoredEdgeTravelTime () const
Returns the stored traveltime for the edge of this lane.
GUILane (const std::string &id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, unsigned int numericalID, const PositionVector &shape, SUMOReal width, SVCPermissions permissions, unsigned int index)
Constructor.
bool isApproachedFrom (MSEdge *const edge)
bool isApproachedFrom (MSEdge *const edge, MSLane *const lane)
bool isEmpty () const
bool isLinkEnd (MSLinkCont::const_iterator &i) const
bool isLinkEnd (MSLinkCont::iterator &i)
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void leftByLaneChange (MSVehicle *v)
MSVehicle * removeVehicle (MSVehicle *remVehicle, MSMoveReminder::Notification notification, bool notify)
void setID (const std::string &newID)
resets the id
void setLength (SUMOReal val)
Sets a new length for the lane (used by TraCI only)
void setMaxSpeed (SUMOReal val)
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
void setPermissions (SVCPermissions permissions)
void visit (const TraCIServerAPI_Lane::StoringVisitor &cont) const
Callback for visiting the lane when traversing an RTree.
~GUILane ()
Destructor.
Access to vehicles
const VehCont & getVehiclesSecure () const
Returns the vehicles container; locks it for microsimulation.
void releaseVehicles () const
Allows to use the container for microsimulation again.
Vehicle movement (longitudinal)
void planMovements (const SUMOTime t)
bool executeMovements (SUMOTime t, std::vector< MSLane * > &into)
bool integrateNewVehicle (SUMOTime t)
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Additional initialisation
void addLink (MSLink *link)
Delayed initialization.
interaction with MSMoveReminder
virtual void addMoveReminder (MSMoveReminder *rem)
Add a move-reminder to move-reminder container.
const std::vector
< MSMoveReminder * > & getMoveReminders () const
Return the list of this lane's move reminders.
Vehicle insertion
bool insertVehicle (MSVehicle &v)
Tries to insert the given vehicle.
bool isInsertionSuccess (MSVehicle *vehicle, SUMOReal speed, SUMOReal pos, bool recheckNextLanes, MSMoveReminder::Notification notification)
Tries to insert the given vehicle with the given state (speed and pos)
bool checkFailure (MSVehicle *aVehicle, SUMOReal &speed, SUMOReal &dist, const SUMOReal nspeed, const bool patchSpeed, const std::string errorMsg) const
bool pWagGenericInsertion (MSVehicle &veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
bool pWagSimpleInsertion (MSVehicle &veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
bool maxSpeedGapInsertion (MSVehicle &veh, SUMOReal mspeed)
bool freeInsertion (MSVehicle &veh, SUMOReal speed, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
void forceVehicleInsertion (MSVehicle *veh, SUMOReal pos)
Inserts the given vehicle at the given position.
Handling vehicles lapping into lanes
SUMOReal setPartialOccupation (MSVehicle *v, SUMOReal leftVehicleLength)
Sets the information about a vehicle lapping into this lane.
void resetPartialOccupation (MSVehicle *v)
Removes the information about a vehicle lapping into this lane.
MSVehicle * getPartialOccupator () const
Returns the vehicle which laps into this lane.
SUMOReal getPartialOccupatorEnd () const
Returns the position of the in-lapping vehicle's end.
std::pair< MSVehicle *, SUMOReal > getLastVehicleInformation () const
Returns the last vehicle which is still on the lane.
Access to vehicles
unsigned int getVehicleNumber () const
Returns the number of vehicles on this lane.
Atomar value getter
size_t getNumericalID () const
Returns this lane's numerical id.
SUMOReal getLengthGeometryFactor () const
return shape.length() / myLength
SUMOReal interpolateLanePosToGeometryPos (SUMOReal lanePos) const
const Position geometryPositionAtOffset (SUMOReal offset) const
SUMOReal interpolateGeometryPosToLanePos (SUMOReal geometryPos) const
SUMOReal getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
SUMOReal getSpeedLimit () const
Returns the lane's maximum allowed speed.
SUMOReal getLength () const
Returns the lane's length.
SVCPermissions getPermissions () const
Returns the vehicle class permissions for this lane.
SUMOReal getWidth () const
Returns the lane's width.
Current state retrieval
SUMOReal getMeanSpeed () const
Returns the mean speed on this lane.
SUMOReal getWaitingSeconds () const
Returns the overall waiting time on this lane.
SUMOReal getBruttoOccupancy () const
Returns the brutto (including minGaps) occupancy of this lane during the last step.
SUMOReal getNettoOccupancy () const
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
SUMOReal getBruttoVehLenSum () const
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
SUMOReal getCO2Emissions () const
Returns the sum of last step CO2 emissions.
SUMOReal getCOEmissions () const
Returns the sum of last step CO emissions.
SUMOReal getPMxEmissions () const
Returns the sum of last step PMx emissions.
SUMOReal getNOxEmissions () const
Returns the sum of last step NOx emissions.
SUMOReal getHCEmissions () const
Returns the sum of last step HC emissions.
SUMOReal getFuelConsumption () const
Returns the sum of last step fuel consumption.
SUMOReal getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
State saving/loading
void saveState (OutputDevice &out)
Saves the state of this lane into the given stream.
void loadState (std::vector< std::string > &vehIDs, MSVehicleControl &vc)
Loads the state of this segment with the given parameters.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSLane *lane)
Static (sic!) container methods {.
static MSLane * dictionary (const std::string &id)
Returns the MSLane associated to the key id.
static size_t dictSize ()
Returns the number of stored lanes.
template<class RTREE >
static void fill (RTREE &into)
Fills the given RTree with lane instances.
static void insertIDs (std::vector< std::string > &into)
Adds the ids of all stored lanes into the given vector.
static MSLinkCont::const_iterator succLinkSec (const SUMOVehicle &veh, unsigned int nRouteSuccs, const MSLane &succLinkSource, const std::vector< MSLane * > &conts)
Data Fields
PositionVector myShape
The shape of the lane.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::map< std::string,
MSLane * > DictType
definition of the static dictionary type
Protected Member Functions
SUMOReal getMaximumBrakeDist () const
compute maximum braking distance on this lane
void handleCollision (SUMOTime timestep, const std::string &stage, MSVehicle *collider, MSVehicle *victim, const SUMOReal gap)
issue warning and add the vehicle to MSVehicleTransfer
virtual void incorporateVehicle (MSVehicle *veh, SUMOReal pos, SUMOReal speed, const MSLane::VehCont::iterator &at, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Inserts the vehicle into this lane, and informs it about entering the network.
void setPrefix (const std::string &prefix)
void swapAfterLaneChange (SUMOTime t)
moves myTmpVehicles int myVehicles after a lane change procedure
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::map< MSEdge
*, std::vector< MSLane * > > myApproachingLanes
SUMOReal myBruttoVehicleLengthSum
The current length of all vehicles on this lane, including their minGaps.
MSEdge *const myEdge
The lane's edge, for routing only.
std::string myID
The name of the object.
std::vector< IncomingLaneInfo > myIncomingLanes
MSVehicle * myInlappingVehicle
The vehicle which laps into this lane.
SUMOReal myInlappingVehicleEnd
End position of a vehicle which laps into this lane.
SUMOReal myLength
Lane length [m].
const SUMOReal myLengthGeometryFactor
MSLinkCont myLinks
MSLane * myLogicalPredecessorLane
SUMOReal myMaxSpeed
Lane-wide speedlimit [m/s].
SUMOReal myNettoVehicleLengthSum
The current length of all vehicles on this lane, excluding their minGaps.
size_t myNumericalID
Unique numerical ID (set on reading by netload)
SVCPermissions myPermissions
The vClass permissions for this lane.
VehCont myTmpVehicles
std::vector< MSVehicle * > myVehBuffer
VehCont myVehicles
The lane's vehicles. The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
const SUMOReal myWidth
Lane width [m].
Static Protected Attributes
static DictType myDict
Static dictionary to associate string-ids with objects.
Private Member Functions
void drawArrows () const
bool drawAsRailway (const GUIVisualizationSettings &s) const
whether to draw this lane as a railway
bool drawAsWaterway (const GUIVisualizationSettings &s) const
whether to draw this lane as a waterway
void drawLane2LaneConnections () const
void drawLinkNo () const
helper methods
void drawLinkRule (const GUIVisualizationSettings &s, const GUINet &net, MSLink *link, const PositionVector &shape, SUMOReal x1, SUMOReal x2) const
void drawLinkRules (const GUIVisualizationSettings &s, const GUINet &net) const
void drawTextAtEnd (const std::string &text, const PositionVector &shape, SUMOReal x) const
void drawTLSLinkNo (const GUINet &net) const
SUMOReal getColorValue (size_t activeScheme) const
gets the color value according to the current scheme index
SUMOReal getScaleValue (size_t activeScheme) const
gets the scaling value according to the current scheme index
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
bool setFunctionalColor (size_t activeScheme) const
sets the color according to the current scheme index and some lane function
bool setMultiColor (const GUIColorer &c) const
sets multiple colors according to the current scheme index and some lane function
Private Attributes
SUMOReal myHalfLaneWidth
Half of lane width, for speed-up.
unsigned int myIndex
The lane index.
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
SUMOReal myQuarterLaneWidth
Quarter of lane width, for speed-up.
std::vector< RGBColor > myShapeColors
The color of the shape parts (cached)
std::vector< SUMOReal > myShapeLengths
The lengths of the shape parts.
std::vector< SUMOReal > myShapeRotations
The rotations of the shape parts.
Detailed Description
Representation of a lane in the micro simulation (gui-version)
An extended MSLane. A mechanism to avoid concurrent visualisation and simulation what may cause problems when vehicles disappear is implemented using a mutex.
Definition at line 70 of file GUILane.h.
Member Typedef Documentation
typedef std::map< std::string, MSLane* > MSLane::DictType protected inherited
definition of the static dictionary type
Definition at line 861 of file MSLane.h.
typedef std::vector< MSVehicle* > MSLane::VehCont inherited
Container for vehicles.
Definition at line 88 of file MSLane.h.
Constructor & Destructor Documentation
GUILane::GUILane (const std::string & id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, unsigned int numericalID, const PositionVector & shape, SUMOReal width, SVCPermissions permissions, unsigned int index)
Constructor.
Parameters
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] edge The edge this lane belongs to
[in] numericalID The numerical id of the lane
[in] shape The shape of the lane
[in] width The width of the lane
[in] permissions Encoding of vehicle classes that may drive on this lane
See Also
SUMOVehicleClass
MSLane
Definition at line 71 of file GUILane.cpp.
References Position::distanceTo2D(), myHalfLaneWidth, myIndex, myQuarterLaneWidth, MSLane::myShape, myShapeColors, myShapeLengths, myShapeRotations, MSLane::myWidth, RAD2DEG, SUMOReal, Position::x(), and Position::y().
GUILane::~GUILane ()
Destructor.
Definition at line 94 of file GUILane.cpp.
References MFXMutex::locked(), myLock, and MFXMutex::unlock().
Member Function Documentation
void MSLane::addApproachingLane (MSLane * lane) inherited
Definition at line 1086 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), Named::getID(), MSEdge::getPurpose(), MSLane::myApproachingLanes, and WRITE_WARNING.
Referenced by NLHandler::addConnection().
void MSLane::addIncomingLane (MSLane * lane, MSLink * viaLink) inherited
Definition at line 1076 of file MSLane.cpp.
References MSLane::getLength(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, MSLane::myIncomingLanes, and MSLane::IncomingLaneInfo::viaLink.
Referenced by NLHandler::addConnection().
void MSLane::addLink (MSLink * link) inherited
Delayed initialization.
Not all lane-members are known at the time the lane is born, above all the pointers to other lanes, so we have to add them later.
Parameters
[in] link An outgoing link
Definition at line 107 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by NLHandler::addConnection().
void MSLane::addMoveReminder (MSMoveReminder * rem) virtual inherited
Add a move-reminder to move-reminder container.
The move reminder will not be deleted by the lane.
Parameters
[in] rem The move reminder to add
Definition at line 114 of file MSLane.cpp.
References MSLane::myMoveReminders, and MSLane::myVehicles.
Referenced by MSMoveReminder::MSMoveReminder().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
bool MSLane::allowsVehicleClass (SUMOVehicleClass vclass) const inline inherited
Definition at line 571 of file MSLane.h.
References MSLane::myPermissions.
Referenced by MSVehicle::addStop(), MSPModel_NonInteracting::PState::getPosition(), and MSVehicle::updateBestLanes().
bool MSLane::appropriate (const MSVehicle * veh) virtual inherited
Returns the information whether this lane may be used to continue the current route
Definition at line 910 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getLaneIndex(), MSEdge::getPurpose(), MSLane::myEdge, MSLane::myLinks, MSBaseVehicle::succEdge(), and MSLane::succLinkSec().
Referenced by MSLane::executeMovements().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and getPopUpMenu().
bool MSLane::checkFailure (MSVehicle * aVehicle, SUMOReal & speed, SUMOReal & dist, const SUMOReal nspeed, const bool patchSpeed, const std::string errorMsg) const inherited
Definition at line 428 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSInsertionControl::descheduleDeparture(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MIN2(), and WRITE_ERROR.
Referenced by MSLane::isInsertionSuccess().
void MSLane::clear () static inherited
Clears the dictionary.
Definition at line 875 of file MSLane.cpp.
References MSLane::myDict.
Referenced by MSNet::clearAll().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void GUILane::detectCollisions (SUMOTime timestep, const std::string & stage) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 162 of file GUILane.cpp.
References MSLane::detectCollisions(), and myLock.
bool MSLane::dictionary (const std::string & id, MSLane * lane) static inherited
Static (sic!) container methods {.
Inserts a MSLane into the static dictionary
Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Parameters
[in] id The id of the lane
[in] lane The lane itself
Returns
Whether the lane was added
Todo:
make non-static
why is the id given? The lane is named
Definition at line 852 of file MSLane.cpp.
References MSLane::myDict.
Referenced by NLHandler::addConnection(), NLHandler::addLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), NLTriggerBuilder::getLane(), NLDetectorBuilder::getLaneChecking(), NLShapeHandler::getLanePos(), TraCIServerAPI_Lane::getShape(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLHandler::parseLanes(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_Lane::processSet().
MSLane * MSLane::dictionary (const std::string & id) static inherited
Returns the MSLane associated to the key id.
The lane is returned if exists, otherwise 0 is returned.
Parameters
[in] id The id of the lane
Returns
The lane
Definition at line 864 of file MSLane.cpp.
References MSLane::myDict.
static size_t MSLane::dictSize () inline static inherited
Returns the number of stored lanes.
Returns
The number of stored lanes
Definition at line 498 of file MSLane.h.
References MSLane::myDict.
void GUILane::drawArrows () const private
Definition at line 326 of file GUILane.cpp.
References GLHelper::drawBoxLine(), GLHelper::drawTriangleAtEnd(), getShape(), LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, LINKSTATE_TL_OFF_NOSIGNAL, MSLane::myLinks, MSLane::myWidth, RAD2DEG, SUMO_const_laneWidth, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
bool GUILane::drawAsRailway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a railway
Definition at line 955 of file GUILane.cpp.
References isRailway(), MSLane::myPermissions, and GUIVisualizationSettings::showRails.
Referenced by drawGL(), and drawLinkRule().
bool GUILane::drawAsWaterway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a waterway
Definition at line 961 of file GUILane.cpp.
References isWaterway(), MSLane::myPermissions, and GUIVisualizationSettings::showRails.
Referenced by drawGL(), and drawLinkRule().
void GUILane::drawBikeMarkings () const
bike lane markings on top of an intersection
Definition at line 592 of file GUILane.cpp.
References getShape(), GLO_JUNCTION, myHalfLaneWidth, myShapeLengths, myShapeRotations, SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUILane::drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const
draw crossties for railroads or pedestrian crossings
Definition at line 617 of file GUILane.cpp.
References getShape(), myShapeLengths, myShapeRotations, and SUMOReal.
Referenced by drawGL().
void GUILane::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See Also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 406 of file GUILane.cpp.
References GLHelper::debugVertices(), drawArrows(), drawAsRailway(), drawAsWaterway(), drawBikeMarkings(), GLHelper::drawBoxLines(), drawCrossties(), GLHelper::drawFilledPoly(), GLHelper::drawFilledPolyTesselated(), GUIVehicle::drawGL(), drawLane2LaneConnections(), GLHelper::drawLine(), GUIVisualizationSettings::drawLinkJunctionIndex, drawLinkNo(), drawLinkRules(), GUIVisualizationSettings::drawLinkTLIndex, drawMarkings(), drawTLSLinkNo(), MSEdge::EDGEFUNCTION_CROSSING, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_WALKINGAREA, GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), MSLinkContHelper::getConnectingLink(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), GUINet::getLinkTLIndex(), MSLane::getLogicalPredecessorLane(), MSVehicleTransfer::getParkingVehicles(), MSEdge::getPurpose(), getScaleValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIGlObject::getType(), getVehiclesSecure(), MSLane::getWidth(), GLO_JUNCTION, MSGlobals::gUseMesoSim, MSLink::havePriority(), isWaterway(), GUIVisualizationSettings::laneScaler, GUIVisualizationSettings::laneWidthExaggeration, MAX2(), GUIVisualizationSizeSettings::minSize, MSLane::myEdge, myHalfLaneWidth, MSLane::myPermissions, myQuarterLaneWidth, MSLane::myShape, myShapeColors, myShapeLengths, myShapeRotations, releaseVehicles(), GUIVisualizationSettings::scale, setColor(), GUIVisualizationSettings::showLane2Lane, GUIVisualizationSettings::showLinkDecals, SUMOReal, SVC_BICYCLE, SVC_PEDESTRIAN, and GUIVisualizationSettings::vehicleSize.
Referenced by GUIEdge::drawGL().
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUILane::drawLane2LaneConnections () const private
Definition at line 387 of file GUILane.cpp.
References GLHelper::drawTriangleAtEnd(), getLinkColor(), getShape(), MSLane::getShape(), MSLane::myLinks, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
void GUILane::drawLinkNo () const private
helper methods
Definition at line 170 of file GUILane.cpp.
References drawTextAtEnd(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLink::getIndex(), MSLane::getLogicalPredecessorLane(), getShape(), myHalfLaneWidth, MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), SUMOReal, and toString().
Referenced by drawGL().
void GUILane::drawLinkRule (const GUIVisualizationSettings & s, const GUINet & net, MSLink * link, const PositionVector & shape, SUMOReal x1, SUMOReal x2) const private
Definition at line 270 of file GUILane.cpp.
References drawAsRailway(), drawAsWaterway(), GUIGlObject::getGlID(), getLinkColor(), GUINet::getLinkTLID(), MSLink::getState(), LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, myHalfLaneWidth, RAD2DEG, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
Referenced by drawLinkRules().
void GUILane::drawLinkRules (const GUIVisualizationSettings & s, const GUINet & net) const private
Definition at line 243 of file GUILane.cpp.
References drawLinkRule(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLane::getLogicalPredecessorLane(), getShape(), MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), and SUMOReal.
Referenced by drawGL().
void GUILane::drawMarkings (const GUIVisualizationSettings & s, SUMOReal scale) const
draw lane borders and white markings
Definition at line 553 of file GUILane.cpp.
References GLHelper::drawBoxLines(), getHalfWidth(), MSEdge::getLanes(), getShape(), getShapeLengths(), getShapeRotations(), GLO_EDGE, MSGlobals::gUseMesoSim, MIN2(), MSLane::myEdge, myHalfLaneWidth, myIndex, MSLane::myPermissions, myQuarterLaneWidth, myShapeLengths, myShapeRotations, setColor(), SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIEdge::drawGL().
void GUILane::drawTextAtEnd (const std::string & text, const PositionVector & shape, SUMOReal x) const private
Definition at line 230 of file GUILane.cpp.
References GLHelper::drawText(), RAD2DEG, SUMOReal, Position::x(), and Position::y().
Referenced by drawLinkNo(), and drawTLSLinkNo().
void GUILane::drawTLSLinkNo (const GUINet & net) const private
Definition at line 197 of file GUILane.cpp.
References drawTextAtEnd(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), GUINet::getLinkTLIndex(), MSLane::getLogicalPredecessorLane(), getShape(), myHalfLaneWidth, MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), SUMOReal, and toString().
Referenced by drawGL().
bool MSLane::empty () const inline inherited
Returns true if there is not a single vehicle on the lane.
Definition at line 437 of file MSLane.h.
References MSLane::myVehBuffer, and MSLane::myVehicles.
Referenced by MSQueueExport::writeLane().
void MSLane::enteredByLaneChange (MSVehicle * v) inherited
Definition at line 1414 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, and MSLane::myNettoVehicleLengthSum.
Referenced by MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool GUILane::executeMovements (SUMOTime t, std::vector< MSLane * > & into) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 134 of file GUILane.cpp.
References MSLane::executeMovements(), and myLock.
template<class RTREE > template void MSLane::fill< LANE_RTREE_QUAL > (RTREE & into) static inherited
Fills the given RTree with lane instances.
Parameters
in,filled] into The RTree to fill
See Also
TraCILaneRTree
Definition at line 892 of file MSLane.cpp.
References PositionVector::getBoxBoundary(), MSLane::getShape(), Boundary::grow(), MSLane::myDict, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::collectObjectsInRange(), and MSNet::getLanesRTree().
SUMOReal GUILane::firstWaitingTime () const
Definition at line 717 of file GUILane.cpp.
References MSLane::myVehicles.
Referenced by getColorValue(), and getScaleValue().
void MSLane::forceVehicleInsertion (MSVehicle * veh, SUMOReal pos) inherited
Inserts the given vehicle at the given position.
No checks are done, vehicle insertion using this method may generate collisions (possibly delayed).
Parameters
[in] veh The vehicle to insert
[in] pos The position at which the vehicle shall be inserted
Definition at line 626 of file MSLane.cpp.
References MSVehicle::getSpeed(), MSLane::incorporateVehicle(), MSLane::myVehicles, and MSVehicle::updateBestLanes().
Referenced by TraCIServerAPI_Vehicle::processSet().
bool MSLane::freeInsertion (MSVehicle & veh, SUMOReal speed, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) inherited
Tries to insert the given vehicle on any place.
Parameters
[in] veh The vehicle to insert
[in] speed The maximum insertion speed
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
Definition at line 275 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getMissingRearGap(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), MSLane::isInsertionSuccess(), MIN2(), MSLane::myLength, MSLane::myVehicles, MSMoveReminder::NOTIFICATION_TELEPORT, POSITION_EPS, and SUMOReal.
Referenced by MSVehicleTransfer::checkInsertions(), and MSLane::insertVehicle().
const Position MSLane::geometryPositionAtOffset (SUMOReal offset) const inline inherited
Definition at line 340 of file MSLane.h.
References MSLane::interpolateLanePosToGeometryPos(), MSLane::myShape, and PositionVector::positionAtOffset().
Referenced by GUIE3Collector::MyWrapper::buildDefinition(), GUIVehicle::drawGL(), MSVehicle::getAngle(), NLShapeHandler::getLanePos(), MSVehicle::getPosition(), GUIInstantInductLoop::MyWrapper::MyWrapper(), and GUIInductLoop::MyWrapper::MyWrapper().
SUMOReal MSLane::getBruttoOccupancy () const inherited
Returns the brutto (including minGaps) occupancy of this lane during the last step.
Returns
The occupancy during the last step
Definition at line 1432 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, MSLane::myInlappingVehicle, MSLane::myInlappingVehicleEnd, MSLane::myLength, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), getScaleValue(), and MSEdge::insertVehicle().
SUMOReal MSLane::getBruttoVehLenSum () const inherited
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
Returns
The sum of vehicle lengths of vehicles in the last step
Definition at line 1462 of file MSLane.cpp.
References MSLane::myBruttoVehicleLengthSum.
Referenced by MSVehicle::checkRewindLinkLanes().
Boundary GUILane::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See Also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 684 of file GUILane.cpp.
References Boundary::add(), Boundary::grow(), and MSLane::myShape.
SUMOReal MSLane::getCO2Emissions () const inherited
Returns the sum of last step CO2 emissions.
Returns
CO2 emissions of vehicles on this lane during the last step
Definition at line 1497 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getCOEmissions () const inherited
Returns the sum of last step CO emissions.
Returns
CO emissions of vehicles on this lane during the last step
Definition at line 1509 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal GUILane::getColorValue (size_t activeScheme) const private
gets the color value according to the current scheme index
Definition at line 800 of file GUILane.cpp.
References firstWaitingTime(), MSLane::getBruttoOccupancy(), MSLane::getCO2Emissions(), MSLane::getCOEmissions(), getEdgeLaneNumber(), MSLane::getFuelConsumption(), GUIGlObject::getGlID(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), MSNet::getInstance(), MSLane::getLength(), getLoadedEdgeWeight(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getNOxEmissions(), MSLane::getPMxEmissions(), MSEdge::getPriority(), getShape(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), GUIGlObject::getType(), MSNet::getWeightsStorage(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSLane::myLength, MSLane::myLengthGeometryFactor, MSLane::myMaxSpeed, MSLane::myPermissions, MSEdgeWeightsStorage::retrieveExistingTravelTime(), SUMOReal, SVC_BICYCLE, SVC_PEDESTRIAN, and SVC_SHIP.
Referenced by setColor().
std::pair< MSVehicle *const, SUMOReal > MSLane::getCriticalLeader (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle & veh) const inherited
Returns the most dangerous leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the ego vehicle will pass it. If so, the subsequent lane is investigated. Check all lanes up to the stopping distance of ego. Return the leader vehicle (and the gap) which puts the biggest speed constraint on ego.
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The (ego) vehicle for which the information shall be computed
Returns
Definition at line 1278 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSLane::getLastVehicle(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), MSLane::isLinkEnd(), max, MAX2(), NUMERICAL_EPS, MSLane::succLinkSec(), SUMOReal, and TIME2STEPS.
Referenced by MSLaneChanger::checkChange().
int MSLane::getCrossingIndex () const inherited
return the index of the link to the next crossing if this is walkingArea, else -1
Definition at line 1421 of file MSLane.cpp.
References MSLane::myLinks.
MSEdge& MSLane::getEdge () const inline inherited
Returns the lane's edge.
Returns
This lane's edge
Definition at line 455 of file MSLane.h.
References MSLane::myEdge.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), TraCIServerAPI_Lane::StoringVisitor::add(), MSLane::addApproachingLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), NLDetectorBuilder::buildInductLoop(), MSVehicle::checkRewindLinkLanes(), MSEdge::closeBuilding(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSLane::executeMovements(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSDevice_Tripinfo::generateOutput(), MSVehicle::getBestLanesContinuation(), MSVehicle::getDistanceToPosition(), MSVehicle::getLaneIndex(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLogicalPredecessorLane(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSVehicle::getPosition(), MSVehicle::influenceChangeDecision(), MSRailSignal::init(), MSLane::isInsertionSuccess(), MSLink::lastWasContMajor(), MSPModel_Striping::moveInDirection(), MSLane::edge_finder::operator()(), NLTriggerBuilder::parseAndBuildCalibrator(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Lane::processSet(), MSPModel_Striping::PState::PState(), MSVehicle::resumeFromStopping(), MSLink::setRequestInformation(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMOReal GUILane::getEdgeLaneNumber () const
Definition at line 723 of file GUILane.cpp.
References MSEdge::getLanes(), MSLane::myEdge, and SUMOReal.
Referenced by getColorValue(), and getScaleValue().
MSVehicle * MSLane::getFirstVehicle () const inherited
Definition at line 969 of file MSLane.cpp.
References MSLane::myVehicles.
Referenced by MSLane::getFollowerOnConsecutive().
std::pair< MSVehicle *const, SUMOReal > MSLane::getFollowerOnConsecutive (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const inherited
return the follower with the largest missing rear gap among all predecessor lanes (within dist)
Definition at line 1149 of file MSLane.cpp.
References MSLane::getFirstVehicle(), MSLane::getIncomingLanes(), MSLane::getLength(), MSLane::getMaximumBrakeDist(), MSVehicleType::getMinGap(), MSLane::getPartialOccupator(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, max, MAX2(), MSLane::myIncomingLanes, SUMOReal, and MSLane::IncomingLaneInfo::viaLink.
Referenced by MSLane::getMissingRearGap().
SUMOReal MSLane::getFuelConsumption () const inherited
Returns the sum of last step fuel consumption.
Returns
fuel consumption of vehicles on this lane during the last step
Definition at line 1557 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), drawLinkRule(), GUIJunctionWrapper::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), getColorValue(), GUIVehicle::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
SUMOReal GUILane::getHalfWidth () const inline
Definition at line 206 of file GUILane.h.
References myHalfLaneWidth.
Referenced by drawMarkings().
SUMOReal MSLane::getHarmonoise_NoiseEmissions () const inherited
Returns the sum of last step noise emissions.
Returns
noise emissions of vehicles on this lane during the last step
Definition at line 1569 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), HelpersHarmonoise::sum(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getHCEmissions () const inherited
Returns the sum of last step HC emissions.
Returns
HC emissions of vehicles on this lane during the last step
Definition at line 1545 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const std::vector<IncomingLaneInfo>& MSLane::getIncomingLanes () const inline inherited
Definition at line 584 of file MSLane.h.
References MSLane::myIncomingLanes.
Referenced by MSLink::getApproachingLane(), MSLane::getFollowerOnConsecutive(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), and MSLink::setRequestInformation().
LinkState MSLane::getIncomingLinkState () const inherited
get the state of the link from the logical predecessor to this lane
Definition at line 1385 of file MSLane.cpp.
References MSLinkContHelper::getConnectingLink(), MSLane::getLogicalPredecessorLane(), MSLink::getState(), and LINKSTATE_DEADEND.
const MSEdge * MSLane::getInternalFollower () const inherited
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
Returns
This lane's follower
Definition at line 841 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::getPurpose(), MSEdge::getSuccessors(), and MSLane::myEdge.
Referenced by MSVehicle::getRerouteOrigin(), and MSVehicle::updateBestLanes().
MSVehicle * MSLane::getLastVehicle () const inherited
returns the last vehicle
Definition at line 960 of file MSLane.cpp.
References MSLane::myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), MSLane::isInsertionSuccess(), and MSLink::maybeOccupied().
std::pair< MSVehicle *, SUMOReal > MSLane::getLastVehicleInformation () const inherited
Returns the last vehicle which is still on the lane.
The information about the last vehicle in this lane's que is returned. If there is no such vehicle, the information about the vehicle which laps into this lane is returned. If there is no such vehicle, the first returned member is 0.
Returns
Information about the last vehicle and it's back position
Definition at line 651 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLane::myInlappingVehicle, MSLane::myInlappingVehicleEnd, MSLane::myVehicles, and SUMOReal.
Referenced by MSVehicle::planMoveInternal().
std::pair< MSVehicle *const, SUMOReal > MSLane::getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle & veh, const std::vector< MSLane * > & bestLaneConts) const inherited
Returns the immediate leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the vehicle will pass it. If so, the subsequent lane is investigated. If a vehicle (leader) is found, it is returned, together with the length of the investigated lanes until this vehicle's end, including the already seen place (seen).
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Todo:
: There are some oddities:
what about crossing a link at red, or if a link is closed? Has a following vehicle to be regarded or not?
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The vehicle for which the information shall be computed
[in] bestLaneConts The lanes the vehicle will use in future
Returns
Definition at line 1215 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSLane::getLastVehicle(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLane::isLinkEnd(), MAX2(), NUMERICAL_EPS, MSLane::succLinkSec(), and TIME2STEPS.
Referenced by MSVehicle::getLeader(), MSLane::pWagGenericInsertion(), and MSLane::pWagSimpleInsertion().
SUMOReal MSLane::getLength () const inline inherited
Returns the lane's length.
Returns
This lane's length
Definition at line 370 of file MSLane.h.
References MSLane::myLength.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), NLHandler::addConnection(), MSLane::addIncomingLane(), MSVehicle::addStop(), GUI_E2_ZS_CollectorOverLanes::buildCollector(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NLDetectorBuilder::buildInductLoop(), MSVehicle::checkRewindLinkLanes(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUIVehicle::drawAction_drawRailCarriages(), MSVehicle::executeMove(), MSLane::executeMovements(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSVehicle::fixPosition(), MSLane::freeInsertion(), getColorValue(), MSLane::getCriticalLeader(), MSVehicle::getDistanceToPosition(), MSLane::getFollowerOnConsecutive(), TraCIServerAPI_Simulation::getLaneChecking(), NLShapeHandler::getLanePos(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSPModel_Striping::getNextLane(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), MSVehicle::getRerouteOrigin(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpaceTillLastStanding(), MSActuatedTrafficLightLogic::init(), MS_E2_ZS_CollectorOverLanes::init(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSLane::maxSpeedGapInsertion(), MSLink::maybeOccupied(), MSPModel_Striping::moveInDirectionOnLane(), NLTriggerBuilder::parseAndBuildBusStop(), NLTriggerBuilder::parseAndBuildContainerStop(), MSVehicle::planMoveInternal(), TraCIServerAPI_Lane::processGet(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), GUIVehicle::selectBlockingFoes(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData::writeEdge(), and MSQueueExport::writeLane().
SUMOReal MSLane::getLengthGeometryFactor () const inline inherited
return shape.length() / myLength
Definition at line 328 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
const MSLinkCont & MSLane::getLinkCont () const inherited
returns the container with all links !!!
Definition at line 1026 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLink::getApproachingLane(), MSVehicle::getBestLanesContinuation(), MSLinkContHelper::getConnectingLink(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), MSRightOfWayJunction::postloadInit(), TraCIServerAPI_Lane::processGet(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMOReal GUILane::getLoadedEdgeWeight () const
Returns the loaded weight (effort) for the edge of this lane.
Definition at line 742 of file GUILane.cpp.
References MSNet::getInstance(), MSNet::getWeightsStorage(), MSEdgeWeightsStorage::knowsEffort(), MSLane::myEdge, MSEdgeWeightsStorage::retrieveExistingEffort(), STEPS2TIME, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), and getScaleValue().
MSLane * MSLane::getLogicalPredecessorLane () const inherited
Definition at line 1357 of file MSLane.cpp.
References MSLane::getEdge(), MSEdge::getIncomingEdges(), MSLane::myEdge, MSLane::myIncomingLanes, and MSLane::myLogicalPredecessorLane.
Referenced by MSEdge::changeLanes(), drawGL(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSLane::getIncomingLinkState(), MSPModel_Striping::getNextLane(), MSLink::lastWasContMajor(), MSVehicle::planMoveInternal(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), and TraCIServerAPI_Vehicle::vtdMap().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), TraCIServerAPI_TLS::processGet(), PCPolyContainer::save(), ROVehicle::saveAllAsXML(), SUMOVTypeParameter::write(), and SUMO::Polygon::writeXML().
SUMOReal MSLane::getMaximumBrakeDist () const protected inherited
compute maximum braking distance on this lane
Definition at line 1140 of file MSLane.cpp.
References MSNet::getInstance(), MSVehicleControl::getMaxSpeedFactor(), MSVehicleControl::getMinDeceleration(), MSLane::getSpeedLimit(), MSNet::getVehicleControl(), and SUMOReal.
Referenced by MSLane::getFollowerOnConsecutive().
SUMOReal MSLane::getMeanSpeed () const inherited
Returns the mean speed on this lane.
Returns
The average speed of vehicles during the last step; default speed if no vehicle was on this lane
Definition at line 1481 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::myMaxSpeed, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
SUMOReal MSLane::getMissingRearGap (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const inherited
return by how much further the leader must be inserted to avoid rear end collisions
Definition at line 1124 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), MSLane::getFollowerOnConsecutive(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), and SUMOReal.
Referenced by MSLane::freeInsertion(), and MSLane::isInsertionSuccess().
const std::vector< MSMoveReminder* >& MSLane::getMoveReminders () const inline inherited
Return the list of this lane's move reminders.
Returns
Previously added move reminder
Definition at line 150 of file MSLane.h.
References MSLane::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::enterLaneAtInsertion(), and MSVehicle::enterLaneAtLaneChange().
SUMOReal MSLane::getNettoOccupancy () const inherited
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
Returns
The occupancy during the last step
Definition at line 1447 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSLane::myInlappingVehicle, MSLane::myInlappingVehicleEnd, MSLane::myLength, MSLane::myNettoVehicleLengthSum, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getNOxEmissions () const inherited
Returns the sum of last step NOx emissions.
Returns
NOx emissions of vehicles on this lane during the last step
Definition at line 1533 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
size_t MSLane::getNumericalID () const inline inherited
Returns this lane's numerical id.
Returns
This lane's numerical id
Definition at line 315 of file MSLane.h.
References MSLane::myNumericalID.
Referenced by MSPModel_Striping::lane_by_numid_sorter::operator()(), and MSPModel_Striping::walkingarea_path_sorter::operator()().
std::vector< const MSLane * > MSLane::getOutgoingLanes () const inherited
get the list of outgoing lanes
Definition at line 1396 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSRailSignal::init().
MSLane * MSLane::getParallelLane (int offset) const inherited
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
Parameters
[in] offset The offset of the result lane
Definition at line 1070 of file MSLane.cpp.
References MSLane::myEdge, and MSEdge::parallelLane().
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
GUIParameterTableWindow * GUILane::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See Also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 661 of file GUILane.cpp.
References GUIParameterTableWindow::closeBuilding(), MSLane::getBruttoOccupancy(), MSEdge::getEdgeType(), getLoadedEdgeWeight(), MSEdge::getPriority(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), MSEdge::getStreetName(), getVehicleClassNames(), GUIParameterTableWindow::mkItem(), MSLane::myEdge, MSLane::myLength, MSLane::myPermissions, and MSLane::myWidth.
MSVehicle* MSLane::getPartialOccupator () const inline inherited
Returns the vehicle which laps into this lane.
Returns
The vehicle which laps into this lane, 0 if there is no such
Definition at line 253 of file MSLane.h.
References MSLane::myInlappingVehicle.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollowerOnConsecutive(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealLeader(), MSLaneChanger::getRealThisLeader(), MSLane::isInsertionSuccess(), MSLane::maxSpeedGapInsertion(), MSLink::maybeOccupied(), MSE2Collector::by_vehicle_position_sorter::operator()(), MSVehicle::planMoveInternal(), and MSLane::planMovements().
SUMOReal MSLane::getPartialOccupatorEnd () const inline inherited
Returns the position of the in-lapping vehicle's end.
Returns
Information about how far the vehicle laps into this lane
Definition at line 261 of file MSLane.h.
References MSLane::myInlappingVehicleEnd.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealLeader(), MSLaneChanger::getRealThisLeader(), MSLane::isInsertionSuccess(), MSLane::maxSpeedGapInsertion(), MSLink::maybeOccupied(), and MSVehicle::planMoveInternal().
SVCPermissions MSLane::getPermissions () const inline inherited
Returns the vehicle class permissions for this lane.
Returns
This lane's allowed vehicle classes
Definition at line 378 of file MSLane.h.
References MSLane::myPermissions.
Referenced by GUIApplicationWindow::onCmdEditChosen(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getPMxEmissions () const inherited
Returns the sum of last step PMx emissions.
Returns
PMx emissions of vehicles on this lane during the last step
Definition at line 1521 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
GUIGLObjectPopupMenu * GUILane::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See Also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 641 of file GUILane.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUISUMOAbstractView::getPositionInformation(), MSLane::interpolateGeometryPosToLanePos(), MSLane::myShape, PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), SUMOReal, toString(), and Position::z().
SUMOReal GUILane::getScaleValue (size_t activeScheme) const private
gets the scaling value according to the current scheme index
Definition at line 888 of file GUILane.cpp.
References firstWaitingTime(), MSLane::getBruttoOccupancy(), MSLane::getCO2Emissions(), MSLane::getCOEmissions(), getEdgeLaneNumber(), MSLane::getFuelConsumption(), GUIGlObject::getGlID(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), MSNet::getInstance(), getLoadedEdgeWeight(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getNOxEmissions(), MSLane::getPMxEmissions(), MSEdge::getPriority(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), GUIGlObject::getType(), MSNet::getWeightsStorage(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSLane::myLength, MSLane::myLengthGeometryFactor, MSLane::myMaxSpeed, MSEdgeWeightsStorage::retrieveExistingTravelTime(), and SUMOReal.
Referenced by drawGL().
const PositionVector & GUILane::getShape () const
Definition at line 699 of file GUILane.cpp.
References MSLane::myShape.
Referenced by drawArrows(), drawBikeMarkings(), drawCrossties(), GUIEdge::drawGL(), drawLane2LaneConnections(), drawLinkNo(), drawLinkRules(), drawMarkings(), GUIVehicle::drawRouteHelper(), drawTLSLinkNo(), and getColorValue().
const std::vector< SUMOReal > & GUILane::getShapeLengths () const
Definition at line 711 of file GUILane.cpp.
References myShapeLengths.
Referenced by drawMarkings(), and GUIVehicle::drawRouteHelper().
const std::vector< SUMOReal > & GUILane::getShapeRotations () const
Definition at line 705 of file GUILane.cpp.
References myShapeRotations.
Referenced by drawMarkings(), and GUIVehicle::drawRouteHelper().
SUMOReal MSLane::getSpeedLimit () const inline inherited
Returns the lane's maximum allowed speed.
Returns
This lane's maximum allowed speed
Definition at line 362 of file MSLane.h.
References MSLane::myMaxSpeed.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSVehicleTransfer::checkInsertions(), MSAbstractLaneChangeModel::congested(), MSLane::executeMovements(), getColorValue(), MSLane::getMaximumBrakeDist(), getParameterWindow(), getScaleValue(), MSActuatedTrafficLightLogic::init(), TraCIServerAPI_Lane::processGet(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData::writeEdge(), and MSFullExport::writeLane().
SUMOReal GUILane::getStoredEdgeTravelTime () const
Returns the stored traveltime for the edge of this lane.
Definition at line 729 of file GUILane.cpp.
References MSNet::getInstance(), MSNet::getWeightsStorage(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSEdgeWeightsStorage::retrieveExistingTravelTime(), STEPS2TIME, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), and getScaleValue().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUIJunctionWrapper::getColorValue(), getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
SUMOReal MSLane::getVehicleMaxSpeed (const SUMOVehicle *const veh) const inline inherited
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
Parameters
[in] The vehicle to return the adapted speed limit for
Returns
This lane's resulting max. speed
Definition at line 354 of file MSLane.h.
References SUMOVehicle::getChosenSpeedFactor(), and MSLane::myMaxSpeed.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSCFModel_IDM::desiredSpeed(), MSVehicle::estimateLeaveSpeed(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::insertVehicle(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::setBlinkerInformation(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
unsigned int MSLane::getVehicleNumber () const inline inherited
Returns the number of vehicles on this lane.
Returns
The number of vehicles on this lane
Definition at line 285 of file MSLane.h.
References MSLane::myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), TraCIServerAPI_Lane::processGet(), MSFullExport::writeLane(), and MSXMLRawOut::writeLane().
const MSLane::VehCont & GUILane::getVehiclesSecure () const virtual
Returns the vehicles container; locks it for microsimulation.
Locks "myLock" preventing usage by microsimulation.
Please note that it is necessary to release the vehicles container afterwards using "releaseVehicles".
Returns
The vehicles on this lane
See Also
MSLane::getVehiclesSecure
Reimplemented from MSLane.
Definition at line 114 of file GUILane.cpp.
References MFXMutex::lock(), myLock, and MSLane::myVehicles.
Referenced by drawGL().
SUMOReal MSLane::getWaitingSeconds () const inherited
Returns the overall waiting time on this lane.
Returns
The sum of the waiting time of all vehicles during the last step;
Definition at line 1468 of file MSLane.cpp.
References MSLane::myVehicles, and SUMOReal.
Referenced by TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getWidth () const inline inherited
Returns the lane's width.
Returns
This lane's width
Definition at line 386 of file MSLane.h.
References MSLane::myWidth.
Referenced by MSAbstractLaneChangeModel::continueLaneChangeManeuver(), drawGL(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::initWalkingAreaPaths(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::numStripes(), TraCIServerAPI_Lane::processGet(), and MSLink::setRequestInformation().
void MSLane::handleCollision (SUMOTime timestep, const std::string & stage, MSVehicle * collider, MSVehicle * victim, const SUMOReal gap) protected inherited
issue warning and add the vehicle to MSVehicleTransfer
Definition at line 723 of file MSLane.cpp.
References MSVehicleTransfer::add(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), Named::getID(), MSBaseVehicle::getID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, MSLane::myNettoVehicleLengthSum, MSVehicleControl::registerCollision(), time2string(), toString(), and WRITE_WARNING.
Referenced by MSLane::detectCollisions().
void GUILane::incorporateVehicle (MSVehicle * veh, SUMOReal pos, SUMOReal speed, const MSLane::VehCont::iterator & at, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) protected virtual
Inserts the vehicle into this lane, and informs it about entering the network.
Calls the vehicles enterLaneAtInsertion function, updates statistics and modifies the active state as needed
Parameters
[in] veh The vehicle to be incorporated
[in] pos The position of the vehicle
[in] speed The speed of the vehicle
[in] at
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
See Also
MSLane::incorporateVehicle
Reimplemented from MSLane.
Definition at line 104 of file GUILane.cpp.
References MSLane::incorporateVehicle(), and myLock.
void MSLane::insertIDs (std::vector< std::string > & into) static inherited
Adds the ids of all stored lanes into the given vector.
Parameters
in,filled] into The vector to add the IDs into
Definition at line 884 of file MSLane.cpp.
References MSLane::myDict.
Referenced by TraCIServerAPI_Lane::processGet().
bool MSLane::insertVehicle (MSVehicle & v) inherited
Tries to insert the given vehicle.
The insertion position and speed are determined in dependence to the vehicle's departure definition, first.
Then, the vehicle is tried to be inserted into the lane using these values by a call to "isInsertionSuccess". The result of "isInsertionSuccess" is returned.
Parameters
[in] v The vehicle to insert
Returns
Whether the vehicle could be inserted
See Also
isInsertionSuccess
MSVehicle::getDepartureDefinition
MSVehicle::DepartArrivalDefinition
Definition at line 358 of file MSLane.cpp.
References DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_MAX_SPEED_GAP, DEPART_POS_PWAG_GENERIC, DEPART_POS_PWAG_SIMPLE, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_SPEED_DEFAULT, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSLane::freeInsertion(), MSVehicleType::getLength(), MSLane::getLength(), MSBaseVehicle::getMaxSpeed(), MSBaseVehicle::getParameter(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLane::isInsertionSuccess(), MSLane::maxSpeedGapInsertion(), MIN2(), MSLane::myLength, MSMoveReminder::NOTIFICATION_DEPARTED, POSITION_EPS, MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), RandHelper::rand(), and SUMOReal.
Referenced by MSEdge::insertVehicle().
bool GUILane::integrateNewVehicle (SUMOTime t) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 155 of file GUILane.cpp.
References MSLane::integrateNewVehicle(), and myLock.
SUMOReal MSLane::interpolateGeometryPosToLanePos (SUMOReal geometryPos) const inline inherited
Definition at line 346 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
Referenced by getPopUpMenu(), and MSLink::setRequestInformation().
SUMOReal MSLane::interpolateLanePosToGeometryPos (SUMOReal lanePos) const inline inherited
Definition at line 334 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
Referenced by MSLane::geometryPositionAtOffset(), MSVehicle::getAngle(), MSPerson::MSPersonStage::getLanePosition(), MSContainer::MSContainerStage::getLanePosition(), MSVehicle::getPosition(), MSVehicle::getSlope(), and MSCFModel_KraussAccelBound::maxNextSpeed().
bool MSLane::isApproachedFrom (MSEdge *const edge) inherited
Definition at line 1100 of file MSLane.cpp.
References MSLane::myApproachingLanes.
bool MSLane::isApproachedFrom (MSEdge *const edge, MSLane *const lane) inherited
Definition at line 1106 of file MSLane.cpp.
References MSLane::myApproachingLanes.
bool MSLane::isEmpty () const inherited
Returns the information whether the lane is has no vehicle and no partial occupation
Definition at line 955 of file MSLane.cpp.
References MSLane::myInlappingVehicle, and MSLane::myVehicles.
bool MSLane::isInsertionSuccess (MSVehicle * vehicle, SUMOReal speed, SUMOReal pos, bool recheckNextLanes, MSMoveReminder::Notification notification) inherited
Tries to insert the given vehicle with the given state (speed and pos)
Checks whether the vehicle can be inserted at the given position with the given speed so that no collisions with leader/follower occur and the speed does not cause unexpected behaviour on consecutive lanes. Returns false if the vehicle can not be inserted.
If the insertion can take place, incorporateVehicleis called and true is returned.
Parameters
[in] vehicle The vehicle to insert
[in] speed The speed with which it shall be inserted
[in] pos The position at which it shall be inserted
[in] recheckNextLanes Forces patching the speed for not being too fast on next lanes
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
See Also
MSVehicle::enterLaneAtInsertion
Definition at line 446 of file MSLane.cpp.
References ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, MSRoute::begin(), MSCFModel::brakeGap(), MSLane::checkFailure(), MSInsertionControl::descheduleDeparture(), MSCFModel::freeSpeed(), MSVehicle::gap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), MSLane::getLastVehicle(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getMissingRearGap(), MSBaseVehicle::getParameter(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLane::incorporateVehicle(), MSCFModel::insertionFollowSpeed(), MSLane::isLinkEnd(), LINKSTATE_ALLWAY_STOP, LINKSTATE_EQUAL, LINKSTATE_MINOR, LINKSTATE_STOP, MAX2(), MSLane::myLength, MSLane::myVehicles, NUMERICAL_EPS, MSVehicle::setTentativeLaneAndPosition(), MSCFModel::stopSpeed(), MSLane::succLinkSec(), SUMO_const_haltingSpeed, SUMOReal, TIME2STEPS, toString(), MSVehicle::updateBestLanes(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSLane::freeInsertion(), MSLane::insertVehicle(), and MSLane::maxSpeedGapInsertion().
bool MSLane::isLinkEnd (MSLinkCont::const_iterator & i) const inherited
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 944 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), MSLane::isInsertionSuccess(), and MSVehicle::planMoveInternal().
bool MSLane::isLinkEnd (MSLinkCont::iterator & i) inherited
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 950 of file MSLane.cpp.
References MSLane::myLinks.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void MSLane::leftByLaneChange (MSVehicle * v) inherited
Definition at line 1407 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, and MSLane::myNettoVehicleLengthSum.
Referenced by MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSLane::loadState (std::vector< std::string > & vehIDs, MSVehicleControl & vc) inherited
Loads the state of this segment with the given parameters.
This method is called for every internal que the segment has. Every vehicle is retrieved from the given MSVehicleControl and added to this lane.
Parameters
[in] vehIDs The vehicle ids for the current que
[in] vc The vehicle control to retrieve references vehicles from
Todo:
What about throwing an IOError?
What about throwing an error if something else fails (a vehicle can not be referenced)?
Definition at line 1629 of file MSLane.cpp.
References MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleControl::getVehicle(), MSLane::incorporateVehicle(), MSLane::myVehicles, MSMoveReminder::NOTIFICATION_JUNCTION, and MSVehicle::updateBestLanes().
bool MSLane::maxSpeedGapInsertion (MSVehicle & veh, SUMOReal mspeed) inherited
Definition at line 226 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getHeadwayTime(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLane::incorporateVehicle(), MSLane::isInsertionSuccess(), MIN2(), MSLane::myLength, MSLane::myVehicles, MSMoveReminder::NOTIFICATION_DEPARTED, and SUMOReal.
Referenced by MSLane::insertVehicle().
void GUILane::planMovements (const SUMOTime t) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 127 of file GUILane.cpp.
References myLock, and MSLane::planMovements().
bool MSLane::pWagGenericInsertion (MSVehicle & veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos) inherited
Definition at line 145 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getLeaderOnConsecutive(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLane::incorporateVehicle(), MSCFModel::insertionFollowSpeed(), MSLane::myVehicles, MSVehicle::setTentativeLaneAndPosition(), SUMOReal, and MSVehicle::updateBestLanes().
Referenced by MSLane::insertVehicle().
bool MSLane::pWagSimpleInsertion (MSVehicle & veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos) inherited
Definition at line 193 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSCFModel::getHeadwayTime(), MSLane::getLeaderOnConsecutive(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLane::incorporateVehicle(), MSLane::myVehicles, MSVehicle::setTentativeLaneAndPosition(), SUMOReal, and MSVehicle::updateBestLanes().
Referenced by MSLane::insertVehicle().
void GUILane::releaseVehicles () const virtual
Allows to use the container for microsimulation again.
Unlocks "myLock" preventing usage by microsimulation.
See Also
MSLane::releaseVehicles
Reimplemented from MSLane.
Definition at line 121 of file GUILane.cpp.
References myLock, and MFXMutex::unlock().
Referenced by drawGL().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
MSVehicle * GUILane::removeVehicle (MSVehicle * remVehicle, MSMoveReminder::Notification notification, bool notify) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 141 of file GUILane.cpp.
References myLock, and MSLane::removeVehicle().
void MSLane::resetPartialOccupation (MSVehicle * v) inherited
Removes the information about a vehicle lapping into this lane.
Parameters
[in] v The vehicle which laps into this lane
Definition at line 642 of file MSLane.cpp.
References MSLane::myInlappingVehicle, and MSLane::myInlappingVehicleEnd.
void MSLane::saveState (OutputDevice & out) inherited
Saves the state of this lane into the given stream.
Basically, a list of vehicle ids
Parameters
in,filled] out The (possibly binary) device to write the state into
Todo:
What about throwing an IOError?
Definition at line 1619 of file MSLane.cpp.
References OutputDevice::closeTag(), MSLane::myVehicles, OutputDevice::openTag(), SUMO_ATTR_VALUE, SUMO_TAG_LANE, SUMO_TAG_VIEWSETTINGS_VEHICLES, and OutputDevice::writeAttr().
void GUILane::setColor (const GUIVisualizationSettings & s) const private
sets the color according to the currente settings
Definition at line 755 of file GUILane.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIVisualizationSettings::laneColorer, GLHelper::setColor(), setFunctionalColor(), and setMultiColor().
Referenced by drawGL(), and drawMarkings().
bool GUILane::setFunctionalColor (size_t activeScheme) const private
sets the color according to the current scheme index and some lane function
Definition at line 764 of file GUILane.cpp.
References PositionVector::beginEndAngle(), RGBColor::fromHSV(), MSLane::myShape, RAD2DEG, GLHelper::setColor(), and SUMOReal.
Referenced by setColor().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void MSLane::setLength (SUMOReal val) inherited
Sets a new length for the lane (used by TraCI only)
Parameters
[in] val the new length in m
Definition at line 1039 of file MSLane.cpp.
References MSLane::myEdge, and MSEdge::recalcCache().
Referenced by TraCIServerAPI_Lane::processSet().
void MSLane::setMaxSpeed (SUMOReal val) inherited
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
Parameters
[in] val the new speed in m/s
Definition at line 1032 of file MSLane.cpp.
References MSLane::myEdge, MSLane::myMaxSpeed, and MSEdge::recalcCache().
Referenced by TraCIServerAPI_Lane::processSet().
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
bool GUILane::setMultiColor (const GUIColorer & c) const private
sets multiple colors according to the current scheme index and some lane function
Definition at line 778 of file GUILane.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIPropertySchemeStorage< T >::getScheme(), MAX2(), MSLane::myShape, myShapeColors, POSITION_EPS, and SUMOReal.
Referenced by setColor().
SUMOReal MSLane::setPartialOccupation (MSVehicle * v, SUMOReal leftVehicleLength) inherited
Sets the information about a vehicle lapping into this lane.
The given left length of vehicle which laps into this lane is used to determine the vehicle's end position in regard to this lane's length. This information is set into myInlappingVehicleState; additionally, the vehicle pointer is stored in myInlappingVehicle; Returns this lane's length for subtracting it from the left vehicle length.
Parameters
[in] v The vehicle which laps into this lane
[in] leftVehicleLength The distance the vehicle laps into this lane
Returns
This lane's length
Definition at line 634 of file MSLane.cpp.
References MSLane::myInlappingVehicle, MSLane::myInlappingVehicleEnd, and MSLane::myLength.
void MSLane::setPermissions (SVCPermissions permissions) inline inherited
Definition at line 566 of file MSLane.h.
References MSLane::myPermissions.
Referenced by TraCIServerAPI_Lane::processSet().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
MSLinkCont::const_iterator MSLane::succLinkSec (const SUMOVehicle & veh, unsigned int nRouteSuccs, const MSLane & succLinkSource, const std::vector< MSLane * > & conts) static inherited
Same as succLink, but does not throw any assertions when the succeeding link could not be found; Returns the myLinks.end() instead; Further, the number of edges to look forward may be given
Definition at line 978 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), Named::getID(), SUMOVehicle::getID(), MSNet::getInstance(), MSEdge::getPurpose(), MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), MSLane::myLinks, SUMOVehicle::succEdge(), time2string(), and WRITE_WARNING.
Referenced by MSLane::appropriate(), MSLane::executeMovements(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), and MSVehicle::setBlinkerInformation().
void GUILane::swapAfterLaneChange (SUMOTime t) protected virtual
moves myTmpVehicles int myVehicles after a lane change procedure
Reimplemented from MSLane.
Definition at line 148 of file GUILane.cpp.
References myLock, and MSLane::swapAfterLaneChange().
void MSLane::visit (const TraCIServerAPI_Lane::StoringVisitor & cont) const inline inherited
Callback for visiting the lane when traversing an RTree.
This is used in the TraCIServerAPI_Lane for context subscriptions.
Parameters
[in] cont The context doing all the work
See Also
TraCIServerAPI_Lane::StoringVisitor::add
Definition at line 768 of file MSLane.h.
References TraCIServerAPI_Lane::StoringVisitor::add().
Referenced by TraCIServer::collectObjectsInRange().
Field Documentation
std::map<MSEdge*, std::vector<MSLane*> > MSLane::myApproachingLanes protected inherited
Definition at line 855 of file MSLane.h.
Referenced by MSLane::addApproachingLane(), and MSLane::isApproachedFrom().
SUMOReal MSLane::myBruttoVehicleLengthSum protected inherited
The current length of all vehicles on this lane, including their minGaps.
Definition at line 839 of file MSLane.h.
Referenced by MSLane::enteredByLaneChange(), MSLane::executeMovements(), MSLane::getBruttoOccupancy(), MSLane::getBruttoVehLenSum(), MSLane::handleCollision(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::leftByLaneChange(), and MSLane::removeVehicle().
MSLane::DictType MSLane::myDict static protected inherited
Static dictionary to associate string-ids with objects.
Definition at line 864 of file MSLane.h.
Referenced by MSLane::clear(), MSLane::dictionary(), MSLane::dictSize(), MSLane::fill(), and MSLane::insertIDs().
MSEdge* const MSLane::myEdge protected inherited
The lane's edge, for routing only.
Definition at line 818 of file MSLane.h.
Referenced by MSLane::appropriate(), drawGL(), drawMarkings(), getColorValue(), MSLane::getEdge(), getEdgeLaneNumber(), MSLane::getInternalFollower(), getLoadedEdgeWeight(), MSLane::getLogicalPredecessorLane(), MSLane::getParallelLane(), getParameterWindow(), getScaleValue(), getStoredEdgeTravelTime(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::by_connections_to_sorter::operator()(), MSLane::setLength(), and MSLane::setMaxSpeed().
SUMOReal GUILane::myHalfLaneWidth private
Half of lane width, for speed-up.
Definition at line 291 of file GUILane.h.
Referenced by drawBikeMarkings(), drawGL(), drawLinkNo(), drawLinkRule(), drawMarkings(), drawTLSLinkNo(), getHalfWidth(), and GUILane().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::vector<IncomingLaneInfo> MSLane::myIncomingLanes protected inherited
Definition at line 834 of file MSLane.h.
Referenced by MSLane::addIncomingLane(), MSLane::getFollowerOnConsecutive(), MSLane::getIncomingLanes(), and MSLane::getLogicalPredecessorLane().
unsigned int GUILane::myIndex private
The lane index.
Definition at line 297 of file GUILane.h.
Referenced by drawMarkings(), and GUILane().
MSVehicle* MSLane::myInlappingVehicle protected inherited
The vehicle which laps into this lane.
Definition at line 848 of file MSLane.h.
Referenced by MSLane::getBruttoOccupancy(), MSLane::getLastVehicleInformation(), MSLane::getNettoOccupancy(), MSLane::getPartialOccupator(), MSLane::isEmpty(), MSLane::resetPartialOccupation(), and MSLane::setPartialOccupation().
SUMOReal MSLane::myInlappingVehicleEnd protected inherited
End position of a vehicle which laps into this lane.
Definition at line 845 of file MSLane.h.
Referenced by MSLane::getBruttoOccupancy(), MSLane::getLastVehicleInformation(), MSLane::getNettoOccupancy(), MSLane::getPartialOccupatorEnd(), MSLane::resetPartialOccupation(), and MSLane::setPartialOccupation().
SUMOReal MSLane::myLength protected inherited
Lane length [m].
Definition at line 812 of file MSLane.h.
Referenced by MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), getColorValue(), MSLane::getLength(), MSLane::getNettoOccupancy(), getParameterWindow(), getScaleValue(), MSLane::incorporateVehicle(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSLane::maxSpeedGapInsertion(), and MSLane::setPartialOccupation().
const SUMOReal MSLane::myLengthGeometryFactor protected inherited
Definition at line 858 of file MSLane.h.
Referenced by getColorValue(), MSLane::getLengthGeometryFactor(), getScaleValue(), MSLane::interpolateGeometryPosToLanePos(), and MSLane::interpolateLanePosToGeometryPos().
MSLinkCont MSLane::myLinks protected inherited
The lane's Links to it's succeeding lanes and the default right-of-way rule, i.e. blocked or not blocked.
Definition at line 853 of file MSLane.h.
Referenced by MSLane::addLink(), MSLane::appropriate(), drawArrows(), drawLane2LaneConnections(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSLane::executeMovements(), MSLane::getCrossingIndex(), MSLane::getLinkCont(), MSLane::getOutgoingLanes(), MSLane::isLinkEnd(), MSLane::succLinkSec(), and MSLane::~MSLane().
MFXMutex GUILane::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 306 of file GUILane.h.
Referenced by detectCollisions(), executeMovements(), getVehiclesSecure(), incorporateVehicle(), integrateNewVehicle(), planMovements(), releaseVehicles(), removeVehicle(), swapAfterLaneChange(), and ~GUILane().
MSLane* MSLane::myLogicalPredecessorLane mutable protected inherited
Definition at line 835 of file MSLane.h.
Referenced by MSLane::getLogicalPredecessorLane().
SUMOReal MSLane::myMaxSpeed protected inherited
Lane-wide speedlimit [m/s].
Definition at line 821 of file MSLane.h.
Referenced by getColorValue(), MSLane::getMeanSpeed(), getScaleValue(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), and MSLane::setMaxSpeed().
SUMOReal MSLane::myNettoVehicleLengthSum protected inherited
The current length of all vehicles on this lane, excluding their minGaps.
Definition at line 842 of file MSLane.h.
Referenced by MSLane::enteredByLaneChange(), MSLane::executeMovements(), MSLane::getNettoOccupancy(), MSLane::handleCollision(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::leftByLaneChange(), and MSLane::removeVehicle().
size_t MSLane::myNumericalID protected inherited
Unique numerical ID (set on reading by netload)
Definition at line 800 of file MSLane.h.
Referenced by MSLane::getNumericalID().
SVCPermissions MSLane::myPermissions protected inherited
The vClass permissions for this lane.
Definition at line 832 of file MSLane.h.
Referenced by MSLane::allowsVehicleClass(), drawAsRailway(), drawAsWaterway(), drawGL(), drawMarkings(), getColorValue(), getParameterWindow(), MSLane::getPermissions(), and MSLane::setPermissions().
SUMOReal GUILane::myQuarterLaneWidth private
Quarter of lane width, for speed-up.
Definition at line 294 of file GUILane.h.
Referenced by drawGL(), drawMarkings(), and GUILane().
PositionVector MSLane::myShape inherited
The shape of the lane.
Definition at line 552 of file MSLane.h.
Referenced by drawGL(), MSLane::geometryPositionAtOffset(), getCenteringBoundary(), getPopUpMenu(), getShape(), MSLane::getShape(), GUILane(), setFunctionalColor(), and setMultiColor().
std::vector<RGBColor> GUILane::myShapeColors mutable private
The color of the shape parts (cached)
Definition at line 288 of file GUILane.h.
Referenced by drawGL(), GUILane(), and setMultiColor().
std::vector<SUMOReal> GUILane::myShapeLengths private
The lengths of the shape parts.
Definition at line 285 of file GUILane.h.
Referenced by drawBikeMarkings(), drawCrossties(), drawGL(), drawMarkings(), getShapeLengths(), and GUILane().
std::vector<SUMOReal> GUILane::myShapeRotations private
The rotations of the shape parts.
Definition at line 282 of file GUILane.h.
Referenced by drawBikeMarkings(), drawCrossties(), drawGL(), drawMarkings(), getShapeRotations(), and GUILane().
VehCont MSLane::myTmpVehicles protected inherited
Container for lane-changing vehicles. After completion of lane-change- process, the two containers will be swapped.
Definition at line 825 of file MSLane.h.
Referenced by MSLane::swapAfterLaneChange().
std::vector<MSVehicle*> MSLane::myVehBuffer protected inherited
buffer for vehicles that moved from their previous lane onto this one
Definition at line 829 of file MSLane.h.
Referenced by MSLane::empty(), MSLane::executeMovements(), MSLane::integrateNewVehicle(), and MSXMLRawOut::writeLane().
VehCont MSLane::myVehicles protected inherited
The lane's vehicles. The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
Definition at line 809 of file MSLane.h.
Referenced by MSLane::addMoveReminder(), MSLane::detectCollisions(), MSLane::empty(), MSLane::executeMovements(), firstWaitingTime(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLane::getFirstVehicle(), MSLane::getLastVehicle(), MSLane::getLastVehicleInformation(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getVehicleNumber(), getVehiclesSecure(), MSLane::getVehiclesSecure(), MSLane::getWaitingSeconds(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::isEmpty(), MSLane::isInsertionSuccess(), MSLane::loadState(), MSLane::maxSpeedGapInsertion(), MSLane::planMovements(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), MSLane::removeVehicle(), MSLane::saveState(), MSLane::swapAfterLaneChange(), MSQueueExport::writeLane(), and MSXMLRawOut::writeLane().
const SUMOReal MSLane::myWidth protected inherited
Lane width [m].
Definition at line 815 of file MSLane.h.
Referenced by drawArrows(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), getParameterWindow(), MSLane::getWidth(), and GUILane().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUILane.h
GUILane.cpp