SUMO - Simulation of Urban MObility: MSCModel_NonInteracting::MoveToNextEdge Class Reference
MSCModel_NonInteracting::MoveToNextEdge Class Reference
Public Member Functions
SUMOTime execute (SUMOTime currentTime)
Executes the command.
MoveToNextEdge (MSContainer *container, MSContainer::MSContainerStage_Tranship &tranship)
~MoveToNextEdge ()
Private Member Functions
MoveToNextEdge & operator= (const MoveToNextEdge &)
Invalidated assignment operator.
Private Attributes
MSContainer * myContainer
MSContainer::MSContainerStage_Tranship & myParent
Detailed Description
Definition at line 78 of file MSCModel_NonInteracting.h.
Constructor & Destructor Documentation
MSCModel_NonInteracting::MoveToNextEdge::MoveToNextEdge (MSContainer * container, MSContainer::MSContainerStage_Tranship & tranship) inline
Definition at line 80 of file MSCModel_NonInteracting.h.
MSCModel_NonInteracting::MoveToNextEdge::~MoveToNextEdge () inline
Definition at line 81 of file MSCModel_NonInteracting.h.
Member Function Documentation
SUMOTime MSCModel_NonInteracting::MoveToNextEdge::execute (SUMOTime currentTime) virtual
Executes the command.
The implementations should return 0 if the command shall not be repeated, or a value larger than 0 that describe the time after which the command shall be executed again. Values below 0 must not be returned.
Parameters
[in] currentTime The current simulation time
Returns
The time after which the command shall be executed again, 0 if this command shall be descheduled.
Exceptions
ProcessError Derived actions may throw this exception
Implements Command.
Definition at line 95 of file MSCModel_NonInteracting.cpp.
References CState::computeTranshipTime(), MSContainer::MSContainerStage_Tranship::getContainerState(), MSContainer::MSContainerStage_Tranship::getEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), myContainer, and myParent.
MoveToNextEdge& MSCModel_NonInteracting::MoveToNextEdge::operator= (const MoveToNextEdge &) private
Invalidated assignment operator.
Field Documentation
MSContainer* MSCModel_NonInteracting::MoveToNextEdge::myContainer private
Definition at line 86 of file MSCModel_NonInteracting.h.
Referenced by execute().
MSContainer::MSContainerStage_Tranship& MSCModel_NonInteracting::MoveToNextEdge::myParent private
Definition at line 85 of file MSCModel_NonInteracting.h.
Referenced by execute().
The documentation for this class was generated from the following files:
MSCModel_NonInteracting.h
MSCModel_NonInteracting.cpp