SUMO - Simulation of Urban MObility: GUIJunctionWrapper Class Reference
GUIJunctionWrapper Class Reference
#include <GUIJunctionWrapper.h>
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
Boundary getBoundary () const
Returns the boundary of the junction.
const MSJunction & getJunction () const
Returns the represented junction.
GUIJunctionWrapper (MSJunction &junction)
Constructor.
bool isInner () const
whether this is an inner junction (a waiting spot for crossing a "real" junction)
virtual ~GUIJunctionWrapper ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Private Member Functions
SUMOReal getColorValue (const GUIVisualizationSettings &s) const
GUIJunctionWrapper (const GUIJunctionWrapper &)
Invalidated copy constructor.
GUIJunctionWrapper & operator= (const GUIJunctionWrapper &)
Invalidated assignment operator.
Private Attributes
bool myAmWaterway
whether this junction has only waterways as incoming and outgoing edges
Boundary myBoundary
The represented junction's boundary.
bool myIsInner
whether this wraps an instance of MSInternalJunction
MSJunction & myJunction
A reference to the represented junction.
SUMOReal myMaxSize
The maximum size (in either x-, or y-dimension) for determining whether to draw or not.
Detailed Description
As MSJunctions do not have a graphical representation but a complex inheritance tree, this class is used to encapsulate the geometry of an abstract junction and to be used as a gl-object.
In the case the represented junction's shape is empty, the boundary is computed using the junction's position to which an offset of 1m to each side is added.
Definition at line 68 of file GUIJunctionWrapper.h.
Constructor & Destructor Documentation
GUIJunctionWrapper::GUIJunctionWrapper (MSJunction & junction)
Constructor.
Parameters
in,changed] idStorage The storage to retrieve the gl-id from
[in] junction The represented junction
Definition at line 67 of file GUIJunctionWrapper.cpp.
References PositionVector::getBoxBoundary(), Boundary::getHeight(), MSJunction::getIncoming(), MSJunction::getOutgoing(), MSJunction::getPosition(), MSJunction::getShape(), Boundary::getWidth(), isWaterway(), MAX2(), myAmWaterway, myBoundary, myIsInner, myJunction, myMaxSize, Position::x(), and Position::y().
GUIJunctionWrapper::~GUIJunctionWrapper () virtual
Destructor.
Definition at line 98 of file GUIJunctionWrapper.cpp.
GUIJunctionWrapper::GUIJunctionWrapper (const GUIJunctionWrapper &) private
Invalidated copy constructor.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIJunctionWrapper::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See Also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 130 of file GUIJunctionWrapper.cpp.
References GLHelper::debugVertices(), GLHelper::drawFilledPoly(), GLHelper::drawFilledPolyTesselated(), GUIVisualizationSettings::drawJunctionShape, GUIGlObject::drawName(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIGlObject::getGlID(), MSJunction::getPosition(), GUIPropertySchemeStorage< T >::getScheme(), MSJunction::getShape(), GUIGlObject::getType(), GUIVisualizationSettings::internalJunctionName, GUIVisualizationSettings::junctionColorer, GUIVisualizationSettings::junctionName, myIsInner, myJunction, myMaxSize, GUIVisualizationSettings::scale, GLHelper::setColor(), and SUMOReal.
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIEdge::drawGL().
Boundary GUIJunctionWrapper::getBoundary () const inline
Returns the boundary of the junction.
Returns
This junction's boundary
Definition at line 125 of file GUIJunctionWrapper.h.
References myBoundary.
Referenced by GUINet::initGUIStructures().
Boundary GUIJunctionWrapper::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See Also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 122 of file GUIJunctionWrapper.cpp.
References Boundary::grow(), and myBoundary.
SUMOReal GUIJunctionWrapper::getColorValue (const GUIVisualizationSettings & s) const private
Definition at line 161 of file GUIJunctionWrapper.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIGlObject::getGlID(), MSJunction::getType(), GUIGlObject::getType(), gSelected, GUISelectedStorage::isSelected(), GUIVisualizationSettings::junctionColorer, myAmWaterway, myJunction, NODETYPE_ALLWAY_STOP, NODETYPE_DEAD_END, NODETYPE_DEAD_END_DEPRECATED, NODETYPE_DISTRICT, NODETYPE_INTERNAL, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, and NODETYPE_UNKNOWN.
Referenced by drawGL().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUILane::drawLinkRule(), getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GUILane::getColorValue(), GUIVehicle::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), GUILane::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
const MSJunction& GUIJunctionWrapper::getJunction () const inline
Returns the represented junction.
Returns
The junction itself
Definition at line 137 of file GUIJunctionWrapper.h.
References myJunction.
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
GUIParameterTableWindow * GUIJunctionWrapper::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See Also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 115 of file GUIJunctionWrapper.cpp.
GUIGLObjectPopupMenu * GUIJunctionWrapper::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See Also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 102 of file GUIJunctionWrapper.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), and GUIGlObject::buildSelectionPopupEntry().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), getColorValue(), GUILane::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUILane::getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
bool GUIJunctionWrapper::isInner () const inline
whether this is an inner junction (a waiting spot for crossing a "real" junction)
Definition at line 130 of file GUIJunctionWrapper.h.
References myIsInner.
GUIJunctionWrapper& GUIJunctionWrapper::operator= (const GUIJunctionWrapper &) private
Invalidated assignment operator.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
bool GUIJunctionWrapper::myAmWaterway private
whether this junction has only waterways as incoming and outgoing edges
Definition at line 167 of file GUIJunctionWrapper.h.
Referenced by getColorValue(), and GUIJunctionWrapper().
Boundary GUIJunctionWrapper::myBoundary private
The represented junction's boundary.
Definition at line 161 of file GUIJunctionWrapper.h.
Referenced by getBoundary(), getCenteringBoundary(), and GUIJunctionWrapper().
bool GUIJunctionWrapper::myIsInner private
whether this wraps an instance of MSInternalJunction
Definition at line 164 of file GUIJunctionWrapper.h.
Referenced by drawGL(), GUIJunctionWrapper(), and isInner().
MSJunction& GUIJunctionWrapper::myJunction private
A reference to the represented junction.
Definition at line 155 of file GUIJunctionWrapper.h.
Referenced by drawGL(), getColorValue(), getJunction(), and GUIJunctionWrapper().
SUMOReal GUIJunctionWrapper::myMaxSize private
The maximum size (in either x-, or y-dimension) for determining whether to draw or not.
Definition at line 158 of file GUIJunctionWrapper.h.
Referenced by drawGL(), and GUIJunctionWrapper().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIJunctionWrapper.h
GUIJunctionWrapper.cpp