SUMO - Simulation of Urban MObility: TraCIServerAPI_Lane::StoringVisitor Class Reference
TraCIServerAPI_Lane::StoringVisitor Class Reference
Allows to store the object; used as context while traveling the rtree in TraCI.
#include <TraCIServerAPI_Lane.h>
Public Member Functions
void add (const MSLane *const l) const
Adds the given object to the container.
StoringVisitor (std::set< std::string > &ids, const PositionVector &shape, const SUMOReal range, const int domain)
Constructor.
~StoringVisitor ()
Destructor.
Data Fields
const int myDomain
std::set< std::string > & myIDs
The container.
const SUMOReal myRange
const PositionVector & myShape
Private Member Functions
StoringVisitor & operator= (const StoringVisitor &src)
invalidated assignment operator
StoringVisitor (const StoringVisitor &src)
invalidated copy constructor
Detailed Description
Allows to store the object; used as context while traveling the rtree in TraCI.
Definition at line 87 of file TraCIServerAPI_Lane.h.
Constructor & Destructor Documentation
TraCIServerAPI_Lane::StoringVisitor::StoringVisitor (std::set< std::string > & ids, const PositionVector & shape, const SUMOReal range, const int domain) inline
Constructor.
Definition at line 90 of file TraCIServerAPI_Lane.h.
TraCIServerAPI_Lane::StoringVisitor::~StoringVisitor () inline
Destructor.
Definition at line 95 of file TraCIServerAPI_Lane.h.
TraCIServerAPI_Lane::StoringVisitor::StoringVisitor (const StoringVisitor & src) private
invalidated copy constructor
Member Function Documentation
void TraCIServerAPI_Lane::StoringVisitor::add (const MSLane *const l) const
Adds the given object to the container.
Definition at line 391 of file TraCIServerAPI_Lane.cpp.
References CMD_GET_EDGE_VARIABLE, CMD_GET_LANE_VARIABLE, CMD_GET_VEHICLE_VARIABLE, PositionVector::distance(), MSLane::getEdge(), Named::getID(), MSLane::getShape(), MSLane::getVehiclesSecure(), myDomain, myIDs, myRange, myShape, and MSLane::releaseVehicles().
Referenced by MSLane::visit().
StoringVisitor& TraCIServerAPI_Lane::StoringVisitor::operator= (const StoringVisitor & src) private
invalidated assignment operator
Field Documentation
const int TraCIServerAPI_Lane::StoringVisitor::myDomain
Definition at line 104 of file TraCIServerAPI_Lane.h.
Referenced by add().
std::set<std::string>& TraCIServerAPI_Lane::StoringVisitor::myIDs
The container.
Definition at line 101 of file TraCIServerAPI_Lane.h.
Referenced by add().
const SUMOReal TraCIServerAPI_Lane::StoringVisitor::myRange
Definition at line 103 of file TraCIServerAPI_Lane.h.
Referenced by add().
const PositionVector& TraCIServerAPI_Lane::StoringVisitor::myShape
Definition at line 102 of file TraCIServerAPI_Lane.h.
Referenced by add().
The documentation for this class was generated from the following files:
TraCIServerAPI_Lane.h
TraCIServerAPI_Lane.cpp