SUMO - Simulation of Urban MObility: RODFNet Class Reference
RODFNet Class Reference
A DFROUTER-network.
#include <RODFNet.h>
Data Structures
class DFRouteDescByTimeComperator
struct idComp
comparator for maps using edges as key, used only in myDetectorsOnEdges to make tests comparable
struct IterationEdge
Public Member Functions
void buildApproachList ()
void buildDetectorDependencies (RODFDetectorCon &detectors)
void buildEdgeFlowMap (const RODFDetectorFlows &flows, const RODFDetectorCon &detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void buildRoutes (RODFDetectorCon &det, bool keepUnfoundEnds, bool includeInBetween, bool keepShortestOnly, int maxFollowingLength) const
void cleanup (SUMOAbstractRouter< ROEdge, ROVehicle > *router)
closes the file output for computed routes and deletes routers and associated threads if necessary
void computeTypes (RODFDetectorCon &dets, bool sourcesStrict) const
SUMOReal getAbsPos (const RODFDetector &det) const
const std::vector< std::string > & getDetectorList (ROEdge *edge) const
const std::map< std::string,
ROEdge * > & getEdgeMap () const
size_t getEdgeNo () const
Returns the total number of edges the network contains including internal edges.
int getInternalEdgeNumber () const
Returns the number of internal edges the network contains.
OutputDevice * getRouteOutput (const bool alternative=false)
bool hasDetector (ROEdge *edge) const
bool hasRestrictions () const
void mesoJoin (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void openOutput (const std::string &filename, const std::string altFilename, const std::string typeFilename)
Opens the output for computed routes.
void removeEmptyDetectors (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void reportEmptyDetectors (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void revalidateFlows (const RODFDetectorCon &detectors, RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
RODFNet (bool amInHighwayMode)
Constructor.
void setRestrictionFound ()
~RODFNet ()
Destructor.
Insertion and retrieval of graph parts
virtual bool addEdge (ROEdge *edge)
bool addDistrict (const std::string id, ROEdge *source, ROEdge *sink)
bool addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource)
const std::map< std::string,
std::pair< std::vector
< std::string >, std::vector
< std::string > > > & getDistricts () const
Retrieves all TAZ (districts) from the network.
ROEdge * getEdge (const std::string &name) const
Retrieves an edge from the network.
void addNode (RONode *node)
RONode * getNode (const std::string &id) const
Retrieves an node from the network.
void addBusStop (const std::string &id, SUMOVehicleParameter::Stop *stop)
void addContainerStop (const std::string &id, SUMOVehicleParameter::Stop *stop)
const SUMOVehicleParameter::Stop * getBusStop (const std::string &id) const
Retrieves a bus stop from the network.
const SUMOVehicleParameter::Stop * getContainerStop (const std::string &id) const
Retrieves a container stop from the network.
Insertion and retrieval of vehicle types, vehicles, routes, and route definitions
bool checkVType (const std::string &id)
Checks whether the vehicle type (distribution) may be added.
virtual bool addVehicleType (SUMOVTypeParameter *type)
Adds a read vehicle type definition to the network.
bool addVTypeDistribution (const std::string &id, RandomDistributor< SUMOVTypeParameter * > *vehTypeDistribution)
Adds a vehicle type distribution.
SUMOVTypeParameter * getVehicleTypeSecure (const std::string &id)
Retrieves the named vehicle type.
bool addRouteDef (RORouteDef *def)
RORouteDef * getRouteDef (const std::string &name) const
Returns the named route definition.
virtual bool addVehicle (const std::string &id, ROVehicle *veh)
bool addFlow (SUMOVehicleParameter *flow, const bool randomize)
void addPerson (const SUMOTime depart, const std::string desc)
void addContainer (const SUMOTime depart, const std::string desc)
Processing stored vehicle definitions
SUMOTime saveAndRemoveRoutesUntil (OptionsCont &options, SUMOAbstractRouter< ROEdge, ROVehicle > &router, SUMOTime time)
Computes routes described by their definitions and saves them.
virtual bool furtherStored ()
Returns the information whether further vehicles, persons or containers are stored.
Protected Types
typedef std::multimap< const
SUMOTime, const std::string > ContainerMap
Known containers.
typedef std::multimap< const
SUMOTime, const std::string > PersonMap
Known persons.
typedef std::map< std::string,
RandomDistributor
< SUMOVTypeParameter * > * > VTypeDistDictType
Vehicle type distribution dictionary type.
Protected Member Functions
void buildDetectorEdgeDependencies (RODFDetectorCon &dets) const
void checkFlows (SUMOTime time)
void computeRoutesFor (ROEdge *edge, RODFRouteDesc &base, int no, bool keepUnfoundEnds, bool keepShortestOnly, ROEdgeVector &visited, const RODFDetector &det, RODFRouteCont &into, const RODFDetectorCon &detectors, int maxFollowingLength, ROEdgeVector &seen) const
ROEdge * getDetectorEdge (const RODFDetector &det) const
ROVehicleCont & getVehicles ()
return vehicles for use by RouteAggregator
bool hasApproached (ROEdge *edge) const
bool hasApproaching (ROEdge *edge) const
bool hasInBetweenDetectorsOnly (ROEdge *edge, const RODFDetectorCon &detectors) const
bool hasSourceDetector (ROEdge *edge, const RODFDetectorCon &detectors) const
bool isDestination (const RODFDetector &det, const RODFDetectorCon &detectors) const
bool isDestination (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors) const
bool isFalseSource (const RODFDetector &det, const RODFDetectorCon &detectors) const
bool isFalseSource (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors) const
bool isSource (const RODFDetector &det, const RODFDetectorCon &detectors, bool strict) const
bool isSource (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors, bool strict) const
void revalidateFlows (const RODFDetector *detector, RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Static Protected Member Functions
static bool computeRoute (SUMOAbstractRouter< ROEdge, ROVehicle > &router, const ROVehicle *const veh, const bool removeLoops, MsgHandler *errorHandler)
Protected Attributes
std::map< std::string,
SUMOVehicleParameter::Stop * > myBusStops
Known bus stops.
ContainerMap myContainers
std::map< std::string,
SUMOVehicleParameter::Stop * > myContainerStops
Known container stops.
bool myDefaultVTypeMayBeDeleted
Whether no vehicle type was loaded.
std::map< std::string,
std::vector< SUMOTime > > myDepartures
Departure times for randomized flows.
unsigned int myDiscardedRouteNo
The number of discarded routes.
std::map< std::string,
std::pair< std::vector
< std::string >, std::vector
< std::string > > > myDistricts
traffic assignment zones with sources and sinks
NamedObjectCont< ROEdge * > myEdges
Known edges.
MsgHandler * myErrorHandler
handler for ignorable error messages
NamedObjectCont
< SUMOVehicleParameter * > myFlows
Known flows.
bool myHaveRestrictions
Whether the network contains edges which not all vehicles may pass.
NamedObjectCont< RONode * > myNodes
Known nodes.
int myNumInternalEdges
The number of internal edges in the dictionary.
PersonMap myPersons
unsigned int myReadRouteNo
The number of read routes.
OutputDevice * myRouteAlternativesOutput
The file to write the computed route alternatives into.
NamedObjectCont< RORouteDef * > myRoutes
Known routes.
OutputDevice * myRoutesOutput
The file to write the computed routes into.
OutputDevice * myTypesOutput
The file to write the vehicle types into.
ROVehicleCont myVehicles
Known vehicles.
NamedObjectCont
< SUMOVTypeParameter * > myVehicleTypes
Known vehicle types.
std::set< std::string > myVehIDs
Known vehicle ids.
VTypeDistDictType myVTypeDistDict
A distribution of vehicle types (probability->vehicle type)
unsigned int myWrittenRouteNo
The number of written routes.
Private Attributes
bool myAmInHighwayMode
std::map< ROEdge *, ROEdgeVector > myApproachedEdges
Map of edge name->list of names of edges approached by this edge.
std::map< ROEdge *, ROEdgeVector > myApproachingEdges
Map of edge name->list of names of this edge approaching edges.
std::map< std::string, ROEdge * > myDetectorEdges
std::map< ROEdge
*, std::vector< std::string >
, idComp > myDetectorsOnEdges
std::vector< std::string > myDisallowedEdges
List of ids of edges that shall not be used.
size_t myInBetweenNumber
size_t myInvalidNumber
bool myKeepTurnarounds
size_t mySinkNumber
size_t mySourceNumber
Detailed Description
A DFROUTER-network.
Definition at line 51 of file RODFNet.h.
Member Typedef Documentation
typedef std::multimap<const SUMOTime, const std::string> RONet::ContainerMap protected inherited
Known containers.
Definition at line 456 of file RONet.h.
typedef std::multimap<const SUMOTime, const std::string> RONet::PersonMap protected inherited
Known persons.
Definition at line 452 of file RONet.h.
typedef std::map< std::string, RandomDistributor<SUMOVTypeParameter*>* > RONet::VTypeDistDictType protected inherited
Vehicle type distribution dictionary type.
Definition at line 435 of file RONet.h.
Constructor & Destructor Documentation
RODFNet::RODFNet (bool amInHighwayMode)
Constructor.
Parameters
[in] amInHighwayMode Whether search for following edges shall stop at slow edges
Definition at line 56 of file RODFNet.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getStringVector(), myDisallowedEdges, and myKeepTurnarounds.
RODFNet::~RODFNet ()
Destructor.
Definition at line 64 of file RODFNet.cpp.
Member Function Documentation
void RONet::addBusStop (const std::string & id, SUMOVehicleParameter::Stop * stop) inherited
Definition at line 144 of file RONet.cpp.
References RONet::myBusStops, and WRITE_ERROR.
Referenced by RONetHandler::parseBusStop().
void RONet::addContainer (const SUMOTime depart, const std::string desc) inherited
Definition at line 313 of file RONet.cpp.
References RONet::myContainers.
Referenced by RORouteHandler::closeContainer().
void RONet::addContainerStop (const std::string & id, SUMOVehicleParameter::Stop * stop) inherited
Definition at line 155 of file RONet.cpp.
References RONet::myContainerStops, and WRITE_ERROR.
Referenced by RONetHandler::parseContainerStop().
bool RONet::addDistrict (const std::string id, ROEdge * source, ROEdge * sink) inherited
Definition at line 96 of file RONet.cpp.
References RONet::addEdge(), ROEdge::ET_DISTRICT, RONet::myDistricts, ROEdge::setType(), and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict().
bool RONet::addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource) inherited
Definition at line 113 of file RONet.cpp.
References ROEdge::addSuccessor(), RONet::getEdge(), RONet::myDistricts, and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict(), and RONetHandler::parseDistrictEdge().
bool RONet::addEdge (ROEdge * edge) virtual inherited
Definition at line 82 of file RONet.cpp.
References NamedObjectCont< T >::add(), ROEdge::ET_INTERNAL, Named::getID(), ROEdge::getType(), RONet::myEdges, RONet::myNumInternalEdges, and WRITE_ERROR.
Referenced by RONet::addDistrict(), and RONetHandler::parseEdge().
bool RONet::addFlow (SUMOVehicleParameter * flow, const bool randomize) inherited
Definition at line 294 of file RONet.cpp.
References NamedObjectCont< T >::add(), SUMOVehicleParameter::depart, SUMOVehicleParameter::id, RONet::myDepartures, RONet::myFlows, RandHelper::rand(), SUMOVehicleParameter::repetitionNumber, and SUMOVehicleParameter::repetitionOffset.
Referenced by RORouteHandler::closeFlow().
void RONet::addNode (RONode * node) inherited
Definition at line 135 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), RONet::myNodes, and WRITE_ERROR.
Referenced by RONetHandler::parseEdge(), and RONetHandler::parseJunction().
void RONet::addPerson (const SUMOTime depart, const std::string desc) inherited
Definition at line 308 of file RONet.cpp.
References RONet::myPersons.
Referenced by RORouteHandler::closePerson().
bool RONet::addRouteDef (RORouteDef * def) inherited
Definition at line 166 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and RONet::myRoutes.
Referenced by RORouteHandler::closeRoute(), and RORouteHandler::closeRouteDistribution().
bool RONet::addVehicle (const std::string & id, ROVehicle * veh) virtual inherited
Definition at line 282 of file RONet.cpp.
References ROVehicleCont::add(), RONet::myReadRouteNo, RONet::myVehicles, RONet::myVehIDs, and WRITE_ERROR.
Referenced by RONet::checkFlows(), and RORouteHandler::closeVehicle().
bool RONet::addVehicleType (SUMOVTypeParameter * type) virtual inherited
Adds a read vehicle type definition to the network.
If the vehicle type definition is already known (another one with the same id exists), false is returned, and the vehicle type is deleted.
Parameters
[in] def The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 259 of file RONet.cpp.
References NamedObjectCont< T >::add(), RONet::checkVType(), SUMOVTypeParameter::id, RONet::myVehicleTypes, and WRITE_ERROR.
Referenced by RORouteHandler::myEndElement().
bool RONet::addVTypeDistribution (const std::string & id, RandomDistributor< SUMOVTypeParameter * > * vehTypeDistribution) inherited
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 272 of file RONet.cpp.
References RONet::checkVType(), and RONet::myVTypeDistDict.
Referenced by RORouteHandler::closeVehicleTypeDistribution().
void RODFNet::buildApproachList ()
Definition at line 69 of file RODFNet.cpp.
References RONet::getEdgeMap(), ROEdge::getFromNode(), Named::getID(), ROEdge::getSuccessors(), ROEdge::getToNode(), myApproachedEdges, myApproachingEdges, myDisallowedEdges, and myKeepTurnarounds.
void RODFNet::buildDetectorDependencies (RODFDetectorCon & detectors)
Definition at line 1006 of file RODFNet.cpp.
References RODFDetector::addPriorDetector(), buildDetectorEdgeDependencies(), RODFDetectorCon::getDetector(), RODFDetectorCon::getModifiableDetector(), RODFDetector::getRouteVector(), RODFDetector::hasRoutes(), myDetectorEdges, and myDetectorsOnEdges.
Referenced by startComputation().
void RODFNet::buildDetectorEdgeDependencies (RODFDetectorCon & dets) const protected
Definition at line 100 of file RODFNet.cpp.
References getDetectorEdge(), RODFDetectorCon::getDetectors(), myDetectorEdges, and myDetectorsOnEdges.
Referenced by buildDetectorDependencies(), buildRoutes(), computeTypes(), and mesoJoin().
void RODFNet::buildEdgeFlowMap (const RODFDetectorFlows & flows, const RODFDetectorCon & detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 933 of file RODFNet.cpp.
References FlowDef::fLKW, RODFDetectorCon::getDetector(), RODFDetectorFlows::getFlowDefs(), Named::getID(), RODFDetector::getPos(), ROEdge::getSpeed(), FlowDef::isLKW, RODFDetectorFlows::knows(), myDetectorsOnEdges, FlowDef::qLKW, FlowDef::qPKW, SUMOReal, FlowDef::vLKW, FlowDef::vPKW, and WRITE_MESSAGE.
Referenced by startComputation().
void RODFNet::buildRoutes (RODFDetectorCon & det, bool keepUnfoundEnds, bool includeInBetween, bool keepShortestOnly, int maxFollowingLength) const
!!;
!!routes->removeIllegal(illegals);
!!;
Definition at line 345 of file RODFNet.cpp.
References BETWEEN_DETECTOR, buildDetectorEdgeDependencies(), computeRoutesFor(), RODFRouteDesc::distance, RODFRouteDesc::distance2Last, RODFRouteDesc::duration2Last, RODFRouteDesc::duration_2, RODFRouteDesc::edges2Pass, RODFRouteDesc::endDetectorEdge, RODFRouteDesc::factor, RODFRouteCont::get(), RODFDetectorCon::getDetector(), getDetectorEdge(), RODFDetectorCon::getDetectors(), ROEdge::getLength(), ROEdge::getSpeed(), RODFDetector::getType(), RODFRouteDesc::lastDetectorEdge, myDetectorsOnEdges, RODFRouteDesc::overallProb, and SUMOReal.
Referenced by startComputation().
void RONet::checkFlows (SUMOTime time) protected inherited
Definition at line 352 of file RONet.cpp.
References RONet::addVehicle(), RORouteDef::copy(), DEFAULT_VTYPE_ID, DELTA_T, SUMOVehicleParameter::depart, NamedObjectCont< T >::erase(), NamedObjectCont< T >::getMyMap(), RONet::getRouteDef(), RONet::getVehicleTypeSecure(), SUMOVTypeParameter::id, SUMOVehicleParameter::id, RONet::myDepartures, RONet::myFlows, RandHelper::rand(), SUMOVehicleParameter::repetitionEnd, SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, toString(), TS, and SUMOVehicleParameter::vtypeid.
Referenced by RONet::saveAndRemoveRoutesUntil().
bool RONet::checkVType (const std::string & id) inherited
Checks whether the vehicle type (distribution) may be added.
This method checks also whether the default type may still be replaced
Parameters
[in] id The id of the vehicle type (distribution) to add
Returns
Whether the type (distribution) may be added
Definition at line 241 of file RONet.cpp.
References DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), RONet::myDefaultVTypeMayBeDeleted, RONet::myVehicleTypes, RONet::myVTypeDistDict, and NamedObjectCont< T >::remove().
Referenced by RONet::addVehicleType(), and RONet::addVTypeDistribution().
void RONet::cleanup (SUMOAbstractRouter< ROEdge, ROVehicle > * router) inherited
closes the file output for computed routes and deletes routers and associated threads if necessary
Definition at line 191 of file RONet.cpp.
References RouteCostCalculator< R, E, V >::cleanup(), OutputDevice::close(), RONet::myRouteAlternativesOutput, RONet::myRoutesOutput, and RONet::myTypesOutput.
Referenced by computeRoutes().
bool RONet::computeRoute (SUMOAbstractRouter< ROEdge, ROVehicle > & router, const ROVehicle *const veh, const bool removeLoops, MsgHandler * errorHandler) static protected inherited
Definition at line 319 of file RONet.cpp.
References RORouteDef::addAlternative(), RORouteDef::buildCurrentRoute(), ROVehicle::getDepartureTime(), ROVehicle::getID(), ROVehicle::getRouteDefinition(), MsgHandler::inform(), RORoute::recheckForLoops(), and RORoute::size().
Referenced by RONet::saveAndRemoveRoutesUntil().
void RODFNet::computeRoutesFor (ROEdge * edge, RODFRouteDesc & base, int no, bool keepUnfoundEnds, bool keepShortestOnly, ROEdgeVector & visited, const RODFDetector & det, RODFRouteCont & into, const RODFDetectorCon & detectors, int maxFollowingLength, ROEdgeVector & seen) const protected
!!! //toDiscard.push_back(current);
!!
Definition at line 186 of file RODFNet.cpp.
References RODFRouteCont::addRouteDesc(), RODFRouteDesc::distance, RODFRouteDesc::distance2Last, RODFRouteDesc::duration2Last, RODFRouteDesc::duration_2, RODFRouteDesc::edges2Pass, RODFRouteDesc::endDetectorEdge, RODFRouteDesc::factor, getDetectorEdge(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getOptions(), ROEdge::getSpeed(), hasApproached(), hasDetector(), hasInBetweenDetectorsOnly(), hasSourceDetector(), RODFRouteDesc::lastDetectorEdge, myAmInHighwayMode, myApproachedEdges, RODFRouteDesc::passedNo, RODFRouteCont::removeRouteDesc(), SUMOReal, UNUSED_PARAMETER, and WRITE_WARNING.
Referenced by buildRoutes().
void RODFNet::computeTypes (RODFDetectorCon & dets, bool sourcesStrict) const
Definition at line 113 of file RODFNet.cpp.
References BETWEEN_DETECTOR, buildDetectorEdgeDependencies(), DISCARDED_DETECTOR, RODFDetectorCon::getDetectors(), isDestination(), isFalseSource(), isSource(), myInBetweenNumber, myInvalidNumber, mySinkNumber, mySourceNumber, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, SINK_DETECTOR, SOURCE_DETECTOR, toString(), TYPE_NOT_DEFINED, and WRITE_MESSAGE.
Referenced by startComputation().
bool RONet::furtherStored () virtual inherited
Returns the information whether further vehicles, persons or containers are stored.
Definition at line 523 of file RONet.cpp.
References RONet::myContainers, RONet::myFlows, RONet::myPersons, RONet::myVehicles, and NamedObjectCont< T >::size().
Referenced by ROLoader::openRoutes(), and ROLoader::processRoutes().
SUMOReal RODFNet::getAbsPos (const RODFDetector & det) const
Definition at line 675 of file RODFNet.cpp.
References getDetectorEdge(), ROEdge::getLength(), and RODFDetector::getPos().
Referenced by isDestination(), and isSource().
const SUMOVehicleParameter::Stop* RONet::getBusStop (const std::string & id) const inline inherited
Retrieves a bus stop from the network.
Parameters
[in] name The name of the stop to retrieve
Returns
The named stop if known, otherwise 0
Definition at line 192 of file RONet.h.
References RONet::myBusStops.
Referenced by RORouteHandler::addStop().
const SUMOVehicleParameter::Stop* RONet::getContainerStop (const std::string & id) const inline inherited
Retrieves a container stop from the network.
Parameters
[in] name The name of the stop to retrieve
Returns
The named stop if known, otherwise 0
Definition at line 206 of file RONet.h.
References RONet::myContainerStops.
Referenced by RORouteHandler::addStop().
ROEdge * RODFNet::getDetectorEdge (const RODFDetector & det) const protected
Definition at line 630 of file RODFNet.cpp.
References RONet::getEdge(), Named::getID(), and RODFDetector::getLaneID().
Referenced by buildDetectorEdgeDependencies(), buildRoutes(), computeRoutesFor(), getAbsPos(), isDestination(), isFalseSource(), isSource(), and revalidateFlows().
const std::vector< std::string > & RODFNet::getDetectorList (ROEdge * edge) const
Definition at line 669 of file RODFNet.cpp.
References myDetectorsOnEdges.
const std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string> > >& RONet::getDistricts () const inline inherited
Retrieves all TAZ (districts) from the network.
Returns
The map of all districts
Definition at line 126 of file RONet.h.
References RONet::myDistricts.
Referenced by main().
ROEdge* RONet::getEdge (const std::string & name) const inline inherited
Retrieves an edge from the network.
This is not very pretty, but necessary, though, as routes run over instances, not over ids.
Parameters
[in] name The name of the edge to retrieve
Returns
The named edge if known, otherwise 0
Definition at line 138 of file RONet.h.
References NamedObjectCont< T >::get(), and RONet::myEdges.
Referenced by RONet::addDistrictEdge(), ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), RORouteHandler::addStop(), ROVehicle::addStop(), ROJTRTurnDefLoader::addToEdge(), ROJTRTurnDefLoader::beginFromEdge(), getDetectorEdge(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), loadJTRDefinitions(), RONetHandler::myEndElement(), RODFDetectorHandler::myStartElement(), ROJTRTurnDefLoader::myStartElement(), RONetHandler::parseBusStop(), RONetHandler::parseConnection(), RONetHandler::parseContainerStop(), RORouteHandler::parseEdges(), RORouteHandler::parseFromViaTo(), AGActivityGenHandler::parseStreets(), RORouteHandler::routePedestrian(), ROMAAssignments::sue(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
const std::map< std::string, ROEdge * > & RONet::getEdgeMap () const inherited
Definition at line 541 of file RONet.cpp.
References NamedObjectCont< T >::getMyMap(), and RONet::myEdges.
Referenced by buildApproachList(), AGCity::completeStreets(), initNet(), ROLoader::loadWeights(), and ROMAAssignments::sue().
size_t RONet::getEdgeNo () const inherited
Returns the total number of edges the network contains including internal edges.
Definition at line 529 of file RONet.cpp.
References RONet::myEdges, and NamedObjectCont< T >::size().
Referenced by computeAllPairs(), computeRoutes(), and main().
int RONet::getInternalEdgeNumber () const inherited
Returns the number of internal edges the network contains.
Definition at line 535 of file RONet.cpp.
References RONet::myNumInternalEdges.
Referenced by computeAllPairs().
RONode* RONet::getNode (const std::string & id) const inline inherited
Retrieves an node from the network.
Parameters
[in] name The name of the node to retrieve
Returns
The named node if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Definition at line 160 of file RONet.h.
References NamedObjectCont< T >::get(), and RONet::myNodes.
Referenced by RONetHandler::myEndElement(), RONetHandler::parseEdge(), and RONetHandler::parseJunction().
RORouteDef* RONet::getRouteDef (const std::string & name) const inline inherited
Returns the named route definition.
Parameters
[in] name The name of the route definition to retrieve
Returns
The named route definition if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Rename myRoutes to myRouteDefinitions
Definition at line 290 of file RONet.h.
References NamedObjectCont< T >::get(), and RONet::myRoutes.
Referenced by RONet::checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeRoute(), RORouteHandler::closeVehicle(), RORouteHandler::openRoute(), and RORouteHandler::openRouteDistribution().
OutputDevice* RONet::getRouteOutput (const bool alternative = false) inline inherited
Definition at line 394 of file RONet.h.
References RONet::myRouteAlternativesOutput, and RONet::myRoutesOutput.
Referenced by computeRoutes().
ROVehicleCont& RONet::getVehicles () inline protected inherited
return vehicles for use by RouteAggregator
Definition at line 407 of file RONet.h.
References RONet::myVehicles.
Referenced by RORouteAggregator::processAllRoutes().
SUMOVTypeParameter * RONet::getVehicleTypeSecure (const std::string & id) inherited
Retrieves the named vehicle type.
If the name is "" the default type is returned. If the named vehicle type (or typeDistribution) was not added to the net before 0 is returned
Parameters
[in] id The id of the vehicle type to return
Returns
The named vehicle type
Todo:
Check whether a const pointer may be returned
Definition at line 217 of file RONet.cpp.
References DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), RONet::myDefaultVTypeMayBeDeleted, RONet::myVehicleTypes, and RONet::myVTypeDistDict.
Referenced by RONet::checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeVehicle(), computeRoutes(), RORouteHandler::openVehicleTypeDistribution(), and ROMAAssignments::ROMAAssignments().
bool RODFNet::hasApproached (ROEdge * edge) const protected
Definition at line 651 of file RODFNet.cpp.
References myApproachedEdges.
Referenced by computeRoutesFor(), and isDestination().
bool RODFNet::hasApproaching (ROEdge * edge) const protected
Definition at line 642 of file RODFNet.cpp.
References myApproachingEdges.
Referenced by isSource().
bool RODFNet::hasDetector (ROEdge * edge) const
Definition at line 660 of file RODFNet.cpp.
References myDetectorsOnEdges.
Referenced by RODFDetector::buildDestinationDistribution(), computeRoutesFor(), RODFDetector::computeSplitProbabilities(), isDestination(), isFalseSource(), isSource(), and revalidateFlows().
bool RODFNet::hasInBetweenDetectorsOnly (ROEdge * edge, const RODFDetectorCon & detectors) const protected
Definition at line 153 of file RODFNet.cpp.
References BETWEEN_DETECTOR, RODFDetectorCon::getDetector(), RODFDetector::getType(), and myDetectorsOnEdges.
Referenced by computeRoutesFor().
bool RONet::hasRestrictions () const inherited
Definition at line 547 of file RONet.cpp.
References RONet::myHaveRestrictions.
Referenced by computeRoutes().
bool RODFNet::hasSourceDetector (ROEdge * edge, const RODFDetectorCon & detectors) const protected
Definition at line 169 of file RODFNet.cpp.
References RODFDetectorCon::getDetector(), RODFDetector::getType(), myDetectorsOnEdges, and SOURCE_DETECTOR.
Referenced by computeRoutesFor().
bool RODFNet::isDestination (const RODFDetector & det, const RODFDetectorCon & detectors) const protected
Definition at line 698 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), and isDestination().
bool RODFNet::isDestination (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors) const protected
Definition at line 808 of file RODFNet.cpp.
References getAbsPos(), RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeed(), hasApproached(), hasDetector(), isDestination(), myAmInHighwayMode, myApproachedEdges, myDetectorEdges, myDetectorsOnEdges, and WRITE_WARNING.
bool RODFNet::isFalseSource (const RODFDetector & det, const RODFDetectorCon & detectors) const protected
Definition at line 691 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), and isFalseSource().
bool RODFNet::isFalseSource (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors) const protected
Definition at line 884 of file RODFNet.cpp.
References BETWEEN_DETECTOR, RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeed(), RODFDetector::getType(), hasDetector(), isFalseSource(), myAmInHighwayMode, myApproachedEdges, myDetectorsOnEdges, SINK_DETECTOR, SOURCE_DETECTOR, and WRITE_WARNING.
bool RODFNet::isSource (const RODFDetector & det, const RODFDetectorCon & detectors, bool strict) const protected
Definition at line 683 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), and isSource().
bool RODFNet::isSource (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors, bool strict) const protected
Definition at line 705 of file RODFNet.cpp.
References getAbsPos(), RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeed(), hasApproaching(), hasDetector(), isSource(), myAmInHighwayMode, myApproachingEdges, myDetectorEdges, myDetectorsOnEdges, and WRITE_WARNING.
void RODFNet::mesoJoin (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 1053 of file RODFNet.cpp.
References buildDetectorEdgeDependencies(), RODFDetectorCon::getDetector(), RODFDetector::getPos(), RODFDetectorFlows::mesoJoin(), RODFDetectorCon::mesoJoin(), myDetectorsOnEdges, and SUMOReal.
void RONet::openOutput (const std::string & filename, const std::string altFilename, const std::string typeFilename) inherited
Opens the output for computed routes.
If the second parameter is set, a second file for route alternatives will be opened. If one of the file outputs can not be build, an IOError is thrown.
Parameters
[in] filename The (base) name of the file(s) to create
[in] altFilename The name of the file for writing alternatives, "" means no alternatives
[in] filename The name of the vtype file to create, "" means no separate types
Definition at line 172 of file RONet.cpp.
References OutputDevice::getDevice(), RONet::myRouteAlternativesOutput, RONet::myRoutesOutput, RONet::myTypesOutput, SUMO_TAG_ROUTES, OutputDevice::writeAttr(), OutputDevice::writeHeader(), and OutputDevice::writeXMLHeader().
Referenced by computeRoutes().
void RODFNet::removeEmptyDetectors (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 589 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors(), RODFDetectorFlows::knows(), RODFDetectorCon::removeDetector(), RODFDetectorFlows::removeFlow(), and WRITE_MESSAGE.
Referenced by startComputation().
void RODFNet::reportEmptyDetectors (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 612 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors(), RODFDetectorFlows::knows(), and WRITE_MESSAGE.
Referenced by startComputation().
void RODFNet::revalidateFlows (const RODFDetectorCon & detectors, RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 575 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors().
Referenced by startComputation().
void RODFNet::revalidateFlows (const RODFDetector * detector, RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset) protected
Definition at line 427 of file RODFNet.cpp.
References RODFNet::IterationEdge::depth, RODFNet::IterationEdge::edge, getDetectorEdge(), RODFDetectorFlows::getFlowDefs(), RODFEdge::getFlows(), Named::getID(), hasDetector(), RODFDetectorFlows::knows(), myApproachedEdges, myApproachingEdges, FlowDef::qLKW, FlowDef::qPKW, RODFDetectorFlows::setFlows(), SUMOReal, FlowDef::vLKW, FlowDef::vPKW, and WRITE_WARNING.
SUMOTime RONet::saveAndRemoveRoutesUntil (OptionsCont & options, SUMOAbstractRouter< ROEdge, ROVehicle > & router, SUMOTime time) inherited
Computes routes described by their definitions and saves them.
As long as a vehicle with a departure time smaller than the given exists, its route is computed and it is written and removed from the internal container.
Parameters
[in] options The options used during this process
[in] router The router to use for routes computation
[in] time The time until which route definitions shall be processed
Returns
The last seen departure time>=time
Definition at line 424 of file RONet.cpp.
References RONet::checkFlows(), SUMOAbstractRouter< E, V >::clone(), RONet::computeRoute(), ROVehicleCont::erase(), NamedObjectCont< T >::erase(), OptionsCont::getBool(), ROVehicle::getDepart(), Named::getID(), ROVehicle::getID(), OptionsCont::getInt(), NamedObjectCont< T >::getMyMap(), ROVehicle::getRouteDefinition(), ROVehicle::getRoutingSuccess(), ROVehicleCont::getTopVehicle(), MIN3(), RONet::myContainers, RONet::myDiscardedRouteNo, RONet::myErrorHandler, RONet::myPersons, RONet::myReadRouteNo, RONet::myRouteAlternativesOutput, RONet::myRoutes, RONet::myRoutesOutput, RONet::myTypesOutput, RONet::myVehicles, RONet::myWrittenRouteNo, ROVehicle::saveAllAsXML(), ROVehicle::saveTypeAsXML(), NamedObjectCont< T >::size(), SUMOTime_MAX, toString(), WRITE_MESSAGE, and OutputDevice::writePreformattedTag().
Referenced by ROLoader::processAllRoutesWithBulkRouter(), and ROLoader::processRoutes().
void RONet::setRestrictionFound () inherited
Definition at line 553 of file RONet.cpp.
References RONet::myHaveRestrictions.
Referenced by RONetHandler::parseLane().
Field Documentation
bool RODFNet::myAmInHighwayMode private
Definition at line 169 of file RODFNet.h.
Referenced by computeRoutesFor(), isDestination(), isFalseSource(), and isSource().
std::map<ROEdge*, ROEdgeVector > RODFNet::myApproachedEdges private
Map of edge name->list of names of edges approached by this edge.
Definition at line 164 of file RODFNet.h.
Referenced by buildApproachList(), computeRoutesFor(), hasApproached(), isDestination(), isFalseSource(), and revalidateFlows().
std::map<ROEdge*, ROEdgeVector > RODFNet::myApproachingEdges private
Map of edge name->list of names of this edge approaching edges.
Definition at line 161 of file RODFNet.h.
Referenced by buildApproachList(), hasApproaching(), isSource(), and revalidateFlows().
std::map<std::string, SUMOVehicleParameter::Stop*> RONet::myBusStops protected inherited
Known bus stops.
Definition at line 426 of file RONet.h.
Referenced by RONet::addBusStop(), and RONet::getBusStop().
ContainerMap RONet::myContainers protected inherited
Definition at line 457 of file RONet.h.
Referenced by RONet::addContainer(), RONet::furtherStored(), and RONet::saveAndRemoveRoutesUntil().
std::map<std::string, SUMOVehicleParameter::Stop*> RONet::myContainerStops protected inherited
Known container stops.
Definition at line 429 of file RONet.h.
Referenced by RONet::addContainerStop(), and RONet::getContainerStop().
bool RONet::myDefaultVTypeMayBeDeleted protected inherited
Whether no vehicle type was loaded.
Definition at line 440 of file RONet.h.
Referenced by RONet::checkVType(), and RONet::getVehicleTypeSecure().
std::map<std::string, std::vector<SUMOTime> > RONet::myDepartures protected inherited
Departure times for randomized flows.
Definition at line 460 of file RONet.h.
Referenced by RONet::addFlow(), and RONet::checkFlows().
std::map<std::string, ROEdge*> RODFNet::myDetectorEdges mutable private
Definition at line 167 of file RODFNet.h.
Referenced by buildDetectorDependencies(), buildDetectorEdgeDependencies(), isDestination(), and isSource().
std::map<ROEdge*, std::vector<std::string>, idComp> RODFNet::myDetectorsOnEdges mutable private
Definition at line 166 of file RODFNet.h.
Referenced by buildDetectorDependencies(), buildDetectorEdgeDependencies(), buildEdgeFlowMap(), buildRoutes(), getDetectorList(), hasDetector(), hasInBetweenDetectorsOnly(), hasSourceDetector(), isDestination(), isFalseSource(), isSource(), and mesoJoin().
std::vector<std::string> RODFNet::myDisallowedEdges private
List of ids of edges that shall not be used.
Definition at line 173 of file RODFNet.h.
Referenced by buildApproachList(), and RODFNet().
unsigned int RONet::myDiscardedRouteNo protected inherited
The number of discarded routes.
Definition at line 478 of file RONet.h.
Referenced by RONet::saveAndRemoveRoutesUntil().
std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string> > > RONet::myDistricts protected inherited
traffic assignment zones with sources and sinks
Definition at line 463 of file RONet.h.
Referenced by RONet::addDistrict(), RONet::addDistrictEdge(), and RONet::getDistricts().
NamedObjectCont<ROEdge*> RONet::myEdges protected inherited
Known edges.
Definition at line 423 of file RONet.h.
Referenced by RONet::addEdge(), RONet::getEdge(), RONet::getEdgeMap(), RONet::getEdgeNo(), and RONet::~RONet().
MsgHandler* RONet::myErrorHandler protected inherited
handler for ignorable error messages
Definition at line 490 of file RONet.h.
Referenced by RONet::saveAndRemoveRoutesUntil().
NamedObjectCont<SUMOVehicleParameter*> RONet::myFlows protected inherited
Known flows.
Definition at line 449 of file RONet.h.
Referenced by RONet::addFlow(), RONet::checkFlows(), and RONet::furtherStored().
bool RONet::myHaveRestrictions protected inherited
Whether the network contains edges which not all vehicles may pass.
Definition at line 484 of file RONet.h.
Referenced by RONet::hasRestrictions(), and RONet::setRestrictionFound().
size_t RODFNet::myInBetweenNumber mutable private
Definition at line 170 of file RODFNet.h.
Referenced by computeTypes().
size_t RODFNet::myInvalidNumber mutable private
Definition at line 170 of file RODFNet.h.
Referenced by computeTypes().
bool RODFNet::myKeepTurnarounds private
Definition at line 176 of file RODFNet.h.
Referenced by buildApproachList(), and RODFNet().
NamedObjectCont<RONode*> RONet::myNodes protected inherited
Known nodes.
Definition at line 420 of file RONet.h.
Referenced by RONet::addNode(), RONet::getNode(), and RONet::~RONet().
int RONet::myNumInternalEdges protected inherited
The number of internal edges in the dictionary.
Definition at line 487 of file RONet.h.
Referenced by RONet::addEdge(), and RONet::getInternalEdgeNumber().
PersonMap RONet::myPersons protected inherited
Definition at line 453 of file RONet.h.
Referenced by RONet::addPerson(), RONet::furtherStored(), and RONet::saveAndRemoveRoutesUntil().
unsigned int RONet::myReadRouteNo protected inherited
The number of read routes.
Definition at line 475 of file RONet.h.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
OutputDevice* RONet::myRouteAlternativesOutput protected inherited
The file to write the computed route alternatives into.
Definition at line 469 of file RONet.h.
Referenced by RONet::cleanup(), RONet::getRouteOutput(), RONet::openOutput(), and RONet::saveAndRemoveRoutesUntil().
NamedObjectCont<RORouteDef*> RONet::myRoutes protected inherited
Known routes.
Definition at line 443 of file RONet.h.
Referenced by RONet::addRouteDef(), RONet::getRouteDef(), RONet::saveAndRemoveRoutesUntil(), and RONet::~RONet().
OutputDevice* RONet::myRoutesOutput protected inherited
The file to write the computed routes into.
Definition at line 466 of file RONet.h.
Referenced by RONet::cleanup(), RONet::getRouteOutput(), RONet::openOutput(), and RONet::saveAndRemoveRoutesUntil().
size_t RODFNet::mySinkNumber mutable private
Definition at line 170 of file RODFNet.h.
Referenced by computeTypes().
size_t RODFNet::mySourceNumber mutable private
Definition at line 170 of file RODFNet.h.
Referenced by computeTypes().
OutputDevice* RONet::myTypesOutput protected inherited
The file to write the vehicle types into.
Definition at line 472 of file RONet.h.
Referenced by RONet::cleanup(), RONet::openOutput(), and RONet::saveAndRemoveRoutesUntil().
ROVehicleCont RONet::myVehicles protected inherited
Known vehicles.
Definition at line 446 of file RONet.h.
Referenced by RONet::addVehicle(), RONet::furtherStored(), RONet::getVehicles(), RONet::saveAndRemoveRoutesUntil(), and RONet::~RONet().
NamedObjectCont<SUMOVTypeParameter*> RONet::myVehicleTypes protected inherited
Known vehicle types.
Definition at line 432 of file RONet.h.
Referenced by RONet::addVehicleType(), RONet::checkVType(), RONet::getVehicleTypeSecure(), RONet::RONet(), and RONet::~RONet().
std::set<std::string> RONet::myVehIDs protected inherited
Known vehicle ids.
Definition at line 417 of file RONet.h.
Referenced by RONet::addVehicle().
VTypeDistDictType RONet::myVTypeDistDict protected inherited
A distribution of vehicle types (probability->vehicle type)
Definition at line 437 of file RONet.h.
Referenced by RONet::addVTypeDistribution(), RONet::checkVType(), and RONet::getVehicleTypeSecure().
unsigned int RONet::myWrittenRouteNo protected inherited
The number of written routes.
Definition at line 481 of file RONet.h.
Referenced by RONet::saveAndRemoveRoutesUntil().
The documentation for this class was generated from the following files:
RODFNet.h
RODFNet.cpp