SUMO - Simulation of Urban MObility: PedestrianEdge< E, L, N > Class Template Reference
PedestrianEdge< E, L, N > Class Template Reference
the edge type that is given to the internal router (SUMOAbstractRouter)
#include <PedestrianRouter.h>
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const E * getEdge () const
const std::string & getID () const
Returns the id.
bool includeInRoute (bool allEdges) const
void setID (const std::string &newID)
resets the id
Static Public Member Functions
static void cleanup ()
static size_t dictSize ()
static PedestrianEdge * getArrivalEdge (const E *e)
Returns the arriving Pedestrian edge.
static const EdgePair & getBothDirections (const E *e)
Returns the pair of forward and backward edge.
static PedestrianEdge * getDepartEdge (const E *e)
Returns the departing Pedestrian edge.
static SUMOReal getEffort (const PedestrianEdge *const edge, const PedestrianTrip< E, N > *const trip, SUMOReal time)
static void initPedestrianNetwork (size_t noE)
Protected Attributes
std::string myID
The name of the object.
Private Types
typedef std::pair
< PedestrianEdge
*, PedestrianEdge * > EdgePair
Private Member Functions
PedestrianEdge (unsigned int numericalID, const E *edge, const L *lane, bool forward, bool connector=false)
Private Attributes
bool myAmConnector
the direction of this edge
const E * myEdge
the original edge
std::vector< PedestrianEdge * > myFollowingEdges
List of edges that may be approached from this edge.
bool myForward
the direction of this edge
const L * myLane
the original edge
unsigned int myNumericalID
the index in myEdgeDict
Static Private Attributes
static std::map< const E
*, EdgePair > myBidiLookup
retrieve the forward and backward edge for the given input edge E
static std::vector
< PedestrianEdge > myEdgeDict
the edge dictionary
static std::map< const E
*, EdgePair > myFromToLookup
retrieve the depart and arrival edge for the given input edge E
The interface as required by SUMOAbstractRouter routes
static const PedestrianEdge * dictionary (size_t index)
Returns the PedstrianEdge with the given numericalID.
unsigned int getNumericalID () const
unsigned int getNumSuccessors () const
const std::vector
< PedestrianEdge * > & getSuccessors () const
const std::vector
< PedestrianEdge * > & getSuccessors (SUMOVehicleClass) const
bool prohibits (const PedestrianTrip< E, N > *const trip) const
Detailed Description
template<class E, class L, class N>
class PedestrianEdge< E, L, N >
the edge type that is given to the internal router (SUMOAbstractRouter)
Definition at line 109 of file PedestrianRouter.h.
Member Typedef Documentation
template<class E , class L , class N > typedef std::pair<PedestrianEdge*, PedestrianEdge*> PedestrianEdge< E, L, N >::EdgePair private
Definition at line 110 of file PedestrianRouter.h.
Constructor & Destructor Documentation
template<class E , class L , class N > PedestrianEdge< E, L, N >::PedestrianEdge (unsigned int numericalID, const E * edge, const L * lane, bool forward, bool connector = false) inline private
Definition at line 405 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::initPedestrianNetwork().
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
template<class E , class L , class N > static void PedestrianEdge< E, L, N >::cleanup () inline static
Definition at line 120 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myBidiLookup, PedestrianEdge< E, L, N >::myEdgeDict, and PedestrianEdge< E, L, N >::myFromToLookup.
Referenced by MSNet::clearAll().
template<class E , class L , class N > static const PedestrianEdge* PedestrianEdge< E, L, N >::dictionary (size_t index) inline static
Returns the PedstrianEdge with the given numericalID.
Definition at line 336 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myEdgeDict.
template<class E , class L , class N > static size_t PedestrianEdge< E, L, N >::dictSize () inline static
Definition at line 116 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myEdgeDict.
Referenced by PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::PedestrianRouter().
template<class E , class L , class N > static PedestrianEdge* PedestrianEdge< E, L, N >::getArrivalEdge (const E * e) inline static
Returns the arriving Pedestrian edge.
Definition at line 319 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myFromToLookup.
Referenced by PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::compute(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
template<class E , class L , class N > static const EdgePair& PedestrianEdge< E, L, N >::getBothDirections (const E * e) inline static
Returns the pair of forward and backward edge.
Definition at line 299 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myBidiLookup.
Referenced by PedestrianEdge< E, L, N >::initPedestrianNetwork(), and PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::prohibit().
template<class E , class L , class N > static PedestrianEdge* PedestrianEdge< E, L, N >::getDepartEdge (const E * e) inline static
Returns the departing Pedestrian edge.
Definition at line 309 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myFromToLookup.
Referenced by PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::compute(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
template<class E , class L , class N > const E* PedestrianEdge< E, L, N >::getEdge () const inline
Definition at line 294 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myEdge.
template<class E , class L , class N > static SUMOReal PedestrianEdge< E, L, N >::getEffort (const PedestrianEdge< E, L, N > *const edge, const PedestrianTrip< E, N > *const trip, SUMOReal time) inline static
Definition at line 370 of file PedestrianRouter.h.
References PedestrianTrip< E, N >::arrivalPos, PedestrianTrip< E, N >::departPos, PedestrianTrip< E, N >::departTime, PedestrianTrip< E, N >::from, Named::getID(), PedestrianTrip< E, N >::getID(), LINKSTATE_TL_RED, MAX2(), PedestrianEdge< E, L, N >::myAmConnector, PedestrianEdge< E, L, N >::myEdge, PedestrianEdge< E, L, N >::myForward, PedestrianEdge< E, L, N >::myLane, POSITION_EPS, PedestrianTrip< E, N >::speed, SUMOReal, TL_RED_PENALTY, and PedestrianTrip< E, N >::to.
Referenced by PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::PedestrianRouter().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
template<class E , class L , class N > unsigned int PedestrianEdge< E, L, N >::getNumericalID () const inline
Definition at line 331 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myNumericalID.
template<class E , class L , class N > unsigned int PedestrianEdge< E, L, N >::getNumSuccessors () const inline
Definition at line 341 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myFollowingEdges.
template<class E , class L , class N > const std::vector<PedestrianEdge*>& PedestrianEdge< E, L, N >::getSuccessors () const inline
Definition at line 345 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myFollowingEdges.
template<class E , class L , class N > const std::vector<PedestrianEdge*>& PedestrianEdge< E, L, N >::getSuccessors (SUMOVehicleClass) const inline
Definition at line 349 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myFollowingEdges.
template<class E , class L , class N > bool PedestrianEdge< E, L, N >::includeInRoute (bool allEdges) const inline
Definition at line 290 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myAmConnector, and PedestrianEdge< E, L, N >::myEdge.
template<class E , class L , class N > static void PedestrianEdge< E, L, N >::initPedestrianNetwork (size_t noE) inline static
Definition at line 126 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::getArrivalEdge(), PedestrianEdge< E, L, N >::getBothDirections(), PedestrianEdge< E, L, N >::getDepartEdge(), Named::getID(), PedestrianEdge< E, L, N >::myBidiLookup, PedestrianEdge< E, L, N >::myEdgeDict, PedestrianEdge< E, L, N >::myFollowingEdges, PedestrianEdge< E, L, N >::myFromToLookup, and PedestrianEdge< E, L, N >::PedestrianEdge().
Referenced by PedestrianRouter< E, L, N, DijkstraRouterTT< PedestrianEdge< E, L, N >, PedestrianTrip< E, N >, prohibited_withRestrictions< PedestrianEdge< E, L, N >, PedestrianTrip< E, N > > > >::PedestrianRouter().
template<class E , class L , class N > bool PedestrianEdge< E, L, N >::prohibits (const PedestrianTrip< E, N > *const trip) const inline
Definition at line 354 of file PedestrianRouter.h.
References PedestrianEdge< E, L, N >::myEdge, and PedestrianTrip< E, N >::node.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
Field Documentation
template<class E , class L , class N > bool PedestrianEdge< E, L, N >::myAmConnector private
the direction of this edge
Definition at line 427 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getEffort(), and PedestrianEdge< E, L, N >::includeInRoute().
template<class E , class L , class N > std::map< const E *, typename PedestrianEdge< E, L, N >::EdgePair > PedestrianEdge< E, L, N >::myBidiLookup static private
retrieve the forward and backward edge for the given input edge E
Definition at line 436 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::cleanup(), PedestrianEdge< E, L, N >::getBothDirections(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
template<class E , class L , class N > const E* PedestrianEdge< E, L, N >::myEdge private
the original edge
Definition at line 418 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getEdge(), PedestrianEdge< E, L, N >::getEffort(), PedestrianEdge< E, L, N >::includeInRoute(), and PedestrianEdge< E, L, N >::prohibits().
template<class E , class L , class N > std::vector< PedestrianEdge< E, L, N > > PedestrianEdge< E, L, N >::myEdgeDict static private
the edge dictionary
Definition at line 433 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::cleanup(), PedestrianEdge< E, L, N >::dictionary(), PedestrianEdge< E, L, N >::dictSize(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
template<class E , class L , class N > std::vector<PedestrianEdge*> PedestrianEdge< E, L, N >::myFollowingEdges private
List of edges that may be approached from this edge.
Definition at line 430 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getNumSuccessors(), PedestrianEdge< E, L, N >::getSuccessors(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
template<class E , class L , class N > bool PedestrianEdge< E, L, N >::myForward private
the direction of this edge
Definition at line 424 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getEffort().
template<class E , class L , class N > std::map< const E *, typename PedestrianEdge< E, L, N >::EdgePair > PedestrianEdge< E, L, N >::myFromToLookup static private
retrieve the depart and arrival edge for the given input edge E
Definition at line 439 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::cleanup(), PedestrianEdge< E, L, N >::getArrivalEdge(), PedestrianEdge< E, L, N >::getDepartEdge(), and PedestrianEdge< E, L, N >::initPedestrianNetwork().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
template<class E , class L , class N > const L* PedestrianEdge< E, L, N >::myLane private
the original edge
Definition at line 421 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getEffort().
template<class E , class L , class N > unsigned int PedestrianEdge< E, L, N >::myNumericalID private
the index in myEdgeDict
Definition at line 415 of file PedestrianRouter.h.
Referenced by PedestrianEdge< E, L, N >::getNumericalID().
The documentation for this class was generated from the following file:
PedestrianRouter.h