SUMO - Simulation of Urban MObility: MSEdge::container_by_position_sorter Class Reference
MSEdge::container_by_position_sorter Class Reference
Sorts containers by their positions.
#include <MSEdge.h>
Public Member Functions
container_by_position_sorter (SUMOTime timestep)
constructor
int operator() (const MSContainer *const c1, const MSContainer *const c2) const
comparing operator
Private Attributes
SUMOTime myTime
Detailed Description
Sorts containers by their positions.
Definition at line 676 of file MSEdge.h.
Constructor & Destructor Documentation
MSEdge::container_by_position_sorter::container_by_position_sorter (SUMOTime timestep) inline explicit
constructor
Definition at line 679 of file MSEdge.h.
Member Function Documentation
int MSEdge::container_by_position_sorter::operator() (const MSContainer *const c1, const MSContainer *const c2) const
comparing operator
Definition at line 674 of file MSEdge.cpp.
References MSContainer::getCurrentStage(), MSContainer::MSContainerStage::getEdgePos(), MSContainer::getID(), and SUMOReal.
Field Documentation
SUMOTime MSEdge::container_by_position_sorter::myTime private
Definition at line 684 of file MSEdge.h.
The documentation for this class was generated from the following files:
MSEdge.h
MSEdge.cpp