SUMO - Simulation of Urban MObility: DijkstraRouterTT< E, V, PF > Class Template Reference
DijkstraRouterTT< E, V, PF > Class Template Reference
Computes the shortest path through a network using the Dijkstra algorithm.
#include <DijkstraRouterTT.h>
Data Structures
struct EdgeInfo
class EdgeInfoByTTComparator
Public Types
typedef SUMOReal(* Operation)(const E *const, const V *const, SUMOReal)
Public Member Functions
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual SUMOAbstractRouter< E,
V > * clone () const
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouterTT (size_t noE, bool unbuildIsWarning, Operation operation)
Constructor.
void endQuery (int visits)
const EdgeInfo & getEdgeInfo (size_t index) const
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
void init ()
virtual void prepare (const E *, const V *, bool)
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void startQuery ()
virtual ~DijkstraRouterTT ()
Destructor.
Protected Attributes
Operation myOperation
The object's operation to perform.
Private Attributes
EdgeInfoByTTComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterTT< E, V, PF >
Computes the shortest path through a network using the Dijkstra algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withRestrictions/prohibited_noRestrictions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 71 of file DijkstraRouterTT.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef SUMOReal(* DijkstraRouterTT< E, V, PF >::Operation)(const E *const, const V *const, SUMOReal)
Definition at line 74 of file DijkstraRouterTT.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> DijkstraRouterTT< E, V, PF >::DijkstraRouterTT (size_t noE, bool unbuildIsWarning, Operation operation) inline
Constructor.
Definition at line 76 of file DijkstraRouterTT.h.
template<class E, class V, class PF> virtual DijkstraRouterTT< E, V, PF >::~DijkstraRouterTT () inline virtual
Destructor.
Definition at line 85 of file DijkstraRouterTT.h.
Member Function Documentation
template<class E, class V, class PF> void DijkstraRouterTT< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 238 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* DijkstraRouterTT< E, V, PF >::clone () const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 87 of file DijkstraRouterTT.h.
template<class E, class V, class PF> virtual void DijkstraRouterTT< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 150 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> const EdgeInfo& DijkstraRouterTT< E, V, PF >::getEdgeInfo (size_t index) const inline
Definition at line 247 of file DijkstraRouterTT.h.
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::recomputeCosts(), BulkStarRouter< E, V, PF >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> void DijkstraRouterTT< E, V, PF >::init () inline
Definition at line 135 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V> virtual void SUMOAbstractRouter< E, V >::prepare (const E * , const V * , bool) inline virtual inherited
Reimplemented in BulkStarRouter< E, V, PF >.
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by RORouteAggregator::processAllRoutes().
template<class E, class V, class PF> SUMOReal DijkstraRouterTT< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 224 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), BulkStarRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V, class PF> EdgeInfoByTTComparator DijkstraRouterTT< E, V, PF >::myComparator private
Definition at line 260 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouterTT< E, V, PF >::myEdgeInfos private
The container of edge information.
Definition at line 253 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::DijkstraRouterTT(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::getEdgeInfo().
template<class E, class V, class PF> MsgHandler* const DijkstraRouterTT< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 263 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTT< E, V, PF >::myFound private
list of visited Edges (for resetting)
Definition at line 258 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTT< E, V, PF >::myFrontierList private
A container for reusage of the min edge heap.
Definition at line 256 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::init().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withRestrictions< MSEdge, SUMOVehicle > >::clone(), CHRouterWrapper< E, V, PF >::clone(), BulkStarRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, PedestrianTrip< E, N > >::getEffort().
The documentation for this class was generated from the following file:
DijkstraRouterTT.h