SUMO - Simulation of Urban MObility: GUIContainerStop Class Reference
GUIContainerStop Class Reference
A lane area vehicles can halt at (gui-version)
#include <GUIContainerStop.h>
Public Member Functions
void addContainer (MSContainer *container)
Adds a container to this stop.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
void enter (SUMOVehicle *what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
SUMOReal getBeginLanePosition () const
Returns the begin position of this container stop.
unsigned int getContainerNumber () const
Returns the number of containers waiting on this stop.
SUMOReal getEndLanePosition () const
Returns the end position of this container stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this container stop is located at.
SUMOReal getLastFreePos (const SUMOVehicle &forVehicle) const
Returns the last free position on this stop.
GUIContainerStop (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, SUMOReal frompos, SUMOReal topos)
Constructor.
void leaveFrom (SUMOVehicle *what)
Called if a vehicle leaves this stop.
void removeContainer (MSContainer *container)
Removes a container from this stop.
void setID (const std::string &newID)
resets the id
~GUIContainerStop ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector
< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
SUMOReal myBegPos
The begin position this stop is located at.
SUMOReal myEndPos
The end position this stop is located at.
std::map< SUMOVehicle
*, std::pair< SUMOReal,
SUMOReal > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
MSLane & myLane
The lane this stop is located at.
SUMOReal myLastFreePos
The last free position at this stop (variable)
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
std::vector< MSContainer * > myWaitingContainers
Containers waiting at this stop.
Static Protected Attributes
static std::vector
< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string,
GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Attributes
PositionVector myFGShape
The shape.
std::vector< SUMOReal > myFGShapeLengths
The lengths of the shape parts.
std::vector< SUMOReal > myFGShapeRotations
The rotations of the shape parts.
Position myFGSignPos
The position of the sign.
SUMOReal myFGSignRot
The rotation of the sign.
Detailed Description
A lane area vehicles can halt at (gui-version)
This gui-version of a container-stop extends MSContainerStop by methods for displaying and interaction.
See Also
MSContainerStop
GUIGlObject_AbstractAdd
GUIGlObject
Definition at line 70 of file GUIContainerStop.h.
Constructor & Destructor Documentation
GUIContainerStop::GUIContainerStop (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, SUMOReal frompos, SUMOReal topos)
Constructor.
Parameters
[in] idStorage The gl-id storage for giving this object an gl-id
[in] id The id of the container stop
[in] lines Names of the container lines that halt on this container stop
[in] lane The lane the container stop is placed on
[in] begPos Begin position of the container stop on the lane
[in] endPos End position of the container stop on the lane
Definition at line 66 of file GUIContainerStop.cpp.
References Position::distanceTo(), PositionVector::getLineCenter(), MSLane::getShape(), PositionVector::getSubpart(), PositionVector::length(), PositionVector::move2side(), myFGShape, myFGShapeLengths, myFGShapeRotations, myFGSignPos, myFGSignRot, PI, PositionVector::rotationDegreeAtOffset(), SUMOReal, Position::x(), and Position::y().
GUIContainerStop::~GUIContainerStop ()
Destructor.
Definition at line 93 of file GUIContainerStop.cpp.
Member Function Documentation
void MSContainerStop::addContainer (MSContainer * container) inline inherited
Adds a container to this stop.
Definition at line 146 of file MSContainerStop.h.
References MSContainerStop::myWaitingContainers.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 65 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void MSContainerStop::computeLastFreePos () protected inherited
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 102 of file MSContainerStop.cpp.
References MSContainerStop::myEndPos, MSContainerStop::myEndPositions, and MSContainerStop::myLastFreePos.
Referenced by MSContainerStop::enter(), MSContainerStop::leaveFrom(), and MSContainerStop::MSContainerStop().
void GUIContainerStop::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See Also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 126 of file GUIContainerStop.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GLHelper::drawBoxLines(), GLHelper::drawFilledCircle(), GUIContainer::drawGL(), GUIGlObject::drawName(), GLHelper::drawText(), getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUIGlObject::getType(), MIN2(), myFGShape, myFGShapeLengths, myFGShapeRotations, myFGSignPos, myFGSignRot, MSContainerStop::myLines, MSContainerStop::myWaitingContainers, pfDrawString(), pfSetPosition(), pfSetScale(), GUIVisualizationSettings::scale, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), drawGL(), GUIBusStop::drawGL(), and GUIEdge::drawGL().
void MSContainerStop::enter (SUMOVehicle * what, SUMOReal beg, SUMOReal end) inherited
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that enters the container stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See Also
computeLastFreePos
Definition at line 78 of file MSContainerStop.cpp.
References MSContainerStop::computeLastFreePos(), and MSContainerStop::myEndPositions.
Referenced by MSVehicle::processNextStop().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 76 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
SUMOReal MSContainerStop::getBeginLanePosition () const inherited
Returns the begin position of this container stop.
Returns
The position the container stop begins at
Definition at line 66 of file MSContainerStop.cpp.
References MSContainerStop::myBegPos.
Referenced by MSRouteHandler::addStop(), and MSVehicle::processNextStop().
Boundary GUIContainerStop::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See Also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 179 of file GUIContainerStop.cpp.
References PositionVector::getBoxBoundary(), Boundary::grow(), and myFGShape.
Referenced by drawGL().
unsigned int MSContainerStop::getContainerNumber () const inline inherited
Returns the number of containers waiting on this stop.
Definition at line 141 of file MSContainerStop.h.
References MSContainerStop::myWaitingContainers.
Referenced by getParameterWindow().
SUMOReal MSContainerStop::getEndLanePosition () const inherited
Returns the end position of this container stop.
Returns
The position the container stop ends at
Definition at line 72 of file MSContainerStop.cpp.
References MSContainerStop::myEndPos.
Referenced by MSRouteHandler::addStop(), MSNet::getContainerStopID(), and MSVehicle::processNextStop().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIJunctionWrapper::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GUILane::getColorValue(), GUIVehicle::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), GUILane::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static inherited
Returns the list of gl-ids of all additional objects.
Definition at line 99 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
const MSLane & MSContainerStop::getLane () const inherited
Returns the lane this container stop is located at.
Returns
Reference to the lane the container stop is located at
Definition at line 60 of file MSContainerStop.cpp.
References MSContainerStop::myLane.
Referenced by MSRouteHandler::addStop(), and MSNet::getContainerStopID().
SUMOReal MSContainerStop::getLastFreePos (const SUMOVehicle & forVehicle) const inherited
Returns the last free position on this stop.
Returns
The last free position of this container stop
Definition at line 85 of file MSContainerStop.cpp.
References MSVehicleType::getMinGap(), SUMOVehicle::getVehicleType(), MSContainerStop::myEndPos, and MSContainerStop::myLastFreePos.
Referenced by MSVehicle::processNextStop().
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 93 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
GUIParameterTableWindow * GUIContainerStop::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Container stops have no parameter windows (yet).
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window (always 0 in this case)
See Also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 111 of file GUIContainerStop.cpp.
References GUIParameterTableWindow::closeBuilding(), MSContainerStop::getContainerNumber(), GUIParameterTableWindow::mkItem(), MSContainerStop::myBegPos, and MSContainerStop::myEndPos.
GUIGLObjectPopupMenu * GUIContainerStop::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See Also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 97 of file GUIContainerStop.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUIJunctionWrapper::getColorValue(), GUILane::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUILane::getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
void MSContainerStop::leaveFrom (SUMOVehicle * what) inherited
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that leaves the container stop
See Also
computeLastFreePos
Definition at line 94 of file MSContainerStop.cpp.
References MSContainerStop::computeLastFreePos(), and MSContainerStop::myEndPositions.
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 86 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
void MSContainerStop::removeContainer (MSContainer * container) inline inherited
Removes a container from this stop.
Definition at line 151 of file MSContainerStop.h.
References MSContainerStop::myWaitingContainers.
Referenced by MSVehicle::processNextStop().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
SUMOReal MSContainerStop::myBegPos protected inherited
The begin position this stop is located at.
Definition at line 179 of file MSContainerStop.h.
Referenced by MSContainerStop::getBeginLanePosition(), and getParameterWindow().
SUMOReal MSContainerStop::myEndPos protected inherited
The end position this stop is located at.
Definition at line 182 of file MSContainerStop.h.
Referenced by MSContainerStop::computeLastFreePos(), MSContainerStop::getEndLanePosition(), MSContainerStop::getLastFreePos(), and getParameterWindow().
std::map<SUMOVehicle*, std::pair<SUMOReal, SUMOReal> > MSContainerStop::myEndPositions protected inherited
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 173 of file MSContainerStop.h.
Referenced by MSContainerStop::computeLastFreePos(), MSContainerStop::enter(), and MSContainerStop::leaveFrom().
PositionVector GUIContainerStop::myFGShape private
The shape.
Definition at line 141 of file GUIContainerStop.h.
Referenced by drawGL(), getCenteringBoundary(), and GUIContainerStop().
std::vector<SUMOReal> GUIContainerStop::myFGShapeLengths private
The lengths of the shape parts.
Definition at line 138 of file GUIContainerStop.h.
Referenced by drawGL(), and GUIContainerStop().
std::vector<SUMOReal> GUIContainerStop::myFGShapeRotations private
The rotations of the shape parts.
Definition at line 135 of file GUIContainerStop.h.
Referenced by drawGL(), and GUIContainerStop().
Position GUIContainerStop::myFGSignPos private
The position of the sign.
Definition at line 144 of file GUIContainerStop.h.
Referenced by drawGL(), and GUIContainerStop().
SUMOReal GUIContainerStop::myFGSignRot private
The rotation of the sign.
Definition at line 147 of file GUIContainerStop.h.
Referenced by drawGL(), and GUIContainerStop().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane& MSContainerStop::myLane protected inherited
The lane this stop is located at.
Definition at line 176 of file MSContainerStop.h.
Referenced by MSContainerStop::getLane().
SUMOReal MSContainerStop::myLastFreePos protected inherited
The last free position at this stop (variable)
Definition at line 185 of file MSContainerStop.h.
Referenced by MSContainerStop::computeLastFreePos(), and MSContainerStop::getLastFreePos().
std::vector<std::string> MSContainerStop::myLines protected inherited
The list of lines that are assigned to this stop.
Definition at line 170 of file MSContainerStop.h.
Referenced by drawGL().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::vector<MSContainer*> MSContainerStop::myWaitingContainers protected inherited
Containers waiting at this stop.
Definition at line 188 of file MSContainerStop.h.
Referenced by MSContainerStop::addContainer(), drawGL(), MSContainerStop::getContainerNumber(), and MSContainerStop::removeContainer().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIContainerStop.h
GUIContainerStop.cpp