SUMO - Simulation of Urban MObility: TraCIAPI::TrafficLightScope Class Reference
TraCIAPI::TrafficLightScope Class Reference
Scope for interaction with traffic lights.
#include <TraCIAPI.h>
Public Member Functions
std::vector< TraCIAPI::TraCILogic > getCompleteRedYellowGreenDefinition (const std::string &tlsID) const
std::vector< std::string > getControlledLanes (const std::string &tlsID) const
std::vector< TraCIAPI::TraCILink > getControlledLinks (const std::string &tlsID) const
std::vector< std::string > getIDList () const
unsigned int getNextSwitch (const std::string &tlsID) const
unsigned int getPhase (const std::string &tlsID) const
std::string getProgram (const std::string &tlsID) const
std::string getRedYellowGreenState (const std::string &tlsID) const
void setCompleteRedYellowGreenDefinition (const std::string &tlsID, const TraCIAPI::TraCILogic &logic) const
void setPhase (const std::string &tlsID, unsigned int index) const
void setPhaseDuration (const std::string &tlsID, unsigned int phaseDuration) const
void setProgram (const std::string &tlsID, const std::string &programID) const
void setRedYellowGreenState (const std::string &tlsID, const std::string &state) const
TrafficLightScope (TraCIAPI &parent)
virtual ~TrafficLightScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
TrafficLightScope & operator= (const TrafficLightScope &src)
invalidated assignment operator
TrafficLightScope (const TrafficLightScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with traffic lights.
Definition at line 563 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::TrafficLightScope::TrafficLightScope (TraCIAPI & parent) inline
Definition at line 565 of file TraCIAPI.h.
virtual TraCIAPI::TrafficLightScope::~TrafficLightScope () inline virtual
Definition at line 566 of file TraCIAPI.h.
TraCIAPI::TrafficLightScope::TrafficLightScope (const TrafficLightScope & src) private
invalidated copy constructor
Member Function Documentation
std::vector< TraCIAPI::TraCILogic > TraCIAPI::TrafficLightScope::getCompleteRedYellowGreenDefinition (const std::string & tlsID) const
Definition at line 1194 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), TL_COMPLETE_DEFINITION_RYG, and TYPE_COMPOUND.
std::vector< std::string > TraCIAPI::TrafficLightScope::getControlledLanes (const std::string & tlsID) const
Definition at line 1229 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and TL_CONTROLLED_LANES.
std::vector< TraCIAPI::TraCILink > TraCIAPI::TrafficLightScope::getControlledLinks (const std::string & tlsID) const
Definition at line 1234 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), TL_CONTROLLED_LINKS, and TYPE_COMPOUND.
std::vector< std::string > TraCIAPI::TrafficLightScope::getIDList () const
Definition at line 1184 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and ID_LIST.
unsigned int TraCIAPI::TrafficLightScope::getNextSwitch (const std::string & tlsID) const
Definition at line 1263 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and TL_NEXT_SWITCH.
unsigned int TraCIAPI::TrafficLightScope::getPhase (const std::string & tlsID) const
Definition at line 1258 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and TL_CURRENT_PHASE.
std::string TraCIAPI::TrafficLightScope::getProgram (const std::string & tlsID) const
Definition at line 1253 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and TL_CURRENT_PROGRAM.
std::string TraCIAPI::TrafficLightScope::getRedYellowGreenState (const std::string & tlsID) const
Definition at line 1189 of file TraCIAPI.cpp.
References CMD_GET_TL_VARIABLE, and TL_RED_YELLOW_GREEN_STATE.
TrafficLightScope& TraCIAPI::TrafficLightScope::operator= (const TrafficLightScope & src) private
invalidated assignment operator
void TraCIAPI::TrafficLightScope::setCompleteRedYellowGreenDefinition (const std::string & tlsID, const TraCIAPI::TraCILogic & logic) const
Definition at line 1301 of file TraCIAPI.cpp.
References CMD_SET_TL_VARIABLE, TraCIAPI::TraCILogic::currentPhaseIndex, TraCIAPI::TraCILogic::phases, TraCIAPI::TraCILogic::subID, TL_COMPLETE_PROGRAM_RYG, TraCIAPI::TraCILogic::type, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::TrafficLightScope::setPhase (const std::string & tlsID, unsigned int index) const
Definition at line 1277 of file TraCIAPI.cpp.
References CMD_SET_TL_VARIABLE, TL_PHASE_INDEX, TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::TrafficLightScope::setPhaseDuration (const std::string & tlsID, unsigned int phaseDuration) const
Definition at line 1293 of file TraCIAPI.cpp.
References CMD_SET_TL_VARIABLE, TL_PHASE_DURATION, TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::TrafficLightScope::setProgram (const std::string & tlsID, const std::string & programID) const
Definition at line 1285 of file TraCIAPI.cpp.
References CMD_SET_TL_VARIABLE, TL_PROGRAM, TYPE_STRING, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::TrafficLightScope::setRedYellowGreenState (const std::string & tlsID, const std::string & state) const
Definition at line 1269 of file TraCIAPI.cpp.
References CMD_SET_TL_VARIABLE, TL_RED_YELLOW_GREEN_STATE, TYPE_STRING, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 190 of file TraCIAPI.h.
Referenced by TraCIAPI::EdgeScope::getIDList().
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp