SUMO - Simulation of Urban MObility: TraCIServerAPI_GUI Class Reference
TraCIServerAPI_GUI Class Reference
APIs for getting/setting GUI values via TraCI.
#include <TraCIServerAPI_GUI.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xac: Get GUI Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xcc: Change GUI State)
Static Protected Member Functions
static GUIMainWindow * getMainWindow ()
Returns the main window.
static GUISUMOAbstractView * getNamedView (const std::string &id)
Returns the named view.
Private Member Functions
TraCIServerAPI_GUI & operator= (const TraCIServerAPI_GUI &s)
invalidated assignment operator
TraCIServerAPI_GUI (const TraCIServerAPI_GUI &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting GUI values via TraCI.
Definition at line 55 of file TraCIServerAPI_GUI.h.
Constructor & Destructor Documentation
TraCIServerAPI_GUI::TraCIServerAPI_GUI (const TraCIServerAPI_GUI & s) private
invalidated copy constructor
Member Function Documentation
GUIMainWindow * TraCIServerAPI_GUI::getMainWindow () static protected
Returns the main window.
Returns
The main window (should exist)
Definition at line 210 of file TraCIServerAPI_GUI.cpp.
Referenced by getNamedView(), and processGet().
GUISUMOAbstractView * TraCIServerAPI_GUI::getNamedView (const std::string & id) static protected
Returns the named view.
Parameters
[in] viewName The name of the view
Returns
The named view if existing, 0 otherwise
Definition at line 224 of file TraCIServerAPI_GUI.cpp.
References getMainWindow(), GUIGlChildWindow::getView(), and GUIMainWindow::getViewByID().
Referenced by processGet(), and processSet().
TraCIServerAPI_GUI& TraCIServerAPI_GUI::operator= (const TraCIServerAPI_GUI & s) private
invalidated assignment operator
bool TraCIServerAPI_GUI::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xac: Get GUI Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 55 of file TraCIServerAPI_GUI.cpp.
References CMD_GET_GUI_VARIABLE, GUISUMOAbstractView::getChanger(), GUISUMOAbstractView::getColoringSchemesCombo(), getMainWindow(), getNamedView(), GUIMainWindow::getViewIDs(), GUISUMOAbstractView::getVisibleBoundary(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), ID_LIST, POSITION_2D, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_GUI_VARIABLE, RTYPE_OK, text(), TYPE_BOUNDINGBOX, TYPE_DOUBLE, TYPE_STRING, TYPE_STRINGLIST, VAR_VIEW_BOUNDARY, VAR_VIEW_OFFSET, VAR_VIEW_SCHEMA, VAR_VIEW_ZOOM, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), tcpip::Storage::writeUnsignedByte(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUILoadThread::run().
bool TraCIServerAPI_GUI::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xcc: Change GUI State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 117 of file TraCIServerAPI_GUI.cpp.
References GUISUMOAbstractView::centerTo(), CMD_SET_GUI_VARIABLE, GUISUMOAbstractView::getChanger(), MSNet::getInstance(), getNamedView(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), GUISUMOAbstractView::makeSnapshot(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingBoundary(), TraCIServer::readTypeCheckingDouble(), TraCIServer::readTypeCheckingPosition2D(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, Position::set(), GUISUMOAbstractView::setColorScheme(), GUISUMOAbstractView::setViewport(), GUISUMOAbstractView::startTrack(), GUISUMOAbstractView::stopTrack(), VAR_SCREENSHOT, VAR_TRACK_VEHICLE, VAR_VIEW_BOUNDARY, VAR_VIEW_OFFSET, VAR_VIEW_SCHEMA, VAR_VIEW_ZOOM, GUIVehicle::VO_TRACKED, TraCIServer::writeErrorStatusCmd(), TraCIServer::writeStatusCmd(), Position::x(), and Position::y().
Referenced by GUILoadThread::run().
The documentation for this class was generated from the following files:
TraCIServerAPI_GUI.h
TraCIServerAPI_GUI.cpp