SUMO - Simulation of Urban MObility: GUIPolygon Class Reference
GUIPolygon Class Reference
#include <GUIPolygon.h>
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
const std::string & getID () const
Returns the id.
const std::map< std::string,
std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
GUIPolygon (const std::string &id, const std::string &type, const RGBColor &color, const PositionVector &shape, bool fill, SUMOReal layer=0, SUMOReal angle=0, const std::string &imgFile="")
Constructor.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setID (const std::string &newID)
resets the id
virtual void setShape (const PositionVector &shape)
set a new shape and update the tesselation
void writeXML (OutputDevice &out, bool geo=false)
~GUIPolygon ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Getter
const PositionVector & getShape () const
Returns whether the shape of the polygon.
bool getFill () const
Returns whether the polygon is filled.
Setter
void setFill (bool fill)
Sets whether the polygon shall be filled.
Getter
const std::string & getType () const
Returns the (abstract) type of the Shape.
const RGBColor & getColor () const
Returns the color of the Shape.
SUMOReal getLayer () const
Returns the layer of the Shape.
SUMOReal getAngle () const
Returns the angle of the Shape.
const std::string & getImgFile () const
Returns the imgFile of the Shape.
Setter
void setType (const std::string &type)
Sets a new type.
void setColor (const RGBColor &col)
Sets a new color.
void setLayer (const SUMOReal layer)
Sets a new layer.
void setAngle (const SUMOReal angle)
Sets a new angle.
void setImgFile (const std::string &imgFile)
Sets a new imgFile.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT)
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector
< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static const SUMOReal DEFAULT_ANGLE = 0
static const std::string DEFAULT_IMG_FILE = ""
static const SUMOReal DEFAULT_IMG_HEIGHT = 1
static const SUMOReal DEFAULT_IMG_WIDTH = 1
static const SUMOReal DEFAULT_LAYER = 128
static const std::string DEFAULT_TYPE = ""
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
SUMOReal myAngle
The angle of the Shape.
RGBColor myColor
The color of the Shape.
bool myFill
Information whether the polygon has to be filled.
std::string myID
The name of the object.
std::string myImgFile
The angle of the Shape.
SUMOReal myLayer
The layer of the Shape.
PositionVector myShape
The positions of the polygon.
std::string myType
The type of the Shape.
Static Protected Attributes
static std::vector
< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string,
GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Member Functions
void performTesselation (SUMOReal lineWidth) const
void storeTesselation (SUMOReal lineWidth) const
store the drawing commands in a display list
Private Attributes
GLuint myDisplayList
id of the display list for the cached tesselation
SUMOReal myLineWidth
the previous line width for deciding whether the display list must be refreshed
MFXMutex myLock
The mutex used to avoid concurrent updates of the shape.
Detailed Description
Definition at line 50 of file GUIPolygon.h.
Constructor & Destructor Documentation
GUIPolygon::GUIPolygon (const std::string & id, const std::string & type, const RGBColor & color, const PositionVector & shape, bool fill, SUMOReal layer = 0, SUMOReal angle = 0, const std::string & imgFile = "")
Constructor.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] fill Whether the polygon shall be filled
Definition at line 52 of file GUIPolygon.cpp.
GUIPolygon::~GUIPolygon ()
Destructor.
Definition at line 63 of file GUIPolygon.cpp.
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was opened.
Parameters
[in] w The opened parameter window
Definition at line 188 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
in,filled] cont The container to add this item to
Definition at line 121 of file Named.h.
References Named::StoringVisitor::add().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 126 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 135 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 116 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 167 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 145 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 179 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 158 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIVehicle::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 65 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIPolygon::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See Also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 140 of file GUIPolygon.cpp.
References GLHelper::debugVertices(), GUIGlObject::drawName(), PositionVector::getBoxBoundary(), Shape::getColor(), GUIVisualizationSizeSettings::getExaggeration(), SUMO::Polygon::getFill(), GUIGlObject::getGlID(), Boundary::getHeight(), Shape::getImgFile(), Shape::getLayer(), PositionVector::getPolygonCenter(), GUITexturesHelper::getTextureID(), Boundary::getWidth(), MAX2(), GUIVisualizationSizeSettings::minSize, myLock, SUMO::Polygon::myShape, performTesselation(), GUIVisualizationSettings::polyName, GUIVisualizationSettings::polySize, GUIVisualizationSettings::scale, GLHelper::setColor(), xPlane, and yPlane.
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const inline virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle, GUIPerson, and GUIContainer.
Definition at line 182 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
Definition at line 215 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIEdge::drawGL().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 76 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
SUMOReal Shape::getAngle () const inline inherited
Returns the angle of the Shape.
Returns
The Shape's rotation angle
Definition at line 94 of file Shape.h.
References Shape::myAngle.
Referenced by GUIPointOfInterest::drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
Boundary GUIPolygon::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See Also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 91 of file GUIPolygon.cpp.
References Boundary::add(), PositionVector::getBoxBoundary(), Boundary::grow(), and SUMO::Polygon::myShape.
const RGBColor& Shape::getColor () const inline inherited
Returns the color of the Shape.
Returns
The Shape's color
Definition at line 79 of file Shape.h.
References Shape::myColor.
Referenced by drawGL(), GUIPointOfInterest::drawGL(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
bool SUMO::Polygon::getFill () const inline inherited
Returns whether the polygon is filled.
Returns
Whether the polygon is filled
Definition at line 90 of file Polygon.h.
References SUMO::Polygon::myFill.
Referenced by drawGL(), performTesselation(), TraCIServerAPI_Polygon::processGet(), and SUMO::Polygon::writeXML().
const std::string& GUIGlObject::getFullName () const inline inherited
Returns the full name appearing in the tool tip.
Returns
This object's typed id
Definition at line 107 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inline inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 115 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIContainer::drawGL(), GUIPerson::drawGL(), drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIJunctionWrapper::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GUILane::getColorValue(), GUIVehicle::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIVehicle::getPopUpMenu(), GUILane::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), and GUIGlObject::~GUIGlObject().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 60 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), Named::StoringVisitor::add(), MSDetectorControl::add(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBEdge::addSidewalk(), NBDistrict::addSink(), NBDistrict::addSource(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), MSVehicle::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSContainer::MSContainerStage_Driving::beginEventOutput(), MSContainer::MSContainerStage_Waiting::beginEventOutput(), MSPerson::MSPersonStage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Waiting::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), NBNode::buildCrossings(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), NBNode::buildInnerEdges(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBNode::buildWalkingAreas(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSAbstractLaneChangeModel::continueLaneChangeManeuver(), NLDetectorBuilder::convUncontE2PosLength(), GUINet::createTLWrapper(), NIVissimDistrictConnection::dict_BuildDistricts(), MSContainer::MSContainerStage_Driving::endEventOutput(), MSContainer::MSContainerStage_Waiting::endEventOutput(), MSPerson::MSPersonStage_Driving::endEventOutput(), MSPerson::MSPersonStage_Waiting::endEventOutput(), MSE3Collector::enter(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSNet::getBusStopID(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), PedestrianEdge< E, L, N >::getEffort(), NBEdge::getFirstNonPedestrianLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPModel_Striping::getNextLane(), GUIVehicle::getParameterWindow(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), MSVehicleControl::getWaitingVehicle(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollision(), NBEdgeCont::ignoreFilterMatch(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), PedestrianEdge< E, L, N >::initPedestrianNetwork(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), NIImporter_OpenDrive::loadNetwork(), ODDistrictCont::makeDistricts(), MSPModel_Striping::moveInDirection(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSContainer::MSContainerStage_Waiting::MSContainerStage_Waiting(), MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_Example::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Container::notifyLeave(), MSDevice_Person::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSDevice_BTreceiver::notifyMove(), GUIViewTraffic::onGamingClick(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_JE2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSRightOfWayJunction::postloadInit(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBNodeCont::rename(), NBEdgeCont::rename(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), PCPolyContainer::save(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), NIXMLEdgesHandler::setNodes(), MSLink::setRequestInformation(), NBOwnTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static inherited
Returns the list of gl-ids of all additional objects.
Definition at line 99 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
const std::string& Shape::getImgFile () const inline inherited
Returns the imgFile of the Shape.
Returns
The Shape's rotation imgFile
Definition at line 101 of file Shape.h.
References Shape::myImgFile.
Referenced by drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
SUMOReal Shape::getLayer () const inline inherited
Returns the layer of the Shape.
Returns
The Shape's layer
Definition at line 87 of file Shape.h.
References Shape::myLayer.
Referenced by drawGL(), GUIPointOfInterest::drawGL(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), GUIVehicle::getParameterWindow(), TraCIServerAPI_TLS::processGet(), PCPolyContainer::save(), ROVehicle::saveAllAsXML(), SUMOVTypeParameter::write(), and SUMO::Polygon::writeXML().
const std::string& GUIGlObject::getMicrosimID () const inline inherited
Returns the id of the object as known to microsim.
Returns
The id of the object
Definition at line 146 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 93 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
GUIParameterTableWindow * GUIPolygon::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See Also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 84 of file GUIPolygon.cpp.
GUIGLObjectPopupMenu * GUIPolygon::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See Also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 68 of file GUIPolygon.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and Shape::myType.
const PositionVector& SUMO::Polygon::getShape () const inline inherited
Returns whether the shape of the polygon.
Returns
The shape of the polygon
Definition at line 82 of file Polygon.h.
References SUMO::Polygon::myShape.
Referenced by TraCIServerAPI_Polygon::getShape(), PCPolyContainer::insert(), TraCIServerAPI_Polygon::processGet(), and SUMO::Polygon::writeXML().
const std::string& Shape::getType () const inline inherited
Returns the (abstract) type of the Shape.
Returns
The Shape's (abstract) type
Definition at line 71 of file Shape.h.
References Shape::myType.
Referenced by TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
GUIGlObjectType GUIGlObject::getType () const inline inherited
Returns the type of the object as coded in GUIGlObjectType.
Returns
The type of the object
See Also
GUIGlObjectType
Definition at line 159 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIJunctionWrapper::drawGL(), GUIVehicle::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIVehicle::drawGLAdditional(), GUIJunctionWrapper::getColorValue(), GUILane::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUILane::getScaleValue(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUISelectedStorage::loadIDs(), LayeredRTree::selectLayer(), and GUISelectedStorage::toggleSelection().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void GUIPolygon::performTesselation (SUMOReal lineWidth) const private
Definition at line 224 of file GUIPolygon.cpp.
References beginCallback(), combineCallback(), GLHelper::drawBoxLines(), GLHelper::drawLine(), endCallback(), SUMO::Polygon::getFill(), myLineWidth, and SUMO::Polygon::myShape.
Referenced by drawGL(), and storeTesselation().
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 86 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 194 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void Shape::setAngle (const SUMOReal angle) inline inherited
Sets a new angle.
Parameters
[in] layer The new angle to use
Definition at line 137 of file Shape.h.
References Shape::myAngle.
void Shape::setColor (const RGBColor & col) inline inherited
Sets a new color.
Parameters
[in] col The new color to use
Definition at line 121 of file Shape.h.
References Shape::myColor.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
void SUMO::Polygon::setFill (bool fill) inline inherited
Sets whether the polygon shall be filled.
Parameters
[in] fill Whether the polygon shall be filled
Definition at line 103 of file Polygon.h.
References SUMO::Polygon::myFill.
Referenced by TraCIServerAPI_Polygon::processSet().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 68 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::rename(), and NBEdgeCont::rename().
void Shape::setImgFile (const std::string & imgFile) inline inherited
Sets a new imgFile.
Parameters
[in] imgFile The new imgFile to use
Definition at line 144 of file Shape.h.
References Shape::myImgFile.
void Shape::setLayer (const SUMOReal layer) inline inherited
Sets a new layer.
Parameters
[in] layer The new layer to use
Definition at line 129 of file Shape.h.
References Shape::myLayer.
void GUIGlObject::setMicrosimID (const std::string & newID) inherited
Changes the microsimID of the object (happens in NETEDIT)
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void GUIPolygon::setShape (const PositionVector & shape) virtual
set a new shape and update the tesselation
Reimplemented from SUMO::Polygon.
Definition at line 216 of file GUIPolygon.cpp.
References myLock.
Referenced by GUIShapeContainer::reshapePolygon().
void Shape::setType (const std::string & type) inline inherited
Sets a new type.
Parameters
[in] type The new type to use
Definition at line 113 of file Shape.h.
References Shape::myType.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
void GUIPolygon::storeTesselation (SUMOReal lineWidth) const private
store the drawing commands in a display list
Definition at line 259 of file GUIPolygon.cpp.
References myDisplayList, and performTesselation().
void Polygon::writeXML (OutputDevice & out, bool geo = false) inherited
Definition at line 60 of file Polygon.cpp.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, StringUtils::escapeXML(), Shape::getAngle(), Shape::getColor(), SUMO::Polygon::getFill(), GeoConvHelper::getFinal(), Named::getID(), Shape::getImgFile(), Shape::getLayer(), Parameterised::getMap(), SUMO::Polygon::getShape(), Shape::getType(), OutputDevice::openTag(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_FILL, SUMO_ATTR_GEO, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_KEY, SUMO_ATTR_LAYER, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, SUMO_TAG_POLY, and OutputDevice::writeAttr().
Field Documentation
const SUMOReal Shape::DEFAULT_ANGLE = 0 static inherited
Definition at line 151 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const std::string Shape::DEFAULT_IMG_FILE = "" static inherited
Definition at line 152 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), PCPolyContainer::save(), and SUMO::Polygon::writeXML().
const SUMOReal Shape::DEFAULT_IMG_HEIGHT = 1 static inherited
Definition at line 154 of file Shape.h.
Referenced by ShapeHandler::addPOI(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), and PCPolyContainer::save().
const SUMOReal Shape::DEFAULT_IMG_WIDTH = 1 static inherited
Definition at line 153 of file Shape.h.
Referenced by ShapeHandler::addPOI(), PCLoaderXML::myStartElement(), TraCIServerAPI_POI::processSet(), and PCPolyContainer::save().
const SUMOReal Shape::DEFAULT_LAYER = 128 static inherited
Definition at line 150 of file Shape.h.
Referenced by ShapeHandler::addPoly().
const std::string Shape::DEFAULT_TYPE = "" static inherited
Definition at line 149 of file Shape.h.
Referenced by ShapeHandler::addPoly().
SUMOReal Shape::myAngle protected inherited
The angle of the Shape.
Definition at line 167 of file Shape.h.
Referenced by Shape::getAngle(), and Shape::setAngle().
RGBColor Shape::myColor protected inherited
The color of the Shape.
Definition at line 161 of file Shape.h.
Referenced by Shape::getColor(), and Shape::setColor().
GLuint GUIPolygon::myDisplayList mutable private
id of the display list for the cached tesselation
Definition at line 121 of file GUIPolygon.h.
Referenced by storeTesselation().
bool SUMO::Polygon::myFill protected inherited
Information whether the polygon has to be filled.
Definition at line 126 of file Polygon.h.
Referenced by SUMO::Polygon::getFill(), and SUMO::Polygon::setFill().
std::string Named::myID protected inherited
The name of the object.
Definition at line 128 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), NBNode::computeNodeShape(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSCalibrator::VehicleRemover::notifyEnter(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), RORouteDef::repairCurrentRoute(), Named::setID(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string Shape::myImgFile protected inherited
The angle of the Shape.
Definition at line 170 of file Shape.h.
Referenced by GUIPointOfInterest::drawGL(), Shape::getImgFile(), and Shape::setImgFile().
SUMOReal Shape::myLayer protected inherited
The layer of the Shape.
Definition at line 164 of file Shape.h.
Referenced by Shape::getLayer(), and Shape::setLayer().
SUMOReal GUIPolygon::myLineWidth mutable private
the previous line width for deciding whether the display list must be refreshed
Definition at line 124 of file GUIPolygon.h.
Referenced by performTesselation().
MFXMutex GUIPolygon::myLock mutable private
The mutex used to avoid concurrent updates of the shape.
Definition at line 118 of file GUIPolygon.h.
Referenced by drawGL(), and setShape().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
PositionVector SUMO::Polygon::myShape protected inherited
The positions of the polygon.
Definition at line 123 of file Polygon.h.
Referenced by drawGL(), getCenteringBoundary(), SUMO::Polygon::getShape(), performTesselation(), and SUMO::Polygon::setShape().
std::string Shape::myType protected inherited
The type of the Shape.
Definition at line 158 of file Shape.h.
Referenced by getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), Shape::getType(), and Shape::setType().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 99 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIPolygon.h
GUIPolygon.cpp