SUMO - Simulation of Urban MObility: MemoryTest.cpp File Reference
MemoryTest.cpp File Reference
#include <stdio.h>
#include <memory.h>
#include <crtdbg.h>
#include "RTree.h"
Data Structures
struct SomeThing
A user type to test with, instead of a simple type such as an 'int'.
struct Vec3
Simplify handling of 3 dimensional coordinate.
Functions
static bool BoxesIntersect (const Vec3 &a_boxMinA, const Vec3 &a_boxMaxA, const Vec3 &a_boxMinB, const Vec3 &a_boxMaxB)
int main (int argc, char *argv[])
bool _cdecl QueryResultCallback (SomeThing *a_data, void *a_context)
A callback function to obtain query results in this implementation.
static float RandFloat (float a_min, float a_max)
Function Documentation
static bool BoxesIntersect (const Vec3 & a_boxMinA, const Vec3 & a_boxMaxA, const Vec3 & a_boxMinB, const Vec3 & a_boxMaxB) static
Definition at line 72 of file MemoryTest.cpp.
References Vec3::v.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 118 of file MemoryTest.cpp.
References ASSERT, BoxesIntersect(), SomeThing::m_creationCounter, SomeThing::m_max, SomeThing::m_min, QueryResultCallback(), RandFloat(), SomeThing::s_outstandingAllocs, and Vec3::v.
bool _cdecl QueryResultCallback (SomeThing * a_data, void * a_context)
A callback function to obtain query results in this implementation.
Definition at line 110 of file MemoryTest.cpp.
References SomeThing::m_creationCounter.
Referenced by main().
static float RandFloat (float a_min, float a_max) static
Definition at line 34 of file MemoryTest.cpp.
References ASSERT.
Referenced by main().